### ISSUE TITLE
FEAT: support CogVLM

### ISSUE THREAD

**Issue by ye4241** [xorbitsai/inference#1009]
### Is your feature request related to a problem? Please describe
None

### Describe the solution you'd like
Please support https://github.com/THUDM/CogVLM

### Describe alternatives you've considered
None

### Additional context
None

**Comment by xs818818** [comment]
CogVLM好像没开源中文版本

**Comment by ye4241** [comment]
@xs818818 似乎是的，只有英文能产出的。

**Comment by xs818818** [comment]
试试yi吧，有俩显卡还能yi-34-vl

**Comment by ye4241** [comment]
@xs818818 我试试看

**Comment by thiner** [comment]
CogVLM 现在支持中文了。https://hf-mirror.com/THUDM/cogvlm2-llama3-chinese-chat-19B
