### ISSUE TITLE
QUESTION: xinference还不支持qwen1.5的模型吗？

### ISSUE THREAD

**Issue by yaoyasong** [xorbitsai/inference#1014]
用自定义注册qwen1.5-72b-chat-int4模型，能正常启动，但推理报错，是不是还不支持qwen1.5模型？

**Comment by aresnow1** [comment]
升级到最新版本，内置就有支持，不需要注册

**Comment by yaoyasong** [comment]
> 升级到最新版本，内置就有支持，不需要注册

确实如此。
