### ISSUE TITLE
希望docker的cpu版本支持rerank model

### ISSUE THREAD

**Issue by AAlexDing** [xorbitsai/inference#1017]
目前 apecloud/xinference:latest-cpu 这个镜像里launch model只有language models 和 embedding models，能否添加rerank models? 

![image](https://github.com/xorbitsai/inference/assets/30212143/3ce7a743-2563-45b2-bb9b-85769c968e14)

**Comment by aresnow1** [comment]
这个镜像应该是安装了老版本，需要apecloud 那边更新，或者参考这个 https://github.com/xorbitsai/inference/blob/main/xinference/deploy/docker/Dockerfile 自己本地 build 下

**Comment by qinxuye** [comment]
现在我们已出官方cpu镜像，请使用 https://hub.docker.com/r/xprobe/xinference/tags -cpu结尾的镜像。
