### ISSUE TITLE
Fail to install Orion-14B-Chat-RAG

### ISSUE THREAD

**Issue by QXQL** [xorbitsai/inference#1020]
### Describe the bug
Fail to install Orion-14B-Chat-RAG

### To Reproduce
Python version: 3.10
The version of xinference : 0.8.5

### Expected behavior
This modeling file requires the following packages that were not found in you  environment: flash_attn. Run pip install falsh_attn

**Comment by codingl2k1** [comment]
`flash_attn` needs to be compiled and installed, and depends on cuda. So, xinference does not depends on it.

 BTW, the error message is clear enough: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`.
