### ISSUE TITLE
BUG python setup.py build_web have a error

### ISSUE THREAD

**Issue by xs818818** [xorbitsai/inference#1022]
/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py:521: UserWarning: 
            Xinference ui is not built at expected directory: /opt/conda/lib/python3.10/site-packages/xinference/web/ui/build/
            To resolve this warning, navigate to /opt/conda/lib/python3.10/site-packages/xinference/web/ui/
            And build the Xinference ui by running "npm run build"
            
  warnings.warn(

**Comment by aresnow1** [comment]
You need to install node.js to build web.

**Comment by xs818818** [comment]
npm run build have a error
[eslint] 
src/components/MenuSide.js
  Line 4:3:  'GitHub' is defined but never used  no-unused-vars
