### ISSUE TITLE
QUESTION 如何在容器启动时自动加载指定模型

### ISSUE THREAD

**Issue by mote0302** [xorbitsai/inference#1025]
容器启动后会拉起服务但是不会加载上次的模型
如何自动在容器启动后加载指定模型？

**Comment by tao2021** [comment]
我是写了这个脚本:
nohup xinference-local -H 0.0.0.0 --port 9997 --log-level DEBUG &
sleep 10
xinference launch --model-name Qwen2-7B-Chat --model-format pytorch --model-engine Transformers
docker启动的时候执行这个脚本，但是容器会频繁重启，查看docker日志没有出现错误。模型显示也加载成功，但是前端页面并没有任何显示。

**Comment by nadirvishun** [comment]
> 我是写了这个脚本: nohup xinference-local -H 0.0.0.0 --port 9997 --log-level DEBUG & sleep 10 xinference launch --model-name Qwen2-7B-Chat --model-format pytorch --model-engine Transformers docker启动的时候执行这个脚本，但是容器会频繁重启，查看docker日志没有出现错误。模型显示也加载成功，但是前端页面并没有任何显示。
你需要保正脚本进程一直存在，但你的脚本执行完就结束了，所以你需要去掉`nohup`，然后再最后一行加上`wait`，这样这个脚本进程就会一直等待` xinference-local`，而它是不会结束的，从而这个脚本进程也不会结束，就不会重启了。
