### ISSUE TITLE
BUG：返回值会自己中断

### ISSUE THREAD

**Issue by YYLCyylc** [xorbitsai/inference#1029]
### Describe the bug
在0.8.5版本的xinference，当模型的返回值token数为2，只有一个字母时会不显示返回值，回退到0.8.2版本则没有这个问题。
在0.8.2版本中输出正常
![image](https://github.com/xorbitsai/inference/assets/50295520/1ee82971-6005-4e49-adea-9ac88066f8b4)
在0.8.5版本中，圈出的content会是 "" 空值，"completion_tokens"都是2.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.python=3.11
2. The version of xinference you use.xinference=0.8.5
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by aresnow1** [comment]
最新版本测试了下没有这个问题。

**
![image](https://github.com/xorbitsai/inference/assets/109642806/ba0fb311-652b-4b08-b58e-abb186a53a86)
**

**Comment by YYLCyylc** [comment]
我更新到0.9.0后部署custom模型后还是出现了这样的问题，我注意到你单独输出一个字母的completion_tokens为1，而我的completion_tokens为2，我感觉应该是我的custom模型的输出中会含有什么特殊字符使得输出为空，在新版本是否有特殊的字符会导致输出的content为空值？如果有的话，我应该如何查看模型的具体输出呢？
![image](https://github.com/xorbitsai/inference/assets/50295520/facdf812-5f51-4552-a9b0-e2fc25c0b41d)
![4d6d1f24ef7326c2c5f59209f436f0a](https://github.com/xorbitsai/inference/assets/50295520/93f323ad-d7d2-4271-a11f-5339ccb41cc7)

**Comment by YYLCyylc** [comment]
我用qwen1.5-chat-14b进行了尝试，出现了同样的问题，输入你好时返回的结果也会有中途被中断的情况出现
![image](https://github.com/xorbitsai/inference/assets/50295520/b34dcbb5-02bf-473d-8f20-232fbdfbe8d5)
![image](https://github.com/xorbitsai/inference/assets/50295520/ac35763b-da22-495a-9d40-30cdee0bb7d8)
我注意到在原来的版本中没有include_stop_str_in_output=False这个参数的设定，是否是这个原因导致的呢？
![image](https://github.com/xorbitsai/inference/assets/50295520/37c3ebb3-a630-447f-844d-ababeae2a78c)
![image](https://github.com/xorbitsai/inference/assets/50295520/725c545a-3a31-4d7f-8d02-4b651186060f)

**Comment by YYLCyylc** [comment]
> 最新版本测试了下没有这个问题。
> 
> ** ![image](https://private-user-images.githubusercontent.com/109642806/307210373-ba0fb311-652b-4b08-b58e-abb186a53a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDI4OTcsIm5iZiI6MTcwOTAwMjU5NywicGF0aCI6Ii8xMDk2NDI4MDYvMzA3MjEwMzczLWJhMGZiMzExLTY1MmItNGIwOC1iNThlLWFiYjE4NmE1M2E4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMjU2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmE3N2YxZjgyOTMxZjYyNDFkNjkwOTMyMzZiYmQ3N2IwYmI0YTc1ZDBkYWNhZTgyMWJlMjhjYmY5YzNiNzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2t2Pps4vKobepbIB6k_e2W3tF71dNs23fcuuyBWga-U) **

我在新版本测试了qwen-chat 14b版本可以正常输出，但是输出一个字母显示输出了2个token，部署qwen1.5-chat和我的custom模型时都会输出空内容
![image](https://github.com/xorbitsai/inference/assets/50295520/3bbf39d9-0cad-4798-ab6e-3a31615eda9e)

**Comment by YYLCyylc** [comment]
进一步排查在0.9.0版本不启用vllm的话qwen1.5模型可以正常回答，启用vllm则不行
![image](https://github.com/xorbitsai/inference/assets/50295520/1e938b14-66ff-4747-ac95-dd5db051dfd5)
![image](https://github.com/xorbitsai/inference/assets/50295520/753ad003-d262-43ec-a10d-4b860d4bf044)

**Comment by YYLCyylc** [comment]
没事了，是vllm的bug
https://github.com/vllm-project/vllm/issues/3034
