### ISSUE TITLE
能不能指定gpu运行？

### ISSUE THREAD

**Issue by shinerdeng** [xorbitsai/inference#1034]
web图形界面能不能指定用哪个gpu，比如模型1用cuda0，模型2用cuda1

**Comment by ChengjieLi28** [comment]
@shinerdeng 目前不支持指定GPU调度。你可以先启动模型1，再启动模型2（都n_gpu=1），就自然是模型1在GPU0上，模型2在GPU1上。

**Comment by ye7love7** [comment]
我选择数量4加载了第一个模型后，加载第二个模型使用数量2，依然加载在了0,1这两张卡上

**Comment by skytodmoon** [comment]
mark can not auto allocate GPU,`Server error: 503 - [address=0.0.0.0:41119, pid=1081757] CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 30.81 MiB is free. Process 1077237 has 9.44 GiB memory in use. Process 1077362 has 9.81 GiB memory in use. Including non-PyTorch memory, this process has 4.39 GiB memory in use. Of the allocated memory 4.08 GiB is allocated by PyTorch, and 24.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

**Comment by web3aipro** [comment]
这个问题很棘手啊，都会调度同一个GPU上
