### ISSUE TITLE
Considering let the user specify the model path( from local machine ) or download repo( custom repo in hf or modelscope) for build-in model

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#1037]
### Is your feature request related to a problem? Please describe
since some model is gated (in hf or modelscope ) , some model is impossible to download

### Describe the solution you'd like
please consider let the user specify the path or repo uri in the UI , so the application can load from the specified server path or target repo id, which can make user load model more easier

**Comment by ChengjieLi28** [comment]
Hi, @onionknightdd . If you have local path of model files, you can register the model to xinference. Refer to: https://inference.readthedocs.io/en/latest/models/custom.html. We also support registering custom model from web UI, in the `Register Model` panel.
