### ISSUE TITLE
BUG: Failed to launch qwe1.5-14b-GGUF using Xinferrence but works fine in pure llama_cpp python

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#1043]
### Describe the bug
Failed to launch qwe1.5-14b-GGUF using Xinferrence but works fine in pure llama_cpp python :
model_name : qwe1.5-14b-GGUF 
quant_method : q8_0
device_type : 1*NVIDIA A100-SXM4-40GB or 4*NVIDIA A100-SXM4-40GB

### To Reproduce
using Xinferrence launch qwe1.5-14b-GGUF with build-in model or register model:
![image](https://github.com/xorbitsai/inference/assets/49679672/5926329c-075c-47af-b353-c64490b13cf5)
![image](https://github.com/xorbitsai/inference/assets/49679672/c36f5d25-faea-400a-a44e-3224d2045dd1)
![image](https://github.com/xorbitsai/inference/assets/49679672/75ec7847-bc2d-402e-9346-9bd2a71c750d)
![image](https://github.com/xorbitsai/inference/assets/49679672/abdbe917-154c-42b0-94b6-948c322485ac)

But it work fine when direct using llama_cpp library both with 1*NVIDIA A100-SXM4-40GB or 4*NVIDIA A100-SXM4-40GB :
![image](https://github.com/xorbitsai/inference/assets/49679672/f84a7206-0683-494a-8e58-4ccdc990b753)

1. Your Python version. --> python3.11
2. The version of xinference you use. --> v0.9.0
3. Versions of crucial packages.  --> llama_cpp v0.2.46
4. Full stack of the error.  --> see pic above
5. Minimized code to reproduce the error. --> see pic above

### Expected behavior
should work the same way with direct using llama_cpp

**Comment by qinxuye** [comment]
Is this issue related to #1038 ?

**Comment by onionknightdd** [comment]
> Is this issue related to #1038 ?

seems not 

the GPUs has enough memory when launch the model:
befor :
![image](https://github.com/xorbitsai/inference/assets/49679672/f73da4b3-41a4-4a39-b0f1-0500d4879106)

Then launch model with llama_cpp in 1 GPU:
![image](https://github.com/xorbitsai/inference/assets/49679672/0db1c0d4-6f96-453f-86d5-9d6ade7c1b92)
![image](https://github.com/xorbitsai/inference/assets/49679672/8af7b86a-f99f-4875-89ac-7d198640941c)

or launch model with llama_cpp in 4 GPUs:
![image](https://github.com/xorbitsai/inference/assets/49679672/0f706c59-71d3-4316-97e2-79c08861154a)
![image](https://github.com/xorbitsai/inference/assets/49679672/a3d3b3bd-bc93-4f95-8c7d-f7ec3e3222b4)

**Comment by zly9844** [comment]
Could you please show me the model.json file when register gguf-format model？ Thank you in advance!
