### ISSUE TITLE
Server error: 500 - [address=127.0.0.1:50182, pid=36312] [WinError None] 客户端没有所需的特权

### ISSUE THREAD

**Issue by cq134cq** [xorbitsai/inference#1052]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context
Server error: 500 - [address=127.0.0.1:50182, pid=36312] [WinError None] 客户端没有所需的特权。: 'C:\\soft\\models\\THUDM_chatglm3-6b' -> 'C:\\Users\\sync\\.xinference\\cache\\chatglm3-6b-pytorch-7b'
我这个是自定模型，请问一定要把模型复制到C:\\Users\\sync\\.xinference\\cache\\chatglm3-6b-pytorch-7b

**Comment by qinxuye** [comment]
文件没有权限吧，修改下权限。

**Comment by XiaoM-997** [comment]
> ### 描述错误
> 对于错误是什么的清晰而简洁的描述。
> 
> ### 复制
> 为了帮助我们重现此错误，请提供以下信息：
> 
> 1. 您的 Python 版本。
> 2. 您使用的 xinference 版本。
> 3. 关键软件包的版本。
> 4. 错误的完整堆栈。
> 5. 最小化代码来重现错误。
> 
> ### 预期行为
> 对于您期望发生的情况的清晰而简洁的描述。
> 
> ### 其他背景信息
> 在此处添加有关该问题的任何其他背景信息。 服务器错误：500 - [address=127.0.0.1:50182, pid=36312] [WinError None] 客户端没有所需的特权。: 'C:\soft\models\THUDM_chatglm3-6b' -> 'C:\Users \sync\.xinference\cache\chatglm3-6b-pytorch-7b' 我这个是自定模型，请一定要把模型复制到C:\Users\sync\.xinference\cache\chatglm3-6b-pytorch-7b

我也是遇到了这个问题请问你解决了吗？ 修改什么权限，我文件权限都是有的 还是不行。

**Comment by oucyangshuai** [comment]
以管理员身份打开Anaconda Prompt
