### ISSUE TITLE
BUG: for windows cannot start with IP 0.0.0.0

### ISSUE THREAD

**Issue by cq134cq** [xorbitsai/inference#1053]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context
用xinference-local没问题，可是用xinference-local --host 0.0.0.0 --port 9997就报错
(c:\soft\xx) C:\soft\xx>xinference-local
2024-02-29 10:27:27,656 xinference.core.supervisor 36632 INFO     Xinference supervisor 127.0.0.1:15269 started
2024-02-29 10:27:27,686 xinference.core.worker 36632 INFO     Starting metrics export server at 127.0.0.1:None
2024-02-29 10:27:27,687 xinference.core.worker 36632 INFO     Checking metrics export server...
2024-02-29 10:27:31,583 xinference.core.worker 36632 INFO     Metrics server is started at: http://127.0.0.1:55825
2024-02-29 10:27:31,585 xinference.core.worker 36632 INFO     Xinference worker 127.0.0.1:15269 started
2024-02-29 10:27:31,586 xinference.core.worker 36632 INFO     Purge cache directory: C:\Users\sync\.xinference\cache
2024-02-29 10:27:33,489 xinference.api.restful_api 31700 INFO     Starting Xinference at endpoint: http://127.0.0.1:9997

(c:\soft\xx) C:\soft\xx>xinference-local --host 0.0.0.0 --port 9997
2024-02-29 10:28:41,260 xinference.core.supervisor 27716 INFO     Xinference supervisor 0.0.0.0:56658 started
2024-02-29 10:28:41,294 xinference.core.worker 27716 INFO     Starting metrics export server at 0.0.0.0:None
2024-02-29 10:28:41,295 xinference.core.worker 27716 INFO     Checking metrics export server...
2024-02-29 10:28:45,659 xinference.core.worker 27716 INFO     Metrics server is started at: http://0.0.0.0:55856
2024-02-29 10:28:45,660 xinference.core.worker 27716 INFO     Xinference worker 0.0.0.0:56658 started
2024-02-29 10:28:45,665 xinference.core.worker 27716 INFO     Purge cache directory: C:\Users\sync\.xinference\cache
Traceback (most recent call last):
  File "c:\soft\xx\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\soft\xx\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\soft\xx\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\xinference\deploy\cmdline.py", line 220, in local
    start_local_cluster(
  File "c:\soft\xx\lib\site-packages\xinference\deploy\cmdline.py", line 107, in start_local_cluster
    main(
  File "c:\soft\xx\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

**Comment by qinxuye** [comment]
看看 9997 是不是被占用了。

**Comment by cq134cq** [comment]
> 看看 9997 是不是被占用了。

看过没有被占用，还有

**Comment by cq134cq** [comment]
> 看看 9997 是不是被占用了。
(c:\soft\xx) C:\soft\xx>netstat -na

活动连接

  协议  本地地址          外部地址        状态
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5040           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6686           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6687           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6688           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6689           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:6711           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:13688          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49669          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49710          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49732          0.0.0.0:0              LISTENING
  TCP    10.0.100.191:139       0.0.0.0:0              LISTENING
  TCP    10.0.100.191:49408     20.197.71.89:443       ESTABLISHED
  TCP    10.0.100.191:49680     123.56.99.17:3570      ESTABLISHED
  TCP    10.0.100.191:49709     42.192.32.66:443       ESTABLISHED
  TCP    10.0.100.191:49876     58.217.207.240:443     ESTABLISHED
  TCP    10.0.100.191:49881     58.217.207.240:8081    ESTABLISHED
  TCP    10.0.100.191:49882     0.0.0.0:0              LISTENING
  TCP    10.0.100.191:49883     10.0.100.171:20000     ESTABLISHED
  TCP    10.0.100.191:49980     23.22.146.5:443        TIME_WAIT
  TCP    10.0.100.191:49995     44.224.154.229:443     TIME_WAIT
  TCP    127.0.0.1:5533         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5533         127.0.0.1:49673        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49676        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49681        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49682        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49688        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49689        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49690        ESTABLISHED
  TCP    127.0.0.1:5533         127.0.0.1:49692        ESTABLISHED
  TCP    127.0.0.1:6688         127.0.0.1:49678        ESTABLISHED
  TCP    127.0.0.1:6688         127.0.0.1:49717        ESTABLISHED
  TCP    127.0.0.1:6688         127.0.0.1:49747        ESTABLISHED
  TCP    127.0.0.1:6688         127.0.0.1:49819        ESTABLISHED
  TCP    127.0.0.1:6689         127.0.0.1:49772        ESTABLISHED
  TCP    127.0.0.1:6690         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:6711         127.0.0.1:49894        ESTABLISHED
  TCP    127.0.0.1:35600        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:35600        127.0.0.1:49789        ESTABLISHED
  TCP    127.0.0.1:35600        127.0.0.1:49880        ESTABLISHED
  TCP    127.0.0.1:35800        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49635        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49673        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49676        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49678        127.0.0.1:6688         ESTABLISHED
  TCP    127.0.0.1:49681        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49682        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49688        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49689        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49690        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49692        127.0.0.1:5533         ESTABLISHED
  TCP    127.0.0.1:49717        127.0.0.1:6688         ESTABLISHED
  TCP    127.0.0.1:49740        127.0.0.1:49741        ESTABLISHED
  TCP    127.0.0.1:49741        127.0.0.1:49740        ESTABLISHED
  TCP    127.0.0.1:49747        127.0.0.1:6688         ESTABLISHED
  TCP    127.0.0.1:49750        127.0.0.1:49751        ESTABLISHED
  TCP    127.0.0.1:49751        127.0.0.1:49750        ESTABLISHED
  TCP    127.0.0.1:49772        127.0.0.1:6689         ESTABLISHED
  TCP    127.0.0.1:49775        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49775        127.0.0.1:50004        ESTABLISHED
  TCP    127.0.0.1:49776        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49776        127.0.0.1:49843        ESTABLISHED
  TCP    127.0.0.1:49789        127.0.0.1:35600        ESTABLISHED
  TCP    127.0.0.1:49790        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49791        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49791        127.0.0.1:49795        ESTABLISHED
  TCP    127.0.0.1:49795        127.0.0.1:49791        ESTABLISHED
  TCP    127.0.0.1:49819        127.0.0.1:6688         ESTABLISHED
  TCP    127.0.0.1:49820        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49843        127.0.0.1:49776        ESTABLISHED
  TCP    127.0.0.1:49880        127.0.0.1:35600        ESTABLISHED
  TCP    127.0.0.1:49894        127.0.0.1:6711         ESTABLISHED
  TCP    127.0.0.1:49975        127.0.0.1:49775        TIME_WAIT
  TCP    127.0.0.1:49977        127.0.0.1:49775        TIME_WAIT
  TCP    127.0.0.1:49996        127.0.0.1:49997        TIME_WAIT
  TCP    127.0.0.1:49998        127.0.0.1:49775        TIME_WAIT
  TCP    127.0.0.1:50003        127.0.0.1:49775        TIME_WAIT
  TCP    127.0.0.1:50004        127.0.0.1:49775        ESTABLISHED
  TCP    127.0.0.1:53563        0.0.0.0:0              LISTENING
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:445               [::]:0                 LISTENING
  TCP    [::]:7680              [::]:0                 LISTENING
  TCP    [::]:13688             [::]:0                 LISTENING
  TCP    [::]:49664             [::]:0                 LISTENING
  TCP    [::]:49665             [::]:0                 LISTENING
  TCP    [::]:49666             [::]:0                 LISTENING
  TCP    [::]:49667             [::]:0                 LISTENING
  TCP    [::]:49669             [::]:0                 LISTENING
  TCP    [::]:49710             [::]:0                 LISTENING
  TCP    [::]:49732             [::]:0                 LISTENING
  TCP    [::1]:13688            [::1]:49868            ESTABLISHED
  TCP    [::1]:13688            [::1]:49884            ESTABLISHED
  TCP    [::1]:13688            [::1]:49885            ESTABLISHED
  TCP    [::1]:49672            [::]:0                 LISTENING
  TCP    [::1]:49868            [::1]:13688            ESTABLISHED
  TCP    [::1]:49884            [::1]:13688            ESTABLISHED
  TCP    [::1]:49885            [::1]:13688            ESTABLISHED

**Comment by qinxuye** [comment]
换个端口能启动吗？

**Comment by cq134cq** [comment]
> 端口能启动吗

一样报错
(c:\soft\xx) C:\soft\xx>xinference-local --host 0.0.0.0 --port 9996
2024-02-29 10:41:09,087 xinference.core.supervisor 18184 INFO     Xinference supervisor 0.0.0.0:38877 started
2024-02-29 10:41:09,116 xinference.core.worker 18184 INFO     Starting metrics export server at 0.0.0.0:None
2024-02-29 10:41:09,118 xinference.core.worker 18184 INFO     Checking metrics export server...
2024-02-29 10:41:13,880 xinference.core.worker 18184 INFO     Metrics server is started at: http://0.0.0.0:50046
2024-02-29 10:41:13,882 xinference.core.worker 18184 INFO     Xinference worker 0.0.0.0:38877 started
2024-02-29 10:41:13,884 xinference.core.worker 18184 INFO     Purge cache directory: C:\Users\sync\.xinference\cache
Traceback (most recent call last):
  File "c:\soft\xx\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\soft\xx\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\soft\xx\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\soft\xx\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\xinference\deploy\cmdline.py", line 220, in local
    start_local_cluster(
  File "c:\soft\xx\lib\site-packages\xinference\deploy\cmdline.py", line 107, in start_local_cluster
    main(
  File "c:\soft\xx\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

**Comment by qinxuye** [comment]
那看来和端口无关，有可能是windows 不能指定 0.0.0.0，换成你的 IP 试下

**Comment by cq134cq** [comment]
> 那看来和端口无关，有可能是windows 不能指定 0.0.0.0，换成你的 IP 试下

换IP就可以了，谢谢

**Comment by qinxuye** [comment]
OK，后续改进下，windows 指定 0.0.0.0 看看如何处理

**Comment by cq134cq** [comment]
> 用xinference-local --host 0.0.0.0 --port 9997就报错
请问这里如何指定它用GPU
![微信图片_20240229105010](https://github.com/xorbitsai/inference/assets/95132993/c7f10ef6-4808-49e3-885d-1355d40ca72c)

**Comment by qinxuye** [comment]
> > 用xinference-local --host 0.0.0.0 --port 9997就报错
> > 请问这里如何指定它用GPU
> > ![微信图片_20240229105010](https://private-user-images.githubusercontent.com/95132993/308778024-c7f10ef6-4808-49e3-885d-1355d40ca72c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzUzODksIm5iZiI6MTcwOTE3NTA4OSwicGF0aCI6Ii85NTEzMjk5My8zMDg3NzgwMjQtYzdmMTBlZjYtNDgwOC00OWUzLTg4NWQtMTM1NWQ0MGNhNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAyNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTYyMGZkYWU3MDU3NjU3M2MzMjgxNmJjYWZiMGU4Mzc4NTlhN2E4YzJmNDFkYWNjZDUzYWRlMmE4YjI3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SmoyNOy6CLZvvQ-CAAv8hHo3VdU0A10v6B5_DwBP6bw)

有可用的应该会自动选择 GPU 的。

**Comment by cq134cq** [comment]
> 择 GPU 的
我的机器上有一个4060显卡是空的
![微信图片_20240229105727](https://github.com/xorbitsai/inference/assets/95132993/cebc1743-e137-4d0d-8a75-96898c6bc863)

**Comment by qinxuye** [comment]
执行 python -c "import torch; print(torch.cuda.is_available())"

看下是否可用。

**Comment by cq134cq** [comment]
> 执行 python -c "import torch; print(torch.cuda.is_available())"
> 
> 看下是否可用。
不能用，那是因为什么？
![微信图片_20240229110325](https://github.com/xorbitsai/inference/assets/95132993/614953c3-33a5-4efd-9690-01ebb187be3a)

**Comment by qinxuye** [comment]
那看下驱动和 torch 版本对应啊之类的，这个是 pytorch 的安装问题了，不在 xinference 范畴内。

**Comment by cq134cq** [comment]
> 在 xinference 范畴内

说的没错，是torch 版本问题

**Comment by cq134cq** [comment]
> 那看下驱动和 torch 版本对应啊之类的，这个是 pytorch 的安装问题了，不在 xinference 范畴内。

在次感谢

**Comment by FinTechCao** [comment]
> 那看来和端口无关，有可能是windows 不能指定 0.0.0.0，换成你的 IP 试下

请问一下 你的IP 是指什么？比如我要从某地址A去访问部在B地址的xinference，那 -H 后面的参数是地址A吗？

**Comment by zhongzhubailong** [comment]
> > 那看来和端口无关，有可能是windows 不能指定 0.0.0.0，换成你的 IP 试下
> 
> 请问一下 你的IP 是指什么？比如我要从某地址A去访问部在B地址的xinference，那 -H 后面的参数是地址A吗？

不要指定IP，直接xinference-local启动

**Comment by WHG555** [comment]
使用0.0.0.0  是为了能让本地的所有IP都能连上。   不然还得手动改IP了

**Comment by itbaby115** [comment]
windows不能指定0.0.0.0，要改成真实ip地址。
