### ISSUE TITLE
显存占用双倍异常

### ISSUE THREAD

**Issue by ybsbbw** [xorbitsai/inference#1059]
使用xinference的web界面部署Qwen1.5-72B-Chat模型时，出现了显存占用双倍异常的问题，理论上应该占用160G左右的显存，实际占用了约320G。怀疑框架加载了两次模型（因为相比之前版本出现了一个replicate设置，怀疑和这个参数的执行有关系）

运行环境配置：
8卡A800服务器
python 3.9
xinference版本 0.9.0
vllm 0.3.0

加载设置：
![image](https://github.com/xorbitsai/inference/assets/47239496/46ca67e1-0a58-4a2f-9088-6116b8ad13d7)

加载模型前：
![01](https://github.com/xorbitsai/inference/assets/47239496/0d260eb5-1d4b-49d4-a4a2-dc888bdf0092)

加载模型后：
![image](https://github.com/xorbitsai/inference/assets/47239496/a0581cd4-2746-4167-b2b7-89cd3fea74c1)
![02](https://github.com/xorbitsai/inference/assets/47239496/c7cd49d6-6090-42c6-b9ad-97ddaa2acfe8)

**Comment by qinxuye** [comment]
replica 是 1 吗？

**Comment by ybsbbw** [comment]
> replica 是 1 吗？

是1，更新了一下问题描述，有截图

**Comment by qinxuye** [comment]
vLLM 是会尝试去占用内存的，有可能是这个原因吗

**Comment by ybsbbw** [comment]
> vLLM 是会尝试去占用内存的，有可能是这个原因吗

相比直接加载模型，会直接double吗？

**Comment by qinxuye** [comment]
> > vLLM 是会尝试去占用内存的，有可能是这个原因吗
> 
> 相比直接加载模型，会直接double吗？

vLLM 会直接占用一定比例的显存，用来放 kvcache。是很有可能 double 的。

**Comment by ybsbbw** [comment]
> > > vLLM 是会尝试去占用内存的，有可能是这个原因吗
> > 
> > 
> > 相比直接加载模型，会直接double吗？
> 
> vLLM 会直接占用一定比例的显存，用来放 kvcache。是很有可能 double 的。

原来是这样，了解了，那我把问题关了，另外还有一个max_token的问题一会我新建一个issue，有时间烦请看下：）

**Comment by qinxuye** [comment]
> > > > vLLM 是会尝试去占用内存的，有可能是这个原因吗
> > > 
> > > 
> > > 相比直接加载模型，会直接double吗？
> > 
> > 
> > vLLM 会直接占用一定比例的显存，用来放 kvcache。是很有可能 double 的。
> 
> 原来是这样，了解了，那我把问题关了，另外还有一个max_token的问题一会我新建一个issue，有时间烦请看下：）

没问题
