### ISSUE TITLE
max_tokens设置似乎出现异常

### ISSUE THREAD

**Issue by ybsbbw** [xorbitsai/inference#1060]
8卡A800服务器
xinference版本0.9.0
vllm0.3.0
web界面配置模型32000的最大输入token长度
![image](https://github.com/xorbitsai/inference/assets/47239496/5bd84474-d2e2-4236-8a81-4d23f6d6ba52)

但是实际运行时，发现似乎加载的模型还是4096长度的，如下图显示
![image](https://github.com/xorbitsai/inference/assets/47239496/d79be7c9-bf32-40ef-8f8d-f7fd191fb283)

我印象中必须max_seq_length和max_model_length都设置为32000，最大输入token长度才能正常完成设置，这里麻烦开发人员检查一下

**Comment by xxWeiDG** [comment]
这个问题现在还是存在，您那解决了吗

**Comment by ybsbbw** [comment]
已经解决了-------- 原始邮件 --------发件人： xxWeiDG ***@***.***>日期： 2024年7月15日周一 15:08收件人： xorbitsai/inference ***@***.***>抄送： ybsbbw ***@***.***>, Author ***@***.***>主    题： Re: [xorbitsai/inference] max_tokens设置似乎出现异常 (Issue #1060)
这个问题现在还是存在，您那解决了吗

**Comment by xxWeiDG** [comment]
> 已经解决了-------- 原始邮件 --------发件人： xxWeiDG ***@***.***>日期： 2024年7月15日周一 15:08收件人： xorbitsai/inference ***@***.***>抄送： ybsbbw ***@***.***>, Author ***@***.***>主 题： Re: [xorbitsai/inference] max_tokens设置似乎出现异常 (Issue #1060) 这个问题现在还是存在，您那解决了吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

请教一下，您是怎么解决的呢，好像vllm有问题

**Comment by jony4** [comment]
<img width="564" alt="image" src="https://github.com/user-attachments/assets/c6186839-2dab-46ee-903f-3f44e14cc04e">
这么处理试试

> > 已经解决了-------- 原始邮件 --------发件人： xxWeiDG _**@**_._**>日期： 2024年7月15日周一 15:08收件人： xorbitsai/inference _**@**_.**_>抄送： ybsbbw _**@**_._**>, Author _**@**_.**_>主 题： Re: [xorbitsai/inference] max_tokens设置似乎出现异常 (Issue #1060) 这个问题现在还是存在，您那解决了吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 请教一下，您是怎么解决的呢，好像vllm有问题
