### ISSUE TITLE
QUESTION： 以xinference作为后台服务，不能同时多人进行提问

### ISSUE THREAD

**Issue by yuanye09** [xorbitsai/inference#1065]
运行环境是
ubuntu 22
python 3.10.9
xinference 0.9.0

用xinference作为后台服务，部署的是chatglm3模型，当两个浏览器客户端同时提问时，发现必须不能同时回复模型推理内容，只能等待一个完成后，下一个才会回复。

**Comment by zhanghx0905** [comment]
如果有gpu，可以考虑使用vllm推理引擎

**Comment by yuanye09** [comment]
> 如果有gpu，可以考虑使用vllm推理引擎

嗯，这个问题解决了，确实和引擎有关。 你使用的时候有没有发现，用xinference发布的本地模型，使用的显存要比模型本身带的demo大很多。例如：chatglm3，用xinference时在22G以上， 自带的demo使用不到13G显存

**Comment by NotAlone0125** [comment]
> > 如果有gpu，可以考虑使用vllm推理引擎
> 
> 嗯，这个问题解决了，确实和引擎有关。 你使用的时候有没有发现，用xinference发布的本地模型，使用的显存要比模型本身带的demo大很多。例如：chatglm3，用xinference时在22G以上， 自带的demo使用不到13G显存

如何使用使用vllm推理引擎，我按照官方文档操作，按道理应该是自动选择了vllm推理引擎，但是还是上一个回答完才能回答下一个
