### ISSUE TITLE
Support FunASR

### ISSUE THREAD

**Issue by elepherai** [xorbitsai/inference#1071]
FunASR is a fundamental speech recognition toolkit that offers a variety of features, including speech recognition (ASR), Voice Activity Detection (VAD), Punctuation Restoration, Language Models, Speaker Verification, Speaker Diarization and multi-talker ASR.

https://github.com/alibaba-damo-academy/FunASR

**Comment by aresnow1** [comment]
Thank you for the information. We will consider adding this model.

**Comment by xs818818** [comment]
同问，还有语音合成模型，paddlecpeech
