### ISSUE TITLE
Qwen-Audio支持

### ISSUE THREAD

**Issue by wangqin666** [xorbitsai/inference#1072]
Qwen-Audio不支持openAI的api嘛？
做对讲机，有需求；
本来想着语音转文字在问答，

**Comment by codingl2k1** [comment]
有的，可以参考：https://github.com/xorbitsai/inference/blob/main/examples/audio_to_text.ipynb

**Comment by WholeWorld-Timothy** [comment]
这个issue跟 https://github.com/xorbitsai/inference/issues/1523 说的是一个事么？这个问的是Qwen-Audio是否支持openai的api，1523问的是xinference能否在audio models里面支持qwen-audio-chat，这个里面的回复说的是xinference是不是支持audio，这是打算咋处理，能明确说一下么？我表示很晕。
