### ISSUE TITLE
QUESTION: Xinference.core.worker 4040 ERROR Failed to load model chatglm3-1-0

### ISSUE THREAD

**Issue by flyicewei** [xorbitsai/inference#1074]
Hi Team

I want to use load chatglm3 model vie pytorch, but got :Xinference.core.worker 4040 ERROR Failed to load model chatglm3-1-0  error

have any idea?
![Uploading xinference.png…]()

**Comment by alfgo** [comment]
Updated chatglm3 with latest model files, I also get an error.
"couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named tokenization_chatglm.py."
