### ISSUE TITLE
xinference.model.audio.whisper 64759 WARNING  Prompt for whisper transcriptions will be ignored:

### ISSUE THREAD

**Issue by LucisBaoshg** [xorbitsai/inference#1081]
### Describe the bug
xinference.model.audio.whisper 64759 WARNING  Prompt for whisper transcriptions will be ignored:
When I call transcriptions API:
text = model.transcriptions(audio=audio_file.read(), language='chinese', prompt='xxxxxx')

### Expected behavior
Hopefully it behaves as described in the api documentation.

![image](https://github.com/xorbitsai/inference/assets/5937220/866197b4-c4f2-4524-9ad4-8dca8c63b341)

**Comment by lujin1** [comment]
这个问题我也遇到了，有下文吗？

**Comment by TragedyN** [comment]
+1
