### ISSUE TITLE
BUG-使用阿里云modelscope的jupyterlab环境，启动qwen-chat-pytorch-1_8b报错404

### ISSUE THREAD

**Issue by thinkclaves** [xorbitsai/inference#1087]
### Describe the bug

启动命令：xinference-local -H 0.0.0.0 -p 9901  --log-level=debug
硬件环境：2080TI 22G + ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.12.0
错误详细：Server error: 500 - [address=0.0.0.0:39523, pid=3003] Response details: 404 page not found, Request id: 451ca6eba0dd45718a867a36385c2d22

### To Reproduce
To help us to reproduce this bug, please provide information below:

1.使用modelscope环境或者自己部署魔搭docker镜像：registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.12.0
2.启动命令：xinference-local -H 0.0.0.0 -p 9901  --log-level=debug
3.在xinference ui中启动xinference-local -H 0.0.0.0 -p 9901  --log-level=debug
4. 部署qwen-chat-pytorch-1_8b时，UI报错：Response details: 404 page not found, 
5. 日志报错：ERROR - Authentication token does not exist, failed to access model /root/.xinference/cache/qwen-chat-pytorch-1_8b which may not exist or may be                 private. Please login first.

**Comment by ChengjieLi28** [comment]
@thinkclaves @leeeex https://github.com/xorbitsai/inference/issues/1112 参考这个issue，跟你的镜像有关，modelscope镜像是有一些配置在里面的，导致你无法下载模型。
