### ISSUE TITLE
BUG 音频模型不能在魔搭社区下载

### ISSUE THREAD

**Issue by zhapi1780** [xorbitsai/inference#1088]
### Describe the bug
使用如下命令不能从魔搭社区下载音频模型
xinference launch --model-name Belle-distilwhisper-large-v2-zh --model-type audio  -e "http://192.168.101.5:9997"

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. 使用python3.11
2. xinference Version | Release: v0.9.0
3. Versions of crucial packages.
4. Full stack of the error.
xinference launch --model-name Belle-distilwhisper-large-v2-zh --model-type audio  -e "http://192.168.101.5:9997"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\zp\.conda\envs\py3.11\Scripts\xinference.exe\__main__.py", line 7, in <module>
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\xinference\deploy\cmdline.py", line 624, in model_launch
    model_uid = client.launch_model(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zp\.conda\envs\py3.11\Lib\site-packages\xinference\client\restful\restful_client.py", line 830, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=192.168.101.5:14185, pid=15976] Failed to download model 'Belle-distilwhisper-large-v2-zh' after 3 attempts

6. Minimized code to reproduce the error.

### Additional context
使用xinference launch -u my-llama-2 -n llama-2-chat -s 13 -f pytorch  -e "http://192.168.101.5:9997"
可以下载模型文件

**Comment by qinxuye** [comment]
Why closed this issue? @zhapi1780

**Comment by GarciaLiu** [comment]
Same problem with 0.12.0

**Comment by turndown** [comment]
> ### Describe the bug
> 使用如下命令不能从魔搭社区下载音频模型 xinference launch --model-name Belle-distilwhisper-large-v2-zh --model-type audio -e "http://192.168.101.5:9997"
> 
> ### To Reproduce
> To help us to reproduce this bug, please provide information below:
> 
> 1. 使用python3.11
> 2. xinference Version | Release: v0.9.0
> 3. Versions of crucial packages.
> 4. Full stack of the error.
>    xinference launch --model-name Belle-distilwhisper-large-v2-zh --model-type audio  -e "http://192.168.101.5:9997"
>    Traceback (most recent call last):
>    File "", line 198, in _run_module_as_main
>    File "", line 88, in _run_code
>    File "C:\Users\zp.conda\envs\py3.11\Scripts\xinference.exe__main__.py", line 7, in 
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1157, in **call**
>    return self.main(*args, **kwargs)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1078, in main
>    rv = self.invoke(ctx)
>    ^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1688, in invoke
>    return _process_result(sub_ctx.command.invoke(sub_ctx))
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\click\core.py", line 1434, in invoke
>    return ctx.invoke(self.callback, **ctx.params)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\click\core.py", line 783, in invoke
>    return __callback(*args, **kwargs)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\xinference\deploy\cmdline.py", line 624, in model_launch
>    model_uid = client.launch_model(
>    ^^^^^^^^^^^^^^^^^^^^
>    File "C:\Users\zp.conda\envs\py3.11\Lib\site-packages\xinference\client\restful\restful_client.py", line 830, in launch_model
>    raise RuntimeError(
>    RuntimeError: Failed to launch model, detail: [address=192.168.101.5:14185, pid=15976] Failed to download model 'Belle-distilwhisper-large-v2-zh' after 3 attempts
> 5. Minimized code to reproduce the error.
> 
> ### Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ### Additional context
> 使用xinference launch -u my-llama-2 -n llama-2-chat -s 13 -f pytorch -e "http://192.168.101.5:9997" 可以下载模型文件

请问这个问题是不是还没解决啊，我在web上点launch音频模型，也是报错下载失败
