### ISSUE TITLE
Support Gemma 2B/7B

### ISSUE THREAD

**Issue by RayJi01** [xorbitsai/inference#1090]
### Is your feature request related to a problem? Please describe
Support the recent open-sourced Gemma 7B

### Describe alternatives you've considered
Implement the Gemma 2b/7b instruct model is also desirable

### Additional context
https://huggingface.co/google/gemma-2b
https://huggingface.co/google/gemma-7b

**Comment by aresnow1** [comment]
We have supported instruction model in #1024

**Comment by 1fishsauce** [comment]
无法运行
