### ISSUE TITLE
自定义模型Yi-6b，原本是base模型微调后成chat模型，运行后无法进行对话，提示：提示model_revision=None is not for chat.

### ISSUE THREAD

**Issue by leeeex** [xorbitsai/inference#1094]
https://modelscope.cn/models/mrsteamedbun/Yi-Agent-6B-Chat
我跑的是经过微调训练过的Yi-6b模型

自定义模型配置文件
`
{
  "version": 1,
  "context_length": 4096,
  "model_name": "custom-Yi-Agent-6B-Chat",
  "model_lang": [
    "en",
    "zh"
  ],
  "model_ability": [
    "generate"
  ],
  "model_family": "Yi",
  "model_specs": [
    {
      "model_format": "pytorch",
      "model_size_in_billions": 6,
      "quantizations": [
        "none"
      ],
      "model_id": "mrsteamedbun/Yi-Agent-6B-Chat",
      "model_uri": "/mnt/workspace/Yi-Agent-6B-Chat"
    }
  ]
}
`
进行对话测试的提示
![微信图片_20240307160431](https://github.com/xorbitsai/inference/assets/9677686/d8b03a12-0408-4b05-a4bb-b245c68cfe22)

model_ability如果改为chat的话无法注册自定义模型，如果model_family改为Yi-chat，注册模型成功，但是跑模型就提示这个错误：
Failed to launch model, detail: [address=0.0.0.0:43171, pid=1811] Response details: 404 page not found, Request id: 86c68e9443f146529dc94fa2e0200df5

**Comment by ChengjieLi28** [comment]
@leeeex 贴一下xinference完整报错
