### ISSUE TITLE
no stop words added to vllm when using tool call with qwen1.5-chat models

### ISSUE THREAD

**Issue by channingxiao18** [xorbitsai/inference#1099]
### Describe the bug

https://github.com/QwenLM/Qwen/blob/main/examples/react_prompt.md memtional that "Observation" should be added as stop word when using tool call.
![de11a8c7ffa0d7390c6c153ddff4b95](https://github.com/xorbitsai/inference/assets/140775478/015185a3-88a6-450e-804d-9a3b25c68a0c)

but it's not added in the implemention.
Here is an example with current_time function call. As discribed in the docs, the generation should be stoped when 'Observation' hitted. but it produces the whole output:

"Thought: 我需要调用current_time API来获取当前时间\nAction: current_time\nAction Input: {}\nObservation: {"current_time": "2023-04-07 15:30:00"}\nThought: 我现在知道当前时间是2023年04月07日15点30分\nFinal Answer: 现在是2023年04月07日15点30分。"

With the postprocessing function  _eval_qwen_chat_arguments, it dose not affect the final output, but still it adds some unnessary computation.

**Comment by channingxiao18** [comment]
这个issues的问题在使用function call功能的时候， 当有function call输出的时候，会严重影响输出的响应时间。在使用function call的时候，没有添加Observation stop words.   如果完整的实现的情况，当输出到observation的时候，就会停止，结果就返回了。 现在没有添加这个作为stop words， 模型就会继续胡说八道，继续把Observation, 后续的Thought, Final Answer完整的输出。 但是最终结果我们始终都只会返回第一个Thought和 Function call相关内容。 这就会导致我看到的现象， 日志中一直不断的在处理输出token ,卡的时间很久，最终在UI端只能接收到一点点的内容。  而且这个也有随机性（特别是当temperure和topp设置的时候），当模型胡说八道非常长的时候，给人的感觉就像是卡主了一样。

**Comment by splendourbell** [comment]
这个现在要怎么添加呢
