### ISSUE TITLE
自注册的chatglm3 qwen1.5 无法使用vllm模式进行启动

### ISSUE THREAD

**Issue by lyn-my** [xorbitsai/inference#1104]
公司内网环境，只能通过下载模型cop到内网，然后使用模型注册，

多卡启动时发现，未用vllm模式进行启动

使用模型有chatglm3-6b-32k    qwen1.5-7b-chat

**Comment by ChengjieLi28** [comment]
@lyn-my 自定义模型注册时，quantization需要填写正确，什么样的quantization能够跑在VLLM上，请参考文档https://inference.readthedocs.io/zh-cn/latest/user_guide/backends.html
