### ISSUE TITLE
BUG: OpenAI Stream API 实现未完全按照OpenAI 格式输出，可能导致部分OpenAI API Client 实现调用报错

### ISSUE THREAD

**Issue by wertycn** [xorbitsai/inference#1113]
### Describe the bug

使用流式请求时 ，在[OpenAI 的API 官方文档](https://platform.openai.com/docs/api-reference/chat/create)中，SSE的第一个事件， content 字段的值是空字符串，而在inference 的OpenAI API 实现中， SSE的第一个事件，content 字段字段不存在， 相当于  content = null，部分OpenAI API Client 实现中，对content字段做了NotNull 校验(如Spring AI)，这将会导致客户端调用异常

inference 响应
```
data: {"id": "chata240e594-ded3-11ee-bd37-1a757c6c50cc", "model": "chatglm3", "created": 1710071103, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"role": "assistant"}, "finish_reason": null}]}

data: {"id": "chata240e594-ded3-11ee-bd37-1a757c6c50cc", "model": "chatglm3", "created": 1710071103, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}
```

OpenAI 响应
```
{"id":"chatcmpl-123","object":"chat.completion.chunk","created":1694268190,"model":"gpt-3.5-turbo-0125", "system_fingerprint": "fp_44709d6fcb", "choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}

{"id":"chatcmpl-123","object":"chat.completion.chunk","created":1694268190,"model":"gpt-3.5-turbo-0125", "system_fingerprint": "fp_44709d6fcb", "choices":[{"index":0,"delta":{"content":"Hello"},"logprobs":null,"finish_reason":null}]}
```

查看相关代码实现后，第一条消息固定返回如图：
![image](https://github.com/xorbitsai/inference/assets/35490288/9ebe4601-0d0f-424c-a2ff-a72bb5facc2d)

只需要在此处添加一行·"content"：”“` , 即可

### To Reproduce

inference version 0.9.2

### Expected behavior

与OpenAI 官方API 输出保持一致 

### Additional context

稍后我会尝试提交PR修复

**Comment by wertycn** [comment]
补充，除格式外，在SSE 消息体的ID 字段中，xinference 的OpenAI API 实现逻辑也不一致 , OpenAI 统一角色的输出，ID 是一致的，而xinference 每次都会发生改变  , 在部分第三方OpenAI API 客户端的实现中，由于不是每个SSE 的事件都携带了`role` 信息,部分框架(如Spring AI) 是使用id 来定位获取role 的 ， 这也将导致客户端以openai 的协议请求xinference 提供的接口出现异常，同时影响相比于 `content`字段更大

For OpenAI 官方文档 
![image](https://github.com/xorbitsai/inference/assets/35490288/d2c5e27c-25a8-4b06-87a7-0a1e7059590d)

实测OpenAI API请求：
![image](https://github.com/xorbitsai/inference/assets/35490288/986cf699-defd-480d-b0d2-c8aa3fc546e2)

Xinference OpenAI API  请求：
![image](https://github.com/xorbitsai/inference/assets/35490288/8b18b07c-ff9a-43c9-a07a-b633f7973771)

可以看到 Xinference OpenAI API  的输出ID每次都不一样

**Comment by ChengjieLi28** [comment]
@mujin2 will fix this

**Comment by wertycn** [comment]
补充信息：
简单查看后发现相关的实现有好几处，，目前本地使用的chatglm  模型， 通过sed命令本地临时替换代码修复（只涉及chatglm相关实现，不包含其他模型实现）， 可供修复参看


```shell
# 第一条消息添加 content 字段
sed -i '453 a \                        "content":""' xinference/model/llm/utils.py
# chunk_id 在for 循环前创建
sed -i '150 a \                    chunk_id = "debug-"+str(uuid.uuid1())' xinference/model/llm/pytorch/chatglm.py
# 替换id 赋值未循环前创建的chunk_id
sed -i '161d'  xinference/model/llm/pytorch/chatglm.py
sed -i '160 a \                            id=chunk_id,' xinference/model/llm/pytorch/chatglm.py
```

**Comment by mujin2** [comment]
@wertycn 收到.  I'll take this issue

**Comment by mujin2** [comment]
take
