### ISSUE TITLE
百川模型的切割存在问题

### ISSUE THREAD

**Issue by wuyeguo** [xorbitsai/inference#1125]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. python 3.10
2. xinference, version 0.9.1
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context

百川的配置：
{'model_uid': 'baichuan-2-chat-1-0', 'model_name': 'baichuan-2-chat', 'model_size_in_billions': 13, 'model_format': 'pytorch', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 'auto', 'request_limits': None}
百川的版本：v2.0.1

多轮对话的第二轮开始出错
cat baichuan.json
{
  "messages": [
    {
      "role": "system",
      "content": "你是一个助手"
    },
    {
      "role": "user",
      "content": "清朝的末代皇帝是谁？"
    },
    {
      "role": "assistant",
      "content": "清朝的末代皇帝是溥仪。他是中国历史上最后一个皇帝，也是清朝的最后一位君主。"
    },
    {
      "role": "user",
      "content": "末代皇帝的名字的拼音是？"
    }
  ],
  "model": "baichuan-2-chat",
  "max_tokens": 2001,
  "stream": false,
  "temperature": 0.01,
  "top_p": 1,
  "user": "933ee52d-ae01-4704-9229-2b15c4a81571"
}

返回结果：
curl -X POST -H "Content-Type: application/json" -d@baichuan.json  http://172.16.1.76:9997/v1/chat/completions -s | jq
{
  "id": "chatc62c6960-df91-11ee-8039-0242ac110002",
  "object": "chat.completion",
  "created": 1710152768,
  "model": "baichuan-2-chat",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "的拼音是？<reserved_107>溥仪"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 39,
    "completion_tokens": 1,
    "total_tokens": 40
  }
}

**Comment by yinghaodang** [comment]
我也遇到了这个问题。不管是用内置的模型还是用自己添加的模型都有这个问题。不是必定出现的。
偶尔会出现。
