### ISSUE TITLE
Embedding 并行

### ISSUE THREAD

**Issue by 1102asd** [xorbitsai/inference#1129]
在使用多线程或者多进程进行embedding时，可以发现embedding不支持并发

**Comment by ChengjieLi28** [comment]
@1102asd `create_embedding`接口可以支持传多个字符串同时让一个embedding模型去生成向量。

**Comment by xrkk** [comment]
> 字符串同时让一个embedd

在使用FastGPT时，FastGPT默认开启15个进程来并行请求嵌入操作，而且每个进程只请求嵌入单个字符串。我查看了FastGPT的源码，要魔改FastGPT使其 “每次请求嵌入时同时传递多个字符串” 很困难。我还尝试了预先把嵌入结果写入到磁盘，xinference启动时从磁盘读取嵌入结果，在create_embedding中匹配缓存的嵌入结果，发现，依然超级慢。

强烈建议支持 create_embedding 并行！

**Comment by 1102asd** [comment]
@ChengjieLi28 尝试修改为了一个文档以list[str]的形式传递  最终多任务依旧是不能并行  只是减少了请求次数  单个embedding请求的时间变长  依旧解决不了问题

**Comment by ChengjieLi28** [comment]
@xrkk @1102asd xinference里面的embedding依托SentenceTransformers实现，但个embedding模型是没法支持并行请求的。详见https://github.com/UKPLab/sentence-transformers/issues/1585。
目前只能多起embedding模型的副本来做到这一点。

**Comment by xrkk** [comment]
> @ChengjieLi28 尝试修改为了一个文档以list[str]的形式传递 最终多任务依旧是不能并行 只是减少了请求次数 单个embedding请求的时间变长 依旧解决不了问题

@1102asd 老哥，你的场景是啥样我不清楚，我用FastGPT嵌入速度慢的原因找到了。我单独写了个脚本，用多进程直接访问xinference的create_embedding()接口, 虽然用于处理请求的进程只有1个，但每个进程的请求都是被异步处理的，速度也很快。而FastGPT默认会启动15个嵌入进程，不知道为啥只有1个，撸一把FastGPT的源码应该能找到原因。

**Comment by 1102asd** [comment]
此问题可以关闭   可以多进程或者多线程访问

**Comment by buctllx** [comment]
> @xrkk @1102asd xinference里面的embedding依托SentenceTransformers实现，单个embedding模型是没法支持并行请求的。详见[https://github.com/UKPLab/sentence-transformers/issues/1585。](https://github.com/UKPLab/sentence-transformers/issues/1585%E3%80%82) 目前只能多起embedding模型的副本来做到这一点。

你好，请问如何起多个副本？
