### ISSUE TITLE
BUG：多GPU环境，docker v0.9.2 modelscope源启动bge-reranker-base和bge-reranker-large模型失败

### ISSUE THREAD

**Issue by bigzws** [xorbitsai/inference#1132]
Web UI 显示bge-reranker-base或bge-reranker-large运行在GPU1上
![image](https://github.com/xorbitsai/inference/assets/45476210/6eb1eed9-09c5-4f71-98fd-a79df4c810d1)
但GPU1上无任何模型运行
使用dify验证，模型不能被调用。
但在单GPU环境，rerank模型运行在GPU0上，模型可以正常启动

**Comment by qinxuye** [comment]
调用报错有错误栈吗？

**Comment by bigzws** [comment]
![屏幕截图 2024-03-12 145107](https://github.com/xorbitsai/inference/assets/45476210/d7e2a2aa-f7df-4698-bef1-34facf78798c)
![bb88e6e284609d6e24a005946232a01](https://github.com/xorbitsai/inference/assets/45476210/30197d32-36fe-46ac-ac50-b5f0e4961db2)

**Comment by qinxuye** [comment]
xinference 日志的错误有没有

**Comment by bigzws** [comment]
![image](https://github.com/xorbitsai/inference/assets/45476210/9a056422-6e4f-4850-af83-6032c9ad7667)docker
无任何报错

**Comment by qinxuye** [comment]
感觉 dify 的请求没有打过来？dify 的版本是最新的吗

**Comment by bigzws** [comment]
dify v0.5.8，在单卡上可以调用rerank模型。测试将qwen 1.5 运行在GPU1上，也可以被正常调用。只有bge-reranker存在这个问题

**Comment by bigzws** [comment]
找到原因了，启动rerank模型失败的机器，cuda版本12.2；启动rerank模型成功的机器cuda版本12.1

**Comment by qinxuye** [comment]
我们镜像应该是基于12.1 的。
