### ISSUE TITLE
BUG：v0.9.2 modelscope源启动bge-reranker-base和bge-reranker-large模型失败

### ISSUE THREAD

**Issue by bigzws** [xorbitsai/inference#1136]
### Describe the bug
显卡 RTX3090，驱动530.30.2，cuda V12.1.105，bge-reranker-base和bge-reranker-large模型不能被正常启动，且无报错

### To Reproduce

1. conda 4.5.11，python 3.10
2. pip install "xinference[all]"
3. XINFERENCE_MODEL_SRC=modelscope XINFERENCE_HOME=/home/rkty/models xinference-local --host 0.0.0.0 --port 9997
4. xinference launch --model-name bge-reranker-large --model-type rerank --model-uid 12
5.  xinference list

### Expected behavior
没有模型被加载，且无报错

### Attachment
![屏幕截图 2024-03-13 084614](https://github.com/xorbitsai/inference/assets/45476210/2ef0e302-8ded-44fc-b13a-eb7a159e9bd3)
![屏幕截图 2024-03-13 084541](https://github.com/xorbitsai/inference/assets/45476210/457a1b56-668e-4265-a422-5289190b18e0)
![屏幕截图 2024-03-13 084550](https://github.com/xorbitsai/inference/assets/45476210/5cdd192f-fa9d-4403-ad49-9f4a0ddf50ca)

**Comment by bigzws** [comment]
在RTX 4090上复现了这个问题，驱动版本 535.129.03，cuda版本 11.8.89，conda 22.11.1，python 3.10
1、启动bge-reranker-large uuid=12，xinference list无启动模型
2、启动bge-large-zh-v1.5 uuid=12，报错uuid重复
3、启动bge-large-zh-v1.5 uuid=13，xinference list显示模型正常启动，显存被正常占用
![屏幕截图 2024-03-13 100051](https://github.com/xorbitsai/inference/assets/45476210/0c2f1df5-9e93-4c3b-9e73-1141f4855fe4)
![屏幕截图 2024-03-13 100359](https://github.com/xorbitsai/inference/assets/45476210/6bc255c7-0aaa-43b0-9f8e-b0e10d27da74)

**Comment by ChengjieLi28** [comment]
@bigzws 收到。我这边可以复现，本周发布新版时将修复。原因是xinference list命令目前还没有加入rerank模型的显示。
另外，launch rerank模型后看不到显存占用是正常的，embedding和rerank模型要在真正使用时才会看到显存占用。

**Comment by bigzws** [comment]
另外，基于我目前的情况，还有一个问题，dify调用bge-reranker报错，但是在xinference服务中，没有任何报错提示.
![屏幕截图 2024-03-13 112742](https://github.com/xorbitsai/inference/assets/45476210/b42d6275-df3f-49ba-b52f-53ebe340b134)
![屏幕截图 2024-03-13 112736](https://github.com/xorbitsai/inference/assets/45476210/6f05312c-373a-40e3-82b1-3a763c8d95f8)

**Comment by bigzws** [comment]
dify版本0.5.8

**Comment by ChengjieLi28** [comment]
@bigzws dify问题请到dify社区咨询
