### ISSUE TITLE
下载bce-reranker-base_v1模型失败

### ISSUE THREAD

**Issue by redstarxz** [xorbitsai/inference#1142]
### Describe the bug

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.modelscope.cn/api/v1/models/maidalun/bce-reranker-base_v1/revisions?EndTime=1710318039

**Comment by Ago327** [comment]
该模型在modelscope上属于申请制，需要登录账号以后在modelscope上也得跟作者申请，通过了才能下载

**Comment by Ago327** [comment]
该模型在modelscope上属于申请制，需要登录账号以后在modelscope上跟作者申请，通过了才能下载

**Comment by redstarxz** [comment]
> 该模型在modelscope上属于申请制，需要登录账号以后在modelscope上跟作者申请，通过了才能下载

可这是在程序里启动下载的，我如果登录账号申请后，怎么能让程序可以直接下载呢？

**Comment by codingl2k1** [comment]
可以参考这个试试登陆你的access token：https://modelscope.cn/docs/ModelScope%20Hub%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
