### ISSUE TITLE
OpenAI Compatible API Incompatibility

### ISSUE THREAD

**Issue by KaedinLian** [xorbitsai/inference#1143]
### Describe the bug
I am reporting an issue encountered while using the xinference library version 0.9.1 with the qwen1.5 model. When attempting to leverage the OpenAI-compatible API, specifically during the invocation of the `ConversableAgent._reflection_with_llm()` function in Autogen, , which automatically appends a summary system message at the end of a dialogue, I encounter a BadRequestError with the following message:

`BadRequestError: Error code: 400 - {'detail': 'System message should be the first one.'}`

This error arises due to the system message not being the first message in the message history. However, this issue does not occur when using an official OpenAI key.

### To Reproduce

1. Deploy the xinference: 0.9.1 Docker container with the qwen1.5-chat model.
2. Full error stack trace: `BadRequestError: Error code: 400 - {'detail': 'System message should be the first one.'}`
3. Simplified reproduction code snippet using curl:
```
curl http://localhost:9997/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer sk-anykey"   -d '{
    "model": "qwen1.5",
    "messages": [
      {
        "role": "user",
        "content": "What is triangle inequality?"
      },
      {
        "role": "assistant",
        "content":"The triangle inequality is a fundamental geometric concept that states that the sum of the lengths of any two sides of a triangle is always greater than or equal to the length of the third side. In other words, in a triangle, if you have two sides a and b, and a third side c, the following inequality must hold:\n\na + b > c\nb + c > a\nc + a > b\n\nThis inequality ensures that the three sides create a valid geometric triangle, as it prevents the formation of a \"triangle\" where the third side is shorter than the combined length of the other two. It is a simple yet essential principle in geometry, particularly in measuring distances and understanding the properties of triangles."
      },
      {
        "role": "system",
        "content": "Summarize the takeaway from the conversation. Do not add any introductory phrases."
      }
    ]
  }'
```

### Expected behavior
xinference's openai compatible API should handle message histories consistently with the actual OpenAI API, even when system messages are not at the beginning of the message sequence.

### Additional context
It would be greatly appreciated if the developers could look into improving the compatibility of xinference's openai compatible API to better align with the official OpenAI API behavior.

Thank you for your attention to this matter!

**Comment by ChengjieLi28** [comment]
@mujin2 will fix this

**Comment by mujin2** [comment]
take
