### ISSUE TITLE
DOC: add doc about adding extra params for backends like ggml and vllm

### ISSUE THREAD

**Issue by qinxuye** [xorbitsai/inference#1148]
Note that the issue tracker is NOT the place for general support.

**Comment by ChengjieLi28** [comment]
已经有了https://inference.readthedocs.io/zh-cn/latest/getting_started/using_xinference.html
<img width="785" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/a9d077ce-3a13-421f-90d9-09d577bec0b9">

**Comment by qinxuye** [comment]
我知道这个，不太全面，没有写在各个后端的位置。
