### ISSUE TITLE
QUESTION：如何强制使用huggingface下载模型？

### ISSUE THREAD

**Issue by lakako** [xorbitsai/inference#1149]
Note that the issue tracker is NOT the place for general support.

环境变量XINFERENCE_MODEL_SRC为空，在代理里看xinference会从modelscope下载mixtral-v0.1
模型，有没有办法强制从huggingface下载模型？

**Comment by ChengjieLi28** [comment]
设置环境变量`XINFERENCE_MODEL_SRC`为`huggingface`

**Comment by ChengjieLi28** [comment]
参考：https://inference.readthedocs.io/zh-cn/latest/getting_started/environments.html#xinference-model-src
