### ISSUE TITLE
qwen1.5 chat 14b 上下文没有 32k，差不多超过 8k 就不输出了是什么情况?

### ISSUE THREAD

**Issue by LucisBaoshg** [xorbitsai/inference#1151]
WARNING 03-15 14:52:00 scheduler.py:195] Input prompt (4108 tokens) is too long and exceeds limit of 4096

**Comment by YYLCyylc** [comment]
默认的max_model_len是4096，启动的时候加个参数--max_model_len 32000就行了

**Comment by ybsbbw** [comment]
> 默认的max_model_len是4096，启动的时候加个参数--max_model_len 32000就行了
我shell下输入命令xinference launch -u Qwen1.5-72B-chat -n Qwen1.5-72B-chat -s 72 -f pytorch --max_model_len 32000，
结果反馈没有--max_model_len这个option

**Comment by ybsbbw** [comment]
另外按照官网的python启动方式启动的时候，输入命令：
from xinference.client import RESTfulClient
client = RESTfulClient("http://127.0.0.1:9997")
model_uid = client.launch_model(
  model_uid="my-llama-2",
  model_name="llama-2-chat",
  model_format="pytorch",
  size_in_billions=13
)
print('Model uid: ' + model_uid)
提示没有size_in_billions这个参数

**Comment by YYLCyylc** [comment]
> > 默认的max_model_len是4096，启动的时候加个参数--max_model_len 32000就行了
> > 我shell下输入命令xinference launch -u Qwen1.5-72B-chat -n Qwen1.5-72B-chat -s 72 -f pytorch --max_model_len 32000，
> > 结果反馈没有--max_model_len这个option

更新下xinference的版本试试？
![image](https://github.com/xorbitsai/inference/assets/50295520/2e6798ed-7b85-4603-acc0-40b91a64ac95)
现在应该是model_size_in_billions这个参数
![image](https://github.com/xorbitsai/inference/assets/50295520/fabc4271-0563-4d82-b901-ae6a70aac056)

**Comment by ybsbbw** [comment]
我现在是0.9.0

**Comment by YYLCyylc** [comment]
> 我现在是0.9.0

参数传递好像是0.9.1加的
https://github.com/xorbitsai/inference/pull/1048

**Comment by ybsbbw** [comment]
> > 我现在是0.9.0
> 
> 参数传递好像是0.9.1加的 #1048

简直了

**Comment by Air-duct** [comment]
docker 启动的怎么传递这个参数呢？

**Comment by Valdanitooooo** [comment]
Same here, 在web中启动时加个参数可以解决
![image](https://github.com/user-attachments/assets/33f5ca97-52e3-43ee-a0a1-6bf912c26dae)
