### ISSUE TITLE
ENH: vLLM latest models support 

### ISSUE THREAD

**Issue by luweizheng** [xorbitsai/inference#1154]
vLLM supports more [models](https://github.com/vllm-project/vllm/releases) and we defined them in `xinference/model/llm/vllm/core.py` should we update the `VLLM_SUPPORTED_MODELS` and `VLLM_SUPPORTED_CHAT_MODELS`
in the following ways:

```
if VLLM_INSTALLED and vllm.__version__ >= "0.3.2":
    VLLM_SUPPORTED_CHAT_MODELS.append("gemma-it")
```

**Comment by qinxuye** [comment]
Yes. In the 0.9.3 we just add support for vllm>0.3.3. Some models could be absent.
