### ISSUE TITLE
BUG: 不支持qwen1.5-72b-chat-int4的function call？

### ISSUE THREAD

**Issue by yaoyasong** [xorbitsai/inference#1162]
### Describe the bug
用xinference部署了qwen1.5-72b-chat-int4，不支持function call?

入参：

POST http://10.10.1.1:8080/v1/chat/completions HTTP/1.1

{
    "model": "qwen-1.5",
    "messages": [
        {
            "role": "user",
            "content": "帮我查询股票10111的价格"
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "track",
                "description": "追踪指定股票的实时价格",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "symbol": {
                            "description": "需要追踪的股票代码"
                        }
                    },
                    "required": [
                        "symbol"
                    ]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "text-to-speech",
                "description": "将文本转换为语音",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "text": {
                            "description": "需要转换成语音的文本"
                        },
                        "voice": {
                            "description": "要使用的语音类型（男声、女声等）"
                        },
                        "speed": {
                            "description": "语音的速度（快、中等、慢等）"
                        }
                    },
                    "required": [
                        "text"
                    ]
                }
            }
        }
    ],
    "stop": [
        "\n"
    ]
}

结果：
{
  "object": "chat.completion",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Thought: 需要用到track api来查询股票价格，但是track api需要输入股票代码，而我只知道股票名字，所以我需要先使用搜索工具找到对应的股票代码。",
        "tool_calls": []
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": -1,
    "completion_tokens": -1,
    "total_tokens": -1
  }
}

**Comment by codingl2k1** [comment]
这个结果是比较符合预期的，可以看到返回了 Thought，说明已经进入了 React 模式进行 tool call 了，但是由于模型理解力限制或者 prompt 准确度问题，它这次没有 tool call 成功。可以试试把参数类型改成 int ，可能会好一点，也可以试试调整 temperature。
```
{
"type": "function",
"function": {
"name": "track",
"description": "追踪指定股票的实时价格",
"parameters": {
"type": "object", # <------int试试？
"properties": {
"symbol": {
"description": "需要追踪的股票代码"
}
```

**Comment by yaoyasong** [comment]
调整了temperature=0，换了更通用的问法："content": "帮我查询股票IBM的价格"

回复：
"message": {
        "role": "assistant",
        "content": "Thought: 需要使用track API来查询股票价格，输入参数为股票代码IBM",
        "tool_calls": []
      },
      
 信息似乎都找出来了，但tool_calls还是空的
 
 看qwen模型的debug信息：

  DEBUG    Tool call content: Thought: 需要使用track API来查询股票价格，输入参数为股票代码IBM, func: None, args: None

**Comment by yaoyasong** [comment]
应该是输入参数的问题
"stop": [
"\n"
]

去掉就可以了
