### ISSUE TITLE
Missing audio model tab.

### ISSUE THREAD

**Issue by vindia9** [xorbitsai/inference#1174]
### Is your feature request related to a problem? Please describe
In both the Launch Model and Running Models pages, the Audio Model tab is not provided.
But when the audio model is running, the response content returned by the API when accessing the Launch Model includes information about the audio model

### Describe the solution you'd like
Add an Audio Model tab to the Launch Model and Running Models pages.

### Describe alternatives you've considered
¯¯\\_( ͡° ͜ʖ ͡°)_/¯¯

### Additional context

<img width="1507" alt="image" src="https://github.com/xorbitsai/inference/assets/9072630/cbfb760e-cfde-45cb-b27f-4907e474b5a4">

**Comment by qinxuye** [comment]
Addressed by #1102 .
