### ISSUE TITLE
自定义模型注册

### ISSUE THREAD

**Issue by 253071608** [xorbitsai/inference#1179]
### Is your feature request related to a problem? Please describe
猿猿圆圆，
特定环境只支持离线部署，模型只能注册后才能使用。
image(stable-diffusion-v1.5) , 
audio(whisper-large-v3),  
vl(qwen-vl-chat-int4),
......等模型注册失败。

**Comment by Ago327** [comment]
可以提供一下报错日志吗？注册模型的步骤也麻烦贴一下

**Comment by Ago327** [comment]
可以提供一下报错日志吗？注册模型的步骤也麻烦贴一下
