### ISSUE TITLE
4卡3090手动launch qwen1.5-chat-gptq-72b-Int4模型时报错：The number of required GPUs exceeds the total number of available GPUs in the cluster.

### ISSUE THREAD

**Issue by elepherai** [xorbitsai/inference#1183]
机器：4卡3090 24G显存
OS：Ubuntu 22.04
xinference版本：v0.9.4

我停掉其他占用显存的程序后，在docker容器里运行如下指令：
`xinference launch --model-name qwen1.5-chat --size-in-billions 72 --model-format gptq --gpu_memory_utilization 0.86 --quantization Int4 --tensor_parallel_size 4 --max_model_len 2048 -e http://0.0.0.0:9997`

报错：
The number of required GPUs exceeds the total number of available GPUs in the cluster.

![image](https://github.com/xorbitsai/inference/assets/43477405/588751a3-9757-4efd-8217-79fe4f6bbde1)

请问如何解决？

**Comment by elepherai** [comment]
补充：直接在容器里用vllm是没问题的

`python -m vllm.entrypoints.openai.api_server --model /root/.cache/modelscope/hub/qwen/Qwen1___5-72B-Chat-GPTQ-Int4 --gpu-memory-utilization 0.86 --max-model-len 2048 --tensor-parallel-size 4`

![image](https://github.com/xorbitsai/inference/assets/43477405/85b80c26-f6b3-42bc-9559-56bc52d8c900)

**Comment by qinxuye** [comment]
服务端的日志有吗？

**Comment by elepherai** [comment]
[xinference.log](https://github.com/xorbitsai/inference/files/14738365/xinference.log)
是这个吗？

**Comment by qinxuye** [comment]
launch 指定 --n-gpu 4 看下

**Comment by elepherai** [comment]
可以了，感谢感谢！
