### ISSUE TITLE
BUG: cannot open Web UI for docker image

### ISSUE THREAD

**Issue by binbinup** [xorbitsai/inference#1184]
### Describe the bug
xprobe/xinference:latest 镜像缺少main.66b1c4fb.js，xinference前端配置页面无法打开

**Comment by binbinup** [comment]
> ### Describe the bug
> xprobe/xinference:latest 镜像缺少main.66b1c4fb.js，xinference前端配置页面无法打开

<img width="766" alt="739aad5c867d629d8951109ae86f2da" src="https://github.com/xorbitsai/inference/assets/86513211/90d3d608-d70a-4481-aa51-e6ac820bfd0a">

**Comment by ChengjieLi28** [comment]
@binbinup 怎么启动的docker image?

**Comment by binbinup** [comment]
> @binbinup 怎么启动的docker image? 我这边没有复现

docker run \
  -v /model/llm:/model/llm \
  -p 9005:9997 \
  --gpus all \
  xprobe/xinference:latest> \
  xinference-local -H 0.0.0.0

**Comment by binbinup** [comment]
> @binbinup 怎么启动的docker image? 我这边没有复现
不好意思又可以用了。 奇怪。

**Comment by ChengjieLi28** [comment]
先close，有问题再开
