### ISSUE TITLE
BUG: GPU index for a running model may mismatch

### ISSUE THREAD

**Issue by qinxuye** [xorbitsai/inference#1191]
### Describe the bug

GPU index for a model may display wrong.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

![image](https://github.com/xorbitsai/inference/assets/357506/3f0c426f-cb97-40b0-afb7-649944285790)

**Comment by SakuraXs** [comment]
通过指定gpu_idx指定GPU启动，idx对应错误
启动脚本
`
from xinference.client import Client
client = Client("http://127.0.0.1:9997/")
config = {
    "gpu_memory_utilization": 0.9,
    "enforce_eager": True,
    "max_model_len": 32768,# 32768
    "gpu_idx":[3,4]
}
model_uid = client.launch_model(
    model_name="qwen",
    model_size_in_billions=14,
    model_format="gptq",
    quantization="4-bits",
    replica=1,
    n_gpu=2,
    trust_remote_code=True,
    **config
)

model = client.get_model(model_uid)
print(model)
`
GPU指定3，4实际使用0，4
![image](https://github.com/xorbitsai/inference/assets/22899569/7596f545-5d0f-4c11-8028-025a420f5ffa)
