### ISSUE TITLE
Can xinference launch surpose the image model such as stable-diffusion-2-1  which is local pattern?

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#1196]
can xinference launch surpose the image model  which is local pattern？ this is my shell 
```
 xinference launch -u miic_graph -n  /usr/local/models/stabilityai/stable-diffusion-2-1 -t image -e "http://127.0.0.1:8888"
```
result:
```
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:32036, pid=177526] Image model /usr/local/models/stabilityai/stable-diffusion-2-1 not found, availablemodel list: dict_keys(['sd-turbo', 'sdxl-turbo', 'stable-diffusion-v1.5', 'stable-diffusion-xl-base-1.0'])

```

**Comment by Songjiadong** [comment]
if it is supporsed,can we give me a simple demo?

**Comment by qinxuye** [comment]
This is a feature we want to add, that is like --model-path xxx, which just uses the default model but with a local path.

This is not implemented yet.

**Comment by Songjiadong** [comment]
@qinxuye  Approximately when will this feature be released？

**Comment by qinxuye** [comment]
This is only work for xinference-local, we plan to add this in 2 weeks approximately, but PR welcomed.

**Comment by qinxuye** [comment]
After discussion internally, we found this feature is underestimated, we may need some refactor, so 2 weeks is not enough, welcome to give advice anyway.
