### ISSUE TITLE
注册embedding 模型后，启动的时候如何设置cpu而不是gpu驱动？

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#1197]
注册embedding 模型后，启动的时候如何设置cpu而不是gpu驱动？目前默认是gpu启动，不知道如何修改？

**Comment by Songjiadong** [comment]
xinference launch -u miic_bge_m3 -n  miic_bge_m3 -t embedding  -e "http://127.0.0.1:8888"

**Comment by ChengjieLi28** [comment]
> xinference launch -u miic_bge_m3 -n miic_bge_m3 -t embedding -e "http://127.0.0.1:8888"

--n-gpu None试试

**Comment by Songjiadong** [comment]
@ChengjieLi28 谢谢！
