### ISSUE TITLE
希望运行embedding模型和rerank模型的时候可以指定gpu的device_id

### ISSUE THREAD

**Issue by biubiuqiu** [xorbitsai/inference#1207]
多gpu场景下目前embedding模型和rerank模型运行的gpu是自动指定的，试了一下会从现有的gpu里一个一个遍历着用，希望可以指定device_id直接指定运行在某一个gpu上，方便多gpu的时候资源分配，前面看到可以通过环境变量改，但是改环境变量的话太死了，希望可以每次启动模型的时候灵活的指定。

**Comment by ChengjieLi28** [comment]
@biubiuqiu  本周发布的版本中将会支持此功能
