### ISSUE TITLE
[Feature request] Support stream=True in tool calls when using vllm

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#1208]
### Is your feature request related to a problem? Please describe

Refer to our previous discussion in the FastGPT issue area.

https://github.com/labring/FastGPT/issues/1046

With the release of Qwen1.5 last month, open-source LLMs now have significant tool calling capabilities. 
Currently, xinference does not support setting stream=True in tool calls.

### Describe the solution you'd like

Based on my research so far, https://github.com/xusenlinzy/api-for-open-llm has implemented a design that appears to be quite scalable, see:

https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/vllm_routes/chat.py

To implement streaming processing for tool calls, xinference should consider rewriting the streaming response function: https://github.com/xorbitsai/inference/blob/5a83dd5774942e0409872f362e9d8eb52a95c6c3/xinference/model/llm/vllm/core.py#L319

**Comment by qinxuye** [comment]
Do you have interest to implement this?

**Comment by zhanghx0905** [comment]
> Do you have interest to implement this?

Of course, I will try to implement the feature as I need it. But I'm not sure when I'll be done, and if I am, I'll submit a pr for you guys!

**Comment by qinxuye** [comment]
Thank you in advance.

BTW, you can comment with a single word `take` to assign this thread to yourself to tell others you are working on it.

**Comment by yanmao2023** [comment]
这个功能是急需的，也是目前xinference的一个受限

**Comment by zhanghx0905** [comment]
take

**Comment by leoterry-ulrica** [comment]
> take

测试验证通过了么？

**Comment by zhanghx0905** [comment]
> 测试验证通过了么？

仍然 WIP。如果你想试试，可以拉取 https://github.com/zhanghx0905/inference/tree/dev-streaming-tools，并执行 `pip install -e .`

**Comment by lm970585581** [comment]
使用python3.11启动会报错
pkg_resources.UnknownExtra: typer 0.12.0 has no such extra feature 'all'

**Comment by lm970585581** [comment]
> > 测试验证通过了么？
> 
> 仍然 WIP。如果你想试试，可以拉取 https://github.com/zhanghx0905/inference/tree/dev-streaming-tools 并执行 `pip install -e .`

用你的分支使用python3.10和3.11启动都会报错
pkg_resources.UnknownExtra: typer 0.12.0 has no such extra feature 'all'
这是什么原因呢？

**Comment by leoterry-ulrica** [comment]
@zhanghx0905 虽然没报错了，但没能正确调用工具。
