### ISSUE TITLE
docs#的接口添加参数示例，方便用户使用

### ISSUE THREAD

**Issue by linhao622** [xorbitsai/inference#1209]
希望给docs#里的每个接口添加参数示例，
<img width="1393" alt="image" src="https://github.com/xorbitsai/inference/assets/144365459/5c43cc57-feb8-493d-9848-232861a23db4">
隔壁llama-cpp-python的接口文档里都有参数示例，希望跟那个一样：
<img width="1419" alt="image" src="https://github.com/xorbitsai/inference/assets/144365459/449a0b74-2535-49f5-a91e-a0e63490ab50">

**Comment by 1572161937** [comment]
take
