### ISSUE TITLE
在使用vllm运行模型失败时出现一直占用gpu问题（The gpu occupied problem occurred when the model failed to run using vllm）

### ISSUE THREAD

**Issue by zscxc** [xorbitsai/inference#1212]
### Is your feature request related to a problem? Please describe
使用两张4090跑了一个较为大的模型出现失败时一直占用gpu，将后台任务杀掉之后gpu并没有得到释放

### Describe the solution you'd like
建议添加“xinference stop”来停止后台运行的进程

### Describe alternatives you've considered
建议添加“xinference stop”来停止后台运行的进程
It is recommended to add xinference stop to stop processes running in the background

### Additional context
<img width="625" alt="image" src="https://github.com/xorbitsai/inference/assets/57797942/670edd5c-9316-48b2-8110-4f04854c99c2">
<img width="747" alt="image" src="https://github.com/xorbitsai/inference/assets/57797942/5c45c61d-8d28-4f33-a1b1-2777626ba17a">

**Comment by ChengjieLi28** [comment]
@zscxc 启动完两卡的vllm模型又执行了什么操作？看起来你没有terminate掉上面的模型

**Comment by zscxc** [comment]
> @zscxc启动完成两卡的vllm模型又执行了什么操作？看起来你没有终止上面的模型

我启动报错了之后我先去查看是否启动了，接着查看日志发现oom了，我以为没啥问题了，就想着启动别打模型吧，结果提示我已经满了，我就去kill所有进程，接着查看我的gpu发现还在被占用

**Comment by ChengjieLi28** [comment]
> > @zscxc启动完成两卡的vllm模型又执行了什么操作？看起来你没有终止上面的模型
> 
> 我启动报错了之后我先去查看是否启动了，接着查看日志发现oom了，我以为没啥问题了，就想着启动别打模型吧，结果提示我已经满了，我就去kill所有进程，接着查看我的gpu发现还在被占用

你这里提到的OOM日志贴一下，可能触发了自动重新launch，导致你的显卡被占用。
另外，kill进程的时候，找到xinference 端口对应的进程，杀那个进程。
```
lsof -i:<xinference web port>
```

**Comment by zscxc** [comment]
> > > @zscxc启动完成两卡的vllm模型又执行了什么操作？看起来你没有终止上面的模型
> > 
> > 
> > 我启动报错了之后我先去查看是否启动了，接着查看日志发现oom了，我以为没啥问题了，就想着启动别打模型吧，结果提示我已经满了，我就去kill所有进程，接着查看我的gpu发现还在被占用
> 
> 你这里提到的OOM日志贴一下，可能触发了自动重新launch，导致你的显卡被占用。 另外，kill进程的时候，找到xinference 端口对应的进程，杀那个进程。
> 
> ```
> lsof -i:<xinference web port>
> ```

都关了，使用了lsof -i:<xinference web port>
ps aux | grep xinference 采用这些命令来进行查看后台的任务，并且使用kill -9 名了把进程都关了，但是gpu仍然被占用，最后使用killall python才完全关闭
