### ISSUE TITLE
是否支持注册本地文生图模型或音频模型？

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#1214]
是否支持注册本地文生图模型或音频模型？即：直接将路径指定到模型的文件夹的方式，我看文档中只有LLM或嵌入模型或rerank模型的案例，是否支持图像模型、音频模型？

**Comment by Songjiadong** [comment]
如果支持，能够给一个案例demo？

**Comment by ChengjieLi28** [comment]
@Songjiadong 暂不支持，需要排期，欢迎提PR
