### ISSUE TITLE
v0.10.0-cpu docker image not working

### ISSUE THREAD

**Issue by YohannesGetu** [xorbitsai/inference#1216]
### Describe the bug
The new realse of xinference docker cpu image  v0.10.0-cpu not runing

### To Reproduce
Docker run -p 9997:9997 xprobe/xinference:v0.10.0-cpu xinference-local -H 0.0.0.0

### Expected behavior
Run the xinference normally 

### Additional context
![20240329_103748.jpg](https://github.com/xorbitsai/inference/assets/61448882/f66a13fb-7f74-41ef-85f1-6ca78b7242f6)

**Comment by ChengjieLi28** [comment]
@YohannesGetu Will fix later.

**Comment by YohannesGetu** [comment]
In my further investigation the nigthly and the latest cpu docker image(v0.10.0-cpu) have the same image id.

![20240329_111826.jpg](https://github.com/xorbitsai/inference/assets/61448882/c914e5bd-627a-4113-b4b0-5f3053e6df1f)

**Comment by YohannesGetu** [comment]
> @YohannesGetu Will fix later.

Ok @ChengjieLi28 , it will be nice if you make it soon

**Comment by ChengjieLi28** [comment]
> In my further investigation the nigthly and the latest cpu docker image(v0.10.0-cpu) have the same image id.
> 
> ![20240329_111826.jpg](https://private-user-images.githubusercontent.com/61448882/317995214-c914e5bd-627a-4113-b4b0-5f3053e6df1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDEwNzgsIm5iZiI6MTcxMTcwMDc3OCwicGF0aCI6Ii82MTQ0ODg4Mi8zMTc5OTUyMTQtYzkxNGU1YmQtNjI3YS00MTEzLWI0YjAtNWYzMDUzZTZkZjFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA4MjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYzk5MGRmMmJkYmIzNTQxM2FlNDcxMDg5YjVjN2M1OTUxMzU2ZDQyM2Q4YjhjM2FiZjUyNmMwNWY0MTdkNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGzZ-f9QFjbtT5_WcaLNR7G0Pm__g_Q4xQ2f8VtwSMs)

Not for now.

**Comment by ChengjieLi28** [comment]
@YohannesGetu Please waiting for making docker image. Will inform you when finished.

**Comment by YohannesGetu** [comment]
> @YohannesGetu Please waiting for making docker image. Will inform you when finished.

Ok, thank you

**Comment by ChengjieLi28** [comment]
@YohannesGetu You could pull and try 0.10.0 image  now.

**Comment by YohannesGetu** [comment]
> @YohannesGetu You could pull and try 0.10.0 image  now.

Sorry @ChengjieLi28 i have pulled the new one and it is the same, not working

![20240329_125618.jpg](https://github.com/xorbitsai/inference/assets/61448882/f9d8b0c6-dbb2-45cc-927d-0e37243c2bdd)

**Comment by ChengjieLi28** [comment]
@YohannesGetu Please try the latest docker image. if it's working, close this issue plz, TY.

**Comment by YohannesGetu** [comment]
> @YohannesGetu Please try the latest docker image. if it's working, close this issue plz, TY.

Thank you @ChengjieLi28 , now it's working
