### ISSUE TITLE
有计划支持通义千问的moe架构吗

### ISSUE THREAD

**Issue by shinerdeng** [xorbitsai/inference#1223]
注册Qwen1.5-MoE-A2.7B-Chat-GPTQ-Int4这个模型，提示不支持的架构

**Comment by qinxuye** [comment]
我重新开一下，等到模型支持了再关。

**Comment by ChengjieLi28** [comment]
Close since PR #1263 has completed this.

**Comment by XiaoCC** [comment]
The checkpoint you are trying to load has model type `qwen2_moe` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
