### ISSUE TITLE
容器化部署和本地部署，运行结果不一致

### ISSUE THREAD

**Issue by qingjiaozyn** [xorbitsai/inference#1226]
机器资源：8卡 A100-SXM4-40GB  40G显存
环境：xinference：0.9.2     vllm 0.3.0
模型：Qwen1.5-72B-Chat

容器化启动命令：
docker run -v /home/models/:/home/models/ -e XINFERENCE_MODEL_SRC=modelscope -d -p 9998:9997  --gpus '"device=0,1,2,3,4,5,6,7"' --shm-size=256g xprobe/xinference:v0.9.2 xinference-local -H 0.0.0.0  --log-level debug

本地启动命令：
xinference-local --host 0.0.0.0 --port 9997

模型注册流程和launch均是相同的。但是两者推理的结果不一致

容器化推理结果（我们想要的，简短明了）：
CRM系统的部署拓扑包括\"debot实例A\"和IP地址为\"192.168.0.188\"的服务器。要分析系统是否正常，需要进一步检查这些组件的状态，例如服务运行状况、响应时间和资源利用率等。没有具体的数据，无法直接判断CRM系统是否正常运行。
本地推理结果如下（存在很多不是很相关的内容）：
根据刚才的拓扑数据查询，CRM系统的组成部分包括“debot实例A”和“192.168.0.188_服务器”。这些信息表明CRM系统由至少这些两部分组成，一个可能是CRM应用的实例，另一个是具体的服务器设备，地址为192.168.0.188。为了全面分析CRM系统是否正常，我们通常会关注以下几个方面：\n实例状态：确认debot实例A是否正在运行，无异常错误或警告，处理请求的速度是否正常。\n服务器状态：检查192.168.0.188服务器的硬件状态，如CPU、内存、磁盘使用情况，以及网络连接是否稳定。\n系统性能：监控系统响应时间和事务处理速度，确保在可接受范围内。\n数据完整性：确认数据存取、备份和恢复流程是否正常。\n安全性和更新：检查系统是否有最新的安全补丁，防止潜在的攻击。\n用户反馈：收集用户的反馈，了解是否有使用上的问题或投诉。\n日志分析：查看系统和应用程序日志，发现并解决潜在的异常行为。\n要执行这些分析，通常需要通过相应的监控工具、性能指标以及错误日志来进行。如果您有权限并需要进一步的详细信息，我可以帮助解释如何获取这些信息或分析数据。请告诉我你具体需要哪方面的帮助。

分析：本地推理结果总是会出现与问题不是很相关的文本，如上面的本地推理结果多余的内容如下：
\n服务器状态：检查192.168.0.188服务器的硬件状态，如CPU、内存、磁盘使用情况，以及网络连接是否稳定。\n系统性能：监控系统响应时间和事务处理速度，确保在可接受范围内。\n数据完整性：确认数据存取、备份和恢复流程是否正常。\n安全性和更新：检查系统是否有最新的安全补丁，防止潜在的攻击。\n用户反馈：收集用户的反馈，了解是否有使用上的问题或投诉。\n日志分析：查看系统和应用程序日志，发现并解决潜在的异常行为。\n要执行这些分析，通常需要通过相应的监控工具、性能指标以及错误日志来进行。如果您有权限并需要进一步的详细信息，我可以帮助解释如何获取这些信息或分析数据。请告诉我你具体需要哪方面的帮助。

这些内容会影响我们下游任务的精度，请问本地部署有什么优化的方案吗

**Comment by qinxuye** [comment]
你们的模型文件一致吗？

**Comment by qingjiaozyn** [comment]
> 你们的模型文件一致吗？

一样的，只有xinference服务启动命令不一样，其他都是一样的

**Comment by qinxuye** [comment]
可能影响的因素挺多的，你到容器内 pip list 下，然后把依赖都对齐试试呢？
