### ISSUE TITLE
why got error of "No available slot found for the model“

### ISSUE THREAD

**Issue by jackleeforce** [xorbitsai/inference#1228]
I deploy xinference by docker image with latest tag [v0.10.0](https://hub.docker.com/layers/xprobe/xinference/v0.10.0/images/sha256-e41982ad0167ac222b2010cc984cf595e69c3200aa86751a34194cbb0dbfa4d4?context=explore) with below command:
```
docker run -v "/home/op/xinference:/xinference" -d -e XINFERENCE_HOME=/xinference  -p 9998:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0 --log-level debug
```

firstly, i launching audio model `whisper-large-v3`, it work fine. and `nvidia-smi` show that only using up to 4GB GPU RAM in totally 24GB
<img width="987" alt="image" src="https://github.com/xorbitsai/inference/assets/4516554/ca8ff788-f7d6-470b-a2cd-a23fae32d3fb">

then i try launching another laguage model `Llama2-Chinese-13b-chat`, it will throw an exeception as below:
```
2024-04-01 14:19:20,431 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:30367, pid=66] No available slot found for the model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 729, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 827, in launch_builtin_model
    await _launch_model()
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 791, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 771, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 656, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 438, in _create_subpool
    else self.allocate_devices(model_uid=model_uid, n_gpu=gpu_cnt)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 337, in allocate_devices
    raise RuntimeError("No available slot found for the model")
RuntimeError: [address=0.0.0.0:30367, pid=66] No available slot found for the model
```

if i change order of launching models , firstly launching `Llama2-Chinese-13b-chat`,  it work normally, and `nvidia-smi` show that only using 8GB GPU RAM, then try launching `whisper-large-v3`, same error occured.

**Comment by ChengjieLi28** [comment]
@jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.

**Comment by jackleeforce** [comment]
> @jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.

i don't get it, where shall i pass the parameter for --gpu-idx?

**Comment by ChengjieLi28** [comment]
> > @jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.
> 
> i don't get it, where shall i pass the parameter for --gpu-idx?

This is for `launch` interface. You can use python client or cmdline.
SDK way:
```
client.launch_model(, gpu_idx=<>)
```
or cmdline way:
```
xinference launch --gpu-idx <your indexes>
```

**Comment by jackleeforce** [comment]
> > > @jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.
> > 
> > 
> > i don't get it, where shall i pass the parameter for --gpu-idx?
> 
> This is for `launch` interface. You can use python client or cmdline. SDK way:
> 
> ```
> client.launch_model(, gpu_idx=<>)
> ```
> 
> or cmdline way:
> 
> ```
> xinference launch --gpu-idx <your indexes>
> ```

ok, i see, but on Web interface,  is there any way to specific the gpu-idx for each model when try launching it?

<img width="407" alt="image" src="https://github.com/xorbitsai/inference/assets/4516554/ad73b94a-b150-427b-b14b-e824ef700f68">

<img width="356" alt="image" src="https://github.com/xorbitsai/inference/assets/4516554/53c7fa46-78df-4ace-b3c1-ecc561ecf81f">

**Comment by ChengjieLi28** [comment]
> > > > @jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.
> > > 
> > > 
> > > i don't get it, where shall i pass the parameter for --gpu-idx?
> > 
> > 
> > This is for `launch` interface. You can use python client or cmdline. SDK way:
> > ```
> > client.launch_model(, gpu_idx=<>)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or cmdline way:
> > ```
> > xinference launch --gpu-idx <your indexes>
> > ```
> 
> ok, i see, but on Web interface, is there any way to specific the gpu-idx for each model when try launching it?
> 
> <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/4516554/318634413-ad73b94a-b150-427b-b14b-e824ef700f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA2MDcsIm5iZiI6MTcxMjAzMDMwNywicGF0aCI6Ii80NTE2NTU0LzMxODYzNDQxMy1hZDczYjk0YS1iMTUwLTQyN2ItYjE0Yi1lODI0ZWY3MDBmNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDM1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgwZDg2OTAxY2E1MjY1Mjg3YWI5MGFlOGQyOGQ1NzQ3YTQ2NTllY2EyNzhjZGYxMzQ4YzA4NzZmYzMzNTU5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vd-RKfz3NqFOGAHK_PhRatq2eoKR3drOv-YI01CFwEk"> <img alt="image" width="356" src="https://private-user-images.githubusercontent.com/4516554/318634518-53c7fa46-78df-4ace-b3c1-ecc561ecf81f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA2MDcsIm5iZiI6MTcxMjAzMDMwNywicGF0aCI6Ii80NTE2NTU0LzMxODYzNDUxOC01M2M3ZmE0Ni03OGRmLTRhY2UtYjNjMS1lY2M1NjFlY2Y4MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDM1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg0NjgxYTM5YmRlZjAwOGFmOTZjYzQ4ZThjODNkZDQyYTYyYWJkNjZiOWIxOGQ2MzU0ODIxYzAyODdkYWI4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G1zA0HhePD1ULr2JiURJhhR_kIy1T3Ugklr3r17yKtw">

Web  will support this option in the release version `v0.10.1`.

**Comment by jackleeforce** [comment]
> > > > > @jackleeforce Currently, only one card for one model. You can use `--gpu-idx` option in cmdline which is introduced in `v0.10.0` to force to launch multiple models on one card.
> > > > 
> > > > 
> > > > i don't get it, where shall i pass the parameter for --gpu-idx?
> > > 
> > > 
> > > This is for `launch` interface. You can use python client or cmdline. SDK way:
> > > ```
> > > client.launch_model(, gpu_idx=<>)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or cmdline way:
> > > ```
> > > xinference launch --gpu-idx <your indexes>
> > > ```
> > 
> > 
> > ok, i see, but on Web interface, is there any way to specific the gpu-idx for each model when try launching it?
> > <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/4516554/318634413-ad73b94a-b150-427b-b14b-e824ef700f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA2MDcsIm5iZiI6MTcxMjAzMDMwNywicGF0aCI6Ii80NTE2NTU0LzMxODYzNDQxMy1hZDczYjk0YS1iMTUwLTQyN2ItYjE0Yi1lODI0ZWY3MDBmNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDM1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgwZDg2OTAxY2E1MjY1Mjg3YWI5MGFlOGQyOGQ1NzQ3YTQ2NTllY2EyNzhjZGYxMzQ4YzA4NzZmYzMzNTU5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vd-RKfz3NqFOGAHK_PhRatq2eoKR3drOv-YI01CFwEk"> <img alt="image" width="356" src="https://private-user-images.githubusercontent.com/4516554/318634518-53c7fa46-78df-4ace-b3c1-ecc561ecf81f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA2MDcsIm5iZiI6MTcxMjAzMDMwNywicGF0aCI6Ii80NTE2NTU0LzMxODYzNDUxOC01M2M3ZmE0Ni03OGRmLTRhY2UtYjNjMS1lY2M1NjFlY2Y4MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDM1ODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg0NjgxYTM5YmRlZjAwOGFmOTZjYzQ4ZThjODNkZDQyYTYyYWJkNjZiOWIxOGQ2MzU0ODIxYzAyODdkYWI4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G1zA0HhePD1ULr2JiURJhhR_kIy1T3Ugklr3r17yKtw">
> 
> Web will support this option in the release version `v0.10.1`.

ok， thanks for supporting. i will close this issue.

**Comment by BradKML** [comment]
@ChengjieLi28 is there a Docker version of this flag for running three models (LLM + Embedding+ Reranker)?
