### ISSUE TITLE
在 CPU 环境下使用 ggufv2 的qwen 大模型报错， Unable to allocate 18.5 GiB，但是qwen1_5-0_5b-chat-q4_0.gguf 只有377M

### ISSUE THREAD

**Issue by golangpkg** [xorbitsai/inference#1244]
### Describe the bug
当使用 CPU 的gguf 报错

参考文档：
https://inference.readthedocs.io/zh-cn/latest/models/builtin/llm/qwen1.5-chat.html

xinference launch --model-name qwen1.5-chat --size-in-billions 0_5 --model-format ggufv2 --quantization q4_0

q4_0 的模型只有 

377M  4月  4 20:25 qwen1_5-0_5b-chat-q4_0.gguf

应该不用申请这么大内存？？

`python
# xinference launch --model-name qwen1.5-chat --size-in-billions 0_5 --model-format ggufv2 --quantization q4_0
Launch model name: qwen1.5-chat with kwargs: {}
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 746, in model_launch
    model_uid = client.launch_model(
  File "/usr/local/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 873, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:40655, pid=98] Unable to allocate 18.5 GiB for an array with shape (32768, 151936) and data type float32

`

**Comment by golangpkg** [comment]
但是使用python 执行运行  qwen1.5 可以：

`
python3
Python 3.10.14 (main, Mar 25 2024, 21:51:59) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from llama_cpp import Llama
>>> llm = Llama(model_path="/models/modelscope/qwen/Qwen1.5-0.5B-Chat-GGUF/qwen1_5-0_5b-chat-q4_0.gguf")
llama_model_loader: loaded meta data with 21 key-value pairs and 291 tensors from /models/modelscope/qwen/Qwen1.5-0.5B-Chat-GGUF/qwen1_5-0_5b-chat-q4_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = Qwen1.5-0.5B-Chat-AWQ-fp16
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 24
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 1024
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 2816
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 16
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 16
llama_model_loader: - kv   8:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  10:                qwen2.use_parallel_residual bool             = true
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  13:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  14:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  16:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  18:                    tokenizer.chat_template str              = {% for message in messages %}{{'<|im_...
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - kv  20:                          general.file_type u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type q4_0:  169 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 293/151936 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151936
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 1024
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 16
llm_load_print_meta: n_layer          = 24
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_embd_head_k    = 64
llm_load_print_meta: n_embd_head_v    = 64
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 2816
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 0.5B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 619.57 M
llm_load_print_meta: model size       = 371.02 MiB (5.02 BPW) 
llm_load_print_meta: general.name     = Qwen1.5-0.5B-Chat-AWQ-fp16
llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors:        CPU buffer size =   371.02 MiB
...............................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =    48.00 MiB
llama_new_context_with_model: KV self size  =   48.00 MiB, K (f16):   24.00 MiB, V (f16):   24.00 MiB
llama_new_context_with_model:        CPU input buffer size   =     4.01 MiB
llama_new_context_with_model:        CPU compute buffer size =   298.75 MiB
llama_new_context_with_model: graph splits (measure): 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | 
Model metadata: {'general.file_type': '2', 'tokenizer.ggml.bos_token_id': '151643', 'general.architecture': 'qwen2', 'general.name': 'Qwen1.5-0.5B-Chat-AWQ-fp16', 'qwen2.block_count': '24', 'qwen2.context_length': '32768', 'tokenizer.chat_template': "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}", 'qwen2.attention.head_count_kv': '16', 'tokenizer.ggml.padding_token_id': '151643', 'qwen2.embedding_length': '1024', 'qwen2.attention.layer_norm_rms_epsilon': '0.000001', 'qwen2.attention.head_count': '16', 'tokenizer.ggml.eos_token_id': '151645', 'qwen2.rope.freq_base': '1000000.000000', 'qwen2.use_parallel_residual': 'true', 'general.quantization_version': '2', 'qwen2.feed_forward_length': '2816', 'tokenizer.ggml.model': 'gpt2'}
Guessed chat format: chatml
>>> llm.create_chat_completion(
...   messages = [{"role": "user","content": "北京景点"
... }])


llama_print_timings:        load time =     105.61 ms
llama_print_timings:      sample time =     342.83 ms /   241 runs   (    1.42 ms per token,   702.97 tokens per second)
llama_print_timings: prompt eval time =     105.53 ms /    16 tokens (    6.60 ms per token,   151.62 tokens per second)
llama_print_timings:        eval time =    4215.82 ms /   240 runs   (   17.57 ms per token,    56.93 tokens per second)
llama_print_timings:       total time =    7602.47 ms /   256 tokens
{'id': 'chatcmpl-bf7f0a20-1483-4f65-acfa-e5a070d85399', 'object': 'chat.completion', 'created': 1712239745, 'model': '/models/modelscope/qwen/Qwen1.5-0.5B-Chat-GGUF/qwen1_5-0_5b-chat-q4_0.gguf', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '北京是中国的首都，拥有众多的历史文化名胜古迹。以下是一些在北京最著名的景点：\n\n1. 故宫：位于北京市中心，是明清两代皇家宫殿，也是世界上现存规模最大、保存最为完整的木质结构古建筑群。\n\n2. 长城：位于北京市北部，是世界文化遗产，被誉为“东方的长城”。\n\n3. 北京动物园：位于北京市西郊，是世界上最大的动物园之一。\n\n4. 天安门广场：位于北京市中心，是中华人民共和国的象征。\n\n5. 北京故宫博物院：位于北京市中心，是世界上最大的古代文化艺术博物馆。\n\n6. 北京植物园：位于北京市西郊，是世界一流的植物园。\n\n7. 北京野生动物园：位于北京市西郊，是世界上最大的野生动物园。\n\n8. 北京动物园：位于北京市西郊，是世界上最大的动物园之一。\n\n9. 北京动物园：位于北京市西郊，是世界上最大的动物园之一。\n\n10. 北京动物园：位于北京市西郊，是世界上最大的动物园之一。\n\n以上就是北京的一些著名景点，每个地方都有其独特的魅力和历史价值。'}, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 16, 'completion_tokens': 240, 'total_tokens': 256}}
>>> 
`

**Comment by qinxuye** [comment]
Xinference 什么版本？此外，有没有服务端日志？

**Comment by mikeshi80** [comment]
其实这个问题是因为xinference默认使用最长的`context_length`造成的，`llama-cpp-python`里，需要预先alloc一个numpy的array，是`context_length` x `vocab size`的，每个元素类型是float32（即4个字节），而LLM的vocab size也是超大的，为152064，而`context_length`是32768，那么占用的大小就是 `152064*32768*4`，折合成GB的话，就是18.56GB。

目前网页前端还没有设置启动时设定`context_length`的选项，需要使用xinference命令行工具来设定，把这个设小点就OK了。

**Comment by lssmlssm** [comment]
xinference, version 0.12.3

xinference launch --model-engine llama.cpp --model-name qwen2-instruct --size-in-billions 0_5 --model-format ggufv2 --quantization q4_k_m --n_ctx 1024

用--n_ctx 來配置
