### ISSUE TITLE
UI 白屏

### ISSUE THREAD

**Issue by yetone** [xorbitsai/inference#1245]
### Describe the bug

<img width="1145" alt="image" src="https://github.com/xorbitsai/inference/assets/1206493/408875db-06e4-4028-8886-90382c2b1a4b">

### To Reproduce
按照文档在 k8s 里安装 xinference，port-forward svc 到本地

### Expected behavior
正常显示

### Additional context
无

**Comment by qinxuye** [comment]
参考的哪个文档？

**Comment by yetone** [comment]
> 参考的哪个文档？

https://inference.readthedocs.io/en/latest/getting_started/using_xinference.html#using-xinference-on-kubernetes

**Comment by iziang** [comment]
@yetone 麻烦确认下xinference pod用的镜像版本是否为xprobe/xinference:latest

```bash
kubectl get pod ${XINFERENCE_POD_NAME} -oyaml | grep image
```

**Comment by yetone** [comment]
> @yetone 麻烦确认下xinference pod用的镜像版本是否为xprobe/xinference:latest
> 
> ```shell
> kubectl get pod ${XINFERENCE_POD_NAME} -oyaml | grep image
> ```
> 
> > XINFERENCE_POD_NAME替换成实际的Pod名字

<img width="1024" alt="image" src="https://github.com/xorbitsai/inference/assets/1206493/a54df6d8-ae02-4e51-b3f5-2335e2f3de1a">
