### ISSUE TITLE
User specified GPU index X has been occupied with a vLLM model

### ISSUE THREAD

**Issue by liuzhenghua** [xorbitsai/inference#1266]
### Describe the bug
I wan't to deploy qwen1.5 with 2 replicas, each replica using 2 gpu:
- deploying qwen1.5 instance 1 on gpu 1,2 
- deploying qwen1.5 instance 2 on gpu 3,4 

using the following command to lanuch 2 replicas of qwen1.5
```shell
xinference launch -u qwen1.5-chat -n qwen1.5-chat -f gptq -s 14 -q Int4 -r 2 --n-gpu 2 --gpu-idx 1,2,3,4
```
I got then error：
**RuntimeError: Failed to launch model, detail: [address=0.0.0.0:55557, pid=1975588] User specified GPU index 1 has been occupied with a vLLM model: qwen1.5-chat-2-0, therefore cannot allocate GPU memory for a new model.**

### To Reproduce
any of the following command would occur this error：
```shell
xinference launch -u qwen1.5-chat -n qwen1.5-chat -f gptq -s 14 -q Int4 -r 2 --n-gpu 2 --gpu-idx 1,2,3,4
xinference launch -u qwen1.5-chat -n qwen1.5-chat -f gptq -s 14 -q Int4 -r 2 --n-gpu 4 --gpu-idx 1,2,3,4
xinference launch -u qwen1.5-chat -n qwen1.5-chat -f gptq -s 14 -q Int4 -r 2 --gpu-idx 1,2,3,4
```

### Expected behavior
launch success

### Additional context
It works if you start one replica or not specified the `--gpu-idx` argument.

**Comment by ChengjieLi28** [comment]
`gpu-idx` has conflict with `n_gpu` and `replica` parameter. If you want to launch two replicas in a single command, do not specify the `gpu-idx` option. Just `-r 2 --n-gpu 2`.
If you want to launch two replicas to the specific gpus, you have to execute the launch command twice with `gpu-idx` option.

**Comment by liuzhenghua** [comment]
> @liuzhenghua `gpu-idx` has conflict with `n_gpu` and `replica` parameter. If you want to launch two replicas in a single command, do not specify the `gpu-idx` option. Just `-r 2 --n-gpu 2`. If you want to launch two replicas to the specific gpus, you have to execute the launch command twice with `gpu-idx` option.

execute the lanuch command twice got the error "model is already in the model list"
![image](https://github.com/xorbitsai/inference/assets/11787325/f51dffa3-2869-4255-8ab1-8f5b84e4c64f)

**Comment by ChengjieLi28** [comment]
> > @liuzhenghua `gpu-idx` has conflict with `n_gpu` and `replica` parameter. If you want to launch two replicas in a single command, do not specify the `gpu-idx` option. Just `-r 2 --n-gpu 2`. If you want to launch two replicas to the specific gpus, you have to execute the launch command twice with `gpu-idx` option.
> 
> execute the lanuch command twice got the error "model is already in the model list" ![image](https://private-user-images.githubusercontent.com/11787325/320764758-f51dffa3-2869-4255-8ab1-8f5b84e4c64f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTAwMTEsIm5iZiI6MTcxMjY0OTcxMSwicGF0aCI6Ii8xMTc4NzMyNS8zMjA3NjQ3NTgtZjUxZGZmYTMtMjg2OS00MjU1LThhYjEtOGY1Yjg0ZTRjNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA4MDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjI4NDJlNjZkYjBiY2JjMDA3ZWEyMzI4NDVmMzljNGM1MzUxNmY0N2E3NGJhNWZmMTE0Mjk5NjYyZWYyMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RE1dwNKS4aR9ZbtRfypKbcTaJhxjg5hgWmEFE7x-hXo)

Remove `-u` option, and then xinference will generate some random suffix for your second model. Or use `-u` to specify a special uid.
If you want the second model to have the same uid as the first model while specifying the card, xinference cannot support this currently.
