### ISSUE TITLE
FEAT: support SeaLLMs - Large Language Models for Southeast Asia

### ISSUE THREAD

**Issue by elepherai** [xorbitsai/inference#1275]
[SeaLLMs/SeaLLM-7B-v2](https://huggingface.co/SeaLLMs/SeaLLM-7B-v2): The most siginificant upgrade since SeaLLM-13B with half the size, outperforming performance across diverse multilingual tasks, from world knowledge, math reasoning, instruction following, etc.
[SeaLLMs/SeaLLM-13B-Chat](https://huggingface.co/SeaLLMs/SeaLLM-13B-Chat): A chatbot optimized for Vietnamese 🇻🇳, Indonesian 🇮🇩, Thai 🇹🇭, Malay 🇲🇾, Khmer🇰🇭, Lao🇱🇦, Tagalog🇵🇭 and Burmese🇲🇲.

**Comment by qinxuye** [comment]
Thanks, we will do some investigation first, we hope we can support it ASAP.

**Comment by elepherai** [comment]
[SeaLLMs/SeaLLMs-v3](https://huggingface.co/SeaLLMs/SeaLLM3-7B-Chat)
SeaLLM3系列也麻烦抽空支持下，谢谢~

**Comment by qinxuye** [comment]
> [SeaLLMs/SeaLLMs-v3](https://huggingface.co/SeaLLMs/SeaLLM3-7B-Chat) SeaLLM3系列也麻烦抽空支持下，谢谢~

开个新issue吧
