### ISSUE TITLE
集群启动 model 报 ConnectionError  BUG

### ISSUE THREAD

**Issue by buctllx** [xorbitsai/inference#1284]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.   3.9
2. The version of xinference you use.    v0.9.4
4. Versions of crucial packages.
5. Full stack of the error.
![企业微信截图_17128030337972(1)(1)](https://github.com/xorbitsai/inference/assets/12623648/0b169386-07ca-402a-9659-e14fc99ad503)
6. Minimized code to reproduce the error.
集群部署，两个worker在不同的服务器上，然后随便启动一个 model 就会报错

### Additional context
启动xinference-supervisor是必须指定注册到所有ip，要写成xinference-supervisor -H 0.0.0.0 -p 9997 --supervisor-port 9998
但是如果写成这样有个问题，不在同一个主机上的work节点访问不到xinference-supervisor

**Comment by qinxuye** [comment]
对于分布式，最好是直接指定 IP，而不是 0.0.0.0。对于 supervisor 和 worker 都指定 IP。
