### ISSUE TITLE
QUESTION: Encoutering libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WillWillWong** [xorbitsai/inference#1286]
### Describe the bug
ImportError: [address=0.0.0.0:44627, pid=1165786] libcudart.so.12: cannot open shared object file: No such file or directory
当我在运行qwen1.5-14b的时候出现这个错误，我查看了过往的问题并没有相关的问题。

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. Python 3.10.13
2. xinference, version 0.10.0
4. Versions of crucial packages.
5. Full stack of the error.
6. Minimized code to reproduce the error.

**Comment by qinxuye** [comment]
Can you paste the full error stack?

**Comment by WillWillWong** [comment]
Now that it has been successfully resolved, the main issue is that vllm cannot find the libcudart.so.12。My solution is,[CUDA Toolkit 12.4 Update 1 Downloads](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network).
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-4
```
