### ISSUE TITLE
FEAT: support text-to-audio open model

### ISSUE THREAD

**Issue by weili20** [xorbitsai/inference#1288]
### Is your feature request related to a problem? Please describe
No.

### Describe the solution you'd like
ModelScope has some text-to-audio open models. here is the link: https://modelscope.cn/models?page=1&tasks=text-to-speech&type=audio

### Describe alternatives you've considered
No

### Additional context
No

**Comment by qinxuye** [comment]
Thank you for your suggestion, text-to-audio is definitely on our roadmap, we will support it in an appropriate time. Meanwhile, contribution welcomed for this feature.

**Comment by liduang** [comment]
希望尽快支持文本转语音的模型，十分感谢
