### ISSUE TITLE
QUESTION:部署0.10.1 docker版本的qwen1.5-32B，聊两句机会出现一直感叹号，不知道是inference的问题还是qwen问题

### ISSUE THREAD

**Issue by panthole** [xorbitsai/inference#1289]
Note that the issue tracker is NOT the place for general support.
![image](https://github.com/xorbitsai/inference/assets/4142451/2709dcdd-a912-4325-be90-5e228b5d04a2)

**Comment by qinxuye** [comment]
qwen 的问题，需要更改系统提示词。

**Comment by WangxuP** [comment]
通过接口调用是没问题的。
