### ISSUE TITLE
How do I use Text-to-speech model ? 

### ISSUE THREAD

**Issue by chenxinlong** [xorbitsai/inference#1290]
There's no tts built-in model in xinference, and IDK how to register a tts kind model by the following page : 

![image](https://github.com/xorbitsai/inference/assets/9261954/b831beb2-befe-4d18-8825-ec79ed370216)

How should I : 

* register a tts model 
* launch it and use it (by the way, is there a built-int webui support it?)

**Comment by qinxuye** [comment]
Duplicated with #1288 . Text2Audio or Text2Speech is not implemented yet, we will support it ASAP, meanwhile, contribution welcomed.
