### ISSUE TITLE
为什么更新到10.1版本以后部署同样的模型显存占用量大幅上升？QUESTION

### ISSUE THREAD

**Issue by woocore** [xorbitsai/inference#1292]
我一直使用xinfernece部署Qwen1.5-14b 4位量化模型，模型启动占用13G左右，几轮对话后会达到22 G左右，清除对话会显存占用会下降。今天更新到10.1版本，同样的模型启动显存占用直接冲高到20G，如果连接到知识库2~3轮对话后显存就会溢出，并且清除对话后显存占用也不会下降。

**Comment by qinxuye** [comment]
我们看下能不能复现。

**Comment by imClumsyPanda** [comment]
同样出现该问题，升级前使用xinference运行Qwen1.5-7B-Chat与CodeLlama-7B-Instruct，内存占用均在15G左右。升级后使用xinference[vllm]，提升当前显卡不支持bhalf16后增加dtype=half的配置，并指定运行所在gpu后发现显存占用接近升级前2倍。

**Comment by qinxuye** [comment]
看样子是用了 vllm 后端，vllm 本身是不管模型多大，都会占用默认 90% 的显存。因此看到的现象是显存大幅上升。

**Comment by imClumsyPanda** [comment]
> 看样子是用了 vllm 后端，vllm 本身是不管模型多大，都会占用默认 90% 的显存。因此看到的现象是显存大幅上升。

感谢回答🙏

**Comment by kratorado** [comment]
vllm 有个 --gpu-memory-utilization ，默认0.9，可以根据需要设置

**Comment by worm128** [comment]
模型：Qwen1.5-14B-Chat-GPTQ-int4
xinference新版本：v0.12.3 容器：docker pull xprobe/xinference:v0.12.3
xinference旧版本：v0.8.5 容器：docker pull xprobe/xinference:v0.8.5

我用的是docker容器版本运行的：
为什么xinference v0.12版本使用vllma加载Qwen1.5-14B-Chat-GPTQ-int4模型显存会到22g这么多，原来旧版本v0.8只需要12g左右，而且回复速度也超快；而在新版有transformer和vllma两种方式加载，其中transformer的回复速度奇慢无比，虽然显存占用小；用vllma占用显存非常多22g，但是速度快。搞不明白xinference改了什么，这是不是开倒车了，没有旧版本好用。

**Comment by chaozZLF** [comment]
你在启动模型的时候有两个cli参数gpu_memory_utilization和--max-model-len可以自行调整模型的显存占用量，具体怎么用可以手下指南

**Comment by chaozZLF** [comment]
你在启动模型的时候有两个cli参数gpu_memory_utilization和max_model_len可以自行调整模型的显存占用量，具体怎么用可以搜下指南

**Comment by dinysen** [comment]
我遇到了同样的问题，确实去掉launch_model，直接用model uid get之后使用就行了，没有自动生成缓存了
