### ISSUE TITLE
xinferrence  rewrite user's prompt cause unexpected behavior with tools parameter in Qwen1.5 series

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#1293]
### Describe the bug
xinferrence seems using `isinstance(tools,list)` to trigger the ReAct Prompt to implement the tool use instead of `True if  tools else False` when use Qwen1.5 LLM

### To Reproduce
To help us to reproduce this bug, please provide information below:
![image](https://github.com/xorbitsai/inference/assets/49679672/6a68b146-29b5-4f44-9668-da41f1fa23da)
![image](https://github.com/xorbitsai/inference/assets/49679672/9051669d-1fbb-486e-ac60-012d8edbefa9)
![image](https://github.com/xorbitsai/inference/assets/49679672/1a067372-d7ed-4bec-acd6-b800ec2cee1b)

when set tools=[]  xinference use ReAct Prompt rewrite the user's promtp and send to llm
when set tools=None  xinference behave like normal
when the tool has no parameters , xinference raise the error ,which should not, the tool use should aceept the tools/func without parms

1. Your Python version. --> 3.10
2. The version of xinference you use.  --->v0.10.1
3. Versions of crucial packages.   -->  xinference 
4. Full stack of the error.  --> n/a
5. Minimized code to reproduce the error.  use post request to access /v1/chat/completions with parameter `"tools" :[ ]`

### Expected behavior
should use `True if  tools else False` to implemet the tool use 
and when the tool has no parammters the api should accpet it instead of raise error

**Comment by qinxuye** [comment]
Do you have interest to send a PR to address this issue?
