### ISSUE TITLE
启动OrionStar-Yi-34B-Chat-Llama-GGUF大模型时发现没有加载到GPU，而是加载到了CPU，是什么原因呢

### ISSUE THREAD

**Issue by michaelxu1107** [xorbitsai/inference#1301]
你好，我在使用xinference启动OrionStar-Yi-34B-Chat-Llama-GGUF大模型时，发现模型没有被加载到GPU，而是加载到了CPU，请问是什么原因呢？

模型地址：
https://hf-mirror.com/TheBloke/OrionStar-Yi-34B-Chat-Llama-GGUF/tree/main/，我使用的是orionstar-yi-34b-chat-llama.Q5_K_M.gguf

python环境如下：
Python 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True

**Comment by amumu96** [comment]
GGML Backend
~~~~~~~~~~~~
It's advised to install the GGML dependencies manually based on your hardware specifications to enable acceleration.

Initial setup::

   pip install xinference

Hardware-Specific installations:

- Apple Silicon::

   CMAKE_ARGS="-DLLAMA_METAL=on" pip install llama-cpp-python

- Nvidia cards::

   CMAKE_ARGS="-DLLAMA_CUDA=on" pip install llama-cpp-python

- AMD cards::

   CMAKE_ARGS="-DLLAMA_HIPBLAS=on" pip install llama-cpp-python

**Comment by amumu96** [comment]
check your environment setting, about
```
# <<< conda initialize <<<

export CUDA_HOME=/usr/local/cuda-11.8
export PATH="$CUDA_HOME/bin:$PATH"
export CPATH=/usr/local/cuda-11.8/targets/x86_64-linux/include:$CPATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.8/targets/x86_64-linux/lib:/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH


```

change it to your path

**Comment by mikeshi80** [comment]
如果已经安装过llama-cpp-python了，需要加入 `--force-reinstall` 以便强制重新安装，否则它会认为依赖已安装，直接跳过的。

**Comment by michaelxu1107** [comment]
我使用如下方法可以加载到gpu了
1、CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python==0.2.57 --no-cache-dir
2、python3 -m llama_cpp.server --model /home/iqas/models/OrionStarAI/OrionStar-Yi-34B-Chat-Llama-GGUF/orionstar-yi-34b-chat-llama.Q5_K_M.gguf --n_threads 30 --n_gpu_layers

但是运行xinference-local时，报了如下错误
ImportError: /home/iqas/model_env_new/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: symbol __nvJitLinkAddData_12_1, version libnvJitLink.so.12 not defined in file libnvJitLink.so.12 with link time reference
这是还需要安装什么库么？

**Comment by michaelxu1107** [comment]
pip install torch==2.1.2改成pip install torch-2.1.2+cu121-cp310-cp310-linux_x86_64.whl ，上述报错问题解决
