### ISSUE TITLE
Can't run 4bit GPTQ model

### ISSUE THREAD

**Issue by yiouyou** [xorbitsai/inference#1308]
Downloaded 4bit GPTQ model from
https://huggingface.co/LoneStriker/Smaug-34B-v0.1-GPTQ/tree/main

In Xinference, the model has been registered as 'Smaug' successfully, but when launching the model, it show error in log:
```
...
FileNotFoundError: [address=0.0.0.0:38475, pid=404] No such file or directory: "/data/cache/Smaug-gptq-34b/model-00001-of-00015.safetensors"
```

It seems:
1. Xinference will automatically add 'gptq-34b' after the registered name for the model folder name
2. Xinference will not be abale to use the gptq_model-4bit-32g.safetensors directly, but trying to read the original un-quantized model

How to fix the problem and launch the 4bit model to run?

Thanks,

**Comment by qinxuye** [comment]
Did you provide the right directory for the model?

**Comment by Alphayellowcat** [comment]
Same question in GPU memory consumption between two versions of the Qwen1.5-Chat-14B model on my NVIDIA RTX 4090 GPU. When running the PyTorch version (qwen1.5-chat-pytorch-14b-4int), the model utilizes approximately 10GB of GPU memory. However, switching to the gpt/awq version (qwen1.5-chat-gptq-14b-4int), the GPU memory usage escalates dramatically to 21.7GB.

This substantial increase in memory usage is puzzling, especially since quantization typically aims to reduce memory footprint and computational load. Could there be a configuration issue or a potential inefficiency in the GPTQ implementation that I might be missing?

Here is my log:
```
024-04-17 12:12:42 2024-04-17 04:12:42,383 xinference.model.llm.vllm.core 65 INFO     Loading qwen1.5-chat with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}
2024-04-17 12:12:42 WARNING 04-17 04:12:42 config.py:211] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2024-04-17 12:12:42 INFO 04-17 04:12:42 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/xinference_home/cache/qwen1.5-chat-awq-14b', tokenizer='/xinference_home/cache/qwen1.5-chat-awq-14b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
2024-04-17 12:12:42 Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-04-17 12:12:43 WARNING 04-17 04:12:43 utils.py:357] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
2024-04-17 12:12:43 INFO 04-17 04:12:43 selector.py:16] Using FlashAttention backend.
2024-04-17 12:16:21 INFO 04-17 04:16:21 model_runner.py:104] Loading model weights took 9.0681 GB
2024-04-17 12:16:23 INFO 04-17 04:16:23 gpu_executor.py:94] # GPU blocks: 858, # CPU blocks: 327
2024-04-17 12:16:23 INFO 04-17 04:16:23 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
2024-04-17 12:16:23 INFO 04-17 04:16:23 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
2024-04-17 12:16:28 INFO 04-17 04:16:28 model_runner.py:867] Graph capturing finished in 6 secs
```

**Comment by yiouyou** [comment]
> Did you provide the right directory for the model?

Yes, I think so. Here is the docker command
```
docker run -v /home/songz/.xinference:/root/.xinference -v /home/songz/.cache/huggingface:/root/.cache/huggingface -v /home/songz/.cache/modelscope:/root/.cache/modelscope -v /home/songz/.cache/sentence-transformers_all-mpnet-base-v2:/root/.cache/sentence-transformers_all-mpnet-base-v2 -v /home/songz/text-generation-webui/models:/data -e XINFERENCE_HOME=/data -p 28277:9997 --gpus=all xprobe/xinference:latest xinference-local -H 0.0.0.0 --log-level debug
```

As you can see, the text-generation-webui/models folder has been mount to /data, and the model has been registered from /data/LoneStriker_Smaug-34B-v0.1-GPTQ, which showed sucessfully registered. Under /data, here are all models:
```
(base) songz:~/text-generation-webui/models$ ll
总计 36
drwxr-xr-x 11 songz songz 4096  4月 16 15:08 ./
drwxr-xr-x 25 songz songz 4096  4月 10 13:49 ../
drwxr-xr-x  3 root  root   122  4月 16 16:33 cache/
drwxr-xr-x  2 songz songz 4096  1月  7 23:24 chatglm3-6B-GPTQ/
-rw-r--r--  1 songz songz 1450  4月 10 13:52 config-user.yaml
-rw-rw-r--  1 songz songz 5829  4月  8 16:10 config.yaml
-rw-r--r--  1 songz songz  162 12月  7 13:47 down.txt
drwxr-xr-x  4 root  root   116  4月 16 16:02 huggingface/
drwxr-xr-x  7 root  root   165  4月 16 16:09 logs/
drwxr-xr-x  2 songz songz 4096  2月 23 15:52 LoneStriker_Smaug-34B-v0.1-GPTQ/
drwxrwxr-x  2 songz songz 4096  4月 10 05:06 macadeliccc_UNA-SimpleSmaug-34b-v1beta-exlv2-6.5bpw/
drwxr-xr-x  4 root  root    46  4月 16 14:36 model/
-rw-r--r--  1 songz songz    0 11月 10 10:08 place-your-models-here.txt
drwxr-xr-x  2 songz songz  284 12月 15 23:28 SUS-Chat-34B-fcv3-GPTQ/
drwxr-xr-x  2 songz songz  336 12月 15 11:06 TheBloke_Phind-CodeLlama-34B-v2-GPTQ/
```
And under LoneStriker_Smaug-34B-v0.1-GPTQ, here are files:
```
(base) songz:~/text-generation-webui/models/LoneStriker_Smaug-34B-v0.1-GPTQ$ ll
总计 20717596
drwxr-xr-x  2 songz songz        4096  2月 23 15:52 ./
drwxr-xr-x 11 songz songz        4096  4月 16 15:08 ../
-rw-r--r--  1 songz songz         713  2月 23 15:52 config.json
-rw-r--r--  1 songz songz         132  2月 23 15:52 generation_config.json
-rw-r--r--  1 songz songz 21210133648  2月 23 16:27 gptq_model-4bit-32g.safetensors
-rw-r--r--  1 songz songz         305  2月 23 15:52 huggingface-metadata.txt
-rw-r--r--  1 songz songz       44754  2月 23 15:52 model.safetensors.index.json
-rw-r--r--  1 songz songz         209  2月 23 15:52 quantize_config.json
-rw-r--r--  1 songz songz        1010  2月 23 15:52 README.md
-rw-r--r--  1 songz songz         552  2月 23 15:52 special_tokens_map.json
-rw-r--r--  1 songz songz        1474  2月 23 15:52 tokenizer_config.json
-rw-r--r--  1 songz songz     3560998  2月 23 15:52 tokenizer.json
-rw-r--r--  1 songz songz     1033105  2月 23 15:52 tokenizer.model
```

It seems that Xinference can't read pre-downloaded quantized model, it tries to read the un-quantized model, because the error shows like: No such file or directory: "/data/cache/Smaug-gptq-34b/model-00001-of-00015.safetensors"

Could you help with the problem?

Thanks,

**Comment by worm128** [comment]
> 在我的 NVIDIA RTX 1.5 GPU 上，两个版本的 Qwen14-Chat-14B 型号之间的 GPU 内存消耗存在相同的问题。 运行 PyTorch 版本 （qwen1.5-chat-pytorch-14b-4int） 时，该模型使用大约 10GB 的 GPU 内存。 然而，切换到 gpt/awq 版本 （qwen1.5-chat-gptq-14b-4int），GPU 内存使用量急剧上升到 21.7GB。
> 
> 内存使用量的大幅增加令人费解，特别是因为量化通常旨在减少内存占用和计算负载。 我可能遗漏的 GPTQ 实现中是否存在配置问题或潜在的低效率？
> 
> 这是我的日志：
> 
> ```
> 024-04-17 12:12:42 2024-04-17 04:12:42,383 xinference.model.llm.vllm.core 65 INFO     Loading qwen1.5-chat with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}
> 2024-04-17 12:12:42 WARNING 04-17 04:12:42 config.py:211] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
> 2024-04-17 12:12:42 INFO 04-17 04:12:42 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/xinference_home/cache/qwen1.5-chat-awq-14b', tokenizer='/xinference_home/cache/qwen1.5-chat-awq-14b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
> 2024-04-17 12:12:42 Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> 2024-04-17 12:12:43 WARNING 04-17 04:12:43 utils.py:357] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
> 2024-04-17 12:12:43 INFO 04-17 04:12:43 selector.py:16] Using FlashAttention backend.
> 2024-04-17 12:16:21 INFO 04-17 04:16:21 model_runner.py:104] Loading model weights took 9.0681 GB
> 2024-04-17 12:16:23 INFO 04-17 04:16:23 gpu_executor.py:94] # GPU blocks: 858, # CPU blocks: 327
> 2024-04-17 12:16:23 INFO 04-17 04:16:23 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
> 2024-04-17 12:16:23 INFO 04-17 04:16:23 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
> 2024-04-17 12:16:28 INFO 04-17 04:16:28 model_runner.py:867] Graph capturing finished in 6 secs
> ```

你可以参考一下我这个帖子的提问：https://github.com/xorbitsai/inference/issues/1797
我也是发现一样的情况，在0.11、0.12版本，显存激增翻倍；最理想的版本是v0.8.5，占用显存小，速度快
