### ISSUE TITLE
Support custom VL models not supported officially

### ISSUE THREAD

**Issue by ybsbbw** [xorbitsai/inference#1311]
xinference V0.10.1
现在想运行服务器上本地存储的一个大模型internlm-xcomposer2-vl，书生浦语的一个文字图像的多模态模型，但是在register model支持的模型列表中没有找到这个模型，这种情况下有什么办法用xinference部署并管理吗？

**Comment by qinxuye** [comment]
目前 vl 的自定义如果列表内没有的会比较难处理。
