### ISSUE TITLE
history of launched model

### ISSUE THREAD

**Issue by kratorado** [xorbitsai/inference#1319]
### Is your feature request related to a problem? Please describe
xinference is a great system/tool. But due to resource limitation, I stop and start different LLM frequently. So each time I start a LLM instance, I have to fill the lauching model form, with the same infomation

### Describe the solution you'd like
Need a history of lauched model or any alternative, to save the form-filling step, maybe a "favorite model lauching arguments"

**Comment by qinxuye** [comment]
Thank you for your suggestion, we will do some investigation and see how to meet your requirements.
