### ISSUE TITLE
In the Rocm5.6/py310/pytorch2.1.2 environment, Xinf unable to recognize the AMD GPU

### ISSUE THREAD

**Issue by Loongel** [xorbitsai/inference#1326]
### Describe the bug
In the Rocm5.6/py310/pytorch2.1.2 environment, Xinf unable to recognize the AMD GPU
The number of GPUs shown in Xinf is 0 (Figure 1), but the actual number of GPUs is 1, and pytorch can find it (Figure 3).
The xinference running environment (Figure 2,  Figure 3) and the phenomenon (Figure 1) are the same conda environment

### To Reproduce
xinference-local -H 0.0.0.0 
env (Figure 3) 

### Expected behavior
Xinf recognize the AMD GPU in Cluster Information / Worker Details

### Additional context
![image](https://github.com/xorbitsai/inference/assets/9842313/89b814d5-30ac-4ece-aed8-a1d847b52657)

![image](https://github.com/xorbitsai/inference/assets/9842313/c8c17a78-ffd7-46da-97f6-c8313fc6c5f5)

![image](https://github.com/xorbitsai/inference/assets/9842313/a2d7e3af-d6cd-4b8a-a210-194df1275566)

**Comment by qinxuye** [comment]
From the code you paste, seems worker should be able to recognize the GPU count.
