### ISSUE TITLE
集群部署xinference注册自定义模型

### ISSUE THREAD

**Issue by LivingXu** [xorbitsai/inference#1327]
请问集群部署xinference注册自定义模型时，指定worker上的模型路径后提示Invalid model URI file应如何解决？
supervisor部署在172.16.52.122，worker部署在172.16.53.201，模型在worker上
![图片](https://github.com/xorbitsai/inference/assets/41823342/476609cb-83c7-44a2-8104-0682ffcc61b9)

![图片](https://github.com/xorbitsai/inference/assets/41823342/ddf29bf5-80ee-47f0-8588-fbb1b9417e00)

**Comment by ChengjieLi28** [comment]
@LivingXu 分布式注册要保证所有节点都有这个模型路径

**Comment by LivingXu** [comment]
> @LivingXu 分布式注册要保证所有节点都有这个模型路径

好的，谢谢。另外请问一下能否在vllm启动模型的时候指定vllm_gpu_util等参数呢？

**Comment by ChengjieLi28** [comment]
> > @LivingXu 分布式注册要保证所有节点都有这个模型路径
> 
> 好的，谢谢。另外请问一下能否在vllm启动模型的时候指定vllm_gpu_util等参数呢？

可以，界面上launch时下方有额外参数添加，命令行也可以，需要的额外参数直接加在后面
```
xinference launch xxx --gpu-memory-utilization 0.85
```

**Comment by LivingXu** [comment]
> > > @LivingXu 分布式注册要保证所有节点都有这个模型路径
> > 
> > 
> > 好的，谢谢。另外请问一下能否在vllm启动模型的时候指定vllm_gpu_util等参数呢？
> 
> 可以，界面上launch时下方有额外参数添加，命令行也可以，需要的额外参数直接加在后面
> 
> ```
> xinference launch xxx --gpu-memory-utilization 0.85
> ```
尝试过添加额外的参数，但是报错如下。“--gpu-memory-utilization”和 “gpu-memory-utilization”都会报错。
![图片](https://github.com/xorbitsai/inference/assets/41823342/9c27604d-7e37-4f34-b2f5-bfdaaed7c28b)

![图片](https://github.com/xorbitsai/inference/assets/41823342/faf003ec-58f1-4a56-a039-4902a8425ccb)

**Comment by ChengjieLi28** [comment]
> > > > @LivingXu 分布式注册要保证所有节点都有这个模型路径
> > > 
> > > 
> > > 好的，谢谢。另外请问一下能否在vllm启动模型的时候指定vllm_gpu_util等参数呢？
> > 
> > 
> > 可以，界面上launch时下方有额外参数添加，命令行也可以，需要的额外参数直接加在后面
> > ```
> > xinference launch xxx --gpu-memory-utilization 0.85
> > ```
> 
> 尝试过添加额外的参数，但是报错如下。“--gpu-memory-utilization”和 “gpu-memory-utilization”都会报错。 ![图片](https://private-user-images.githubusercontent.com/41823342/323827315-9c27604d-7e37-4f34-b2f5-bfdaaed7c28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTk1MjYsIm5iZiI6MTcxMzQ5OTIyNiwicGF0aCI6Ii80MTgyMzM0Mi8zMjM4MjczMTUtOWMyNzYwNGQtN2UzNy00ZjM0LWIyZjUtYmZkYWFlZDdjMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjRiZWE0NGUyOWQ4M2Y3ZjFiNDA3YjkzNjU5YmZhOGU0OGNkODRhOTIxZjhlMWQwMDMwODE5ZDNjOTcyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JFZB5KlYtmhjcDpndwa3HawXv31EJ5Skg62Ps6NzJHA)
> 
> ![图片](https://private-user-images.githubusercontent.com/41823342/323827235-faf003ec-58f1-4a56-a039-4902a8425ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTk1MjYsIm5iZiI6MTcxMzQ5OTIyNiwicGF0aCI6Ii80MTgyMzM0Mi8zMjM4MjcyMzUtZmFmMDAzZWMtNThmMS00YTU2LWEwMzktNDkwMmE4NDI1Y2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNzc0ZDM3MDIyYmQ0YWU1OTQ0OTdlMWU0N2M2MjFkMzI2MzNlYjY5MWU3OTk4ZGQ4NWQ1ZmQ0MjU5MjFkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHQ7_HcmJlPqsv17PHl4sGuWAfOYN892yLKBwsPadmE)

下划线，同时在页面不要加--前缀
填入`gpu_memory_utilization`

**Comment by LivingXu** [comment]
> > > > > @LivingXu 分布式注册要保证所有节点都有这个模型路径
> > > > 
> > > > 
> > > > 好的，谢谢。另外请问一下能否在vllm启动模型的时候指定vllm_gpu_util等参数呢？
> > > 
> > > 
> > > 可以，界面上launch时下方有额外参数添加，命令行也可以，需要的额外参数直接加在后面
> > > ```
> > > xinference launch xxx --gpu-memory-utilization 0.85
> > > ```
> > 
> > 
> > 尝试过添加额外的参数，但是报错如下。“--gpu-memory-utilization”和 “gpu-memory-utilization”都会报错。 ![图片](https://private-user-images.githubusercontent.com/41823342/323827315-9c27604d-7e37-4f34-b2f5-bfdaaed7c28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTk1MjYsIm5iZiI6MTcxMzQ5OTIyNiwicGF0aCI6Ii80MTgyMzM0Mi8zMjM4MjczMTUtOWMyNzYwNGQtN2UzNy00ZjM0LWIyZjUtYmZkYWFlZDdjMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjRiZWE0NGUyOWQ4M2Y3ZjFiNDA3YjkzNjU5YmZhOGU0OGNkODRhOTIxZjhlMWQwMDMwODE5ZDNjOTcyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JFZB5KlYtmhjcDpndwa3HawXv31EJ5Skg62Ps6NzJHA)
> > ![图片](https://private-user-images.githubusercontent.com/41823342/323827235-faf003ec-58f1-4a56-a039-4902a8425ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTk1MjYsIm5iZiI6MTcxMzQ5OTIyNiwicGF0aCI6Ii80MTgyMzM0Mi8zMjM4MjcyMzUtZmFmMDAzZWMtNThmMS00YTU2LWEwMzktNDkwMmE4NDI1Y2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNzc0ZDM3MDIyYmQ0YWU1OTQ0OTdlMWU0N2M2MjFkMzI2MzNlYjY5MWU3OTk4ZGQ4NWQ1ZmQ0MjU5MjFkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHQ7_HcmJlPqsv17PHl4sGuWAfOYN892yLKBwsPadmE)
> 
> 下划线，同时在页面不要加--前缀 填入`gpu_memory_utilization`

已解决，十分感谢。
