### ISSUE TITLE
ChatGLM3-128k 模型实际 最大输出被限制在了 4096

### ISSUE THREAD

**Issue by jony4** [xorbitsai/inference#1334]
https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/vllm/core.py#L194 应该是这儿的 max_model_len 给锁死了最大长度？

**Comment by qinxuye** [comment]
UI上添加额外选项 key是max_model_len，value是长度看下。

**Comment by jony4** [comment]
好的，我试下
