### ISSUE TITLE
v10.2.post1,命令行BUG,默认执行pytorch格式模型

### ISSUE THREAD

**Issue by xcpuma** [xorbitsai/inference#1336]
命令行BUG,默认执行pytorch格式模型，测试qwen1.5-7b 或qwen1.5-32b awq、gptq量化模型
 --model-format awq 或  --model-format gptq 不起作用，默认启动pytorch格式模型

**Comment by qinxuye** [comment]
收到，我们会尽快定位问题。

**Comment by ChengjieLi28** [comment]
@xcpuma try `v0.10.3` and close this issue if it works.
