### ISSUE TITLE
无法注册模型

### ISSUE THREAD

**Issue by QichangZheng** [xorbitsai/inference#1339]
使用docker部署，宿主机默认路径有huggingface下载的模型，也挂载了路径，但是无法注册模型。提示'Please fill in valid value for all fields',路径换成'/root/.cache/huggingface/hub/models--mistralai--Mistral-7B-Instruct-v0.2'也不行。
![image](https://github.com/xorbitsai/inference/assets/82627111/6ab68fe4-914a-447c-9bd7-8568f2ab55df)

**Comment by shell-nlp** [comment]
这个问题怎么解决
