### ISSUE TITLE
rerank models运行成功，但是访问端口无响应

### ISSUE THREAD

**Issue by 983183947** [xorbitsai/inference#1349]
页面上显示rerank model运行成功，但是实际访问端口一直卡着没有数据返回，通过浏览器和dify都一样。
<img width="1439" alt="image" src="https://github.com/xorbitsai/inference/assets/25240344/a3ea9950-4a49-4fa5-9ba2-b23bd228e691">
<img width="1439" alt="image" src="https://github.com/xorbitsai/inference/assets/25240344/2403f455-2364-4647-9335-708b99f09843">

**Comment by amumu96** [comment]
服务端日志贴一下看看

**Comment by 983183947** [comment]
配置时使用启动的端口（默认9997）就行了
