### ISSUE TITLE
FEAT: support llava vl series models, e.g. llava-v1.6-34b

### ISSUE THREAD

**Issue by Index103000** [xorbitsai/inference#1353]

**Comment by uana777** [comment]
xinf version: 0.12.1
Doenload llava1.6-13B from hf-mirror. Register model params:
{
    "version": 1,
    "model_name": "custom-llava",
    "model_description": "This is a custom model description.",
    "context_length": 4096,
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "generate",
        "chat"
    ],
    "model_family": "vicuna-v1.5",
    "model_specs": [
        {
            "model_uri": "/home/clo/llava-13B",
            "model_size_in_billions": 13,
            "model_format": "pytorch",
            "quantizations": [
                "none"
            ]
        }
    ],
    "prompt_style": {
        "style_name": "ADD_COLON_TWO",
        "system_prompt": "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.",
        "roles": [
            "USER",
            "ASSISTANT"
        ],
        "intra_message_sep": " ",
        "inter_message_sep": "</s>",
        "stop": null,
        "stop_token_ids": null
    }
}

Got error:
 Server error: 400 - [address=10.183.159.37:45789, pid=1501914] Unrecognized configuration class <class 'transformers.models.llava.configuration_llava. LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.  Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, JambaConfig,  JetMoeConfig, LlamaConfig, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, OlmoConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig,  RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
 
 
 Any suggestions? ths.
