### ISSUE TITLE
如何判断模型有使用GPU。

### ISSUE THREAD

**Issue by 983183947** [xorbitsai/inference#1356]
如何判断模型有使用GPU。从正在运行的模型界面看GPU Indexes空白。但是我机器有显卡
![image](https://github.com/xorbitsai/inference/assets/25240344/a758e111-f09a-44aa-82df-de4bec7ae92e)

**Comment by qinxuye** [comment]
检查你的 llama-cpp-python 安装是否正确，对于 cuda 使用

```
CMAKE_ARGS="-DLLAMA_CUDA=on" pip install llama-cpp-python
```

安装

**Comment by 983183947** [comment]
可以了，感谢。
