### ISSUE TITLE
Use pip install to install xinference. How to install only the worker role or supervisor role?QUESTION

### ISSUE THREAD

**Issue by m199369309** [xorbitsai/inference#1386]
Use pip install to install xinference. How to install only the worker role or supervisor role?

**Comment by qinxuye** [comment]
The roles are mixed together, just install xinference is OK for both.

**Comment by m199369309** [comment]
> The roles are mixed together, just install xinference is OK for both.
意思是说，xinference的supervisor/worker这些角色，无法单独安装？都集成在xinference里面对吧
