### ISSUE TITLE
Latest docker image detects only one NVIDIA card

### ISSUE THREAD

**Issue by emulated24** [xorbitsai/inference#1390]
### Describe the bug
For some reason the latest docker container doesn't detect two of my Tesla P40 cards, but only one. Loading Mixtral LLM fails:

`ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Tesla P40, compute capability 6.1, VMM: yes
llm_load_tensors: ggml ctx size =    0.83 MiB
warning: failed to mlock 90112000-byte buffer (after previously locking 0 bytes): Cannot allocate memory`

When executing this test, both cards are correctly detected:
`sudo docker run -it --gpus all nvidia/cuda:12.4.1-runtime-ubuntu22.04 nvidia-smiPlease kindly advise.`

### To Reproduce

Docker version 26.1.0, build 9714adc

```
sudo docker run \
  -v /home/<user>/.xinference:/root/.xinference \
  -v /home/<user>/.cache/huggingface:/root/.cache/huggingface \
  -v /home/<user>/.cache/modelscope:/root/.cache/modelscope \
  -p 9997:9997 \
  --gpus all \
  xprobe/xinference:latest \
  xinference-local -H 0.0.0.0
```

**Comment by qinxuye** [comment]
Does not look like it's the problem of Xinference, looks like sth wrong with driver or sth.
