### ISSUE TITLE
FEAT: Support Arctic of Snowflake

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#1392]
model link⬇️: 
https://huggingface.co/Snowflake/snowflake-arctic-base
https://huggingface.co/Snowflake/snowflake-arctic-instruct

**Comment by qinxuye** [comment]
This is a weird model, huge weights but with insanely small part activated.

**Comment by Minamiyama** [comment]
It has high performance and low cost, espacially useful on enterprice scenes😆
