### ISSUE TITLE
ERROR: Failed building wheel for chatglm-cpp when pip install xinference[all]

### ISSUE THREAD

**Issue by Maplemx** [xorbitsai/inference#1393]
### Describe the bug
`ERROR: Failed building wheel for chatglm-cpp` will be showed and break the installation process when `pip install xinference[all]`

### To Reproduce
1. Python 3.10.11
2. Xinference 0.10.3
3. Windows 11

### Expected behavior
installation finished

### Additional context
**SOLUTION FOR THOSE WHO COME ACROSS THIS ERROR, GO TO [chatglm.cpp project to DOWNLOAD WHEEL FILE RELEASE](https://github.com/li-plus/chatglm.cpp/releases) and INSTALL IT BY YOURSELF!**

download and use `pip install <wheel_file_path>` to install.

It's not Xinference's fault, it's chatglm.cpp's and this error is an old one last for months and they never fixed it.

**Comment by BradKML** [comment]
Seconding this as well but does it work with Docker?
