### ISSUE TITLE
BUG: launch Qwen1.5-moe failed on docker

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#1395]
Error message: ValueError: [address=0.0.0.0:38973, pid=80] The checkpoint you are trying to load has model type `qwen2_moe` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

![image](https://github.com/xorbitsai/inference/assets/918617/e0c88e87-6f4c-4f16-a184-599b2fbea7f7)

**Comment by qinxuye** [comment]
The qwen1.5-moe requires installing transformers from source code.

```
pip install git+https://github.com/huggingface/transformers
```

We just installed latest transformers in docker, you need to install it on your own.

**Comment by Minamiyama** [comment]
> The qwen1.5-moe requires installing transformers from source code.
> 
> ```
> pip install git+https://github.com/huggingface/transformers
> ```
> 
> We just installed latest transformers in docker, you need to install it on your own.

use `pip install --upgrade transformers` upgrade to latest version(now is 4.40.1) is ok

**Comment by qinxuye** [comment]
Oh, transformers 4.40.0 has supported it.
