### ISSUE TITLE
Xinference 只提供bge的rerank模型？？？

### ISSUE THREAD

**Issue by liangpn** [xorbitsai/inference#1398]
fastgpt 调用 xinference rerank接口报错
fastgpt的配置
![image](https://github.com/xorbitsai/inference/assets/52708183/1dd40a46-cf08-42bb-95cf-f9993b4d2dd3)

使用bce的reank会有下面的错误
![69cb08bb59c01b9eea328d3d2a898f6](https://github.com/xorbitsai/inference/assets/52708183/3fe04377-17cc-49b4-9943-45022f9af2c7)
![61622e47e94db52755c596b9f40dac0](https://github.com/xorbitsai/inference/assets/52708183/833cdfd9-4ae1-4955-9b37-357e1efbb827)
使用bge的reank则是正常
![f2a56b93a0dba4f31eaad604966129f](https://github.com/xorbitsai/inference/assets/52708183/cb5a52e2-322f-4252-b6e6-23b0ee9c74cd)
![cc0b1ab03cd32142d7743ba5e109f8f](https://github.com/xorbitsai/inference/assets/52708183/44b3d3d3-dbf4-4bbc-a35d-52fad557e265)

但是直接curl 调用xinference 的rerank 接口是返回正常
![image](https://github.com/xorbitsai/inference/assets/52708183/a25a292d-d008-4f4c-a0c5-5bbb545cbf01)

**Comment by qinxuye** [comment]
Xinference 如果 curl 没问题，感觉是 FastGPT 那边的问题。

**Comment by liangpn** [comment]
> Xinference 如果 curl 没问题，感觉是 FastGPT 那边的问题。
是的，curl 是没问题的，fastgpt那边我也提了issue.

**Comment by NaiveYan** [comment]
dify上复现了类似的报错。
dify调用部署在0.10.1和0.10.3版本xinference上的bce reranker模型都会报类似的错误，但0.10.2.post1版本可以正常使用。

**Comment by codingl2k1** [comment]
但是只有0.10.2post1用的是FlagEmbedding推理的，0.10.3又改回了sentence transformers推理因为很多用户说FlagEmbedding出错。

**Comment by NaiveYan** [comment]
v0.11.0上问题依然存在。我检查了一下具体的http request，以下请求使用bce模型会报错，使用bge模型可以正常rerank
`
{"model": "bce-reranker-base_v1", "documents": ["override def stop(): Unit = Option(server).foreach(_.close())\n\n}\n\nobject App {\n val logger: Logger = Logger[App]\n\n def main(args: Array[String]): Unit = {\n val config = new JsonObject(Files.readString(new File(args(0)).toPath))\n val vertx = Vertx.vertx(VertxOptions().setPreferNativeTransport(true))\n\n printConfig(vertx)\n\n vertx.exceptionHandler(_.printStackTrace())\n\n implicit val executionContext: VertxExecutionContext = VertxExecutionContext(vertx.getOrCreateContext())\n\n vertx\n .deployVerticleFuture(\n ScalaVerticle.nameForVerticle[App],\n DeploymentOptions().setInstances(JVertxOptions.DEFAULT_EVENT_LOOP_POOL_SIZE).setConfig(config)\n )\n .onComplete {\n case _: Success[String] => logger.info(\"Server listening on port 8080\")\n case f: Failure[String] => logger.error(\"Unable to start application\", f.exception)\n }\n }\n\n private def printConfig(vertx: Vertx): Unit = {\n val version = Try {\n def resourceAsStream(resource: String) = classOf[Vertx].getClassLoader.getResourceAsStream(resource)\n\n val in =\n Option(resourceAsStream(\"META-INF/vertx/vertx-version.txt\")).getOrElse(resourceAsStream(\"vertx-version.txt\"))\n val out = new ByteArrayOutputStream\n val buffer = new Array[Byte](256)\n\n Iterator\n .continually(in.read(buffer))\n .takeWhile(_ != -1)\n .foreach(read => out.write(buffer, 0, read))\n\n out.toString\n }.recover { case e: IOException =>\n logger.error(\"Could not read Vert.x version\", e)\n \"unknown\"\n }.get", "package test\n\nimport com.typesafe.scalalogging.Logger\nimport io.vertx.core.buffer.Buffer\nimport io.vertx.core.http.HttpHeaders\nimport io.vertx.core.json.{JsonArray, JsonObject}\nimport io.vertx.core.{AsyncResult, Handler, VertxOptions => JVertxOptions}\nimport io.vertx.lang.scala.{ScalaVerticle, VertxExecutionContext}\nimport io.vertx.pgclient.{PgConnectOptions, PgConnection}\nimport io.vertx.scala.core.http.{HttpServer, HttpServerRequest, HttpServerResponse}\nimport io.vertx.scala.core.{DeploymentOptions, Vertx, VertxOptions}\nimport io.vertx.scala.ext.web.Router\nimport io.vertx.sqlclient.{Row, RowSet, SqlConnection, Tuple}\nimport test.model.{Fortune, Message, World}\n\nimport java.io.{ByteArrayOutputStream, File, IOException}\nimport java.nio.file.Files\nimport java.util.concurrent.ThreadLocalRandom\nimport scala.collection.JavaConverters._\nimport scala.concurrent.{Future, Promise}\nimport scala.util.{Failure, Sorting, Success, Try}\n\ncase class Header(name: CharSequence, value: String)\n\nclass App extends ScalaVerticle {\n\n private val HELLO_WORLD = \"Hello, world!\"\n private val HELLO_WORLD_BUFFER = Buffer.buffer(HELLO_WORLD, \"UTF-8\")\n\n private val contentTypeJson = Header(HttpHeaders.CONTENT_TYPE, \"application/json\")\n private val contentTypeHtml = Header(HttpHeaders.CONTENT_TYPE, \"text/html; charset=UTF-8\")\n private val contentTypePlainText = Header(HttpHeaders.CONTENT_TYPE, \"text/plain\")\n\n private var server: HttpServer = _\n private var client: PgConnection = _\n\n override def startFuture(): Future[_] = {", "private var server: HttpServer = _\n private var client: PgConnection = _\n\n override def startFuture(): Future[_] = {\n\n val pgConnectOptions = new PgConnectOptions()\n .setDatabase(config.getString(\"database\"))\n .setHost(config.getString(\"host\"))\n .setPort(config.getInteger(\"port\", 5432))\n .setUser(config.getString(\"username\"))\n .setPassword(config.getString(\"password\"))\n .setCachePreparedStatements(true)\n .setPipeliningLimit(100000)\n\n val jVertx = vertx.asJava.asInstanceOf[io.vertx.core.Vertx]\n val pgConnectionPromise = Promise[Unit]\n PgConnection.connect(\n jVertx,\n pgConnectOptions,\n (ar => {\n client = ar.result()\n pgConnectionPromise.success()\n }): Handler[AsyncResult[PgConnection]]\n )\n\n val router = Router.router(vertx)\n router.get(\"/plaintext\").handler(context => handlePlainText(context.request()))\n router.get(\"/json\").handler(context => handleJson(context.request()))\n router.get(\"/db\").handler(context => handleDb(context.request()))\n router.get(\"/queries\").handler(context => handleQueries(context.request()))\n router.get(\"/updates\").handler(context => handleUpdates(context.request()))\n router.get(\"/fortunes\").handler(context => handleFortunes(context.request()))\n\n val port = 8080\n server = vertx.createHttpServer()\n val httpServerPromise = Promise[Unit]\n server\n .requestHandler(router.accept)\n .listen(port, (_ => httpServerPromise.success()): Handler[AsyncResult[HttpServer]])\n\n pgConnectionPromise.future.flatMap(_ => httpServerPromise.future)\n }\n\n private def handlePlainText(request: HttpServerRequest): Unit = {\n responseWithHeaders(request.response, contentTypePlainText).end(HELLO_WORLD_BUFFER)\n }"], "query": "\u8fd9\u662f\u4ec0\u4e48\u9879\u76ee\uff1f", "top_n": 3, "max_chunks_per_doc": null, "return_documents": null}
`
