### ISSUE TITLE
运行启动模型命令报错，模型不存在。Model not found in the model list, uid: qwen1.5-chat-1-0

### ISSUE THREAD

**Issue by sammichenVV** [xorbitsai/inference#1403]
在执行启动命令时如果不指定gpu报错No available slot found for the model，指定gpu的index后又报模型不存在，不知道在哪里删除这个模型，模型列表里也没有，有谁知道么？
![image](https://github.com/xorbitsai/inference/assets/22388079/688d109d-506e-4f5b-a1c4-9fce805271bd)

**Comment by qinxuye** [comment]
No available slot 意思是没有显卡能分配这个模型了。

另外指定 gpu idx 是 --gpu-idx 0。

**Comment by sammichenVV** [comment]
> No available slot 意思是没有显卡能分配这个模型了。
> 
> 另外指定 gpu idx 是 --gpu-idx 0。
依然报错，我是没有启动任何LLM，页面上没有显示，显卡也没有被占用，现在因为这个不存在的qwen model 我自己的chatglm模型无法启动
![image](https://github.com/xorbitsai/inference/assets/22388079/bcded511-0f93-4100-ae62-5030787416f6)
![image](https://github.com/xorbitsai/inference/assets/22388079/93873385-03dc-4fe8-b5d2-9e7e44890b93)

**Comment by qinxuye** [comment]
服务端日志看下

**Comment by sammichenVV** [comment]
> 服务端日志看下
我重启了一下可以了
