### ISSUE TITLE
Embedding模型和rerank模型不支持指定GPU编号？

### ISSUE THREAD

**Issue by Chen94yue** [xorbitsai/inference#1409]
使用如下指令启动模型：
xinference launch --model-name bce-embedding-base_v1 --model-type embedding --gpu-idx 5
服务端的log为：
xinference.core.worker 3771 INFO     You specify to launch the model: bce-embedding-base_v1 on GPU index: [5] of the worker: 0.0.0.0:28950, xinference will automatically ignore the `n_gpu` option.
似乎设置是生效了，但是模型还在加载在了0号卡上。

**Comment by qinxuye** [comment]
支持的，你是用的什么版本？

**Comment by Chen94yue** [comment]
xinference, version 0.10.2.post1+4.g30420f5

**Comment by qinxuye** [comment]
你是从源码安装的？更新到最新的代码吧。

**Comment by Chen94yue** [comment]
直接用的官方提供的镜像

**Comment by qinxuye** [comment]
> 直接用的官方提供的镜像

那个镜像？

**Comment by qinxuye** [comment]
什么时候拉的，这两天刚修复一个相关问题。

**Comment by Chen94yue** [comment]
我拉最新的试试

**Comment by Chen94yue** [comment]
最新的没有问题
