### ISSUE TITLE
FEAT: support modifying registered custom model configs

### ISSUE THREAD

**Issue by ConleyKong** [xorbitsai/inference#1411]
对于xinference未官方支持的模型我们常需要自己手动注册，但是有时候并不确定注册的模型类型或者模型名是否合适，当部署失败时常常需要返回修改一些参数，但是目前平台仅支持删除后重建，无法快速修改部分参数，就很不方便，期望可以支持修改的功能

**Comment by qinxuye** [comment]
收到，我们看下怎么支持。
