### ISSUE TITLE
怎么在启动的时候设置vllm的显存占用率？

### ISSUE THREAD

**Issue by sammichenVV** [xorbitsai/inference#1413]
启动qwen-1.5-7b-chat默认就把显存给吃满了，我还要部署其他模型服务，怎么设置？
![e417935211d98875a11aaf89496d37f](https://github.com/xorbitsai/inference/assets/22388079/f94b71bd-c87c-41fe-ad0c-e3f335a8543c)

**Comment by qinxuye** [comment]
界面上在 launch +号加一个 gpu_memory_utilization，值是 0.8（默认是 0.9，即90%）

如果是命令行，增加 --gpu_memory_utilization 0.8

**Comment by sammichenVV** [comment]
> 界面上在 launch +号加一个 gpu_memory_utilization，值是 0.8（默认是 0.9，即90%）
> 
> 如果是命令行，增加 --gpu_memory_utilization 0.8

好的 已解决
