### ISSUE TITLE
同样用 docker 部署 看别人视频2080ti 比我的3090 推理速度 快好几倍 是什么原因

### ISSUE THREAD

**Issue by maogeigei** [xorbitsai/inference#1414]
模型用的 qwen1.5-7b-chat-gptq-int8
![image](https://github.com/xorbitsai/inference/assets/122587001/011d416a-9ffb-4165-84f5-3e4b11d409f0)
下面是别人用2080ti
![image](https://github.com/xorbitsai/inference/assets/122587001/5ee3fc34-e19b-4d85-996c-ccc3d46e23fd)

**Comment by qinxuye** [comment]
Int8 支持用 vllm 后端还没有发版，如果用 docker 可以试用下最新的 nightly-main

**Comment by maogeigei** [comment]
![image](https://github.com/xorbitsai/inference/assets/122587001/e77de5c4-05df-44e1-a88c-e8dc0a403733)
这是我的显卡性能感觉没啥问题

**Comment by maogeigei** [comment]
> Int8 支持用 vllm 后端还没有发版，如果用 docker 可以试用下最新的 nightly-main

就是疑惑他推理速度这么快呢

**Comment by qinxuye** [comment]
> > Int8 支持用 vllm 后端还没有发版，如果用 docker 可以试用下最新的 nightly-main
> 
> 就是疑惑他推理速度这么快呢

你的这个量化格式没有用最高效的后端来加速，等新版发布了速度会有大幅提高，如果不等新版就按我说的，用我指定的镜像。

**Comment by maogeigei** [comment]
谢谢 好的我试试

**Comment by qinxuye** [comment]
先关闭 issue，如果遇到问题可以再开。

**Comment by qinxuye** [comment]
xinference-local 

哪里来的 xinference-night？

**Comment by maogeigei** [comment]
这个是我取的容器的名字，名字不能随便取吗

**Comment by maogeigei** [comment]
改成local了好了我先试试

**Comment by maogeigei** [comment]
![image](https://github.com/xorbitsai/inference/assets/122587001/b48e71c7-f419-401d-8184-0e76a4547348)
以为可以了容器日志到这里就关闭了 起步起来
