### ISSUE TITLE
加载自定义模型 qwen1.5 0.5B chat

### ISSUE THREAD

**Issue by GXKIM** [xorbitsai/inference#1415]
### 如上述文字
自定义模型0.5B 是json文件这么写不对吗？请指教，json无法解析

![image](https://github.com/xorbitsai/inference/assets/125621025/873e5d80-2f66-45f3-b234-97e729b81b32)

![image](https://github.com/xorbitsai/inference/assets/125621025/fcf8fb9b-d280-42bb-a812-2e3e822afd83)

**Comment by qinxuye** [comment]
碰到什么报错？

**Comment by GXKIM** [comment]
> 碰到什么报错？

0.5B 1.8这种这么写模型权重大小不对吗

**Comment by qinxuye** [comment]
"0_5"

**Comment by GXKIM** [comment]
> "0_5"

嗯感谢可以使用了，请问现在支持注册多个模型吗，在一个json文件里写入相关模型参数的话
