### ISSUE TITLE
I saw the configuration file of Yi-9b in the source code, but I can't use it.

### ISSUE THREAD

**Issue by moyudaduizhang** [xorbitsai/inference#1421]
![image](https://github.com/xorbitsai/inference/assets/113818551/efccccff-345f-4e9d-8945-f2babcbe1cd0)

![QQ截图20240502203237](https://github.com/xorbitsai/inference/assets/113818551/27149e6e-50d7-411f-a694-d1959eb4764e)

**Comment by codingl2k1** [comment]
Could you update your xinference?
![image](https://github.com/xorbitsai/inference/assets/138426806/99cab6c9-be7d-4052-8e39-d14e459f28eb)
