### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\anaconda\Lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by zhaoyuchen1128** [xorbitsai/inference#1428]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context
shm.dll存在但报此错误

**Comment by tankGe** [comment]
请问你解决了吗？我也碰到这个问题
