### ISSUE TITLE
FEAT: support deepseek v2 chat and coder

### ISSUE THREAD

**Issue by GXKIM** [xorbitsai/inference#1440]
如题

**Comment by qinxuye** [comment]
deepseek coder 支持了吧

**Comment by adogcode** [comment]
https://www.modelscope.cn/models/deepseek-ai/DeepSeek-V2-Chat/summary

**Comment by 100ZZ** [comment]
<img width="2463" alt="image" src="https://github.com/xorbitsai/inference/assets/95963615/3126e8d5-158a-46c0-b904-0bda31f2a017">
Mac M系列这个问题能搞定么？我都是本地下载好的模型自定义注册
Model Family：deepseek-chat（other也一样）
xinference：0.12.0

**Comment by ye7love7** [comment]
236B的那个模型没有支持

**Comment by dongfangzan** [comment]
什么时候可以支持呢？一直等着这个模型

**Comment by qinxuye** [comment]
We will support it ASAP.
