### ISSUE TITLE
BUG: there is no tool_call ability

### ISSUE THREAD

**Issue by mikeshi80** [xorbitsai/inference#1445]
https://github.com/xorbitsai/inference/blob/944bf6c033e2cd60d0eb22edcf15e2f4ffdb0765/xinference/model/llm/llm_family.py#L169

Here it is compared with `tool_call`, but there is only `tools` ability in model abilities.

https://github.com/xorbitsai/inference/blob/944bf6c033e2cd60d0eb22edcf15e2f4ffdb0765/xinference/model/llm/llm_family.py#L117

**Comment by qinxuye** [comment]
Yes, this must be a bug, can you fix it?

**Comment by mikeshi80** [comment]
> Yes, this must be a bug, can you fix it?

Sure, but which is right? `tool_call` or `tools`, I notice that the source code use `tool_call` everywhere, maybe it is better to unify the term first.

**Comment by qinxuye** [comment]
@codingl2k1 What is your opinion?

**Comment by mikeshi80** [comment]
Unified to `tools` anyway.

**Comment by Starlento** [comment]
Hi guys, for the docker version for v0.11.1. I still cannot see it. Did I miss something?
![image](https://github.com/xorbitsai/inference/assets/33574105/8c7d8297-cd55-4f67-9ac4-5d599ddb0d62)
![image](https://github.com/xorbitsai/inference/assets/33574105/c2bc5321-12d4-47bd-aef0-a2f457032fbf)

**Comment by qinxuye** [comment]
The custom model can have tools ability only if the model family has.

**Comment by Starlento** [comment]
> The custom model can have tools ability only if the model family has.

Could you kindly show me the list for the model families which support tools?
As there is no tools selection to filter:
![image](https://github.com/xorbitsai/inference/assets/33574105/75c3ffb3-b8df-415e-92fd-10e3b0a12aac)

And is it possible to just "assign the wrong family" to hack the function?

**Comment by Starlento** [comment]
> > The custom model can have tools ability only if the model family has.
> 
> Could you kindly show me the list for the model families which support tools? As there is no tools selection to filter: ![image](https://private-user-images.githubusercontent.com/33574105/333173792-75c3ffb3-b8df-415e-92fd-10e3b0a12aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjcwMDQsIm5iZiI6MTcxNjQ2NjcwNCwicGF0aCI6Ii8zMzU3NDEwNS8zMzMxNzM3OTItNzVjM2ZmYjMtYjhkZi00MTVlLTkyZmQtMTBlM2IwYTEyYWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEyMTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYmExNjk5YTFiMGVhODQ1YjY2MTY4MjEyZDA3YzdiY2NhMDc4ZWI4ZDdjY2MxMGUxN2U5YTE5YmU1NTNiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PXAK58T2l-4ylnMFfYvjq086U9OqHs1o8R86zUSmzk) Also, I think chatglm3 family is for sure have tools ability. But when I select it, the json file has no tools there and I do not find anywhere to modify it in webui: ![image](https://private-user-images.githubusercontent.com/33574105/333174657-07bef68b-9ea0-4b3c-a0dc-b9afe48b294e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjcwMDQsIm5iZiI6MTcxNjQ2NjcwNCwicGF0aCI6Ii8zMzU3NDEwNS8zMzMxNzQ2NTctMDdiZWY2OGItOWVhMC00YjNjLWEwZGMtYjlhZmU0OGIyOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEyMTgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzI4NWM5YWU3OWQ2ZDBiZjQxNzYyZDE2ZDMwMjg4NWNiODdlODU5NjYyN2RlYjVkNDUzMWVmNWU4MGViYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cjFZzq7i0N3MCTqU6LIw0KQHwVrGups4tlqOndj5uA)
> 
> And is it possible to just "assign the wrong family" to hack the function?

I just check llm_family.json, I found that qwen1.5 supports tools. I am actually using qwen1.5 32B q4_k_m. And I also modify the json config file with tools. I still cannot use the function call in dify. But when I change model_family to chatglm3, dify can identify it as function call. But the request just failed.

**Comment by qinxuye** [comment]
If you still encounter issue, better to open a new issue instead of discussing in this closed issue.
