### ISSUE TITLE
xinference-local 启动怎么自动启动上次停止时运行的模型

### ISSUE THREAD

**Issue by icedfired** [xorbitsai/inference#1449]
xinference-local  启动怎么自动启动上次停止时运行的模型，每次都需要去页面再启动一次？

**Comment by qinxuye** [comment]
目前不支持启动上次停止的模型。你可以用命令行 xinference launch 写在 shell 里，每次重启 xinference-local 后跑对应 shell。

**Comment by redreamality** [comment]
This may be a good feature to add.

**Comment by qinxuye** [comment]
The GUI will remember the parameters, it's quite convenient .
