### ISSUE TITLE
Ray worker crashed error in docker

### ISSUE THREAD

**Issue by insistence-essenn** [xorbitsai/inference#1450]
Server error: 500 - [address=xinference-worker-3:43697, pid=28225] The actor died unexpectedly before finishing this task. class_name: RayWorkerVllm actor_id: 43bef624e9a09fa65fb3f0f701000000 pid: 41977 namespace: 9c8e6b06-be1a-45ef-8c47-0cd7d1168cd0 ip: 172.27.0.4 The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors. The actor never ran - it was cancelled before it started running.

Note that the issue tracker is NOT the place for general support.

**Comment by qinxuye** [comment]
Refer to https://inference.readthedocs.io/en/latest/getting_started/troubleshooting.html#when-using-the-official-docker-image-rayworkervllm-died-due-to-oom-causing-the-model-to-fail-to-load

**Comment by insistence-essenn** [comment]
> Refer to https://inference.readthedocs.io/en/latest/getting_started/troubleshooting.html#when-using-the-official-docker-image-rayworkervllm-died-due-to-oom-causing-the-model-to-fail-to-load

How to do the same for docker-compose.yml using docker compose up, I am using that method because I need multiple workers?

**Comment by insistence-essenn** [comment]
@qinxuye Can you please help?

**Comment by qinxuye** [comment]
I am not familiar with docker-compose, for docker itself, the failure is due to shm size.
