### ISSUE TITLE
BUG: Install Error  Macbook

### ISSUE THREAD

**Issue by ciaoyizhen** [xorbitsai/inference#1454]
macbook air 2022
python 3.10.11
```
pip install "xinference[transformers]"
```

Collecting xinference[transformers]
  Using cached xinference-0.10.3-py3-none-any.whl (21.8 MB)
Collecting peft
  Using cached peft-0.10.0-py3-none-any.whl (199 kB)
Requirement already satisfied: typing-extensions in ./.env/lib/python3.10/site-packages (from xinference[transformers]) (4.11.0)
Collecting pynvml
  Using cached pynvml-11.5.0-py3-none-any.whl (53 kB)
Collecting sse-starlette>=1.6.5
  Using cached sse_starlette-2.1.0-py3-none-any.whl (9.2 kB)
Collecting async-timeout
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting openai>1
  Using cached openai-1.26.0-py3-none-any.whl (314 kB)
Collecting s3fs
  Using cached s3fs-2024.3.1-py3-none-any.whl (29 kB)
Collecting timm
  Using cached timm-0.9.16-py3-none-any.whl (2.2 MB)
Requirement already satisfied: torch in ./.env/lib/python3.10/site-packages (from xinference[transformers]) (2.3.0)
Collecting pydantic
  Using cached pydantic-2.7.1-py3-none-any.whl (409 kB)
Collecting fsspec<=2023.10.0,>=2023.1.0
  Using cached fsspec-2023.10.0-py3-none-any.whl (166 kB)
Collecting click
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Collecting passlib[bcrypt]
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Collecting modelscope>=1.10.0
  Using cached modelscope-1.14.0-py3-none-any.whl (5.7 MB)
Collecting huggingface-hub<1.0,>=0.19.4
  Using cached huggingface_hub-0.23.0-py3-none-any.whl (401 kB)
Collecting tabulate
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting xoscar>=0.3.0
  Using cached xoscar-0.3.0-cp310-cp310-macosx_10_9_universal2.whl (2.1 MB)
Collecting aioprometheus[starlette]>=23.12.0
  Using cached aioprometheus-23.12.0-py3-none-any.whl (31 kB)
Collecting typer[all]<0.12.0
  Using cached typer-0.11.1-py3-none-any.whl (43 kB)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-macosx_11_0_arm64.whl (44.2 MB)
Collecting pillow
  Using cached pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl (3.4 MB)
Collecting python-jose[cryptography]
  Using cached python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
Collecting fastapi
  Using cached fastapi-0.111.0-py3-none-any.whl (91 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting uvicorn
  Using cached uvicorn-0.29.0-py3-none-any.whl (60 kB)
Collecting gradio>=3.39.0
  Using cached gradio-4.29.0-py3-none-any.whl (12.3 MB)
Collecting optimum
  Using cached optimum-1.19.1-py3-none-any.whl (417 kB)
Collecting sentencepiece
  Using cached sentencepiece-0.2.0-cp310-cp310-macosx_11_0_arm64.whl (1.2 MB)
Collecting transformers>=4.34.1
  Using cached transformers-4.40.2-py3-none-any.whl (9.0 MB)
Collecting transformers-stream-generator
  Using cached transformers-stream-generator-0.0.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting torchvision
  Downloading torchvision-0.18.0-cp310-cp310-macosx_11_0_arm64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 546.5 kB/s eta 0:00:00
Collecting xinference[transformers]
  Using cached xinference-0.10.2.post1-py3-none-any.whl (21.8 MB)
  Using cached xinference-0.10.2-py3-none-any.whl (21.8 MB)
  Using cached xinference-0.10.1-py3-none-any.whl (21.8 MB)
  Using cached xinference-0.10.0-py3-none-any.whl (21.8 MB)
Collecting opencv-python
  Using cached opencv_python-4.9.0.80-cp37-abi3-macosx_11_0_arm64.whl (35.4 MB)
Collecting xinference[transformers]
  Using cached xinference-0.9.4-py3-none-any.whl (21.7 MB)
Collecting accelerate>=0.20.3
  Using cached accelerate-0.30.0-py3-none-any.whl (302 kB)
Collecting einops
  Downloading einops-0.8.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 2.3 MB/s eta 0:00:00
Collecting tiktoken
  Using cached tiktoken-0.6.0-cp310-cp310-macosx_11_0_arm64.whl (949 kB)
Collecting protobuf
  Using cached protobuf-5.26.1-cp37-abi3-macosx_10_9_universal2.whl (404 kB)
Collecting bitsandbytes
  Using cached bitsandbytes-0.42.0-py3-none-any.whl (105.0 MB)
Collecting auto-gptq
  Using cached auto_gptq-0.7.1.tar.gz (126 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/bt/5tsbfy851nl82znjzr3216rr0000gn/T/pip-install-1e5oum6q/auto-gptq_354fee009ae24cb1af444fea9494748f/setup.py", line 62, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

macbook only have mps and no cuda. if xinference support macbook?

**Comment by ciaoyizhen** [comment]
![WechatIMG26](https://github.com/xorbitsai/inference/assets/83450192/74a13eda-c01a-4489-8571-51737b3c44fa)

**Comment by ChengjieLi28** [comment]
@ciaoyizhen Thanks for reporting. This is a bug. Will fix for the next release. MacOS should not install the `auto-gptq` package.

**Comment by jj449** [comment]
I'm on windows 10 ,  encounter this error too . 
pip install "xinference[all]"

`  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\morri\AppData\Local\Temp\pip-install-4lydoq3u\auto-gptq_bd06011723874fd2a0c5a393da35403d\setup.py", line 62, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'`
