### ISSUE TITLE
Have anyone sucessed install from source code?

### ISSUE THREAD

**Issue by sunhaha123** [xorbitsai/inference#1455]
Facing promble "ValueError: --model-engine is required for LLM models."  when using "pip install .[transfomers]".

**Comment by qinxuye** [comment]
This is new feature introduced, when launching, now you have to specify model engine, and the web UI is not available for now.

If you want to use on web UI, you have to use an older version, you can run 

```
git reset --hard 1063585d2115da0e4132e0b4207c0c3c11d19c7e
```

to set the source code to a version that not introduced the engine.
