### ISSUE TITLE
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

### ISSUE THREAD

**Issue by insistence-essenn** [xorbitsai/inference#1464]
Note that the issue tracker is NOT the place for general support.
Unable to solve this issue as I am using Distributed-compose.yml

**Comment by insistence-essenn** [comment]
@frostyplanet @qinxuye @bufferoverflow Any help?

**Comment by frostyplanet** [comment]
I've encounter the same problem, do not have any clue for now. What's your enviroment and related package version? (vllm, pytorch, ray,  nvidia-drivers, cuda )
I you are using docker, vllm will print error into stdout （but do not log to xinference.log）.  Could you look for error before this exception ? Is there anything simular to this :
![ray_error_libgomp_20240514-144338](https://github.com/xorbitsai/inference/assets/318150/347e1561-1269-4266-89cb-403e0f620f07)
