### ISSUE TITLE
多卡启动自定义模型时，报Remote server unixsocket错误

### ISSUE THREAD

**Issue by mrkingsun** [xorbitsai/inference#1474]
两张卡，第一张（12G/32G）,第二张（1G/32G）。模型是internlm2-chat-7b。

- 只使用第二张卡加载，显存占用大概30G，可以正常启动；
- 因为占用快满了，想利用下第一张卡，在注册页面设置了gpu-index为0，1。启动时就报错Remote server unixsocket

**Comment by codingl2k1** [comment]
有没有服务端的错误信息？

**Comment by mrkingsun** [comment]
解决了，检索了一下是docker内存不足，在run的时候加上--shm-size=10.24gb即可
