### ISSUE TITLE
使用xinference部署模型，输出异常截断的问题

### ISSUE THREAD

**Issue by ybsbbw** [xorbitsai/inference#1480]
xinference版本 0.10.1
vllm 0.3.0

使用xinference部署qwen-72B模型时，输出内容长度达到2000~3000汉字时，出现输出内容逻辑上还没有结束，但是输出内容异常中断的情形。

输入+输出的总长度约为13000个汉字，

使用的是本地存储的原始模型

直接通过vllm部署时从来没有出现过这一问题

部署命令：
model_uid = client.launch_model(model_uid='Qwen1.5-72B-chat',
                                             model_name='Qwen1.5-72B-chat',
                                             model_format='pytorch',
                                             model_size_in_billions=72,
                                             max_model_len=32000,
                                             gpu_memory_utilization=0.8,
                                             n_gpu=8)

是因为还需要其它的配置参数吗？能否出一份文档详细介绍下部署模型时可能用到的各个参数？

**Comment by qinxuye** [comment]
确认走了 vllm 后端了吗？

**Comment by ybsbbw** [comment]
> 确认走了 vllm 后端了吗？

肯定是走了，8张卡的显存都快占满了，占用比例和gpu_memory_utilization=0.8基本一致

**Comment by ybsbbw** [comment]
> 确认走了 vllm 后端了吗？

会不会和vllm版本有关系？
我在另一台服务器上用0.4.0版本的vllm部署，命令
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m vllm.entrypoints.openai.api_server \
             --model "${model_path}" \
             --served-model-name "Qwen1.5-110B-Chat" \
             --tensor-parallel-size 4 \
             --gpu-memory-utilization 1 \
             --max-model-len 32000 \
             --host [0.0.0.0](http://0.0.0.0/) \
             --port 8889
就没有问题

**Comment by WangxuP** [comment]
你在注册模型的时候那个content-length设置的多大呢？

**Comment by ybsbbw** [comment]
> 你在注册模型的时候那个content-length设置的多大呢？
max_model_len=32000
