### ISSUE TITLE
安装xinference卡住不动

### ISSUE THREAD

**Issue by wangyongpenga** [xorbitsai/inference#1483]
<img width="1120" alt="image" src="https://github.com/xorbitsai/inference/assets/27179069/e9abeb5d-4141-472d-ad5d-9b96997aebc9">
卡在这1小时了

**Comment by tanyo520** [comment]
+1
![企业微信截图_17155938045127](https://github.com/xorbitsai/inference/assets/5094034/829d65a1-51e7-426b-8d88-ed933b94555c)

**Comment by Alchemistqqqq** [comment]
+1

**Comment by hwzhuhao** [comment]
+1

**Comment by Xudong-Mao** [comment]
可以尝试下面的解决办法： https://github.com/vllm-project/vllm/issues/4360
