### ISSUE TITLE
无法注册qwen1.5模型

### ISSUE THREAD

**Issue by shell-nlp** [xorbitsai/inference#1498]
### Describe the bug
无法注册qwen1.5模型
![image](https://github.com/xorbitsai/inference/assets/39985245/8cb15aed-58f0-4e80-a337-1ecbb6188887)
![image](https://github.com/xorbitsai/inference/assets/39985245/1c9d33ba-430b-4ec9-b090-50f9ead27e54)

### To Reproduce
1. 启动docker 方式
docker run  -v /home/dev/.xinference:/root/.xinference -v /home/dev/.cache/huggingface:/root/.cache/huggingface -v /home/dev/.cache/modelscope:/root/.cache/modelscope -v  /home/dev/model:/home/dev/model -p 9997:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

**Comment by ChengjieLi28** [comment]
@shell-nlp 提示你选择model_family了啊。你这个选择qwen1.5-chat。
