### ISSUE TITLE
v0.11.0 启动容器异常

### ISSUE THREAD

**Issue by liangpn** [xorbitsai/inference#1499]
这是服务器cuda版本
![a2d637219cdbe0dac9ebf3ec130d1a5](https://github.com/xorbitsai/inference/assets/52708183/7108b21f-ee5f-40fa-9cd6-bb43de851c07)
服务器是Ubuntu 22.04
![image](https://github.com/xorbitsai/inference/assets/52708183/04f88d51-7ae5-4d8c-9370-3d54bdff8bfd)

执行的启动命令是
docker run -d -e XINFERENCE_MODEL_SRC=modelscope -e XINFERENCE_HOME=/data/models -v /home/lenovo/AI/xinference-models:/data/models -p 9997:9997 --gpus all --name xinference xprobe/xinference:v0.11.0 xinference-local -H 0.0.0.0

容器输出日志为
![7aba77bd60502c3b2e58f4808b6d124](https://github.com/xorbitsai/inference/assets/52708183/2c48f11e-4a90-4a30-8f90-7de9ad1378c9)

容器只输出了这一段内容就退出进程了，不知道什么问题。。

**Comment by ChengjieLi28** [comment]
@liangpn docker logs <container_id>看下有什么日志，贴出来。我这边复现不出来，大概率跟宿主机的cuda相关

**Comment by sadlay** [comment]
> @liangpn docker logs <container_id>看下有什么日志，贴出来。我这边复现不出来，大概率跟宿主机的cuda相关

同样问题
CUDA 版本：12.3
docker logs日志
```
==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

```
然后就退出了，没有其他的日志显示

**Comment by ChengjieLi28** [comment]
> > @liangpn docker logs <container_id>看下有什么日志，贴出来。我这边复现不出来，大概率跟宿主机的cuda相关
> 
> 同样问题，v0.7.5版本正常，v0.11.0有问题。
> 
> CUDA 版本：12.3 docker logs日志
> 
> ```
> ==========
> == CUDA ==
> ==========
> 
> CUDA Version 12.1.1
> 
> Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
> 
> This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> By pulling and using the container, you accept the terms and conditions of this license:
> https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> 
> A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
> ```
> 
> 然后就退出了，没有其他的日志显示
> 
> dan shi

0.7.5到0.11.0都不可以吗？你这也是linux上运行的docker吗？

**Comment by sadlay** [comment]
> > > @liangpn docker logs <container_id>看下有什么日志，贴出来。我这边复现不出来，大概率跟宿主机的cuda相关
> > 
> > 
> > 同样问题，v0.7.5版本正常，v0.11.0有问题。
> > CUDA 版本：12.3 docker logs日志
> > ```
> > ==========
> > == CUDA ==
> > ==========
> > 
> > CUDA Version 12.1.1
> > 
> > Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
> > 
> > This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> > By pulling and using the container, you accept the terms and conditions of this license:
> > https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> > 
> > A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后就退出了，没有其他的日志显示
> > dan shi
> 
> 0.7.5到0.11.0都不可以吗？你这也是linux上运行的docker吗？

CUDA 12.3版本，0.7.5正常，0.11.0启动失败，其他版本没有测试

**Comment by wxxz666** [comment]
同样问题，解决了吗

**Comment by ChengjieLi28** [comment]
@sadlay @liangpn @wxxz666 尝试下这个镜像：
```
docker pull xprobe/xinference:nightly-docker_crash_due_to_llama
```

**Comment by CamusGao** [comment]
> @sadlay @liangpn @wxxz666 尝试下这个镜像：
> 
> ```
> docker pull xprobe/xinference:nightly-docker_crash_due_to_llama
> ```

Same problem get resolved by this solution.
