### ISSUE TITLE
能否接入Qwen-Audio-Chat模型？

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [xorbitsai/inference#1523]
### Describe the solution you'd like
在语音模型中能否接入Qwen-Audio-Chat模型？我们发现whisper对中文的转录并不是太好，Qwen-Audio-Chat效果好得多，能否在语音模型中接入Qwen-Audio-Chat？

**Comment by qinxuye** [comment]
Duplicated with #1072 .

**Comment by WholeWorld-Timothy** [comment]
https://github.com/xorbitsai/inference/issues/1072 跟我这个说i的是一个事么？1072问的是Qwen-Audio是否支持openai的api，我问的是xinference能否在audio models里面支持qwen-audio-chat，1072里面那回复说的是xinference是不是支持audio，这是打算咋处理，能明确说一下么？
