### ISSUE TITLE
codeqwen1.5-7b-base，deepseek-coder-6.7b-base等base模型，在注册时无法找到对应的family，选other后，没有vllm引擎

### ISSUE THREAD

**Issue by Ellenyan123** [xorbitsai/inference#1525]
xinference对base模型支持比较少。目前codeqwen1.5-7b-base，deepseek-coder-6.7b-base vllm都是可以支持的，但是在xinference上，无法通过注册进行添加。

**Comment by wangyongpenga** [comment]
我也遇到了+1
