### ISSUE TITLE
After xinference is installed successfully, the model deployment fails

### ISSUE THREAD

**Issue by Alchemistqqqq** [xorbitsai/inference#1565]
After installing xinference, I am trying to deploy codeqwen. The following error is displayed on my terminal. How do I resolve it?
![77478547285cf6cb93a513ab9237b80](https://github.com/xorbitsai/inference/assets/146717415/5de60974-e088-4203-a926-dd4fa48e4bde)
![96f22ebd83198450e438f29c51bd6bb](https://github.com/xorbitsai/inference/assets/146717415/ab14114d-9294-4adb-b1bc-df7efa6a05e1)

**Comment by qinxuye** [comment]
In additional parameters, add one record, key is `dtype`, value is `half` would solve your problem

**Comment by Alchemistqqqq** [comment]
> dtype

> In additional parameters, add one record, key is `dtype`, value is `half` would solve your problem.
How much GPU memory does this need? I have two tesla t4 16G each, but after using the solution you gave me, the memory is not enough
![image](https://github.com/xorbitsai/inference/assets/146717415/53765747-5fb9-40c6-829b-56062cd9e295)
![image](https://github.com/xorbitsai/inference/assets/146717415/b9b68016-bc26-4651-a589-2af6b8aa53f8)
