### ISSUE TITLE
希望尽快支持 glm-4-9b-chat，谢谢！

### ISSUE THREAD

**Issue by mrkingsun** [xorbitsai/inference#1587]
希望尽快支持 glm-4-9b-chat，谢谢！

**Comment by qinxuye** [comment]
Supported already on main branch.

**Comment by goldeneave** [comment]
So how to boot the model in web interface, I do not find the model

**Comment by edisonzf2020** [comment]
Node LLM run failed: [xinference] Error: An error occurred during streaming
使用GLM-4-chat报错

**Comment by yechaoying** [comment]
have you solved this problem?
