### ISSUE TITLE
glm4 tool calls support

### ISSUE THREAD

**Issue by wuyiclover** [xorbitsai/inference#1592]
![image](https://github.com/xorbitsai/inference/assets/37546904/761d7265-cac7-4b97-bcd3-d0059a484ba9)

**Comment by 13428116504** [comment]
为什么glm4的tool call用不了，chatglm3是可以调用的，是不是glm的tool call 还不支持？

**Comment by jlcoo** [comment]
有人能回答一下这个问题么？

**Comment by wuyiclover** [comment]
对，现在还不支持
