### ISSUE TITLE
A BUG when use qwen with stream and tools.

### ISSUE THREAD

**Issue by idiotTest** [xorbitsai/inference#1596]
### Describe the bug
When i use tools and stream in qwen vllm,I found the result was truncated. I mean many results lost.
### To Reproduce
I depoly the model ,which is qwen1.5-14b-chat,and i use the vllm.
```shell
curl --location 'http://124.70.213.108:7009/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "qwen1.5-14b-chat",
    "messages": [
        {
            "content": "\n            你是一位智能助手，请通过你自己的知识和调用工具解决问题,全部回答请用中文,如果可以调用工具解决，请调用工具，如果不可以则用自己的理解回答。\n            ",
            "role": "system"
        },
        {
            "content": "中国有几个省份",
            "role": "user"
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "search_wheather",
                "description": "search_wheather(input: str) - 当你需要对某个城市的天气进行查询时,使用这个工具",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "input": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "input"
                    ]
                }
            }
        }
    ],
    "stream": true,
    "n": 1,
    "temperature": 0.0
}' 
```
### Expected behavior
The model stream result seems to be truncated.Only the last a few message received.

**Comment by DCJsenior** [comment]
I have also been troubled by this bug for a long time when I use langchain AgentExecutor. I hope the developers can solve it, I would appreciate it if it can be solved.

**Comment by zhanghx0905** [comment]
For streaming responses to qwen's tool calls, xinference's current implementation performs some filtering operations, in order to filter out the ReAct "thought" process. This operation seems somewhat problematic. Maybe the filtering step should be removed.

**Comment by idiotTest** [comment]
> For streaming responses to qwen's tool calls, xinference's current implementation performs some filtering operations, in order to filter out the ReAct "thought" process. This operation seems somewhat problematic. Maybe the filtering step should be removed.

Thinks for your reply.
I want to test your  methods，But because of some reason，not available for now.
Did you test question and your idea?

**Comment by Jiehuishun** [comment]
> For streaming responses to qwen's tool calls, xinference's current implementation performs some filtering operations, in order to filter out the ReAct "thought" process. This operation seems somewhat problematic. Maybe the filtering step should be removed.

Having tested your pr, now Streaming outputs from Qwen1.5 goes well when using vLLM(Maybe the content is not we need, when function-call reply). Thanks a lot. Hope maintainer review your pr asap.

**Comment by edisonzf2020** [comment]
+1
qwen2 and glm-4-chat same issue

**Comment by zhanghx0905** [comment]
Since my PR has been merged, please update xinference to the latest version and check if the same issue occurs.

**Comment by qinxuye** [comment]
Close first, feel free to reopen if issue exists still.
