### ISSUE TITLE
BUG: missing ChatTTS thirdparty files in docker image

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#1608]
in docker container files⬇️: 

![image](https://github.com/xorbitsai/inference/assets/918617/97ae58fe-6705-4cbb-8a3d-ea3f8b751767)

in source codes ⬇️:

![image](https://github.com/xorbitsai/inference/assets/918617/63e48f3c-ea92-4fe3-9daf-6115862f1288)

so, launch chattts from docker failed

**Comment by qinxuye** [comment]
Yes, it should be fixed by #1606 , we can wait for the nighly-main built tomorrow.
