### ISSUE TITLE
chatTTS BUG

### ISSUE THREAD

**Issue by LixiangHello** [xorbitsai/inference#1611]
ModuleNotFoundError: [address=0.0.0.0:41497, pid=2853] No module named 'xinference.thirdparty.ChatTTS.model'

**Comment by liduang** [comment]
![image](https://github.com/xorbitsai/inference/assets/37337756/f625276c-6e61-47ce-8103-2b2a16dea929)

**Comment by qinxuye** [comment]
This is addressed by #1606 , you can try nightly-main image or wait for the next release.
