### ISSUE TITLE
BUG: XINFERENCE_MODEL_SRC=huggingface 在中文系统下不生效

### ISSUE THREAD

**Issue by LukeWang-Plus** [xorbitsai/inference#1615]
版本 v0.12.0 ，在设置环境变量 `XINFERENCE_MODEL_SRC=huggingface` 后仍然从 modelscope 下载模型。

在查看了仓库源码后发现，如下代码逻辑使得中文系统只能使用 modelscope 。

https://github.com/xorbitsai/inference/blob/1ea34120ddea40ccc93cf576f3bc82fc6aae2070/xinference/model/utils.py#L44-L50

issue #1149 提到，通过该环境变量的设置可以强制使用 huggingface 下载模型，而上述逻辑是否有违该变量的设计目标。

改为如下的类似逻辑是不是更好？（代码有点渣，但大概意思是这）优先根据环境变量设置下载源，接着才根据其他条件判断。

``` python
def download_from_modelscope() -> bool:
    if os.environ.get(XINFERENCE_ENV_MODEL_SRC) == "modelscope":
        return True
    elif os.environ.get(XINFERENCE_ENV_MODEL_SRC) == "huggingface":
        return False
    elif is_locale_chinese_simplified():
        return True
    else:
        return False
```

**Comment by qinxuye** [comment]
可能比较好的做法是：

```
if os.environ.get(XINFERENCE_ENV_MODEL_SRC):
    # 当设置了环境变量
    return os.environ.get(XINFERENCE_ENV_MODEL_SRC) =="modelscope"
elif is_locale_chinese_simplified():
    return True
else:
    return False    
```

欢迎提交 PR。
