### ISSUE TITLE
Qwen2-7B & Qwen2-72B support context length 128K？

### ISSUE THREAD

**Issue by gamersover** [xorbitsai/inference#1623]
The docs at https://inference.readthedocs.io/zh-cn/latest/models/builtin/llm/qwen2-instruct.html indicates that the context length of qwen2-instruct is 32K. However, the Qwen2-7B and Qwen2-72B models officially support a context length of 128K. Is it possible to support the longer context length in qwen2-instruct?

**Comment by majestichou** [comment]
> The docs at https://inference.readthedocs.io/zh-cn/latest/models/builtin/llm/qwen2-instruct.html indicates that the context length of qwen2-instruct is 32K. However, the Qwen2-7B and Qwen2-72B models officially support a context length of 128K. Is it possible to support the longer context length in qwen2-instruct?

Maybe you can read this: https://modelscope.cn/models/qwen/Qwen2-72B-Instruct/summary. 
```
To handle extensive inputs exceeding 32,768 tokens, we utilize [YARN](https://arxiv.org/abs/2309.00071), a technique for enhancing model length extrapolation, ensuring optimal performance on lengthy texts.

For deployment, we recommend using vLLM. You can enable the long-context capabilities by following these steps:
...
```
