### ISSUE TITLE
关于自己注册的模型无法使用vLLM加速的问题。

### ISSUE THREAD

**Issue by KnightLancelot** [xorbitsai/inference#1624]
我自己注册了一个qwen2moe的模型，详见下面的参数：
{"version": 1, "context_length": 32768, "model_name": "my-qwen2-moe-instruct", "model_lang": ["en", "zh"], "model_ability": ["chat"], "model_description": "Qwen2 is the new series of Qwen large language models.", "model_family": "other", "model_specs": [{"model_format": "pytorch", "model_size_in_billions": 14, "quantizations": ["4-bit", "8-bit", "none"], "model_id": "Qwen/Qwen2-57B-A14B-Instruct", "model_hub": "modelscope", "model_uri": "/home/server/.cache/modelscope/hub/qwen/Qwen2-57B-A14B-Instruct"}], "prompt_style": {"style_name": "QWEN", "system_prompt": "You are a helpful assistant.", "roles": ["user", "assistant"], "intra_message_sep": "\n", "stop_token_ids": [151643, 151644, 151645], "stop": ["<|endoftext|>", "<|im_start|>", "<|im_end|>"]}}

使用
xinference launch --model-engine http://localhost:9997 --model-engine transformers --model-name my-qwen2-moe-instruct --size-in-billions 14 --model-format pytorch --quantization none --gpu-idx 4
或是通过浏览器，model-engine选择transformers，是可以正常启动的。
但是如果将model-engine改为vLLM，就会报“ValueError: [address=0.0.0.0:40912, pid=45068] Model my-qwen2-moe-instruct cannot be run on engine vLLM.”
同时，我发现xinference中自带的qwen2-moe-instruct是可以model-engine选vLLM的。

请问这是什么原因？

**Comment by qinxuye** [comment]
model_family 请选择 qwen2-moe-instruct。
