### ISSUE TITLE
when i update inference to least,Custom definition Rerank model happen error

### ISSUE THREAD

**Issue by WillWillWong** [xorbitsai/inference#1635]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Expected behavior
![image](https://github.com/xorbitsai/inference/assets/104180186/76e5742c-5844-43fa-b767-07863183034b)

**Comment by codingl2k1** [comment]
Which version of xinference did you use before?

**Comment by WillWillWong** [comment]
> Which version of xinference did you use before? And which model was your custom model based on?
model:peg rerank model,vesion is v0.11 but I don't know the exact version
