### ISSUE TITLE
xinference用pip安装后如何修改huggingface模型默认位置？

### ISSUE THREAD

**Issue by chenqp** [xorbitsai/inference#1636]
xinference用docker安装时可以用-v </your/home/path>/.cache/huggingface:/root/.cache/huggingface改变huggingface模型的默认位置，但是用pip安装后设置 HF_HOME不管用，还是在XINFERENCE_HOM生成huggingface目录，模型下载到里面，如何将huggingface模型目录设置到指定位置？

**Comment by chenqp** [comment]
而且在docker 和pip安装huggingface模型下载的位置不一致，docker中-v </your/home/path>/.cache/huggingface:/root/.cache/huggingface，模型下载到huggingface/hub下，但是pip中模型直接下载到huggingface目录，导致软链接的方式也不行

**Comment by ChengjieLi28** [comment]
@chenqp 启动xinference的时候指定HUGGINGFACE_HUB_CACHE这个环境变量试试？
```
HUGGINGFACE_HUB_CACHE=<your path> xinference-local xxx
```

**Comment by qinxuye** [comment]
问题有解决吗？
