### ISSUE TITLE
huggingface源和modelscope源下载的模型cache不能共存？

### ISSUE THREAD

**Issue by chenqp** [xorbitsai/inference#1638]
### Describe the bug
huggingface源和modelscope源下载的模型都会在XINFERENCE_HOME下的cache目录建立软链接，但是因为huggingface源和modelscope源结构不同，在huggingface源下载的模型切换到modelscope源就会报错，必须删除cache目录的模型软链接，在modelscope源重新下载，如何下次再切换源，又会报错。

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version：3.11
2. The version of xinference you use:0.12

### Expected behavior
建议cache分别建立huggingface和modelscope目录，huggingface源和modelscope源相互不干扰

**Comment by qinxuye** [comment]
目前 xinference 界面上已经提供了删除 cache 的能力，这种情况还是先删除缓存。
