### ISSUE TITLE
qwen2.0-7b-instruct cannot use file as request body.(不能上传文件)

### ISSUE THREAD

**Issue by Bobyuan1015** [xorbitsai/inference#1640]
`
client = OpenAI(api_key="not empty",base_url='http://10.0.0.10:10009/v1')
file = client.files.create(file=Path(fname), purpose="file-extract")
completion = client.chat.completions.create(
  model="qwen2-instruct",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {
            'role': 'system',
            'content': f'fileid://{file.id}'
        },
    {"role": "user", "content": prompt}
  ]
)
`

`NotFoundError: Error code: 404 - {'detail': 'Not Found'}`
报错，我用的qwen模型，官方qwen是可以实现上传file的
请问下，xinference为什么不行

**Comment by qinxuye** [comment]
qwen 官方服务提供了 file 接口，而 xinference 并不提供此类功能。使用文件的内容请自行读取并放到 prompt 内。
