### ISSUE TITLE
glm4-chat的tool call 在dify下，无法使用

### ISSUE THREAD

**Issue by 13428116504** [xorbitsai/inference#1644]
背景：今天将xinfer升级到v0.12.1版本，跑glm4-chat模型，尝试使用tool call功能, 
使用的是dify下调用xinfer的glm4-chat的tool call功能，然后提示报错，报错图片如下：
![1](https://github.com/xorbitsai/inference/assets/64519449/bf72f4b2-0341-4a07-9280-c6191f09317b)
![2](https://github.com/xorbitsai/inference/assets/64519449/27ec9736-81e2-441f-b746-af9000fd7732)
![3](https://github.com/xorbitsai/inference/assets/64519449/087581d5-af8e-447b-ba8e-639fef06c152)

**Comment by 13428116504** [comment]
![4](https://github.com/xorbitsai/inference/assets/64519449/bf25b306-ba42-46e0-8e7a-8114dd90058f)
![5](https://github.com/xorbitsai/inference/assets/64519449/8673954e-2aaa-4e32-a2a0-bceebf0fa04e)

**Comment by okwinds** [comment]
Error log
[xinference.log](https://github.com/user-attachments/files/15839335/xinference.log)

**Comment by codingl2k1** [comment]
看上去是 tool call 后边的 observation 挂了，我尝试复现一下。

**Comment by codingl2k1** [comment]
你可以试试这个 PR吗？

**Comment by 13428116504** [comment]
![1718791972014](https://github.com/xorbitsai/inference/assets/64519449/cec973bf-0888-48c2-8ee7-df774a31d016)
@codingl2k1

**Comment by 13428116504** [comment]
还是有问题，会问第一次tool call，必现报错，后面提问没有出现报错，但是输出不稳定，工具掉不稳定
[xinfer.log](https://github.com/user-attachments/files/15899336/xinfer.log)

**Comment by 13428116504** [comment]
@XprobeBot @frostyplanet @codingl2k1 @okwinds

**Comment by 13428116504** [comment]
![image](https://github.com/xorbitsai/inference/assets/64519449/58d0fab9-7d9e-4553-aba5-567e87a92d83)

**Comment by codingl2k1** [comment]
> 还是有问题，会问第一次tool call，必现报错，后面提问没有出现报错，但是输出不稳定，工具掉不稳定 [xinfer.log](https://github.com/user-attachments/files/15899336/xinfer.log)

看日志你用的不是我那个分支的代码。你能尝试用这个分支吗？https://github.com/codingl2k1/inference/tree/bugfix/fix_tool_call_observation

**Comment by 13428116504** [comment]
我是用你的提交合并到主分支的代码跑的，只修改了你提交的这个文件xinference/model/llm/pytorch/chatglm.py
还是出现问题

> > 还是有问题，会问第一次tool call，必现报错，后面提问没有出现报错，但是输出不稳定，工具掉不稳定 [xinfer.log](https://github.com/user-attachments/files/15899336/xinfer.log)
> 
> 看日志你用的不是我那个分支的代码。你能尝试用这个分支吗？https://github.com/codingl2k1/inference/tree/bugfix/fix_tool_call_observation

**Comment by 13428116504** [comment]
> 我是用你的提交合并到主分支的代码跑的，只修改了你提交的这个文件xinference/model/llm/pytorch/chatglm.py 还是出现问题
> 
> > > 还是有问题，会问第一次tool call，必现报错，后面提问没有出现报错，但是输出不稳定，工具掉不稳定 [xinfer.log](https://github.com/user-attachments/files/15899336/xinfer.log)
> > 
> > 
> > 看日志你用的不是我那个分支的代码。你能尝试用这个分支吗？https://github.com/codingl2k1/inference/tree/bugfix/fix_tool_call_observation

![1719283406036](https://github.com/xorbitsai/inference/assets/64519449/65b00204-2a68-41de-aa15-6e646e8c487e)

**Comment by 13428116504** [comment]
> 我是用你的提交合并到主分支的代码跑的，只修改了你提交的这个文件xinference/model/llm/pytorch/chatglm.py 还是出现问题
> 
> > > 还是有问题，会问第一次tool call，必现报错，后面提问没有出现报错，但是输出不稳定，工具掉不稳定 [xinfer.log](https://github.com/user-attachments/files/15899336/xinfer.log)
> > 
> > 
> > 看日志你用的不是我那个分支的代码。你能尝试用这个分支吗？https://github.com/codingl2k1/inference/tree/bugfix/fix_tool_call_observation

我用你这个分支跑，环境依赖xinference-local 这个指令
![1719284013480](https://github.com/xorbitsai/inference/assets/64519449/8e2772d0-62c4-43a9-8fba-a7a7bbaf477d)
