### ISSUE TITLE
BUG: docker image of 0.12.1 launch failed

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#1646]
![image](https://github.com/xorbitsai/inference/assets/918617/480ffbc1-3a9b-4f88-95d9-a1c9d2d7759c)

**Comment by rabbitpig** [comment]
the same like this. restart without error.

![image](https://github.com/xorbitsai/inference/assets/2839943/b8fa943a-b8f5-41bb-9eeb-eea69a1eaaa4)

**Comment by ChengjieLi28** [comment]
@Minamiyama @rabbitpig Enter the container via `bash`, and try to import llama_cpp and see if there are some errors.
```
from llama_cpp import Llama
```

**Comment by rabbitpig** [comment]
> @

![image](https://github.com/xorbitsai/inference/assets/2839943/612dcedb-7618-473e-a766-14c2bd9dd0c8)

**Comment by ChengjieLi28** [comment]
> @ChengjieLi28
> 
> ![image](https://private-user-images.githubusercontent.com/2839943/340169893-612dcedb-7618-473e-a766-14c2bd9dd0c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTUzOTgsIm5iZiI6MTcxODU5NTA5OCwicGF0aCI6Ii8yODM5OTQzLzM0MDE2OTg5My02MTJkY2VkYi03NjE4LTQ3M2UtYTc2Ni0xNGMyYmQ5ZGQwYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDMzMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFlOWZmZDNlY2M4MWI2NmNmMDQyZmU1OGU4YWViOTFjMzkwOTdiNjU3NzFmZDM5MjMxOGMzMzY4ZTExNzg4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bRNJIYr68oraSN-Pol_iVsiyndsGcVQ8eYJwW54awes)

```
pip show llama-cpp-python
```
See the version information.

**Comment by ChengjieLi28** [comment]
@rabbitpig try build your own xinference image:
```
from xprobe/xinference:latest

RUN pip install "llama-cpp-python==0.2.77" --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121
```

Then try it to start xinference.

**Comment by rabbitpig** [comment]
> @rabbitpig try build your own xinference image:
> 
> ```
> FROM xprobe/xinference:latest
> 
> RUN pip install -U "llama-cpp-python==0.2.77" --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121
> ```
> 
> Then try it to start xinference.

it works. thanks

**Comment by Minamiyama** [comment]
> @rabbitpig try build your own xinference image:
> 
> ```
> FROM xprobe/xinference:latest
> 
> RUN pip install -U "llama-cpp-python==0.2.77" --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121
> ```
> 
> Then try it to start xinference.

wonderful, it works

**Comment by worm128** [comment]
我使用v0.12.2.post1和v0.12.1 镜像，都是启动失败不停重启，但是看docker日志又没看到报错信息

**Comment by worm128** [comment]
v0.12新版本【亲测可以，请叫我活雷锋】：
问题：使用v0.12.2.post1和v0.12.1 镜像，都是启动失败不停重启，但是看docker日志又没看到报错信息
1、新建dockerfile文件：
```
FROM xprobe/xinference:v0.12.2.post1
ENV all_proxy socks5://192.168.2.198:10806
RUN pip install -U "llama-cpp-python==0.2.77"
RUN pip install -U "httpx[socks]"
```
ENV设置环境变量的代理ip

创建一个安装了llama-cpp-python==0.2.77的自定义docker镜像
`docker build -f ./dockerfile -t xinference:winlone .`
2、运行自定义镜像xinference:winlone
`docker run --name xinference -d --restart always -p 9997:9997 -e XINFERENCE_HOME=/data -v /j/ai/ai-code/xinference1/:/data --gpus all xinference:winlone xinference-local -H 0.0.0.0`
