### ISSUE TITLE
Feat: Support download model only.

### ISSUE THREAD

**Issue by wxiwnd** [xorbitsai/inference#1652]
Now xinference only support download model with launch.
If I want to download a model for future use:
```bash
xinference launch -n qwen1.5-chat -s 7 -q Int4 -f awq -u qwen1.5-7 -en vllm
```
Then stop the model.

Add command line for download model only:
```bash
xinference model download -n qwen1.5-chat -s 7 -q Int4 -f awq
# Download model only without launch.
```

**Comment by qinxuye** [comment]
You can add --worker-ip to support downloading from specified worker.
