### ISSUE TITLE
BUG When I reasoning the model Qwen-VL-Chat-Int4 and Yi-VL-6B, the Model Engine cannot be found

### ISSUE THREAD

**Issue by okwinds** [xorbitsai/inference#1664]
**First, register the model as shown in the following screenshot.**

![image](https://github.com/xorbitsai/inference/assets/26739942/85fa05d9-ebaf-4f3d-b0f7-3d6f49008400)

**Second, find the Qwen-VL-Chat-Int4 inference in the list of custom models, as shown in the following screenshot**

![image](https://github.com/xorbitsai/inference/assets/26739942/040fde39-b017-4a7e-9a97-3ce92fb29be7)

**Qwen-VL-Chat-Int4**

<img width="942" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/c6e27e6b-8644-4a3f-913f-99fb344271c0">

<img width="678" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/c6929e53-c4ca-4df9-8995-a4ed39944b09">

**xinference, version 0.12.1**

**Comment by okwinds** [comment]
**Additional explanation
Yi-VL-6B has the same issue.**

<img width="408" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/65d98d02-30ce-4980-a2e7-af0b60817848">


<img width="352" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/367501d5-67f8-4047-921f-96aed651b848">

**Comment by ChengjieLi28** [comment]
@okwinds provide us the full screenshot. Did you select `vision` for VL models in `Model Abilities` section on the UI?

**Comment by okwinds** [comment]
> @okwinds provide us the full screenshot. Did you select `vision` for VL models in `Model Abilities` section on the UI?

yep, Registered again

![image](https://github.com/xorbitsai/inference/assets/26739942/d022df9f-7d9d-4c8c-81cc-9bc8c5093075)


![image](https://github.com/xorbitsai/inference/assets/26739942/91fe2541-cb7f-4767-aabd-b12751929561)


![image](https://github.com/xorbitsai/inference/assets/26739942/00d97c19-51bc-44a6-96ef-cf291c5f4cc2)

**Comment by yiyangshen** [comment]
Do not choose Generate in Abilities.

**Comment by okwinds** [comment]
> Do not choose Generate in Abilities.不要选择“能力”中的“生成”。

tried again 
it cannot work

    "model_ability": [
        "vision",
        "chat"
    ],

**Comment by amumu96** [comment]
This error cannot be reproduced in version 0.13.1, please try upgrading to the latest version. @okwinds

**Comment by okwinds** [comment]
The version of Xinference that I updated.

 now, xinference, version 0.13.2. 

The same operation process, the same problems still exist.

**Comment by xueqizhang121** [comment]
插眼，我使用0.11.3和0.13.1都存在这个问题

**Comment by lorra1990** [comment]
0.13.2版本  问题还是存在的 如果之前部署过其他模型有config缓存，可以正常配置，如果没有缓存的引擎选择不了，下拉框为空
![企业微信截图_7901af4f-795d-426b-b812-fdce57daa3ca](https://github.com/user-attachments/assets/3b64dfa4-eb8e-47ac-bdbe-bb6cc7e909c9)

**Comment by ricky977** [comment]
same question!

**Comment by Yog-AI** [comment]
0.12.0的含金量还在上升，我通过版本降级解决了
pip install xinference==0.12.0

**Comment by ricky977** [comment]
> 0.12.0的含金量还在上升，我通过版本降级解决了 pip install xinference==0.12.0
Pip install xinference==0.12.0 Is xinference [all] installed by default and how to install xinference [transformers]

**Comment by qinxuye** [comment]
主分支应该已经解决，本周发版后请尝试。使用镜像的话可以尝试拉 nightly-main 分支。
