### ISSUE TITLE
能否支持开机启动加载指定模型？

### ISSUE THREAD

**Issue by jony4** [xorbitsai/inference#1676]

**Comment by qinxuye** [comment]
可以 xinference-local 命令后 sleep 比如 10s，然后用 xinference launch 命令来加载模型。

**Comment by jony4** [comment]
好的，我试试

**Comment by nadirvishun** [comment]
> 可以 xinference-local 命令后 sleep 比如 10s，然后用 xinference launch 命令来加载模型。

这样是不行的，因为`xinference-local`命令是不会停止的，导致后续的脚本命令都不会执行，正确的方式参考：[服务Docker重启之后，如何恢复之前运行的模型](https://github.com/xorbitsai/inference/issues/1431)
