### ISSUE TITLE
QUESTION  how to load mini cpmV 2.5 gguf model which has two model files with xinference?

### ISSUE THREAD

**Issue by HakaishinShwet** [xorbitsai/inference#1681]
Mini cpmV 2.5 or other similar chat+vision support gguf models have two files one is chat model which is big file and one is small generally 1gb file which add vision capabilities and combining and running both together will only give complete model which I have seen in ollama but how can we do that in xinference? please guide step wise step in detail so that not just for mini cpmV type of multimodels but for other type of similar models too it will help everyone
Thankyou

**Comment by ChengjieLi28** [comment]
@HakaishinShwet You need to register gguf model to xinference and then use it. You can do it through web UI and refer to the document: https://inference.readthedocs.io/en/latest/models/custom.html
