### ISSUE TITLE
BUG：UI端关闭模型，资源没释放

### ISSUE THREAD

**Issue by leoterry-ulrica** [xorbitsai/inference#1682]
### Describe the bug
通过UI端点击关闭模型，但显存资源没有释放，或者释放不干净的问题。

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
   Python-3.10
3. The version of xinference you use.
   0.12.0
5. vllm version
   0.4.3

### Additional context
LLM：qwen2-72b-4bit/8bit

![image](https://github.com/xorbitsai/inference/assets/18339429/0cd973eb-261e-4fbf-a4ec-c331262b9f62)
![image](https://github.com/xorbitsai/inference/assets/18339429/2a8462da-10f4-4616-9d3e-8ad3e09a6236)
![image](https://github.com/xorbitsai/inference/assets/18339429/b41b2889-2a61-4c88-aadd-ada67acc6e3f)

**Comment by ChengjieLi28** [comment]
@leoterry-ulrica 4卡启动的qwen2-72b-4bit/8bit？启动成功后running models页面什么样发下截图。
然后点了ternimate按钮之后的日志是什么样，也发下

**Comment by leoterry-ulrica** [comment]
> @leoterry-ulrica 4卡启动的qwen2-72b-4bit/8bit？启动成功后running models页面什么样发下截图。 然后点了ternimate按钮之后的日志是什么样，也发下

1. 启动成功后running models
![image](https://github.com/xorbitsai/inference/assets/18339429/c54a6ebd-c011-4825-ac1a-f5888d90b603)

2. 点了terminate之后日志
![image](https://github.com/xorbitsai/inference/assets/18339429/4696cd6c-fdff-4027-aa04-63b612395f5d)

**Comment by leoterry-ulrica** [comment]
@ChengjieLi28 目前在4*L20和8*H800都能复现这个问题。

**Comment by ChengjieLi28** [comment]
> @ChengjieLi28 目前在4张L20和8张H800都能复现这个问题。

首先我这边没出现多卡无法释放资源的问题。先建议升级xinference和vllm。然后建议如下测试：
1. 不管xinference，只用vllm接口去4卡加载你的模型，然后使用一下再杀掉，看看他本身有没有问题。
2. 杀掉指直接干掉进程。
3. 多试几个vllm版本，如果你可以的话。

xinference没有额外做什么管理显存的事情，vllm加载后就完全交给vllm。

**Comment by leoterry-ulrica** [comment]
新版本v-0.14.1测试通过，已解决这个问题，点赞！ @qinxuye @ChengjieLi28
