### ISSUE TITLE
It seems that this preserves the ReAct "thought" process, but this is not user-friendly. Is it possible to use the method of the official Qwen function call?

### ISSUE THREAD

**Issue by okwinds** [xorbitsai/inference#1685]
It seems that this preserves the ReAct "thought" process, but this is not user-friendly. Is it possible to use the method of the official Qwen function call?
https://qwen.readthedocs.io/zh-cn/latest/framework/function_call.html

_Originally posted by @GabrielXie in https://github.com/xorbitsai/inference/issues/1598#issuecomment-2159605576_

https://github.com/xorbitsai/inference/pull/1598
推理引擎应该只做推理引擎该做的事情，对于用户体验是否友好的判断，这是业务领域的决策。官方的Qwen function call的方法，不应该隐藏react “thought”的推理过程。隐藏“thought”信息的逻辑，这在架构上，不应该放在模型层的推理引擎去帮业务做决定。这样的设计在分域治理的架构上是不可取的，希望官方谨慎考虑处理这样的推理逻辑。这可能会因为穿透性的给最终用户“良好体验”，反而给更多的推理业务带来风险和困扰。这在架构上应该解耦业务逻辑。

The inference engine should stick to its own duties, and the judgment of whether the user experience is friendly should be a decision made in the business domain. The official method of calling the Qwen function should not obscure the reasoning process of the "thought" in React. The logic of concealing "thought" information should not be incorporated into the model layer's inference engine to assist the business in making decisions. Such a design is undesirable in the architecture of domain-based governance, and it is hoped that the official will carefully consider the handling of such reasoning logic. This could potentially lead to a "good experience" for the end user through penetration, but in turn, it may bring risks and troubles to more inference operations.

This should decouple the business logic in the architecture.

**Comment by zhanghx0905** [comment]
I think it's useful to use a global variable to control whether the feature takes effect.

**Comment by zhanghx0905** [comment]
take

**Comment by okwinds** [comment]
> I think it will be useful to have a global variable to control whether the feature takes effect.

这也许是一个折中妥协的解决方案。基于你所提出的方案我能给出的建议是，默认显示react的“thought”内容，通过变量配置选择隐藏，以适配一些特殊需要。谢谢你的工作

Yep, this might be a compromise solution. Based on the proposal you have put forward, my suggestion is to display the "thought" content of React by default, and provide the option to hide it through variable configuration to accommodate some special needs. Thanks a lot for ur work.

**Comment by okwinds** [comment]
补充一下，关于qwen1.5的模型react prompt 隐藏“thought”推理过程，我做了一个demo，使用Langchain做react推理，要求两步调用工具，会出推理bug，而无法得到正确的结论。demo源代码见附件。


`from dotenv import load_dotenv, find_dotenv
from langchain.tools import Tool, tool
from langchain_community.utilities import SerpAPIWrapper
import calendar
import dateutil.parser as parser
from langchain import hub
from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor, create_react_agent

load_dotenv(find_dotenv())

search = SerpAPIWrapper()
tools = [
    Tool.from_function(
        func=search.run,
        name="Search",
        description="useful for when you need to answer questions about current events"
    ),
]

# 自定义工具
@tool("weekday")
def weekday(date_str: str) -> str:
    """Convert date to weekday name / 将日期转化为星期几"""
    d = parser.parse(date_str.replace('"', ''))
    print(f"\n\033[95m{llm.model_name} calling: --para--{date_str}\033[0m\n")
    return calendar.day_name[d.weekday()]

tools += [weekday]

prompt = hub.pull("hwchase17/react")

print(prompt.template)

# 此处的模型，可以换成qwen1.5的模型，因模型推理引擎隐藏了thought内容，Langchain无法正确处理推理调用工具，可复现bug
llm = ChatOpenAI(model_name='Qwen2-1.5B-Instruct-Int8', temperature=0)

# 定义一个 agent: 需要大模型、工具集、和 Prompt 模板
agent = create_react_agent(llm, tools, prompt)
# 定义一个执行器：需要 agent 对象 和 工具集
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True,
                               return_intermediate_steps=True, max_iterations=5)

agent_executor.invoke({"input": "王菲生日那天是星期几"})
print(f"Used model: {llm.model_name}")`


截图调用效果，如下

<img width="666" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/ff78341b-cc2a-4d68-9a7d-8bf2ef25d9fe">

<img width="772" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/797b7452-af31-4dca-b48e-4c9a52ebb869">

<img width="727" alt="image" src="https://github.com/xorbitsai/inference/assets/26739942/ad5c727d-1de8-42ab-ba6b-d208a7137218">




[qwreact.txt](https://github.com/user-attachments/files/15931551/qwreact.txt)

**Comment by zhanghx0905** [comment]
> 补充一下，关于qwen1.5的模型react prompt 隐藏“thought”推理过程，我做了一个demo，使用Langchain做react推理，要求两步调用工具，会出推理bug，而无法得到正确的结论。demo源代码见附件。 Demo bug复现源代码 [qwreact.txt]

I'm pretty sure that there is no relationship between the so-called "hidden" thought process and whether or not the model invokes the tool, it's just a filter on the output. 

As for the example you gave, LLM's tool calls are inherently unstable and unreliable. Changing the prompt might get the exact opposite effect.

**Comment by okwinds** [comment]
> > 补充一下，关于qwen1.5的模型react prompt 隐藏“thought”推理过程，我做了一个demo，使用Langchain做react推理，要求两步调用工具，会出推理bug，而无法得到正确的结论。demo源代码见附件。 Demo bug复现源代码 [qwreact.txt]
> 
> I'm pretty sure that there is no relationship between the so-called "hidden" thought process and whether or not the model invokes the tool, it's just a filter on the output.我非常确定所谓的“隐藏”思维过程与模型是否调用该工具之间没有任何关系，它只是对输出的过滤器。
> 
> As for the example you gave, LLM's tool calls are inherently unstable and unreliable. Changing the prompt might get the exact opposite effect.至于你举的例子，LLM的工具调用本质上是不稳定和不可靠的。更改提示可能会产生完全相反的效果。


I've examined a portion of the source code and I'm uncertain if it covers everything. Could you confirm whether the code appears to have implemented "thought" filtering only for the "function calling" method, without addressing "thought" filtering for the "prompt react" approach?

**Comment by JinCheng666** [comment]
mark.wait for final conclusion

**Comment by zhanghx0905** [comment]
Thanks for that, I suddenly realized there are actually multiple scenarios to consider. For example, what kind of reasoning backend to use (vllm or not) and whether to enable stream response or not. My PR only considered the case where vllm is used and stream is enabled so it shouldn't be merged now.

You should double-check the reasoning backend and reasoning options you're using. From the screenshot you followed up with, it looks like the so-called hidden mechanism isn't actually working, otherwise you shouldn't be able to see "Final Answer:". I suspect that the library you're using (langchain) doesn't actually call the Tools interface. From my previous experience, qwen-agent does not use the tools interface. It implements its own tools mechanism on the client side.

**Comment by okwinds** [comment]
> I've examined a portion of the source code and I'm uncertain if it covers everything. Could you confirm whether the code appears to have implemented "thought" filtering only for the "function calling" method, without addressing "thought" filtering for the "prompt react" approach?

You are correct in saying that the essence of Langchain's React does not use tool calls but instead relies on prompt inference models, and then processes the model's response to achieve indirect tool invocation. So, in my previous reply, I mentioned, 

`"I've examined a portion of the source code and I'm uncertain if it covers everything. Could you confirm whether the code appears to have implemented 'thought' filtering only for the 'function calling' method, without addressing 'thought' filtering for the 'prompt react' approach?"`
**Can you confirm the above content?**


If this hidden “thought” action does not occur within the processing of the externally entered “prompt react”, then the error in the final result's reasoning is unrelated to the hidden "thought" information in the tool call. 
The occurrence of such a result is likely to be strongly correlated with the issues inherent in the model itself.
I have found that qwen1.5-32B may have inference issues in its int4 performance. This could be a problem inherent to the model itself.

**Comment by zhanghx0905** [comment]
Yeah. I've been using qwen32B int4 in my business for the last two months, and I've found that its tool calls are very unstable, different prompts and even different random number seeds affecting it.

I don't quite understand your question, what do you mean by addressing 'thought' filtering for the 'prompt react' approach, can you give me an example?

**Comment by okwinds** [comment]
> Yeah. I've been using qwen32B int4 in my business for the last two months, and I've found that its tool calls are very unstable, different prompts and even different random number seeds affecting it.
> 
> I don't quite understand your question, what do you mean by addressing 'thought' filtering for the 'prompt react' approach, can you give me an example? I don't think xinference implements a similar feature.

OK, so,

1. Xinference has only filtered "Thought" information under the capability of "function calling" .
2. Xinference has not performed "any information filtering" on the reasoning responses produced by "direct input prompts". Is my understanding correct?

**Comment by okwinds** [comment]
> > Yeah. I've been using qwen32B int4 in my business for the last two months, and I've found that its tool calls are very unstable, different prompts and even different random number seeds affecting it.
> > I don't quite understand your question, what do you mean by addressing 'thought' filtering for the 'prompt react' approach, can you give me an example? I don't think xinference implements a similar feature.
> 
> OK, so,
> 
> 1. Xinference has only filtered "Thought" information under the capability of "function calling" .
> 2. Xinference has not performed "any information filtering" on the reasoning responses produced by "direct input prompts". 

**Is my understanding correct?**
