### ISSUE TITLE
Failed to build chatglm-cpp llama-cpp-python pynini

### ISSUE THREAD

**Issue by XiaoTongDeng** [xorbitsai/inference#1690]
**when i install xinference through command line: pip install "xinference[all]"
the following error happened:**
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\DengXiaoTong\AppData\Local\Temp\pip-install-2tveq5wl\pynini_1fcdaa3fe5bb47d093fcbd2da202ed7b\setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**and then i do it : pip install Cython,and install xinference again.however ,another error occured:**
cl: command line error D8021 :Invalid numerical parameter“/Wno-register”
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
  Running setup.py clean for pynini
Failed to build chatglm-cpp llama-cpp-python pynini
ERROR: Could not build wheels for chatglm-cpp, llama-cpp-python, pynini, which is required to install pyproject.toml-based projects

so how can i solve this problem?

**Comment by qinxuye** [comment]
Duplicated with #1702 .

`pynini` can be installed via conda.

```
conda install -c conda-forge pynini=2.1.5
```

**Comment by XiaoTongDeng** [comment]
> Duplicated with #1702 .
> 
> `pynini` can be installed via conda.
> 
> ```
> conda install -c conda-forge pynini=2.1.5
> ```

thanks! i have solved it

**Comment by highwalker2** [comment]
请问你是如何解决的，我尝试用conda install -c conda-forge pynini=2.1.5，但是还是报错：
ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.

**Comment by huangchuhong** [comment]
thanks,i solve this problem in the same way
