### ISSUE TITLE
运行速度很慢，为什么？

### ISSUE THREAD

**Issue by bleakie** [xorbitsai/inference#1697]
我是用的是v100显卡，最新xinference的docker运行qwen1.5-14b-int4，运行速度大约5tokens/s，但是不使用xinference，用tansformer直接运行可以15tokens/s，这是为什么会那么慢呢？

**Comment by qinxuye** [comment]
用的什么后端？Transformers 吗？

**Comment by qinxuye** [comment]
那先close，还有问题再reopen。
