### ISSUE TITLE
[QUESTION] can't install "xinference[all]", No module named 'Cython'

### ISSUE THREAD

**Issue by MichaelYang1995** [xorbitsai/inference#1702]
Note that the issue tracker is NOT the place for general support.
I can't pip install xinference[all].
 There are some error `No module named 'Cython'`.

**env**:
`python: 3.9`
`os: macOS-14.4-arm64-arm-64bit.`

**pip list**:
`pip        24.1`
`setuptools 68.2.0`
`wheel      0.41.2`

**error log:**

Collecting pynini==2.1.5 (from nemo-text-processing->xinference[all])
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/pb/ccq4gf2d3jn8fwh_m7glk90w0000gn/T/pip-install-w9eh4u_r/pynini_0e5a80bc517b422084be6f80e20f50f8/setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MichaelYang1995** [comment]
> Note that the issue tracker is NOT the place for general support. I can't pip install xinference[all]. There are some error `No module named 'Cython'`.
> 
> **env**: `python: 3.11.9` `os: macOS-14.4-arm64-arm-64bit.`
> 
> **pip list**: `pip 24.1` `setuptools 68.2.0` `wheel 0.41.2`
> 
> **error log:**
> 
> Collecting pynini==2.1.5 (from nemo-text-processing->xinference[all]) Using cached https://pypi.tuna.tsinghua.edu.cn/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [6 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/private/var/folders/pb/ccq4gf2d3jn8fwh_m7glk90w0000gn/T/pip-install-w9eh4u_r/pynini_0e5a80bc517b422084be6f80e20f50f8/setup.py", line 22, in from Cython.Build import cythonize ModuleNotFoundError: No module named 'Cython' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

And then, I `pip install Cython`.
But still there are some error like this:

Collecting pycparser (from cffi>=1.12->cryptography>=3.4.0->python-jose[cryptography]->xinference[all])
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl (117 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<0.12.0->xinference[all])
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: chatglm-cpp, llama-cpp-python, antlr4-python3-runtime, controlnet-aux, FlagEmbedding, pynini, transformers-stream-generator, encodec, quantile-python, cdifflib, ffmpy, oss2, wget, aliyun-python-sdk-core, crcmod
  Building wheel for chatglm-cpp (pyproject.toml) ... done
  Created wheel for chatglm-cpp: filename=chatglm_cpp-0.4.0-cp39-cp39-macosx_14_0_universal2.whl size=1103011 sha256=3991331cdcdc5dd8da324811097d92c55cc188a538f22cfe39dd912bfe6553be
  Stored in directory: /Users/yangqingyuan/Library/Caches/pip/wheels/a9/80/ba/44cd288dfca8d4a2ff31a19985edde0da9b1843978be33d371
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.79-cp39-cp39-macosx_14_0_arm64.whl size=3576730 sha256=305c42a680355c7188fdf2b75d5380ccd57afe55d7d0ccd06cdd7977302fba4f
  Stored in directory: /Users/yangqingyuan/Library/Caches/pip/wheels/13/cb/80/969b7d635c2260020baccb0be4ffe19d714d84dd8a6927588c
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144554 sha256=737ad28d39b8a0845b0b4a484fff8a0eac2cfb5943ff213e3c633042709af9e0
  Stored in directory: /Users/yangqingyuan/Library/Caches/pip/wheels/b9/0a/c0/fc0de68aa14c7066272aed9fdf29080aad637f3530d865ac86
  Building wheel for controlnet-aux (setup.py) ... done
  Created wheel for controlnet-aux: filename=controlnet_aux-0.0.7-py3-none-any.whl size=274341 sha256=e34124f9ba7a0212edfdc9e1f302a6cb912e3e097d7f5391fb6b71ddffe8f27c
  Stored in directory: /Users/yangqingyuan/Library/Caches/pip/wheels/7f/6e/4f/db41b9ba2a8821f270418d0460048f0dcb1b4eb5489b4ced5c
  Building wheel for FlagEmbedding (setup.py) ... done
  Created wheel for FlagEmbedding: filename=FlagEmbedding-1.2.10-py3-none-any.whl size=166101 sha256=e6a28c62b5ca329202b135c60b65f24f6acc8672bc6570c37dcf248e030b97e9
  Stored in directory: /Users/yangqingyuan/Library/Caches/pip/wheels/5b/06/d9/00c81a849cbb9def9374128e2c09a5b6efc82aa631dcf45704
  Building wheel for pynini (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/pywrapfst
      copying pywrapfst/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/pywrapfst
      creating build/lib.macosx-10.9-universal2-cpython-39/pynini
      copying pynini/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini
      creating build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/chatspeak.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/chatspeak_model.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/weather.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/numbers.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/plurals.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/t9.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/case.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/dates.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/examples/g2p.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      creating build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/edit_transducer.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/utf8.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/features.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/pynutil.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/paradigms.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/tagger.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/rule_cascade.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/rewrite.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/lib/byte.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      creating build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/export.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/multi_grm_example.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/multi_grm.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/grm.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pynini/export/grm_example.py -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      copying pywrapfst/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-39/pywrapfst
      copying pywrapfst/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/pywrapfst
      copying pynini/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-39/pynini
      copying pynini/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/pynini
      copying pynini/examples/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/pynini/examples
      copying pynini/lib/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/pynini/lib
      copying pynini/export/py.typed -> build/lib.macosx-10.9-universal2-cpython-39/pynini/export
      running build_ext
      building '_pywrapfst' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/extensions
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Wno-error=unreachable-code -I/Users/yangqingyuan/PycharmProjects/xinference4/.venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c extensions/_pywrapfst.cpp -o build/temp.macosx-10.9-universal2-cpython-39/extensions/_pywrapfst.o -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char -stdlib=libc++ -mmacosx-version-min=10.7
      extensions/_pywrapfst.cpp:1291:10: fatal error: 'fst/util.h' file not found
      #include <fst/util.h>
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini

maybe the reason is my os?

**Comment by qinxuye** [comment]
For mac, `pynini` can only be installed via conda.

```
conda install -c conda-forge pynini=2.1.5
```

**Comment by 1WorldCapture** [comment]
> For mac, `pynini` can only be installed via conda.
> 
> ```
> conda install -c conda-forge pynini=2.1.5
> ```

Not only for mac, windows also needs this :)
