### ISSUE TITLE
xinference 格式初始化llm，sse 流式输出有问题

### ISSUE THREAD

**Issue by liangpn** [xorbitsai/inference#1705]
### Describe the bug
使用 xinference 格式初始化llm，sse 流式输出有问题,会修改用户原来的问题

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python 3.10.12.
2. xinference v0.12.2.post1.

我的代码：
from sse_starlette import EventSourceResponse
from fastapi import FastAPI
from pydantic import BaseModel

from langchain_community.llms import Xinference
llm = Xinference(server_url="http://ip:9997", model_uid="qwen2-instruct")

app = FastAPI()

class StreamData(BaseModel):
    user_input: str

@app.post("/api/question_answer_service/stream")
async def stream_run(
    data: StreamData
):
    print('收到前端数据：{}'.format(data.user_input))

    def llm_talk(data:StreamData):
        for chunk in llm.stream(data.user_input):
            print('-------------')
            print(chunk)
            yield chunk

    return EventSourceResponse(llm_talk(data))

if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8100)

会这样输出
![image](https://github.com/xorbitsai/inference/assets/52708183/246299c0-f875-4c01-840c-99025d0af887)

尝试换一个llm，改为glm-4-9b-chat，也是一样的问题，会修改用户原来的问题
![image](https://github.com/xorbitsai/inference/assets/52708183/2aec5cf3-337e-4b07-99ff-3ad4e3d26c6b)

而使用ChatOpenAI格式初始化llm时,分別调用qwen2-instruct和glm-4-9b-chat，则都是正常的输出，不会修改用户原有的问题
llm = ChatOpenAI(model="qwen2-instruct", openai_api_key="xxx", openai_api_base="http://ip:9997/v1/")
![image](https://github.com/xorbitsai/inference/assets/52708183/d7c0537e-52db-4145-a65c-32861eae5879)
![image](https://github.com/xorbitsai/inference/assets/52708183/fd7020eb-2af8-4fb2-a999-41111924fcf7)
![image](https://github.com/xorbitsai/inference/assets/52708183/7ca969d0-346b-45d1-8e97-7d8089d7c7a5)
![image](https://github.com/xorbitsai/inference/assets/52708183/7c2b9f19-0fd1-46a9-9701-69850c5f1721)

**Comment by ChengjieLi28** [comment]
@liangpn langchain里的xinference很久没更新过，建议用后者，langchain社区维护周期较长，不取决于我们
