### ISSUE TITLE
CURL没返回值

### ISSUE THREAD

**Issue by ZimaBlueee** [xorbitsai/inference#1706]
我按照官方文档方法测试部署的大模型，在终端curl没有接收到返回值；但是这几个大模型在dify里是可以正常使用的。

![图片](https://github.com/xorbitsai/inference/assets/53747502/54511932-eb99-4b89-93f1-f0074cdd3b11)

以下图片是我在别人的博客下看到的，是有返回值的
![d40c26a861a847aab4ecbf374a8eb0df](https://github.com/xorbitsai/inference/assets/53747502/f837a9ed-4e5e-4be9-b84b-bb015c90e969)

**Comment by ChengjieLi28** [comment]
> 我按照官方文档方法测试部署的大模型，在终端curl没有接收到返回值；但是这几个大模型在dify里是可以正常使用的。
> 
> ![图片](https://private-user-images.githubusercontent.com/53747502/342090934-54511932-eb99-4b89-93f1-f0074cdd3b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5MzQtNTQ1MTE5MzItZWI5OS00Yjg5LTkzZjEtZjAwNzRjZGQzYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZmRhMThlODU3OWU2ZjlmZjljYjM5MTY4MzkyZWU2ZjRmYzdlZjhiYmVlMDRjMDZlMjBmZmViZWIxYzkxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vewdEgpueofiAoIxzddsOhC9QbtXruboiQwPo_Vx8Hw)
> 
> 以下图片是我在别人的博客下看到的，是有返回值的 ![d40c26a861a847aab4ecbf374a8eb0df](https://private-user-images.githubusercontent.com/53747502/342090983-f837a9ed-4e5e-4be9-b84b-bb015c90e969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5ODMtZjgzN2E5ZWQtNGU1ZS00YmU5LWI4NGItYmIwMTVjOTBlOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjQwZDY1MmMzMjM0ZTIxYzYyN2MxYjZlMTZiMWEzMmIwZDU3NjBmZGNjMDYzMWNhMDFiOGVhMTI3N2JhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YrmKyKmNqBJyFt3rY43lzdkBqRKrp0Ndfygia4fo_iw)

没看明白，你一个请求请求了9997端口，一个请求了7005端口？哪个是你的xinference后端服务端口？后端有什么报错吗？

**Comment by ZimaBlueee** [comment]
> > 我按照官方文档方法测试部署的大模型，在终端curl没有接收到返回值；但是这几个大模型在dify里是可以正常使用的。
> > ![图片](https://private-user-images.githubusercontent.com/53747502/342090934-54511932-eb99-4b89-93f1-f0074cdd3b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5MzQtNTQ1MTE5MzItZWI5OS00Yjg5LTkzZjEtZjAwNzRjZGQzYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZmRhMThlODU3OWU2ZjlmZjljYjM5MTY4MzkyZWU2ZjRmYzdlZjhiYmVlMDRjMDZlMjBmZmViZWIxYzkxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vewdEgpueofiAoIxzddsOhC9QbtXruboiQwPo_Vx8Hw)
> > 以下图片是我在别人的博客下看到的，是有返回值的 ![d40c26a861a847aab4ecbf374a8eb0df](https://private-user-images.githubusercontent.com/53747502/342090983-f837a9ed-4e5e-4be9-b84b-bb015c90e969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5ODMtZjgzN2E5ZWQtNGU1ZS00YmU5LWI4NGItYmIwMTVjOTBlOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjQwZDY1MmMzMjM0ZTIxYzYyN2MxYjZlMTZiMWEzMmIwZDU3NjBmZGNjMDYzMWNhMDFiOGVhMTI3N2JhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YrmKyKmNqBJyFt3rY43lzdkBqRKrp0Ndfygia4fo_iw)
> 
> 没看明白，你一个请求请求了9997端口，一个请求了7005端口？哪个是你的xinference后端服务端口？后端有什么报错吗？

抱歉，9997的截图错了，我的端口是7005，curl没有返回值，后端没报错。

但是，仅仅是curl没返回值，我用其他方式都是正常的，比如下图的Python请求是有的：
![图片](https://github.com/xorbitsai/inference/assets/53747502/c02bc306-edb0-43f3-8046-4831dea66a97)

**Comment by ChengjieLi28** [comment]
> > > 我按照官方文档方法测试部署的大模型，在终端curl没有接收到返回值；但是这几个大模型在dify里是可以正常使用的。
> > > ![图片](https://private-user-images.githubusercontent.com/53747502/342090934-54511932-eb99-4b89-93f1-f0074cdd3b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5MzQtNTQ1MTE5MzItZWI5OS00Yjg5LTkzZjEtZjAwNzRjZGQzYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZmRhMThlODU3OWU2ZjlmZjljYjM5MTY4MzkyZWU2ZjRmYzdlZjhiYmVlMDRjMDZlMjBmZmViZWIxYzkxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vewdEgpueofiAoIxzddsOhC9QbtXruboiQwPo_Vx8Hw)
> > > 以下图片是我在别人的博客下看到的，是有返回值的 ![d40c26a861a847aab4ecbf374a8eb0df](https://private-user-images.githubusercontent.com/53747502/342090983-f837a9ed-4e5e-4be9-b84b-bb015c90e969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2NzgsIm5iZiI6MTcxOTIwMTM3OCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIwOTA5ODMtZjgzN2E5ZWQtNGU1ZS00YmU5LWI4NGItYmIwMTVjOTBlOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjQwZDY1MmMzMjM0ZTIxYzYyN2MxYjZlMTZiMWEzMmIwZDU3NjBmZGNjMDYzMWNhMDFiOGVhMTI3N2JhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YrmKyKmNqBJyFt3rY43lzdkBqRKrp0Ndfygia4fo_iw)
> > 
> > 
> > 没看明白，你一个请求请求了9997端口，一个请求了7005端口？哪个是你的xinference后端服务端口？后端有什么报错吗？
> 
> 抱歉，9997的截图错了，我的端口是7005，curl没有返回值，后端没报错。
> 
> 但是，仅仅是curl没返回值，我用其他方式都是正常的，比如下图的Python请求是有的： ![图片](https://private-user-images.githubusercontent.com/53747502/342199636-c02bc306-edb0-43f3-8046-4831dea66a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDc0NzQsIm5iZiI6MTcxOTIwNzE3NCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIxOTk2MzYtYzAyYmMzMDYtZWRiMC00M2YzLTgwNDYtNDgzMWRlYTY2YTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA1MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzU5ZDQwMzdjMTM3ZGI1MGM4MTE1NGI4YTI0ODIwZDBhZDgzOTU4Yzc5MDdkODhjY2MzNzZlMzBlNDk5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQIJnwAbbNK44MqiMM6t7PR09GCFH3Ot2Z4fh0_y-zg)
> 
> 而同样的参数，curl是没有返回值的： ![图片](https://private-user-images.githubusercontent.com/53747502/342200014-38fdefca-b7b4-40f7-8bfb-954eb6a9e38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDc0NzQsIm5iZiI6MTcxOTIwNzE3NCwicGF0aCI6Ii81Mzc0NzUwMi8zNDIyMDAwMTQtMzhmZGVmY2EtYjdiNC00MGY3LThiZmItOTU0ZWI2YTllMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA1MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjI5Zjc2ZWQ0MThhODU2YWJhNjJjZTM1ZTE5MWNmMWRhZWNjZDIzYTY3NmQyZDdmYzEwMDg4N2JkYjkxYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qz004X-DDrlsY_8QnnAAmTcO1bZv-RBAgx8PN0XNmo4)

首先，无法复现：
<img width="1290" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/b4514a68-4c7d-43a2-b151-5dd6c9afa64c">
我这边完全没有问题。

你的后端应该都没收到你的请求。检查你的网络拓扑，比如有没有网关、代理之类的拦截了你的请求。
