### ISSUE TITLE
启动xinference后新注册了本地模型，但是在重启xinference后，注册的模型没有记录需要重新注册  After starting xinference, a new local model was registered, but after restarting xinference, the registered model has no record and needs to be re-registered.

### ISSUE THREAD

**Issue by tao2021** [xorbitsai/inference#1713]
![图片](https://github.com/xorbitsai/inference/assets/78005981/b3aa0ed2-1fc4-4f69-8851-f77e06fab4e4)
1.如上注册本地模型
我是使用xinference镜像启动的，注册好本地模型后，如果重启xinference容器的话，先前注册的模型信息就消失了，需要重新注册再启动，我的问题是注册信息会保存吗？

**Comment by ChengjieLi28** [comment]
@tao2021 提issue请把完整的信息提供出来，而不是只写个标题。
怎么注册的？网页还是命令行还是python客户端？后端有报错吗？报错贴一下？

**Comment by tao2021** [comment]
> @tao2021 提issue请把完整的信息提供出来，而不是只写个标题。 怎么注册的？网页还是命令行还是python客户端？后端有报错吗？报错贴一下？
ok

**Comment by ChengjieLi28** [comment]
@tao2021 你的容器都重启了，当然所有信息都消失了。这是docker，文件都在容器内部，除非你把XINFERNCE_HOME通过volume在宿主机上挂载

**Comment by oldpiao** [comment]
在【Launch Model】的【CUSTOM MODELS】里
