### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by vikrantrathore** [xorbitsai/inference#1737]
### Describe the bug
Cannot install xinference from git repository. It throws an error.

```
ChefBuildError

  Backend operation failed: HookMissing('build_editable')

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
```

### To Reproduce
Install the xinference from 

1. 3.11
2. git latest version
3. Full stack of the error.
```
ChefBuildError

  Backend operation failed: HookMissing('build_editable')

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with xinference (0.12.2.post1+12.g2a64f4b
```
4. Minimized code to reproduce the error.

### Expected behavior
Install xinference

**Comment by ChengjieLi28** [comment]
@vikrantrathore Could you paste out your command that you pip install from git?

**Comment by vikrantrathore** [comment]
The error is through poetry which uses pip behind. The command is `poetry add git+https://github.com/xorbitsai/inference` within a local project.

Once the installation fails at installing xinference, I can go activate the venv by `poetry shell` and then install using `pip install git+https://github.com/xorbitsai/inference`. It works, but then there is an error of Web UI which is using npm and need to run

```
npm install
npm run build
```

This will build the UI. Also vllm used is 0.4.3 and wanted to try 0.5.0 from the git given it supports gemma-2 9B and 27B but couldn't do it due to other dependencies.

Also sglang support gemma-it but when I use sglang worker for gemma-it model it throws an error model not supported so was trying to install it from git directly to see if can use gemma-it with sglang.

**Comment by vikrantrathore** [comment]
Ok after doing a second try by removing the vllm from the git it started to work now,

**Comment by vikrantrathore** [comment]
It seems the error still persist when I try to install it from local directory like `poetry add -e ../inference/.["all"]`, probably need to test more extensively with poetry.
