### ISSUE TITLE
QUESTION: when temperature=0（greedy），model answers are still random

### ISSUE THREAD

**Issue by seedclaimer** [xorbitsai/inference#1744]
我理解当temperature=0，输入相同输出应该也相同？如果不是这样，我应该怎么改以使其相同？
As I know, when temperature=0, same input shall make same output? If not, how should I make it same?

复现（recurrence） ：
from xinference.client import RESTfulClient
import threading

client = RESTfulClient("http://127.0.0.1:9998")
model = client.get_model("qwen2-instruct")#7b、vllm、cuda118、xinference-latest
def t():
    print(model.chat(
        prompt="你好,请你给我讲个笑话",
        chat_history=[],
        generate_config={
            "max_tokens": 512,
            "temperature": 0,
            'top_k':1,
        }
    ))

if __name__ == '__main__':
    for i in range(10):
        threading.Thread(target=t,).start()

…………………………………………………………………………………………………………………………………………………………………………………………………………
result：（第10条与其它9条不同。10th result diffs from the others）
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“感冒”了。'}
{'role': 'assistant', 'content': '当然可以，这里有一个简单的笑话给你：\n\n为什么电脑经常生病？\n\n因为它的窗户（Windows）总是开着，结果就“染”上了各种病毒。'}

**Comment by qinxuye** [comment]
Try to set temperature=0 and top_k=1, but I cannot guarantee it can work. Anyway, I don't think it's the issue that related to Xinf, I will close it first, but welcome to have discussions here.
