### ISSUE TITLE
Some models require login to Hugging Face for download

### ISSUE THREAD

**Issue by NTLx** [xorbitsai/inference#1749]
Sometimes, model downloads fail not due to network issues, but because certain projects require agreement to terms or, in essence, necessitate logging into Hugging Face in order to download the model files. This is detrimental to the user experience of xinference. Is there a solution to this issue?

**Comment by ChengjieLi28** [comment]
Refer to #1734 . This is not an issue of xinference.

**Comment by NTLx** [comment]
@ChengjieLi28 Thank you, I didn't notice there were issue and doc already. Problem Solved.
