### ISSUE TITLE
launch beg-reranker-base error trust_remote_code

### ISSUE THREAD

**Issue by opsvr202** [xorbitsai/inference#1751]
when launch beg-reranker-base model, error:
File "/xx/xx/python3.10/site-packages/xinference/model/rerank/core.py"
TypeError: [address=0.0.0.0:39573, pid=xxxx] CrossEncoder.__init__() got an unexpected keyword argument 'trust_remote_code'

other model launch normal.

**Comment by qinxuye** [comment]
Please upgrade sentence_transformers.
