### ISSUE TITLE
Can't deploy bge-reranker-v2-m3

### ISSUE THREAD

**Issue by Arcmoon-Hu** [xorbitsai/inference#1754]
### Describe the bug
参考文档 `xinference launch --model-name bge-reranker-v2-m3 --model-type rerank`
出错：`RuntimeError: Failed to launch model, detail: [address=0.0.0.0:41765, pid=611834] Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/.xinference/cache/bge-reranker-v2-m3.`

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python 3.10
2. xinference 0.12.3
3. Versions of crucial packages.
    - transformers                  4.41.2
    - sentence-transformers         3.0.1
4. Full stack of the error.
这里是 xinference 自动缓存的模型文件列表
![image](https://github.com/xorbitsai/inference/assets/50002441/ebffb848-b019-412d-986d-428042235814)

### Expected behavior
Hope solve the problem

### Additional context
No

**Comment by qinxuye** [comment]
服务端日志完整的贴一下呢

**Comment by Arcmoon-Hu** [comment]
> 服务端日志完整的贴一下呢

![image](https://github.com/xorbitsai/inference/assets/50002441/375591ad-b9d8-447a-9c9e-f4a83141981a)
