### ISSUE TITLE
本地启动无法用gpu拉起自定义路径的本地模型 ValueError: [address=0.0.0.0:11083, pid=11576] Worker 0.0.0.0:11083 cannot use the GPUs with these indexes: [2]. Worker 0.0.0.0:11083 can only see these GPUs: [].

### ISSUE THREAD

**Issue by shendepuren** [xorbitsai/inference#1757]
1. 启动方式 xinference-local --host 0.0.0.0 --port 9997
2. 版本 0.12.3
3. 报错
`2024-07-01 19:52:53,099 xinference.api.restful_api 11474 ERROR    [address=0.0.0.0:11083, pid=11576] Worker 0.0.0.0:11083 cannot use the GPUs with these indexes: [2]. Worker 0.0.0.0:11083 can only see these GPUs: [].
Traceback (most recent call last):
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 822, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 871, in launch_builtin_model
    await _launch_model()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 835, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 816, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 643, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 490, in _create_subpool
    devices = await self.allocate_devices_with_gpu_idx(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 400, in allocate_devices_with_gpu_idx
    raise ValueError(
ValueError: [address=0.0.0.0:11083, pid=11576] Worker 0.0.0.0:11083 cannot use the GPUs with these indexes: [2]. Worker 0.0.0.0:11083 can only see these GPUs: [].`

模型配置：
`{
    "version": 1,
    "context_length": 2048,
    "model_name": "chatglm3-6b-base",
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "generate",
        "chat"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "chatglm3",
    "model_specs": [
        {
            "model_format": "pytorch",
            "model_size_in_billions": 6,
            "quantizations": [
                "none"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/data/ai_server/hub/chatglm3-6b-base",
            "model_revision": null
        }
    ],
    "prompt_style": {
        "style_name": "CHATGLM3",
        "system_prompt": "",
        "roles": [
            "user",
            "assistant"
        ],
        "intra_message_sep": "",
        "inter_message_sep": "",
        "stop": [
            "<|user|>",
            "<|observation|>"
        ],
        "stop_token_ids": [
            64795,
            64797,
            2
        ]
    },
    "is_builtin": false
}`
5. 操作
![image](https://github.com/xorbitsai/inference/assets/8724079/4a4d017c-2eec-4a46-a66e-762ade0edf0c)

**Comment by ChengjieLi28** [comment]
xinference识别不到你的GPU，检查自己的环境。

**Comment by ASan1527** [comment]
> xinference识别不到你的GPU，检查自己的环境。

大哥，请问怎么检查呢

**Comment by public-cdn** [comment]
![image](https://github.com/user-attachments/assets/ea8ab208-d993-4e2f-9c3d-14f6ff43ebf5)
大佬 我这个使用docker 部署，进入docker 能识别到 显卡驱动 也是和宿主机的驱动版本一样 560，cuda 12.6
![image](https://github.com/user-attachments/assets/85ecd857-b83e-4437-af2f-91c0924ea49c)
dan'sh但是启动报错一样的

**Comment by ChengjieLi28** [comment]
> ![image](https://private-user-images.githubusercontent.com/48397024/363827169-ea8ab208-d993-4e2f-9c3d-14f6ff43ebf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzgxMzIsIm5iZiI6MTcyNTMzNzgzMiwicGF0aCI6Ii80ODM5NzAyNC8zNjM4MjcxNjktZWE4YWIyMDgtZDk5My00ZTJmLTljM2QtMTRmNmZmNDNlYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhM2ZkN2E3YjYwYmNjY2I3MzkwNWU1MDA2ZWJjM2U4YTk2OTcxN2MzNTczNTFhNjNkYTRmODdjYjI3YzIwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nJDLTJbfjKqm_PswlqnXGeA4ZNT0VSPEgqiZGb3uWO0) 大佬 我这个使用docker 部署，进入docker 能识别到 显卡驱动 也是和宿主机的驱动版本一样 560，cuda 12.6 ![image](https://private-user-images.githubusercontent.com/48397024/363827327-85ecd857-b83e-4437-af2f-91c0924ea49c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzgxMzIsIm5iZiI6MTcyNTMzNzgzMiwicGF0aCI6Ii80ODM5NzAyNC8zNjM4MjczMjctODVlY2Q4NTctYjgzZS00NDM3LWFmMmYtOTFjMDkyNGVhNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0MzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzYzODY5Y2RiMjRlYTk0MDUwZDI0MzYwZWM4ZTQxZTUyNmNjZGI0YmRlY2Q5NTMyMzllNzkxNGI3N2FiOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BU-KVQTp9rRGcStIpcwFHl3gqYTqP-lCFRc40Nl8yjQ) dan'sh但是启动报错一样的

哪个版本的docker，怎么启动的？服务端日志是什么样的？

**Comment by public-cdn** [comment]
![image](https://github.com/user-attachments/assets/7a247068-9f30-40ce-af29-ef38f2337324)
![image](https://github.com/user-attachments/assets/2aa7c1a4-49fa-415d-842a-85a78b4e3166)
![image](https://github.com/user-attachments/assets/4bd2bff5-5539-4ec3-9d14-2cf3376f242b)

这是docker docker-compose 版本，在windows wsl2 Ubuntu 24.04 系统下启动
![image](https://github.com/user-attachments/assets/bcf1ca32-9c56-4eda-a1c9-09ea1df1e480)
![image](https://github.com/user-attachments/assets/060982cf-fde2-4869-b2b1-42e60881f96b)
看着一切正常 就是没办法启动

**Comment by ChengjieLi28** [comment]
> ![image](https://private-user-images.githubusercontent.com/48397024/363930292-7a247068-9f30-40ce-af29-ef38f2337324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzAyOTItN2EyNDcwNjgtOWYzMC00MGNlLWFmMjktZWYzOGYyMzM3MzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmFjNTEyNGRlYmY2ZGQ3NWRkOTM1YmU1MjAyMTAwZmUzOTM2YmNhMDY3NDdlZmE3YTIyYzE2OTFhMjRmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YakCEiJ19FFJYgHELDbMmkgEWzJQATa7-s9d9NYRRk4) ![image](https://private-user-images.githubusercontent.com/48397024/363930411-2aa7c1a4-49fa-415d-842a-85a78b4e3166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA0MTEtMmFhN2MxYTQtNDlmYS00MTVkLTg0MmEtODVhNzhiNGUzMTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjhiMWI0MTkyOTYxNzJlYTNlMWFhNWFmNWU1NmU5NDEzODRlZjg1YTI0ZDI4ZDBjMzVhMjRlZTMzNjZkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rG85NW-obfyQO6G-O17x5iSZ1ZX3xgIk1u3rED5sHrY) ![image](https://private-user-images.githubusercontent.com/48397024/363930583-4bd2bff5-5539-4ec3-9d14-2cf3376f242b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA1ODMtNGJkMmJmZjUtNTUzOS00ZWMzLTlkMTQtMmNmMzM3NmYyNDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDg5NDY2YWUyNmNiOTAwNDA2NDU5MjMyZDE5YWQyNDM5OGY0NjEwMmM0YjU1NzQ2ZDY2MzlhNzY5NjBiZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqp-Sdz-LPw5aB-rYX4r5lNIVtBOPprzFnFblJCkvxE)
> 
> 这是docker docker-compose 版本，在windows wsl2 Ubuntu 24.04 系统下启动 ![image](https://private-user-images.githubusercontent.com/48397024/363930908-bcf1ca32-9c56-4eda-a1c9-09ea1df1e480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA5MDgtYmNmMWNhMzItOWM1Ni00ZWRhLWExYzktMDllYTFkZjFlNDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYmUxNDg1ODBmMDMwYmMwZTAwYjJiOTJjNWE5YzFmOWMxMWU0NjFmMTAwMmQxZDAwYjI5NzllMDg1YzNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxaYrsOxIyvMqaPv9tputMooktDAPvbAGrSu_Q09qnA) ![image](https://private-user-images.githubusercontent.com/48397024/363931277-060982cf-fde2-4869-b2b1-42e60881f96b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzEyNzctMDYwOTgyY2YtZmRlMi00ODY5LWIyYjEtNDJlNjA4ODFmOTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MDU4YWQzZGU1ZmQ1MmI0M2M0MGUzZTAzZTAzZmI2Y2Y3YzE2NzM5OWEyNWIxNDkzZDhkYmMxYjMwYzNjNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dS9uWo2mLpR6QTR4QfZVscl0Me1j2CnAr7XaJkWh544) 看着一切正常 就是没办法启动

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/b2e429ad-6f61-4dba-a7db-805d734b35fc">
这个环境变量去掉，这个是不能这样设置的

**Comment by ChengjieLi28** [comment]
> ![image](https://private-user-images.githubusercontent.com/48397024/363930292-7a247068-9f30-40ce-af29-ef38f2337324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzAyOTItN2EyNDcwNjgtOWYzMC00MGNlLWFmMjktZWYzOGYyMzM3MzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmFjNTEyNGRlYmY2ZGQ3NWRkOTM1YmU1MjAyMTAwZmUzOTM2YmNhMDY3NDdlZmE3YTIyYzE2OTFhMjRmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YakCEiJ19FFJYgHELDbMmkgEWzJQATa7-s9d9NYRRk4) ![image](https://private-user-images.githubusercontent.com/48397024/363930411-2aa7c1a4-49fa-415d-842a-85a78b4e3166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA0MTEtMmFhN2MxYTQtNDlmYS00MTVkLTg0MmEtODVhNzhiNGUzMTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjhiMWI0MTkyOTYxNzJlYTNlMWFhNWFmNWU1NmU5NDEzODRlZjg1YTI0ZDI4ZDBjMzVhMjRlZTMzNjZkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rG85NW-obfyQO6G-O17x5iSZ1ZX3xgIk1u3rED5sHrY) ![image](https://private-user-images.githubusercontent.com/48397024/363930583-4bd2bff5-5539-4ec3-9d14-2cf3376f242b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA1ODMtNGJkMmJmZjUtNTUzOS00ZWMzLTlkMTQtMmNmMzM3NmYyNDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDg5NDY2YWUyNmNiOTAwNDA2NDU5MjMyZDE5YWQyNDM5OGY0NjEwMmM0YjU1NzQ2ZDY2MzlhNzY5NjBiZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqp-Sdz-LPw5aB-rYX4r5lNIVtBOPprzFnFblJCkvxE)
> 
> 这是docker docker-compose 版本，在windows wsl2 Ubuntu 24.04 系统下启动 ![image](https://private-user-images.githubusercontent.com/48397024/363930908-bcf1ca32-9c56-4eda-a1c9-09ea1df1e480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzA5MDgtYmNmMWNhMzItOWM1Ni00ZWRhLWExYzktMDllYTFkZjFlNDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYmUxNDg1ODBmMDMwYmMwZTAwYjJiOTJjNWE5YzFmOWMxMWU0NjFmMTAwMmQxZDAwYjI5NzllMDg1YzNhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxaYrsOxIyvMqaPv9tputMooktDAPvbAGrSu_Q09qnA) ![image](https://private-user-images.githubusercontent.com/48397024/363931277-060982cf-fde2-4869-b2b1-42e60881f96b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAwNzksIm5iZiI6MTcyNTM1OTc3OSwicGF0aCI6Ii80ODM5NzAyNC8zNjM5MzEyNzctMDYwOTgyY2YtZmRlMi00ODY5LWIyYjEtNDJlNjA4ODFmOTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MDU4YWQzZGU1ZmQ1MmI0M2M0MGUzZTAzZTAzZmI2Y2Y3YzE2NzM5OWEyNWIxNDkzZDhkYmMxYjMwYzNjNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dS9uWo2mLpR6QTR4QfZVscl0Me1j2CnAr7XaJkWh544) 看着一切正常 就是没办法启动

你这个compose文件跟官方写的有点出入。建议改成官方的再试试，runtime: nvidia那里，官方文件不是这么写的。https://github.com/xorbitsai/inference/blob/main/xinference/deploy/docker/docker-compose.yml

容器内部执行
import torch
torch.cuda.is_available()
返回什么？
