### ISSUE TITLE
[BUG]Rerank模型返回结果document字段，python客户端返回正常，curl返回字段为空

### ISSUE THREAD

**Issue by rayallen335** [xorbitsai/inference#1762]
### Describe the bug
Rerank模型返回结果document字段，python客户端返回正常，curl返回字段为空
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
   3.11.5
2. The version of xinference you use.
 latest
![bug](https://github.com/xorbitsai/inference/assets/24689253/114179a0-27f4-4299-b0b8-a9ffe5a12b30)
![bug2](https://github.com/xorbitsai/inference/assets/24689253/2ff6af60-d25f-4444-9f23-f5c67b5cc02b)

**Comment by ChengjieLi28** [comment]
@rayallen335 curl返回空是正确的。python client行为不一致的问题将下个版本修复。想返回document，传入参数return_documents=True。此参数默认是False。
