### ISSUE TITLE
GLM4-9B，量化int4运行，显存占用与不用int4一样

### ISSUE THREAD

**Issue by zidanereal5** [xorbitsai/inference#1768]
### Describe the bug
GLM4-9B，int4运行，显存占用与不用int4一样，似乎量化并没有起作用。

日志如下：

2024-07-03 03:27:40,649 xinference.model.llm.llm_family 95 INFO     Cache /root/.xinference/cache/glm4-chat-pytorch-9b exists
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|███████████████| 10/10 [00:06<00:00,  1.53it/s]
2024-07-03 03:27:48,790 xinference.model.llm.pytorch.core 112 DEBUG    Model Memory: 17868767296
![图片](https://github.com/xorbitsai/inference/assets/123045775/7bf17794-d622-4779-9564-554c116e30a7)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. The version of xinference you use.
Docker，v0.12.1

### Expected behavior
显存占用在10GB以下
![图片](https://github.com/xorbitsai/inference/assets/123045775/0fbce48c-66e2-481f-a320-5c446beacfa0)

**Comment by qinxuye** [comment]
运行的时候 kvcache 会占用显存，不只是模型会占用。

**Comment by zidanereal5** [comment]
kvcache 大概会占用多少显存，int4量化，预期总共占用10GB以下，现在是17GB
