### ISSUE TITLE
chatTTS部署报错

### ISSUE THREAD

**Issue by xxch** [xorbitsai/inference#1770]
### Describe the bug
自定义部署的时候，单卡A800  80G的显存，已经部署了一个大模型占用了40G。再部署chatTTS的时候Optional中不知道选择填什么才能让gpu_ids=0。
于是我就用命令的方式命令行的方式启动，命令如下：
`xinference launch --model-name ChatTTS --file chatTTS.json  --model-type audio --gpu-idx 0

{
    "model_name": "chatTTS",
    "model_id": null,
    "model_revision": null,
    "model_hub": "huggingface",
    "model_family": "whisper",
    "multilingual": false,
    "model_uri": "/app/models/chatTTS",
    "is_builtin": false
}`

启动后报错。我使用的模型是https://modelscope.cn/models/pzc163/chatTTS。是我模型下载的不对吗？
![chatts](https://github.com/xorbitsai/inference/assets/36878412/9d703e46-c50a-449c-957a-c6f3c509ac98)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 3.11.9
2. The version of xinference you use. 0.12.3
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by qinxuye** [comment]
modelscope 的 ChatTTS 下载我们会支持。目前注册 ChatTTS 需要用命令行。

写一个 chattts.json，内容如下，记得要把路径替换。

```
{
  "model_name": "my_chattts",
  "model_uri": "/path/to/ChatTTS",
  "ability": "text-to-audio",
  "multilingual": true,
  "model_family": "ChatTTS"
}
```

然后用命令行注册：

xinference register --model-type audio --file chattts.json --persist

界面上就可以加载 my_chattts。
