### ISSUE TITLE
在模型下载前，提示用户相关模型参数的限制，避免下载后模型无法使用。

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#1784]
### Is your feature request related to a problem? Please describe
环境：Linux，CPU模式（无GPU，无cuda）
问题：模型下载完成后，依然无法使用（不在界面中显示，也无法删除），出现类似如下的错误
ValueError: [address=0.0.0.0:41647, pid=166121] AWQ is only available on GPU
ValueError: [address=0.0.0.0:42784, pid=165747] Only 8-bit quantization is supported if it is not linux system or cuda device

### Describe the solution you'd like
建议：
- 在模型下载前，加强这模型参数限制方面的提示，避免用户下载时模型参数选择错误，导致下载后不可用。
- 增加显示正在下载任务；用户可随时取消或删除。
-

**Comment by nikelius** [comment]
类似的问题还有，下载 internvl-chat 后显示：
RuntimeError: [address=0.0.0.0:36213, pid=173672] Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by ChengjieLi28** [comment]
Not planned.
