### ISSUE TITLE
xinference有提供helm的部署方式嘛

### ISSUE THREAD

**Issue by liqiankun1111** [xorbitsai/inference#1787]
我司运维习惯用helm 来管理服务，且kubeblock 要求k8s 1.22+，我司的k8s集群一时升级不了。
另一是，对于xinference来说，是不是一个k8s node 运行一个xinference worker？

**Comment by qinxuye** [comment]
See https://inference.readthedocs.io/en/latest/getting_started/using_kubernetes.html#helm-support .
