### ISSUE TITLE
求助下xinference如何使用命令行启动本地下载好的大模型

### ISSUE THREAD

**Issue by qq745639151** [xorbitsai/inference#1791]
查了一些教程都是命令行启动远程下载的大模型

**Comment by Valdanitooooo** [comment]
应该可以用自定义模型的方式
https://inference.readthedocs.io/zh-cn/latest/models/custom.html

**Comment by jimmytanj** [comment]
我也是用modelscope下载了内置模型，然后拷贝到机器上。机器本身不能通互联网。
这种情况下，日志显示已经找到modelscope的模型，为何还要从网上下载。
![image](https://github.com/xorbitsai/inference/assets/13470396/dc670d95-a888-49f1-9945-dd8f17ca92ed)
另外，有自定义rerank模型的例子么。

**Comment by jimmytanj** [comment]
直接在页面点register model，然后选择模型的类型，输入模型的本地地址。
只是模型的名称不能与内置模型同名。
兄弟们可以试试
