### ISSUE TITLE
使用inference启动模型，模型的id改变了

### ISSUE THREAD

**Issue by xxch** [xorbitsai/inference#1796]
### Describe the bug
**### 问题一**
 使用页面启动Qwen2-57B模型时，我给模型的model name取名为xxc-llm。
启动后正常应该再running modles中应该显示id和name都是xxc-llm
id                                          name 
xxc-llm                                 xxc-llm
启动错误的情况是：id : xxc-llm-sdeFZw  外加了一个字符串。

### **问题二**
模型和inference正常运行的时候，并发量增加了。模型的id改成成了xxc-llm-1-0

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 3.11
2. The version of xinference you use.  0.12.3
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by xxch** [comment]
![1237](https://github.com/xorbitsai/inference/assets/36878412/e60ecc9f-8481-4538-99a0-67b6bf6e626d)
错误截图是这样的

**Comment by xxch** [comment]
![1237](https://github.com/xorbitsai/inference/assets/36878412/50f93e3a-4ac1-4c9b-8b04-ad579b833b19)
错误是这样的。是因为并发导致模型重启吗？

**Comment by ChengjieLi28** [comment]
@xxch 触发OOM导致模型自动重启，`-1-0`后缀你不需要关心，是内部uid号，表示副本情况。
