### ISSUE TITLE
xinference加载的Embedding模型怎样和oneapi通信

### ISSUE THREAD

**Issue by goodmaney** [xorbitsai/inference#1800]
测试了Oneapi渠道里添加xinference加载的Embedding模型，结果不能用；单独curl post 数据到xinference后台能正确接收和返回，但oneapi发送了测试包后xinference后台似乎无法收到请求。又使用py脚本加载Embedding，倒可以正常收到oneapi发送的请求并返回，xinference和脚本接收url都是相同的，测了几次发现在除了oneapi填写秘钥那里外，同样的配置xinference无法受到请求。因为xinference很方便所以本打算以后都是用它来加载llm embedding和ranker，就想弄清楚

**Comment by qinxuye** [comment]
xinference 的使用方式无误的话，请咨询 oneapi 社区。
