### ISSUE TITLE
模型选择  quantization 4-bit或 8-bit无法使用

### ISSUE THREAD

**Issue by hiistar** [xorbitsai/inference#1801]
选4-bit时，ValueError: [address=127.0.0.1:50858, pid=6864] Only 8-bit quantization is supported if it is not linux system or cuda device。
选8-bit时，KeyError: [address=127.0.0.1:50988, pid=6228] 'transformer.embedding.word_embeddings.weight'。

安装是 pip install "xinference[transformers]"
安装了 conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

**Comment by qinxuye** [comment]
哪个模型？量化可以考虑用 GPTQ 或者 AWQ 格式。

**Comment by willwellwei** [comment]
我也遇到同样的问题

**Comment by wangsen1110** [comment]
我也遇到同样的问题，在win11系统下，Xinference 接入glm4-chat模型报错 KeyError: [address=127.0.0.1:63143, pid=32360] 'transformer.embedding.word_embeddings.weight'
Xinference 里面选择chatglm3 是可以正常启动。
glm4-chat  是通过 Xinference 进行安装的，方式和chatglm3一样。   glm4-chat的 quantization只能选择8-bit，4-bit是提示不支持。  但是8-bit，启动的时候报错：'transformer.embedding.word_embeddings.weight

**Comment by Leiyanzangxiangsi** [comment]
> 哪个模型？量化可以考虑用 GPTQ 或者 AWQ 格式。

根据我一天的排查，llama3 qwen等等模型，在模型选择quantization的时候，不管4还是8都会报各种embed_tokens.weight等错误，只要none就不会有问题

**Comment by ZCravenQ** [comment]
> 是xinference的问题， ![企业微信截图_17236257912967](https://private-user-images.githubusercontent.com/31689107/357757851-5e9d4918-ad6d-4cea-854e-6ac9d315fb22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTMyOTIsIm5iZiI6MTcyMzc5Mjk5MiwicGF0aCI6Ii8zMTY4OTEwNy8zNTc3NTc4NTEtNWU5ZDQ5MTgtYWQ2ZC00Y2VhLTg1NGUtNmFjOWQzMTVmYjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA3MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MDQ3MGExZDhlZjRkMTJjNTJiMmNmNjEwMDg4YWJkYjkxZjVkZGVmMmI2OTRkNzkyNGZlNWVlOWI5Yjg5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8E5iCOzKCwypFy7Eb39AJJUvXDdy0hKJ3VfCC91zlzw) 在量化过程中，只选择后缀为bin的模型，因为其他格式的模型需要转化为bin,

请教下这是哪份文件内的源代码

**Comment by ladyishenlong** [comment]
我1.6版本的glm4-chat也量化不了，明明1.5是ok的

**Comment by qinxuye** [comment]
> 我1.6版本的glm4-chat也量化不了，明明1.5是ok的

1.6 版本修改了方式，文档稍后补充。我在 https://github.com/xorbitsai/inference/issues/3689 已经回复你了。等文档 ready 了，我在那边通知。
