### ISSUE TITLE
Fail to download the models with a 503 error

### ISSUE THREAD

**Issue by AChao628** [xorbitsai/inference#1803]
试了好几个model和一些参数，都是抛503 error

请问，需要额外进行一些网络配置吗

<img width="1253" alt="1720258286863" src="https://github.com/xorbitsai/inference/assets/81001471/fc90321c-e0ea-459d-939c-1919bb96bfba">

**Comment by qinxuye** [comment]
启动的时候设置环境变量 `XINFERENCE_MODEL_SRC=modelscope` 从魔搭下载。

参考：https://inference.readthedocs.io/zh-cn/latest/models/sources/sources.html#modelscope
