### ISSUE TITLE
如何设置精度

### ISSUE THREAD

**Issue by moerfei** [xorbitsai/inference#1804]
ValueError: [address=0.0.0.0:37495, pid=262] Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your NVIDIA GeForce RTX 2080 Ti GPU has compute capability 7.5. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.

**Comment by qinxuye** [comment]
命令行就是 --dtype half。
界面上 extra +号点击，key是 dtype，值是 half。
