### ISSUE TITLE
The checkpoint you are trying to load has model type `gemma2` but Transformers does not recognize this architecture.

### ISSUE THREAD

**Issue by HuuHuy227** [xorbitsai/inference#1808]
### Describe the bug
Transformer 4.34.1 do not support 'gemma2' architecture

Please upgrade docker image or requirements to transformers version support 'gemma2' (version: 4.42.3 supported)

**Comment by ChengjieLi28** [comment]
Not an issue of xinference. Just upgrade `transformers` to use `gemma2`.
