### ISSUE TITLE
服务器部署docker镜像的时候，本机访问ui页面，前端页面总是闪

### ISSUE THREAD

**Issue by ccly1996** [xorbitsai/inference#1813]
### Describe the bug
服务器部署docker镜像的时候，本机访问ui页面，页面总是闪

### To Reproduce
前端页面详细报错如下
![IMG_8822](https://github.com/xorbitsai/inference/assets/39228103/7978f7ae-5416-4396-ba45-730886692811)
![IMG_8824](https://github.com/xorbitsai/inference/assets/39228103/75fec0b2-f9eb-4b2c-b97e-0fe2b38d69ba)
![IMG_8823](https://github.com/xorbitsai/inference/assets/39228103/0774db26-158d-45de-a8db-3918a4772401)

docker镜像版本v0.13.0

**Comment by CharlesSong** [comment]
最新拉取的镜像，也出现了这个问题。最终跳转到登录页，不知道默认的用户名、密码

**Comment by ChengjieLi28** [comment]
使用最新镜像：`xprobe/xinference:latest`，我这边无法复现。
