### ISSUE TITLE
BUG 利用llamacpp部署模型进行并发测试提示报错 Parallel generation is not supported by ggml

### ISSUE THREAD

**Issue by EnzoLiang** [xorbitsai/inference#1816]
### Describe the bug
注册了一个本地的gguf格式模型，然后利用llamacpp方式部署，进行并发测试时有以下错误：
Parallel generation is not supported by ggml

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. python=3.10
3. The version of xinference you use. xinference=0.12.3
4. Versions of crucial packages. llama_cpp_python=0.2.77
5. Full stack of the error.
6. Minimized code to reproduce the error.

**Comment by ChengjieLi28** [comment]
llama-cpp-python 目前就不支持并发
