### ISSUE TITLE
接口返回空

### ISSUE THREAD

**Issue by silence-pan84** [xorbitsai/inference#1825]
![image](https://github.com/xorbitsai/inference/assets/174668054/e6d81c8a-7531-4c18-b99c-ddc634ab6e58)

使用的是qwen2-7b在Xinference Chat Bot测试返回正常，但是用时Dify调用看似接口返回200了，但是没有任何值。

**Comment by ChengjieLi28** [comment]
@silence-pan84 移步dify社区。
