### ISSUE TITLE
模型为什么经常重启呢

### ISSUE THREAD

**Issue by xxch** [xorbitsai/inference#1831]
### Describe the bug
模型正常可以提供服务，但是问答次数多了，模型会自动重启.特别是在接口调用的时候经常会重启，不稳定。
报错：chat completion stream got an error: remote server 0.0.0.0:36413

![微信截图_20240710172757](https://github.com/xorbitsai/inference/assets/36878412/772860c7-8f31-4238-b09d-39d551e18817)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 3.10
2. The version of xinference you use. 0.12.3
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by qinxuye** [comment]
重启一般是 OOM 了，可以考虑用 vllm 后端（仅 linux 和 cuda），transformers 后端的话可以尝试用持续批处理的功能，参考 https://inference.readthedocs.io/zh-cn/latest/user_guide/continuous_batching.html
