### ISSUE TITLE
支持阿里巴巴文字转换语音模型：CosyVoice，支持多音色以及复刻音色

### ISSUE THREAD

**Issue by chenfolingithub** [xorbitsai/inference#1837]
### Feature request / 功能建议

目前只有一个chattts，文字语音上不支持音色复刻

### Motivation / 动机

希望有功能更强大的cosyvoice

### Your contribution / 您的贡献

https://github.com/FunAudioLLM/CosyVoice

**Comment by qinxuye** [comment]
我们会尽快支持 CosyVoice，音色克隆的接口我们也在设计。

**Comment by qinxuye** [comment]
Fixed by #1881 .
