### ISSUE TITLE
在启动内置模型时支持自定义模型权重目录

### ISSUE THREAD

**Issue by Valdanitooooo** [xorbitsai/inference#1838]
### Feature request / 功能建议

在启动内置模型时支持自定义模型名称和指定模型权重目录

### Motivation / 动机

部署模型时的一大痛点，就是很多时候自己注册的模型实际上就是系统内置的模型(或者经过微调的)，只不过需要改一下权重目录，其他配置都是一样的

### Your contribution / 您的贡献

不知道是否符合项目roadmap，是否与其他功能冲突
如果可行，愿意贡献代码

**Comment by ChengjieLi28** [comment]
@Valdanitooooo 可以，你来实现吧。
模型名称不是问题，launch本就可以指定model_uid；
launch接口需要新增参数model_path，有了这个参数，绕过cache逻辑，就可以了。

**Comment by Valdanitooooo** [comment]
好的我周末找时间试试
这项目挺好的，希望社区能保持活跃
专注于部署模型就好，大杂烩的工具再好也不适合生产，玩具再好也只是玩具
