### ISSUE TITLE
bge-reranker-large推理异常

### ISSUE THREAD

**Issue by caixiongjiang** [xorbitsai/inference#1839]
### System Info / 系統信息

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       On  |   00000000:18:00.0 Off |                    0 |
| N/A   69C    P0             68W /   70W |   12763MiB /  15360MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       On  |   00000000:3B:00.0 Off |                    0 |
| N/A   54C    P0             30W /   70W |    9371MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        On  |   00000000:5E:00.0 Off |                  Off |
| 32%   35C    P8             12W /  450W |   22033MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|

x86 cpu
64g 内存
ubuntu22.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

Docker启动命令：
docker run -v /data/caixj/Interests/xinference_hub:/model_hub -e XINFERENCE_HOME=/model_hub -e XINFERENCE_MODEL_SRC=modelscope -p 9998:9997 --gpus all caixj/xinference:v0.13.0 xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程

1. 使用控制面板注册了bge-reranker-large（下载地址：https://modelscope.cn/models/Xorbits/bge-reranker-large）
2. 控制面板启动了rerank模型
3. 使用官方指令curl测试发现问题：
curl -X 'POST' \
  'http://20.20.136.251:9998/v1/rerank' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "bge-reranker-large",
    "query": "A man is eating pasta.",
    "documents": [
        "A man is eating food.",
        "A man is eating a piece of bread.",
        "The girl is carrying a baby.",
        "A man is riding a horse.",
        "A woman is playing violin."
    ]
  }'
  
  返回结果：
  {"id":"e25427a4-3f31-11ef-928a-0242ac110039","results":[{"index":4,"relevance_score":null,"document":null},{"index":3,"relevance_score":null,"document":null},{"index":2,"relevance_score":null,"document":null},{"index":1,"relevance_score":null,"document":null},{"index":0,"relevance_score":null,"document":null}],"meta":{"api_version":null,"billed_units":null,"tokens":null,"warnings":null}}
  
  出现了很多null的情况

### Expected behavior / 期待表现

官方给的返回格式：
{
    "id": "480dca92-8910-11ee-b76a-c2c8e4cad3f5",
    "results": [{
        "index": 0,
        "relevance_score": 0.9999247789382935,
        "document": "A man is eating food."
    }, {
        "index": 1,
        "relevance_score": 0.2564932405948639,
        "document": "A man is eating a piece of bread."
    }, {
        "index": 3,
        "relevance_score": 0.00003955026841140352,
        "document": "A man is riding a horse."
    }, {
        "index": 2,
        "relevance_score": 0.00003742107219295576,
        "document": "The girl is carrying a baby."
    }, {
        "index": 4,
        "relevance_score": 0.00003739788007806055,
        "document": "A woman is playing violin."
    }]
}

**Comment by ChengjieLi28** [comment]
@caixiongjiang 内置模型没发现这个问题。
```
使用控制面板注册了bge-reranker-large（下载地址：[https://modelscope.cn/models/Xorbits/bge-reranker-large）](https://modelscope.cn/models/Xorbits/bge-reranker-large%EF%BC%89)
```
不要从Xorbits空间下载，那个模型非常老。他们有官方仓库：
```
BAAI/bge-reranker-large
```
从他们那个仓库下载注册再试下。document那里显示null需要传入参数加上return_documents: true

**Comment by caixiongjiang** [comment]
好的，我去试试

**Comment by caixiongjiang** [comment]
> @caixiongjiang 内置模型没发现这个问题。
> 
> ```
> 使用控制面板注册了bge-reranker-large（下载地址：[https://modelscope.cn/models/Xorbits/bge-reranker-large）](https://modelscope.cn/models/Xorbits/bge-reranker-large%EF%BC%89)
> ```
> 
> 不要从Xorbits空间下载，那个模型非常老。他们有官方仓库：
> 
> ```
> BAAI/bge-reranker-large
> ```
> 
> 从他们那个仓库下载注册再试下。document那里显示null需要传入参数加上return_documents: true

请问return_documents: true是在调用的时候加还是在加载模型的时候加？
使用控制面板是否是在注册模型的时候加参数

**Comment by ChengjieLi28** [comment]
> > @caixiongjiang 内置模型没发现这个问题。
> > ```
> > 使用控制面板注册了bge-reranker-large（下载地址：[https://modelscope.cn/models/Xorbits/bge-reranker-large）](https://modelscope.cn/models/Xorbits/bge-reranker-large%EF%BC%89)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不要从Xorbits空间下载，那个模型非常老。他们有官方仓库：
> > ```
> > BAAI/bge-reranker-large
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 从他们那个仓库下载注册再试下。document那里显示null需要传入参数加上return_documents: true
> 
> 请问return_documents: true是在调用的时候加还是在加载模型的时候加？ 使用控制面板是否是在注册模型的时候加参数

调用的时候，就是你上面curl的body里面加一个这个参数字段

**Comment by caixiongjiang** [comment]
{'id': '09e431fa-3f38-11ef-a3c2-0242ac11003a', 'results': [{'index': 0, 'relevance_score': 0.9999258518218994, 'document': {'text': 'A man is eating food.'}}, {'index': 1, 'relevance_score': 0.048283521085977554, 'document': {'text': 'A man is eating a piece of bread.'}}, {'index': 2, 'relevance_score': 7.636439841007814e-05, 'document': {'text': 'The girl is carrying a baby.'}}, {'index': 4, 'relevance_score': 7.636331429239362e-05, 'document': {'text': 'A woman is playing violin.'}}, {'index': 3, 'relevance_score': 7.617334631504491e-05, 'document': {'text': 'A man is riding a horse.'}}], 'meta': {'api_version': None, 'billed_units': None, 'tokens': None, 'warnings': None}}

返回的格式里面增加了“text”字段，与https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/rerank.html#rerank不同，如果更新了，请把说明文档也更新一下

**Comment by ChengjieLi28** [comment]
> {'id': '09e431fa-3f38-11ef-a3c2-0242ac11003a', 'results': [{'index': 0, 'relevance_score': 0.9999258518218994, 'document': {'text': 'A man is eating food.'}}, {'index': 1, 'relevance_score': 0.048283521085977554, 'document': {'text': 'A man is eating a piece of bread.'}}, {'index': 2, 'relevance_score': 7.636439841007814e-05, 'document': {'text': 'The girl is carrying a baby.'}}, {'index': 4, 'relevance_score': 7.636331429239362e-05, 'document': {'text': 'A woman is playing violin.'}}, {'index': 3, 'relevance_score': 7.617334631504491e-05, 'document': {'text': 'A man is riding a horse.'}}], 'meta': {'api_version': None, 'billed_units': None, 'tokens': None, 'warnings': None}}
> 
> 返回的格式里面增加了“text”字段，与[https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/rerank.html#rerank不同，如果更新了，请把说明文档也更新一下](https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/rerank.html#rerank%E4%B8%8D%E5%90%8C%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9B%B4%E6%96%B0%E4%BA%86%EF%BC%8C%E8%AF%B7%E6%8A%8A%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B)

rerank没有类似openAI 那种官方的格式，众多支持模型中，保持与jina那种风格是一致的。
