### ISSUE TITLE
xinference v0.12.3  模型运行后随着对话次数增多,GPU资源占用不释放

### ISSUE THREAD

**Issue by later2x** [xorbitsai/inference#1851]
### System Info / 系統信息

Ubuntu 22.04 LTS
xinference v0.12.3
cuda   12.2
Nvidia Version  535.129.03

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference v0.12.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference 版本 0.12.3  
模型运行后占用GPU 256G   
随着对话次数增多  资源占用达到 304G ，GPU 资源未释放。

### Reproduction / 复现过程

1、模型运行配置:
![运行配置_2024-07-12_16-52-41](https://github.com/user-attachments/assets/34d2998a-003a-4c59-8d41-66e765600ef8)

2、运行后资源占用情况 
![nviudia-smi](https://github.com/user-attachments/assets/f26ec5d3-b815-4ba8-a1b1-2880dd2aa709)

3、多轮对话资源占用情况 
![15 48 100 1_nvidia-smi_2024-07-12_16-49-43](https://github.com/user-attachments/assets/1cb62741-4379-4813-9ee7-36f7f249d1ac)

### Expected behavior / 期待表现

是否有相关配置解决该问题

**Comment by qinxuye** [comment]
vLLM 默认会按你的配置占用 80% 显存，不会释放。

**Comment by CytFree** [comment]
我使用glm-4v-9b也有类似的情况，没有使用vllm也是GPU内存一直在增长，问题回答完成后GPU内存不释放
![image](https://github.com/user-attachments/assets/2e0e6718-aec2-4a7a-96b9-7d2d3990b98e)

**Comment by jiliangqian** [comment]
请问怎么解决呢？
