### ISSUE TITLE
Regarding the support for the MLX UI interface issue

### ISSUE THREAD

**Issue by okwinds** [xorbitsai/inference#1853]
Xinference has already supported the inference of MLX format models in the previous version ( 0.13.1 ). 

After I registered a downloaded MLX model and tried to launch it from the custom UI interface, I couldn't find the MLX model engine. I hope the next version will support it on the UI.

0.13.2
![image](https://github.com/user-attachments/assets/a924644f-1654-4575-bb68-252096510022)

**Comment by qinxuye** [comment]
Registering MLX custom model is not supported yet, we will support it ASAP.

**Comment by okwinds** [comment]
This feature is already supported and can be closed
