### ISSUE TITLE
missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by Silenceang** [xorbitsai/inference#1856]
### System Info / 系統信息

ubuntu22.04  xinference 13.1   cuda12.1    

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

pip安装，非docker

### Reproduction / 复现过程

UI 启动内置glm4-chat   transformer

### Expected behavior / 期待表现

Exception: [address=0.0.0.0:37625, pid=14714] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

**Comment by Silenceang** [comment]
Exception: [address=0.0.0.0:37625, pid=14714] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

这个报错该怎么解决呢

**Comment by qinxuye** [comment]
Duplicated with #1752.
