### ISSUE TITLE
vllm流式推理问题

### ISSUE THREAD

**Issue by caixiongjiang** [xorbitsai/inference#1858]
### System Info / 系統信息

操作系统：Ubuntu 22.04
显卡驱动信息：
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
| 30%   38C    P8              9W /  425W |   21946MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1301      G   /usr/lib/xorg/Xorg                            296MiB |
|    0   N/A  N/A      1546      G   /usr/bin/gnome-shell                          156MiB |
|    0   N/A  N/A      4878      G   gnome-control-center                            6MiB |
|    0   N/A  N/A      6657      G   /proc/self/exe                                 56MiB |
|    0   N/A  N/A      8433      G   ...seed-version=20240710-180217.653000         33MiB |
|    0   N/A  N/A      8778      G   ...irefox/4539/usr/lib/firefox/firefox        176MiB |
|    0   N/A  N/A     15577      G   ...ures=SpareRendererForSitePerProcess        166MiB |
|    0   N/A  N/A     16641      G   ...erProcess --variations-seed-version         66MiB |
|    0   N/A  N/A     20815      C   /usr/bin/python3                            20932MiB |
+-----------------------------------------------------------------------------------------+

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference:v0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -v /home/caixj/data/model_hub:/model_hub -e XINFERENCE_HOME=/model_hub -e XINFERENCE_MODEL_SRC=modelscope -itd -p 9998:9997 --gpus all --name xinference caixj/xinference:v0.13.0 xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程

使用qwen2-7b-instruct vllm引擎启动流式推理输出不正常，非流式则正常。

非流式推理输出结果：

{"id":"chat512505f8-4127-11ef-9973-0242ac110003","object":"chat.completion","created":1720882260,"model":"qwen2-7b-instruct","choices":[{"index":0,"message":{"role":"assistant","content":"你好！我是一个基于大模型的人工智能助手，被设计用来提供信息、解答问题、帮助学习、完成任务等。我能够处理各种类型的查询，从科普知识、历史事件、科学概念到日常生活中的小问题，甚至是更深入的学术讨论。我还支持多语言交流，努力为用户提供及时、准确、有帮助的回答。不论你需要学习知识、解决问题，还是寻求灵感，我都在这里为你提供帮助。"},"finish_reason":"stop"}],"usage":{"prompt_tokens":27,"completion_tokens":93,"total_tokens":120}}

流式输出结果：
data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"role": "assistant", "content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4f60\u597d"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\uff01\u6211"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u662f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e00\u4e2a"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u57fa\u4e8e"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5927"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8bed\u8a00"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6a21\u578b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7684\u4eba"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5de5\u667a"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u80fd\u52a9"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u624b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\uff0c\u65e8"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882118, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5728\u5e2e"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u52a9"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7528\u6237"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u89e3\u7b54"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u95ee"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u9898\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u63d0\u4f9b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4fe1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u606f\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8fdb\u884c"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5bf9\u8bdd"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u548c\u5b8c"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6210\u4efb\u52a1\u3002"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6211\u7684"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e3b\u8981"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u529f\u80fd"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5305"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u62ec\u4f46"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e0d\u9650"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e8e"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u63d0\u4f9b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u77e5\u8bc6"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u67e5"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8be2"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8bed\u8a00"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7ffb"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8bd1\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u521b\u610f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6fc0"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u53d1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u65e5"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7a0b\u7ba1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7406"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001\u4fe1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u606f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u68c0\u7d22\u7b49"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3002"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6211\u7531\u963f\u91cc"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e91\u5f00"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u53d1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\uff0c\u81f4"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u529b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e8e\u4e3a"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7528\u6237"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u63d0\u4f9b"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4fbf\u6377"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u9ad8\u6548"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001\u4e2a\u6027"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5316\u7684"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u670d\u52a1"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4f53"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882119, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u9a8c\u3002"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u65e0\u8bba"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4f60"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u9700\u8981"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5b66\u4e60"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5efa\u8bae"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3001"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5de5"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4f5c\u5e2e"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u52a9\uff0c"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u8fd8\u662f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u65e5\u5e38"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u5a31"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4e50"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\uff0c\u6211"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u90fd\u4f1a\u5c3d"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u529b\u63d0"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u4f9b\u652f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6301"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u3002\u8bf7"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u968f"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u65f6"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u544a\u8bc9"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6211\u4f60"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u7684\u9700"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\u6c42"}, "finish_reason": null}]}

data: {"id": "chatfd4b81b4-4126-11ef-9973-0242ac110003", "model": "qwen2-7b-instruct", "created": 1720882120, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": "\uff0c\u6211\u4f1a\u5c3d\u6211\u6240\u80fd\u63d0\u4f9b\u5e2e\u52a9\u3002"}, "finish_reason": "stop"}]}

data: [DONE]

流式会出现内容乱码的情况，如果engine换成Transformers则不会有这种情况。

### Expected behavior / 期待表现

vllm流式输出内容正常

**Comment by qinxuye** [comment]
原则上这个额问题应该被 #1732 在 0.12.3 中就修复了。

**Comment by caixiongjiang** [comment]
可能时它使用的engine不是vllm？

**Comment by ChengjieLi28** [comment]
@caixiongjiang 下个版本修复。
