### ISSUE TITLE
More clear installation instructions

### ISSUE THREAD

**Issue by onlyone-hyphen** [xorbitsai/inference#1859]
### System Info / 系統信息

On the Github page, to install it says run the following:

docker run --name xinference -d -p 9997:9997 -e XINFERENCE_HOME=/data -v </on/your/host>:/data --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

But you dont say what </on/your/host> is for?

Shall i create a new folder? What goes in there? Does it already exist? Is it going to create a new folder? Why am i here? Whats the purpose of life? Are black holes real? Are we living in a simulation?

So many questions :)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Yes

### The command used to start Xinference / 用以启动 xinference 的命令

No

### Reproduction / 复现过程

Maybe

### Expected behavior / 期待表现

42

**Comment by ChengjieLi28** [comment]
You need to learn some of the basics of docker Since you're using docker.
I can't teach you from scratch.

**Comment by onlyone-hyphen** [comment]
In that case, you may aswell just delete all the documentation, and tell your users to go fuck themselves

Good luck with the project, you're going to need it

**Comment by ChengjieLi28** [comment]
We’ll get right on that! And while we're at it, would you like us to hold your hand and teach you how to eat, sleep, and walk too?

**Comment by onlyone-hyphen** [comment]
No, what I'd like you to do is to take feedback seriously. I took the time to leave feedback to help you improve. If you make your documentation clearer, it becomes more usable and more developers will want to contribute. If you reply with snarky comments designed to attempt to belittle the very people that will be implementing your code and making improvements, why bother releasing it open source in the first place?

**Comment by ChengjieLi28** [comment]
Oh, don't worry, I'm not here to coddle anyone. You started this, and let's be clear—I'm talking about people like you who expect everything handed to them without any effort. As for the significance of this project, don't concern yourself. It's none of your business.

**Comment by onlyone-hyphen** [comment]
You started this, not me.

I left some light hearted feedback, and you got all high and mighty.

Anyway, enjoy your life. Let's agree to disagree. You go that way, I'll go this way. Good bye
