### ISSUE TITLE
embedding模型无法指定gpu

### ISSUE THREAD

**Issue by Pandas886** [xorbitsai/inference#1860]
### System Info / 系統信息

windows10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

docker启动
```
 docker run -d -e XINFERENCE_MODEL_SRC=modelscope -p 9998:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0 --log-level debug
```

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/04c3fa98-2aee-464e-b2b6-7cfdfa42a8f5)
![image](https://github.com/user-attachments/assets/bc54d432-057b-4ae9-8117-78d5f86841d6)

### Expected behavior / 期待表现

可以选择gpu运行而不是cpu

**Comment by qinxuye** [comment]
没有识别到  GPU。

确认如下的代码能运行：

```
python -c "import torch; print(torch.cuda.is_available())"
```

如果输出为 False 就是没有可用的显卡。

**Comment by Pandas886** [comment]
> 没有识别到 GPU。
> 
> 确认如下的代码能运行：
> 
> ```
> python -c "import torch; print(torch.cuda.is_available())"
> ```
> 
> 如果输出为 False 就是没有可用的显卡。

进入容器后执行上述代码，返回的是 true

**Comment by Firehdx** [comment]
same issue, cuda available but cannot use gpu for embedding
