### ISSUE TITLE
升级到0.13.1后局域网访问时要求用户登录

### ISSUE THREAD

**Issue by yibohub** [xorbitsai/inference#1863]
### System Info / 系統信息

cuda:12.1,ubuntu22.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

version: '3.8'
services:
  xprobe-service:
   image: xprobe/xinference:latest
    container_name: xinference
    restart: always
    volumes:
      - /mnt/diska/xinfer/.xinference:/root/.xinference 
      - /mnt/diska/xinfer/.cache/huggingface:/root/.cache/huggingface  
      - /mnt/diska/xinfer/.cache/modelscope:/root/.cache/modelscope  
    ports:
      - "6007:9997"
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
    command: xinference-local -H 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

### Reproduction / 复现过程

升级到0.13.1后
1.从内网192.*.*.*:6007访问时提示登录界面。且登录页面闪烁后可以稳定在Launch Model界面。
![image](https://github.com/user-attachments/assets/9a1693a2-ba12-406f-90e4-07e573d6b25b)
切换到runing models时，登录页面闪缩后稳定在登录界面。
![image](https://github.com/user-attachments/assets/e87cb36d-2f71-4841-ad09-507f2c5a07c5)
2.以域名加端口模式访问时提示登录界面。（现象同上）
3.以IP加端口模式访问时可以正常访问。
在升级前没有要求登录。

### Expected behavior / 期待表现

正常页面，没有登录页面出现。

**Comment by ChengjieLi28** [comment]
使用你的局域网访问url访问api `/v1/cluster/auth`, 如果无法访问或者访问失败，请检查你的局域网相关设置，与xinference无关。

**Comment by yibohub** [comment]
局域网访问失败。
![image](https://github.com/user-attachments/assets/5c7a7797-a84e-453c-b501-4c4369b27283)
ip地址访问也是失败。
![image](https://github.com/user-attachments/assets/f6f46245-4161-44c2-a33d-0f0148884c6c)
如果是网络问题，一般会是什么问题？因为前面都是正常的，就周末升级后出现的问题。网络都没有调整。

**Comment by ChengjieLi28** [comment]
> 局域网访问失败。 ![image](https://private-user-images.githubusercontent.com/161293070/348599129-5c7a7797-a84e-453c-b501-4c4369b27283.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTgxNTIsIm5iZiI6MTcyMTAxNzg1MiwicGF0aCI6Ii8xNjEyOTMwNzAvMzQ4NTk5MTI5LTVjN2E3Nzk3LWE4NGUtNDUzYy1iNTAxLTRjNDM2OWIyNzI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGU5ZmU4ZWQ5NjM4MTgyOTMwMjRmMWY3YmNjMWFkYjkwM2JjZjBhYmU0OGUxYWNkOWJmMzVlYTkzMTRmNjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.728s3QrMnZYrRbRUVZwJjeGwuMhx0fdb9xWCfVozkK4) ip地址访问也是失败。 ![image](https://private-user-images.githubusercontent.com/161293070/348599210-f6f46245-4161-44c2-a33d-0f0148884c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTgxNTIsIm5iZiI6MTcyMTAxNzg1MiwicGF0aCI6Ii8xNjEyOTMwNzAvMzQ4NTk5MjEwLWY2ZjQ2MjQ1LTQxNjEtNDRjMi1hMzNkLTBmMDE0ODg4NGM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWIyNDNjOTE2YjBiM2U4ZGRiMjM1YWNhZDEwZTNmODNmZjkzMGE0MWIwZjQ0MjdjNjEyNTIxMjhhYjJkZGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gwj_Vfz6rpB7RmRbYqpbOmUquT8slXJqmuw_A1HhsYY) 如果是网络问题，一般会是什么问题？因为前面都是正常的，就周末升级后出现的问题。网络都没有调整。

这种返回是正确的。上面说`以IP加端口模式访问时可以正常访问`，这跟你截图给的有什么区别？截图访问的默认的80端口？

**Comment by yibohub** [comment]
IP地址访问用的也是配置文件映射出来的端口，不是80端口。
我感觉不是网络的问题。前面出问题是用的google浏览器，但是用遨游浏览器、Edge浏览器访问又是正常的。

**Comment by ChengjieLi28** [comment]
> IP地址访问用的也是配置文件映射出来的端口，不是80端口。 我感觉不是网络的问题。前面出问题是用的google浏览器，但是刚才用遨游浏览器、Edge浏览器访问又是正常的。

建议完全清空浏览器缓存。感觉之前的有影响，应该不是xinference的问题。

**Comment by yibohub** [comment]
谢谢，按你的建议，清空浏览器缓存后正常了。

**Comment by hwb96** [comment]
> > IP地址访问用的也是配置文件映射出来的端口，不是80端口。 我感觉不是网络的问题。前面出问题是用的google浏览器，但是刚才用遨游浏览器、Edge浏览器访问又是正常的。
> 
> 建议完全清空浏览器缓存。感觉之前的有影响，应该不是xinference的问题。

感谢，正常了
