### ISSUE TITLE
调用rerank接口，返回的结果中，results.document 字段返回值都是空

### ISSUE THREAD

**Issue by shujun1992** [xorbitsai/inference#1864]
### System Info / 系統信息

redhat7.8

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1.启动xinference-local --host 0.0.0.0 --port 9997
2.注册本地 bge-reranker-large
3.启动bge-reranker-large
4.接口调用 /v1/rerank

### Expected behavior / 期待表现

调用rerank接口，返回的结果中，results.document 字段返回值  不为空

**Comment by ChengjieLi28** [comment]
调用接口传入参数 return_documents=True
