### ISSUE TITLE
建议能支持一张卡加载多个模型

### ISSUE THREAD

**Issue by songpb** [xorbitsai/inference#1868]
### Feature request / 功能建议

总是遇到No available slot found for the model，建议支持一张卡上加载多个模型，否则太浪费了

### Motivation / 动机

rt

### Your contribution / 您的贡献

无

**Comment by qinxuye** [comment]
Duplicate with #1586 .

Thanks, we will support multiple models for a single card in the future.

**Comment by Bruce-ysy** [comment]
Is it currently supported to run multiple models on a single GPU? Now I get the same issue.

**Comment by qinxuye** [comment]
You can specify gpu-idx to force deploy a model to the same GPU.
