### ISSUE TITLE
Qwen1.5-14b-chat-gptq-int4 推理速度

### ISSUE THREAD

**Issue by caixiongjiang** [xorbitsai/inference#1880]
### System Info / 系統信息

ubuntu22.04
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
| 30%   39C    P8             20W /  425W |   12382MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -v /home/caixj/data/model_hub:/model_hub -e XINFERENCE_HOME=/model_hub -e XINFERENCE_MODEL_SRC=modelscope -itd -p 9998:9997 --gpus all --name xinference caixj/xinference:v0.13.0 xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程

qwen1.5-14b-chat-gptq-int4使用Transformers库进行推理速度很慢，vllm推理不存在问题
qwen2-7b-instruct使用transformers库推理速度正常

### Expected behavior / 期待表现

速度正常

**Comment by qinxuye** [comment]
Duplicated with #1650, close this first.
