### ISSUE TITLE
增加embedding多卡分布式部署能力

### ISSUE THREAD

**Issue by zhangyanbo2007** [xorbitsai/inference#1894]
### Feature request / 功能建议

增加embedding多卡分布式部署能力

### Motivation / 动机

增加embedding多卡分布式部署能力

### Your contribution / 您的贡献

增加embedding多卡分布式部署能力

**Comment by qinxuye** [comment]
Thanks, we will support it ASAP.

**Comment by zhangyanbo2007** [comment]
我是说多张卡模型并行那种部署，我一张卡装不下7B显存

**Comment by smilesy115** [comment]
请问实现了吗

**Comment by qinxuye** [comment]
对于 gte-Qwen2 可以支持多卡。使用命令行加载 --n-gpu 2 。
