### ISSUE TITLE
xinference载入glm4-chat模型无法正常回复, 报错'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by cptbaker233** [xorbitsai/inference#1915]
### System Info / 系統信息

cuda V12.5.82
python 3.11.9
transformers 4.41.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/0827981d-3d62-41f0-ab58-9df10ce1fe80)
启动GLM4-chat模型后, 提问任意问题

### Expected behavior / 期待表现

正常回复

**Comment by qinxuye** [comment]
Will be addressed in #1876 .

**Comment by 0zyl** [comment]
怎么解决的呀？求

**Comment by jhj033** [comment]
调试发现python环境中pytorch都没有正常安装，修复此bug有望解决！

**Comment by jhj033** [comment]
这个问题出在你下载的glm4-9b模型的~/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat/modeling_chatglm.py文件里没有stream_chat函数，我从modelscope中找了个带stream_chat函数的文件拷进去就work了
