### ISSUE TITLE
xinference载入glm4-chat模型无法正常回复, 报错TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by cptbaker233** [xorbitsai/inference#1923]
### System Info / 系統信息

cuda V12.5.82
python 3.11.9
transformers 4.41.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/0d9d0e80-da12-42fd-a9da-0ae3b693fe99)
![image](https://github.com/user-attachments/assets/1ad5855a-71dc-4da4-ae74-44b91eedf8c7)

启动GLM4-chat模型后, 提问任意问题
后台日志报错
2024-07-23 14:32:16,188 transformers.generation.utils 71784 WARNING  Both `max_new_tokens` (=512) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "/home/gien/.conda/envs/xinference/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/gien/.conda/envs/xinference/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gien/.conda/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gien/.conda/envs/xinference/lib/python3.11/site-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/gien/.conda/envs/xinference/lib/python3.11/site-packages/transformers/generation/utils.py", line 2390, in _sample
    model_kwargs = self._get_initial_cache_position(input_ids, model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gien/.conda/envs/xinference/lib/python3.11/site-packages/transformers/generation/utils.py", line 1321, in _get_initial_cache_position
    past_length = model_kwargs["past_key_values"][0][0].shape[2]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

### Expected behavior / 期待表现

正常回复

**Comment by RandyChen1985** [comment]
我gemma2 也是这个错误。
![image](https://github.com/user-attachments/assets/29d33f71-926e-41a5-9657-7c35087ee1da)

**Comment by cptbaker233** [comment]
> 我gemma2 也是这个错误。 ![image](https://private-user-images.githubusercontent.com/1704661/351216360-5efe871a-c634-486a-94bc-f58eb80c49ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTkwNDIsIm5iZiI6MTcyMTcxODc0MiwicGF0aCI6Ii8xNzA0NjYxLzM1MTIxNjM2MC01ZWZlODcxYS1jNjM0LTQ4NmEtOTRiYy1mNThlYjgwYzQ5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDcxMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzhjNDI1ZWQ1OTk5ODkyODJjMjkyZTljMDY1M2YwMjBkODA2NTI3YTIxZjM1NzhjMDQ5ZDBlNzhlOTQyNGNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SyILEcpwuVbgpYMcp_qKONAuExHNRYMIe6CtrNLRXzM)
> 
> ![image](https://private-user-images.githubusercontent.com/1704661/351216048-29d33f71-926e-41a5-9657-7c35087ee1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTkwNDIsIm5iZiI6MTcyMTcxODc0MiwicGF0aCI6Ii8xNzA0NjYxLzM1MTIxNjA0OC0yOWQzM2Y3MS05MjZlLTQxYTUtOTY1Ny03YzM1MDg3ZWUxZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDcxMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJlZjYzMDgxZWY1ZDgzY2I1MTdiOTEyZGI3ZTM0Y2MzZjBmZGIxNzA2MTkzYzYwMzQyZDVkMjA4MDE1ZDA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IxCdnYyWOGeQqp8U_mehlmhFEmcsDSifL-dhuGCnl6g)

咱俩报错的原因应该不一样, 等待官方大佬回复吧

**Comment by cptbaker233** [comment]
> 我gemma2 也是这个错误。 ![image](https://private-user-images.githubusercontent.com/1704661/351216360-5efe871a-c634-486a-94bc-f58eb80c49ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjExNjEsIm5iZiI6MTcyMTcyMDg2MSwicGF0aCI6Ii8xNzA0NjYxLzM1MTIxNjM2MC01ZWZlODcxYS1jNjM0LTQ4NmEtOTRiYy1mNThlYjgwYzQ5ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDc0NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmODRjZjE0MDE3ZTYyMWZmMzlhNjE4YzZkY2JkODcxZGRmY2Y0MjcxOWNlOTgzMjFhN2ZkYTg1YWViMDYwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lWft-vUdRA2dlrhZdDOmCvV_d0tlqQRhZEmmhK89EZA)
> 
> ![image](https://private-user-images.githubusercontent.com/1704661/351216048-29d33f71-926e-41a5-9657-7c35087ee1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjExNjEsIm5iZiI6MTcyMTcyMDg2MSwicGF0aCI6Ii8xNzA0NjYxLzM1MTIxNjA0OC0yOWQzM2Y3MS05MjZlLTQxYTUtOTY1Ny03YzM1MDg3ZWUxZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDc0NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM4MWRkODJkNzUyN2Y3MjhlOWU4YjUzNWQxZjU4ODEwYmQzYzVjMDZhZTg2Y2ZkNGVkYWRjZWY4MDQwNTM0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u7NQt5NdFC84M7Q-dF4KuZPWSFcV7UnEYv5M-tdGQ24)
我升级transformer到4.41.4解决了
