### ISSUE TITLE
docker 创建inference ，通过网页的形式或命令行的形式都无法下载model。

### ISSUE THREAD

**Issue by wjhmiss** [xorbitsai/inference#1939]
### System Info / 系統信息

win10  wsl2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

1，WebUI 不能下载，如图：
![1](https://github.com/user-attachments/assets/cc78e86f-bba6-402c-acac-73e877db7a91)
![2](https://github.com/user-attachments/assets/8289a762-4a34-4422-9c75-9d5cca76d859)
2，既然UI不能下载，我就进入容器内部，用命令下载，先确定容器可以上网，然后down，不行。如图：
![3](https://github.com/user-attachments/assets/dcdef9be-8a7c-4052-a86c-73efdb16758d)
3，环境cuda11.8 ，按说明直接部署运行如下，
pip install "xinference[vllm]"
报错，如图：
![4](https://github.com/user-attachments/assets/00ea00de-68d1-46bc-a31b-374bd06ec70e)

### Reproduction / 复现过程

同上

### Expected behavior / 期待表现

能下载model

**Comment by qinxuye** [comment]
最新版页面上 optional 选项里，选择 modelscope 作为下载源。
