### ISSUE TITLE
自定义模型 xuanyuan-6b 模型，模型推理时无法正确停止。

### ISSUE THREAD

**Issue by bf96163** [xorbitsai/inference#1940]
### System Info / 系統信息

Software:  python 3.10.14,   xinference 0.13.2, transformers 4.43.1, vllm 0.5.3post1,
hardware： docker host:Ubuntu 20.04.6  container:Ubuntu 22.04.3 CUDA 12.4 （3090 driver 550.78）

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

开发容器内使用: 
nohup xinference-local --host 0.0.0.0 --port 8080 &

### Reproduction / 复现过程

1. modelscope 下载模型 Duxiaoman-DI/XuanYuan-6B
2. 用如下配置注册模型：
`{
    "version": 1,
    "context_length": 4096,
    "model_name": "xxx_xuanyuan-6b",
    "model_lang": [
      "en","ch"
    ],
    "model_ability": [
      "generate","chat"
    ],
    "model_family": "other",
    "model_specs": [
      {
        "model_format": "pytorch",
        "model_size_in_billions": 6,
        "quantizations": [
          "4-bit",
          "8-bit",
          "none"
        ],
        "model_id": "xxx/xuanyuan-6b",
        "model_uri": "/xxx/Duxiaoman-DI/XuanYuan-6B"
      }
    ],
    "prompt_style": {
      "style_name": "ADD_COLON_TWO",
      "system_prompt": "",
      "roles": [
        "Human",
        "Assistant"
      ],
      "intra_message_sep": " ",
      "inter_message_sep": "</s>",
      "stop": ["</s>"],
      "stop_token_ids": [2]
    }
  }`
4. 访问 /v1/completions 或 /v1/chat/completions 接口 发送请求：
` {
    "model": "xxx_xuanyuan-6b",
    "messages": [
        {
            "role": "system",
            "content": ""
        },
        {
            "role": "user",
            "content": "解释下头寸"
        }
    ]
  }`
 能看到返回的结果没有正确停止。
![截图20240726113911569](https://github.com/user-attachments/assets/feeeb73c-7061-4023-95b1-703a7a8027aa)
补充信息：千问1.5 千问2 系列模型可以在该开发容器内正确通过自定义注册方式运行。

### Expected behavior / 期待表现

该模型地址是：https://github.com/Duxiaoman-DI/XuanYuan 
期望模型能够正确截断输出。

**Comment by qinxuye** [comment]
谢谢，我们希望能更好的支持不在 Xinf 列表里的模型，我们正在做一些调研。
