### ISSUE TITLE
kubeblocks  集群版本目前还是0.11.0 麻烦抽空更新到最新版本吧

### ISSUE THREAD

**Issue by da-peng** [xorbitsai/inference#1942]
### Feature request / 功能建议

![image](https://github.com/user-attachments/assets/770423b9-0db7-4785-aba9-f32478e91f0b)
![image](https://github.com/user-attachments/assets/5c81c771-3a77-4544-8b42-20876eec40fb)

### Motivation / 动机

![image](https://github.com/user-attachments/assets/770423b9-0db7-4785-aba9-f32478e91f0b)

### Your contribution / 您的贡献

![image](https://github.com/user-attachments/assets/770423b9-0db7-4785-aba9-f32478e91f0b)

**Comment by qinxuye** [comment]
Now Xinference on kubeblocks is maintained by Kubeblocks team, refer to https://kubeblocks.io/docs/preview/user_docs/kubeblocks-for-xinference/manage-xinference for more information.
