### ISSUE TITLE
。新版本似乎webui有严重bug.如何安装旧版本，例如0.13.2

### ISSUE THREAD

**Issue by zzlTim** [xorbitsai/inference#1948]
### System Info / 系統信息

w

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

w

### The command used to start Xinference / 用以启动 xinference 的命令

w

### Reproduction / 复现过程

![9b6a825cd2f07114a57565d17e3376bc](https://github.com/user-attachments/assets/12219d71-ac43-4208-9857-a4ebbf49bffe)

### Expected behavior / 期待表现

能够安装旧版本

**Comment by qinxuye** [comment]
```
pip install xinference==xxx  # xxx is the version
```

We are addressing the bug on Web UI.
