### ISSUE TITLE
ENH: ChatInterface class from Gradio

### ISSUE THREAD

**Issue by Bojun-Feng** [xorbitsai/inference#195]
The Gradio `𝙲𝚑𝚊𝚝𝙸𝚗𝚝𝚎𝚛𝚏𝚊𝚌𝚎` class provides a faster and more convenient way to build a Chatbot UI with undo/retry features.

Here is the [twitter post](https://twitter.com/gradio/status/1681019343226695686?s=46&t=bfCfzw8w814e-2qdeCcZyw) with an overview

**Comment by UranusSeven** [comment]
Resolved by #208
