### ISSUE TITLE
glm4-9v多卡推理失败

### ISSUE THREAD

**Issue by JiaLingLi** [xorbitsai/inference#1963]
### System Info / 系統信息

使用的官方最新镜像registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

直接给的--gpus all，qwen-7b这些纯文字模型双卡推理是正常的，但是glm4-9v这种多模态模型就只会使用其中一张显卡，并不会切分模型到两张显卡中，进而造成oom。

### Reproduction / 复现过程

注册custom模型为glm4v，然后设置transformer启动，双卡。具体设置如下图所示
![glm4-v报错](https://github.com/user-attachments/assets/1d91d8ae-8cf6-48db-a68d-761feb0b2175)

### Expected behavior / 期待表现

希望后续版本可以支持glm4-9v的多卡推理功能。

**Comment by Jalen-Zhong** [comment]
一样的问题，自定义glm-4v无法多卡部署。此外，xinference内置glm-4v下载失败。

**Comment by blizzardwj** [comment]
这个应该是加载失败吧，不是推理失败，遇到了同样的问题，使用显卡2*3090 24G

**Comment by ChengjieLi28** [comment]
@JiaLingLi 双卡NGPU选择2，你选的auto默认是1张卡。

**Comment by buctllx** [comment]
v0.16.3 docker 启动，多卡推理 glm-4v 还是报错 oom

**Comment by JiaLingLi** [comment]
> @JiaLingLi 双卡NGPU选择2，你选的auto默认是1张卡。

那这个auto的意义是什么？
