### ISSUE TITLE
Support Kolors (a text-to-image model)

### ISSUE THREAD

**Issue by BrightXiaoHan** [xorbitsai/inference#1972]
### Feature request / 功能建议

SD系列的模型对中文非原生支持，Kolors对中文提示词的生成效果较好，希望进行支持。

### Motivation / 动机

Kolors is a large-scale text-to-image generation model based on latent diffusion, developed by the Kuaishou Kolors team. Trained on billions of text-image pairs, Kolors exhibits significant advantages over both open-source and proprietary models in visual quality, complex semantic accuracy, and text rendering for both Chinese and English characters. Furthermore, Kolors supports both Chinese and English inputs, demonstrating strong performance in understanding and generating Chinese-specific content. 

### Your contribution / 您的贡献

Links：
https://huggingface.co/Kwai-Kolors/Kolors-diffusers
https://github.com/Kwai-Kolors/Kolors

**Comment by qinxuye** [comment]
Thanks, we will do some investigation first.
