### ISSUE TITLE
lanch jina-embeddings-v2-base-zh fail 

### ISSUE THREAD

**Issue by randy163** [xorbitsai/inference#1977]
### System Info / 系統信息

Cuda 12.1
vllm 0.5.3.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.13.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-supervisor -H ip -p 9997 --log-level DEBUG

export XINFERENCE_MODEL_SRC=modelscope

xinference-worker -e http://ip :9997 -H ip2 --worker-port 9996 --log-level DEBUG

### Reproduction / 复现过程

xinference launch --model-name jina-embeddings-v2-base-zh --model-type embedding --model-uid jina-embeddings-v2-base-zh -e http://ip:9997 --worker-ip ip2 --gpu-idx 0

### Expected behavior / 期待表现

RuntimeError: Failed to launch model, detail: [address=ip:34885, pid=84495] We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like jinaai/jina-bert-implementation is not the path to a directory containing a file named configuration_bert.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by randy163** [comment]
安装[Llama.cpp](https://inference.readthedocs.io/zh-cn/latest/getting_started/installation.html#installation-ggml)，失败，
仅使用pip安装transformers和vllm
pip install "xinference[transformers]"
pip install "xinference[vllm]"

**Comment by qinxuye** [comment]
看上去是连接问题。参考 https://inference.readthedocs.io/zh-cn/latest/models/sources/sources.html#modelscope 设置环境变量启动，从 modelscope 下载。
