### ISSUE TITLE
安装llama-cpp-python  cuda 推理加速支持，提示"Could not find nvcc, please set CUDAToolkit_ROOT."

### ISSUE THREAD

**Issue by da-peng** [xorbitsai/inference#1979]
### System Info / 系統信息

0.13.3 最新版本

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

最新版本
![image](https://github.com/user-attachments/assets/5f69a0b0-2b01-471d-8f9b-27e01e1dd922)

### The command used to start Xinference / 用以启动 xinference 的命令

 CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python -i https://pypi.tuna.tsinghua.edu.cn/simple

### Reproduction / 复现过程

CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python -i https://pypi.tuna.tsinghua.edu.cn/simple

![image](https://github.com/user-attachments/assets/974a50b9-ef78-41b9-96f8-d0fe71389242)

### Expected behavior / 期待表现

![image](https://github.com/user-attachments/assets/2afccd86-5bc7-4464-aab6-9369c61bbb9d)

能够支持  llama.cpp(CUDA 加速支持)
CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python

**Comment by da-peng** [comment]
查看/user/local/cuda下面好像是缺少 bin 文件
![image](https://github.com/user-attachments/assets/b2787246-652c-4059-bd9c-4c8b1207e495)

**Comment by da-peng** [comment]
![image](https://github.com/user-attachments/assets/f64f7730-c727-4f90-9412-1e28190d3e06)

**Comment by da-peng** [comment]
建议修复，多谢

**Comment by qinxuye** [comment]
主分支已经修复了，可以等明天的 nightly-main tag 的镜像。
