### ISSUE TITLE
chatTTS模型新增固定音色的功能

### ISSUE THREAD

**Issue by ZhouShaoyang** [xorbitsai/inference#1988]
### Feature request / 功能建议

辛苦考虑接入一下稳定音色模型。

### Motivation / 动机

使用随机音色在生成语音聊天对话时，连贯性不好。

### Your contribution / 您的贡献

https://modelscope.cn/studios/ttwwwaa/ChatTTS_Speaker

**Comment by qinxuye** [comment]
简单看了下，关于这个稳定音色接入，有什么建议吗？是内置几个音色，对应 seed？

**Comment by ZhouShaoyang** [comment]
> 简单看了下，关于这个稳定音色接入，有什么建议吗？是内置几个音色，对应 seed？

能否直接开放一个自定义音色pt模型路径的参数（类似LLM中能指定n_ctx长度）？当用户指定时就加载该指定的音色模型；不加入该参数的时候，给一个评分最高音色模型（比如seed_2155）作为default值，或者就维持目前的随机音色，这样是否可行？

**Comment by ZhouShaoyang** [comment]
> 简单看了下，关于这个稳定音色接入，有什么建议吗？是内置几个音色，对应 seed？

比较建议是指定seed_2155作为默认值，再提供一个自定义音色模型路径的参数。这样用户接入其他音色（挑选下载音色，或者自训练音色）都比较灵活。

**Comment by qinxuye** [comment]
@codingl2k1 有啥想法吗？
