### ISSUE TITLE
deploy llama-3.1-instruct-405B config.json validate error

### ISSUE THREAD

**Issue by JustWeZero** [xorbitsai/inference#1989]
### System Info / 系統信息

ubuntu系统，docker部署，镜像版本v0.13.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.13.3

### The command used to start Xinference / 用以启动 xinference 的命令

sh -c "pip uninstall -y llama-cpp-python && xinference-local -H 0.0.0.0"

### Reproduction / 复现过程

模型地址：https://modelscope.cn/models/LLM-Research/Meta-Llama-3.1-405B-Instruct-GPTQ-INT4/files
在WEBUI页面上注册模型，启动，报错：`rope_scaling` must be a dictionary with two fields,`type` and `factor`,got {
    "factor": 8.0,
    "low_freq_factor": 1.0,
    "high_freq_factor": 4.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  }

测试过Meta-Llama-3.1-70B-Instruct-GPTQ-INT4，模型正常启动，应该就是这部分config的问题

### Expected behavior / 期待表现

模型能够正确部署

**Comment by JustWeZero** [comment]
> 看上去是 transformers 或者 vllm 引擎的版本问题。

我是使用的docker v0.13.3镜像中的vllm引擎启动的，明天我上班看一下具体的版本

**Comment by ganwumeng** [comment]
同样的问题，llama-3.1-instruct，8b，pytorch格式。用的transformers引擎，transformers库版本4.40.2

**Comment by JustWeZero** [comment]
> > 看上去是 transformers 或者 vllm 引擎的版本问题。
> 
> 我是使用的docker v0.13.3镜像中的vllm引擎启动的，明天我上班看一下具体的版本

使用pip show命令查看了一下docker镜像v0.13.3版本的transformer和vllm版本。对应版本如下：
vllm: 0.5.3.post1 [https://github.com/vllm-project/vllm/releases/tag/v0.5.3.post1](url) 
看起来应该是支持llama3.1的.
transfiormers: v4.42.4  [https://github.com/huggingface/transformers/releases/tag/v4.42.4](url)
meta的huggingface仓库url:
[https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct#use-with-transformers](url) 
根据meta的标注，transformers的版本应大于4.43.0. 镜像中的transformers版本小于对应版本. 

[](https://huggingface.co/blog/zh/llama31#using-hugging-face-transformers)
根据huggingface的post，transformers版本需要更新为大于4.43.0才支持llama3.1.

升级transformers版本有可能解决问题。我使用的是docker hub发布的v0.13.3官方镜像，最近没有时间，请有心人测试一下是否能解决问题。

**Comment by ganwumeng** [comment]
尝试更新transformers版本到4.43.0后，出现了另外一个错误：
> 2024-08-01 17:17:41,567 xinference.api.restful_api 52519 ERROR    [address=0.0.0.0:44167, pid=52670] 'type'
Traceback (most recent call last):
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/api/restful_api.py", line 848, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 768, in load
    super().load()
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 326, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 201, in _load_model
    model = AutoModelForCausalLM.from_pretrained(
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3775, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1066, in __init__
    self.model = LlamaModel(config)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in __init__
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in <listcomp>
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 632, in __init__
    self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 306, in __init__
    self.rotary_emb = LlamaRotaryEmbedding(config=self.config)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 110, in __init__
    self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling["type"])
    ^^^^^^^^^^^^^^^^^
KeyError: [address=0.0.0.0:44167, pid=52670] 'type'

**Comment by JustWeZero** [comment]
上班呢，老板让我优先解决这个问题，所以搞了一下。

### 目前的结果：

因为我的环境是内网环境，手动导出transformers==4.43.4的离线包到内网，执行pip install --upgrade transformers之后进行升级，提示某些依赖冲突，transformer形式部署成功，正常占用GPU显存，但流式推理速度极慢，一句“你好”回答用了2分钟才生成完成。

### 目前发现的根本原因
xinference在build镜像的时候引用的是vllm-openai:latest镜像，在[v0.5.3.post1](https://github.com/vllm-project/vllm/releases/tag/v0.5.3.post1)的发布版本中，requirements-common.txt中标注的transformers版本为>=4.42.4，所以导致transformers版本过低报错。在其main分支中已经修复该问题，transformers >= 4.43.2. 

### 解决办法
在本仓库发布xinference时，在Dockerfile中做额外的pip install操作，安装新版的transformers. 根本的解决办法需要等vllm-openai那边发布新的发行版image.

**Comment by JustWeZero** [comment]
> **尝试更新transformers版本到4.43.0后，vllm运行成功。**
> 
> 如果使用transformers引擎，出现了另外一个错误： xinference版本0.13.3
> 
> > 2024-08-01 17:17:41,567 xinference.api.restful_api 52519 ERROR    [address=0.0.0.0:44167, pid=52670] 'type'
> > Traceback (most recent call last):
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/api/restful_api.py", line 848, in launch_model
> > model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
> > return self._process_result_message(result)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
> > raise message.as_instanceof_cause()
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
> > result = await self._run_coro(message.message_id, coro)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
> > return await coro
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in **on_receive**
> > return await super().**on_receive**(message)  # type: ignore
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 558, in **on_receive**
> > raise ex
> > File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive**
> > async with self._lock:
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive**
> > with debug_async_timeout('actor_lock_timeout',
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive**
> > result = await result
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
> > await _launch_model()
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
> > await _launch_one_model(rep_model_uid)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
> > await worker_ref.launch_builtin_model(
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
> > async with lock:
> > File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
> > result = await result
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
> > ret = await func(*args, **kwargs)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
> > await model_ref.load()
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
> > return self._process_result_message(result)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
> > raise message.as_instanceof_cause()
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
> > result = await self._run_coro(message.message_id, coro)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
> > return await coro
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in **on_receive**
> > return await super().**on_receive**(message)  # type: ignore
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 558, in **on_receive**
> > raise ex
> > File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive**
> > async with self._lock:
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive**
> > with debug_async_timeout('actor_lock_timeout',
> > ^^^^^^^^^^^^^^^^^
> > File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive**
> > result = await result
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
> > self._model.load()
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 768, in load
> > super().load()
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 326, in load
> > self._model, self._tokenizer = self._load_model(**kwargs)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 201, in _load_model
> > model = AutoModelForCausalLM.from_pretrained(
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
> > return model_class.from_pretrained(
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3775, in from_pretrained
> > model = cls(config, *model_args, **model_kwargs)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1066, in **init**
> > self.model = LlamaModel(config)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in **init**
> > [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in 
> > [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 632, in **init**
> > self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 306, in **init**
> > self.rotary_emb = LlamaRotaryEmbedding(config=self.config)
> > ^^^^^^^^^^^^^^^^^
> > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 110, in **init**
> > self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling["type"])
> > ^^^^^^^^^^^^^^^^^
> > KeyError: [address=0.0.0.0:44167, pid=52670] 'type'

请问一下，部署成功后的推理速度怎么样？

**Comment by ganwumeng** [comment]
> > **尝试更新transformers版本到4.43.0后，vllm运行成功。**
> > 如果使用transformers引擎，出现了另外一个错误： xinference版本0.13.3
> > > 2024-08-01 17:17:41,567 xinference.api.restful_api 52519 ERROR    [address=0.0.0.0:44167, pid=52670] 'type'
> > > Traceback (most recent call last):
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/api/restful_api.py", line 848, in launch_model
> > > model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
> > > return self._process_result_message(result)
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
> > > raise message.as_instanceof_cause()
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
> > > result = await self._run_coro(message.message_id, coro)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
> > > return await coro
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in **on_receive**
> > > return await super().**on_receive**(message)  # type: ignore
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 558, in **on_receive**
> > > raise ex
> > > File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive**
> > > async with self._lock:
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive**
> > > with debug_async_timeout('actor_lock_timeout',
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive**
> > > result = await result
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
> > > await _launch_model()
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
> > > await _launch_one_model(rep_model_uid)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
> > > await worker_ref.launch_builtin_model(
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
> > > async with lock:
> > > File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
> > > result = await result
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
> > > ret = await func(*args, **kwargs)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
> > > await model_ref.load()
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
> > > return self._process_result_message(result)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
> > > raise message.as_instanceof_cause()
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
> > > result = await self._run_coro(message.message_id, coro)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
> > > return await coro
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xoscar/api.py", line 384, in **on_receive**
> > > return await super().**on_receive**(message)  # type: ignore
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 558, in **on_receive**
> > > raise ex
> > > File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive**
> > > async with self._lock:
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive**
> > > with debug_async_timeout('actor_lock_timeout',
> > > ^^^^^^^^^^^^^^^^^
> > > File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive**
> > > result = await result
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
> > > self._model.load()
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 768, in load
> > > super().load()
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 326, in load
> > > self._model, self._tokenizer = self._load_model(**kwargs)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 201, in _load_model
> > > model = AutoModelForCausalLM.from_pretrained(
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
> > > return model_class.from_pretrained(
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3775, in from_pretrained
> > > model = cls(config, *model_args, **model_kwargs)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1066, in **init**
> > > self.model = LlamaModel(config)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in **init**
> > > [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 845, in
> > > [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 632, in **init**
> > > self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 306, in **init**
> > > self.rotary_emb = LlamaRotaryEmbedding(config=self.config)
> > > ^^^^^^^^^^^^^^^^^
> > > File "/data/anaconda3/envs/llm_tl/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 110, in **init**
> > > self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling["type"])
> > > ^^^^^^^^^^^^^^^^^
> > > KeyError: [address=0.0.0.0:44167, pid=52670] 'type'
> 
> 请问一下，部署成功后的推理速度怎么样？

我跑的是8b的版本。速度和其他的8b模型差不多，挺快。

**Comment by JustWeZero** [comment]
使用docker image v0.13.3 + transformers==4.43.0试了一下，transformers部署会提示KeyError: 'type',vllm会提示 unhandled NCCL error. 
llama-3.1-405B的config.json与70B和8B的文件内容不一样。
405B的rope_scaling内容为：
`"rope_scaling": {
    "factor": 8.0,
    "low_freq_factor": 1.0,
    "high_freq_factor": 4.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },`
70B与8B的rope_scaling内容为null. 

应该是这个地方出了问题，但是不知道怎么解决了。

**Comment by jiusi9** [comment]
Hi, 请问这个问题怎么解决的呀， 我使用llama3.1也遇到了类似问题

**Comment by JustWeZero** [comment]
新的版本镜像还没试，试试最新版的镜像呗











发自我的iPad

---Original---
From: ***@***.***&gt;
Date: Tue, Aug 13, 2024 16:59 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [xorbitsai/inference] deploy llama-3.1-instruct-405B config.jsonvalidate error (Issue #1989)




 
Hi, 请问这个问题怎么解决的呀， 我使用llama3.1也遇到了类似问题

**Comment by jiusi9** [comment]
It works for me.
`pip install --upgrade transformers`

Reference:
https://github.com/huggingface/transformers/issues/32232
https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15
