### ISSUE TITLE
CosyVoice-300M unavailable

### ISSUE THREAD

**Issue by tsiens** [xorbitsai/inference#1992]
### System Info / 系統信息

cuda 12.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.13.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/8b56be87-8703-4f26-966f-06b880383393)
```
from xinference.client import Client
client = Client("http://0.0.0.0:9997")
model = client.get_model("CosyVoice-300M")
model.speech(input='您好')
```
![image](https://github.com/user-attachments/assets/f7560077-2760-469b-87c0-8b34a31d92d7)
```
from xinference.client import Client
client = Client("http://0.0.0.0:9997")
model = client.get_model("CosyVoice-300M")
model.speech(prompt_speech='你是一个机器人',input='您好')
![image](https://github.com/user-attachments/assets/34b1a3ee-3502-4049-bae6-6840fe1a4aeb)


### Expected behavior / 期待表现

Normal use

**Comment by qinxuye** [comment]
Follow instruction: https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/audio.html#cosyvoice-usage

You are using wrong.

**Comment by tsiens** [comment]
> Follow instruction: https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/audio.html#cosyvoice-usage
> 
> You are using wrong.

```
>>> from xinference.client import Client
>>>
>>> client =  Client("http://0.0.0.0:9997")
>>>
>>> model = client.get_model("CosyVoice-300M")
>>> speech_bytes = model.speech(
...     input='您好',
...     # ['中文女', '中文男', '日语男', '粤语女', '英文女', '英文男', '韩语女']
...     voice="中文女"
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/inference/xinference/client/restful/restful_client.py", line 820, in speech
    raise RuntimeError(
RuntimeError: Failed to speech the text, detail: [address=0.0.0.0:39956, pid=48] CosyVoice model expect a prompt_speech
```

**Comment by tsiens** [comment]
Sorry, I didn't understand the meaning of the three models. I'll study them again

**Comment by qinxuye** [comment]
The doc showed the corresponding model you should use for the specific API.
