### ISSUE TITLE
embedding模型的usage一直为37

### ISSUE THREAD

**Issue by yinghaodang** [xorbitsai/inference#2000]
### System Info / 系統信息

这些因素和此bug无关。

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

最新提交为：[2c810c6](https://github.com/xorbitsai/inference/commit/2c810c64e10e52a38a4490e226874f7d7d4dcf1e)

### The command used to start Xinference / 用以启动 xinference 的命令

未启动

### Reproduction / 复现过程

https://github.com/xorbitsai/inference/blob/main/xinference/model/embedding/core.py
的第236行计算token数错误。导致token长度恒为37.

### Expected behavior / 期待表现

能够正确计算embedding请求的token数。

**Comment by qinxuye** [comment]
有兴趣贡献代码解决这个问题吗？

**Comment by yinghaodang** [comment]
修复过程比较简单,比较水。
第236行，all_token_nums += sum([len(f) for f in features]) 改成 all_token_nums += sum([len(features[f]) for f in features]) 即可。
——————————————————————————————————————
除开这个问题，我比较好奇的是：embedding模型在推理的过程中进行了一次排序，也就是记录中从sentence-transformers库中拷贝的encode函数，先对输入模型的sentences做了一次排序。这么做是可以加快推理速度吗？

**Comment by yinghaodang** [comment]
好的
