### ISSUE TITLE
无法启动本地下载好的内置模型

### ISSUE THREAD

**Issue by HaiShin** [xorbitsai/inference#2017]
### System Info / 系統信息

。。。

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14

### The command used to start Xinference / 用以启动 xinference 的命令

使用helm安装的

### Reproduction / 复现过程

1. 从hf下载bge--reranker-v2-gemma模型
2. 在xinference web中选择Launch model，会从远端hf进行下载。
3. 随即，在registger model中配置，又显示bge--reranker-v2-gemma名字已经在内置模型中。
4. 请问：在离线状态下，通过下载内置模型的文件转到离线环境中，是否有其他方式进行启动？

### Expected behavior / 期待表现

可以启动内置模型

**Comment by qinxuye** [comment]
在 launch 页面的 optional 里，model_path 选择你的路径。
