### ISSUE TITLE
如何调用API接口，流式输出回答？

### ISSUE THREAD

**Issue by as100863** [xorbitsai/inference#2018]
### Feature request / 功能建议

下面代码是非流式回答，要使用流式回答，可以提供下参考方法？

from xinference.client import Client

client = Client("http://localhost:9997")
# The chatglm2 model has the capabilities of "chat" and "embed".
model_uid = client.launch_model(model_name="chatglm2",
                                model_engine="llama.cpp",
                                model_format="ggmlv3",
                                model_size_in_billions=6,
                                quantization="q4_0")
model = client.get_model(model_uid)

chat_history = []
prompt = "What is the largest animal?"
# If the model has "generate" capability, then you can call the
# model.generate API.
model.chat(
    prompt,
    chat_history=chat_history,
    generate_config={"max_tokens": 1024}
)

### Motivation / 动机

功能需求

### Your contribution / 您的贡献

功能需求

**Comment by ChengjieLi28** [comment]
```
generate_config={"max_tokens": 1024, "stream": True}
```
