### ISSUE TITLE
前端页面无限跳转登录页问题

### ISSUE THREAD

**Issue by WalkerWang731** [xorbitsai/inference#2021]
### System Info / 系統信息

前端页面打开后，无限跳转登录和launch/llm页面
经过排查，是因为我的本地浏览器有一个默认的token cookie, 导致 这里的判断过不去，所以不会设置no_auth 的 cookie
https://github.com/xorbitsai/inference/blob/3f7dc2ddccfd023dc3aabee7200891de6a60eee0/xinference/web/ui/src/App.js#L40

建议 去除 `if (!data.auth && cookie.token !== 'no_auth')` 中 `cookie.token !== 'no_auth'` 这个判断逻辑
或 
更换cookie的key值：例如xinference-token

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -p 9997:9997 --gpus all xprobe/xinference:v0.14.0 xinference-local -H 0.0.0.0

### Reproduction / 复现过程

1. 浏览器先设置一个token的cookie

### Expected behavior / 期待表现

改进cookie和sessionStorage的key值

**Comment by qinxuye** [comment]
可以更换key值。有兴趣贡献吗？

**Comment by WalkerWang731** [comment]
> 可以更换key值。有兴趣贡献吗？

ok 我改一下稍后会提交PR
