### ISSUE TITLE
The dify application reports an error when calling the model. The running models is an empty model and then automatically restarts. The background log shows that the model cannot be found, and -1-0 is added after the uid.

### ISSUE THREAD

**Issue by ricky977** [xorbitsai/inference#2027]
### System Info / 系統信息

cuda 12.4
transformers   4.42.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference v14.0，LLM：qwen2-72B

### The command used to start Xinference / 用以启动 xinference 的命令

Configure the conda environment by pip install xinference["transformers"] and start the xinference command

### Reproduction / 复现过程

After deploying qwen-72b and integrating it into the dify platform, the application often reports an error when calling the model: xinference: An error occurred during streaming.
<img width="271" alt="微信图片_20240806184946" src="https://github.com/user-attachments/assets/0203ea0c-d7ed-47a8-81d2-9d960be98855">
Then the model was no longer in the running models on the xinference homepage. I checked with the nvidia-smi command and found that the model was being loaded again. After a while, I refreshed it and found that the qwen-72b model appeared in the running model list again.

Checking the background log shows model not found in the model list, uid:72B-1-0, but my model uid is 72B, and there is no 1-0 at the end. I don't know where it comes from.
![屏幕截图 2024-08-06 185752](https://github.com/user-attachments/assets/9f988878-bee6-494a-a6d9-20399c88767f)
If two parties call the same model at the same time, the model will crash and report the same error.

### Expected behavior / 期待表现

I hope that the loading model call can be more stable, no errors are reported, and multiple parties can call it at the same time.

**Comment by ychy00001** [comment]
一样的问题，我是更改transformers版本后运行报错 一直换版本，在起模型就报错了。但是停掉整体的服务重启下就好使了。
我docker安装了 重启了下容器
