### ISSUE TITLE
NameError: Field name "schema" shadows a BaseModel attribute; use a different field name with "alias='schema'"

### ISSUE THREAD

**Issue by magicyuan876** [xorbitsai/inference#2032]
### System Info / 系統信息

Package                           Version
--------------------------------- --------------
absl-py                           2.1.0
accelerate                        0.33.0
aiobotocore                       2.7.0
aiofiles                          23.2.1
aiohappyeyeballs                  2.3.4
aiohttp                           3.10.1
aioitertools                      0.11.0
aioprometheus                     23.12.0
aiosignal                         1.3.1
alembic                           1.13.2
altair                            5.3.0
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             4.4.0
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
async-lru                         2.0.4
async-timeout                     4.0.3
attrdict                          2.0.1
attrs                             24.2.0
audioread                         3.0.1
auto_gptq                         0.7.1
autoawq                           0.2.5
autoawq_kernels                   0.0.6
autopage                          0.5.2
Babel                             2.15.0
bcrypt                            4.2.0
beautifulsoup4                    4.12.3
bibtexparser                      2.0.0b7
bitsandbytes                      0.43.3
bleach                            6.1.0
boto3                             1.28.64
botocore                          1.31.64
cdifflib                          1.2.6
certifi                           2024.7.4
cffi                              1.17.0
cfgv                              3.4.0
charset-normalizer                3.3.2
chattts                           0.1.1
click                             8.1.7
cliff                             4.7.0
clldutils                         3.22.2
cloudpickle                       3.0.0
cmaes                             0.11.0
cmake                             3.30.2
cmd2                              2.4.3
colorama                          0.4.6
coloredlogs                       15.0.1
colorlog                          6.8.2
comm                              0.2.2
conformer                         0.3.2
contourpy                         1.2.1
controlnet_aux                    0.0.7
cryptography                      43.0.0
csvw                              3.3.0
cycler                            0.12.1
Cython                            3.0.11
datasets                          2.20.0
debugpy                           1.8.5
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.25.0
dill                              0.3.8
diskcache                         5.6.3
distlib                           0.3.8
distro                            1.9.0
dlinfo                            1.2.1
ecdsa                             0.19.0
editdistance                      0.8.1
einops                            0.8.0
einx                              0.3.0
encodec                           0.1.1
exceptiongroup                    1.2.2
executing                         2.0.1
fastapi                           0.110.3
fastjsonschema                    2.20.0
ffmpeg-python                     0.2.0
ffmpy                             0.4.0
filelock                          3.15.4
FlagEmbedding                     1.2.10
flatbuffers                       24.3.25
fonttools                         4.53.1
fqdn                              1.5.1
frozendict                        2.4.4
frozenlist                        1.4.1
fsspec                            2023.10.0
future                            1.0.0
gdown                             5.2.0
gekko                             1.2.1
gradio                            4.26.0
gradio_client                     0.15.1
greenlet                          3.0.3
grpcio                            1.65.4
h11                               0.14.0
hiredis                           3.0.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.24.5
humanfriendly                     10.0
hydra-colorlog                    1.2.0
hydra-core                        1.3.2
hydra-optuna-sweeper              1.2.0
HyperPyYAML                       1.2.2
identify                          2.6.0
idna                              3.7
imageio                           2.34.2
importlib_metadata                8.2.0
importlib_resources               6.4.0
inflect                           7.3.1
iniconfig                         2.0.0
interegular                       0.3.3
ipykernel                         6.29.5
ipython                           8.26.0
ipywidgets                        8.1.3
isodate                           0.6.1
isoduration                       20.11.0
jedi                              0.19.1
Jinja2                            3.1.4
jiter                             0.5.0
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.25
jsonpointer                       3.0.0
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
jupyter_client                    8.6.2
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_terminals          0.5.3
jupyterlab                        4.2.4
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.11
kiwisolver                        1.4.5
language-tags                     1.2.0
lark                              1.1.9
lazy_loader                       0.4
libnacl                           2.1.0
librosa                           0.10.2.post1
lightning                         2.3.3
lightning-utilities               0.11.6
llama_cpp_python                  0.2.80
llvmlite                          0.43.0
lm-format-enforcer                0.10.3
lxml                              5.2.2
Mako                              1.3.5
Markdown                          3.6
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matcha-tts                        0.0.5.1
matplotlib                        3.9.1.post1
matplotlib-inline                 0.1.7
mdurl                             0.1.2
mistune                           3.0.2
modelscope                        1.17.0
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.8
multidict                         6.0.5
multiprocess                      0.70.16
nbclient                          0.10.0
nbconvert                         7.16.4
nbformat                          5.10.4
nemo_text_processing              1.0.2
nest-asyncio                      1.6.0
networkx                          3.3
ninja                             1.11.1.1
nodeenv                           1.9.1
notebook                          7.2.1
notebook_shim                     0.2.4
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.555.43
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.20
nvidia-nvtx-cu12                  12.1.105
omegaconf                         2.3.0
onnxruntime                       1.16.0
openai                            1.40.0
openai-whisper                    20230306
opencv-contrib-python             4.10.0.84
opencv-python                     4.10.0.84
optimum                           1.21.3
optuna                            2.10.1
orjson                            3.10.6
outlines                          0.0.46
overrides                         7.7.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.1
parso                             0.8.4
passlib                           1.7.4
pbr                               6.0.0
peft                              0.12.0
pexpect                           4.9.0
phonemizer                        3.3.0
pillow                            10.4.0
pip                               24.0
piper-phonemize                   1.1.0
platformdirs                      4.2.2
pluggy                            1.5.0
pooch                             1.8.2
pre-commit                        3.8.0
prettytable                       3.10.2
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.47
protobuf                          4.25.4
psutil                            6.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.6.0
pybase16384                       0.3.7
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.8.2
pydantic_core                     2.20.1
pydub                             0.25.1
Pygments                          2.18.0
pylatexenc                        2.10
pynini                            2.1.5
pynvml                            11.5.3
pyparsing                         3.1.2
pyperclip                         1.9.0
PySocks                           1.7.1
pytest                            8.3.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-jose                       3.3.0
python-json-logger                2.0.7
python-multipart                  0.0.9
pytorch-lightning                 2.3.3
pytz                              2024.1
PyYAML                            6.0.2
pyzmq                             26.1.0
quantile-python                   1.1
ray                               2.34.0
rdflib                            7.0.0
redis                             5.0.8
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
rfc3339-validator                 0.1.4
rfc3986                           1.5.0
rfc3986-validator                 0.1.1
rich                              13.7.1
rootutils                         1.0.7
rouge                             1.0.1
rpds-py                           0.20.0
rsa                               4.9
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruff                              0.5.6
s3fs                              2023.10.0
s3transfer                        0.7.0
sacremoses                        0.1.1
safetensors                       0.4.4
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.14.0
seaborn                           0.13.2
segments                          2.2.1
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentence-transformers             3.0.1
sentencepiece                     0.2.0
setuptools                        72.1.0
sglang                            0.2.10
shellingham                       1.5.4
six                               1.16.0
sniffio                           1.3.1
soundfile                         0.12.1
soupsieve                         2.5
soxr                              0.4.0
SQLAlchemy                        2.0.32
sse-starlette                     2.1.3
stack-data                        0.6.3
starlette                         0.37.2
stevedore                         5.2.0
sympy                             1.13.1
tabulate                          0.9.0
tblib                             3.0.0
tensorboard                       2.17.0
tensorboard-data-server           0.7.2
tensorizer                        2.9.0
terminado                         0.18.1
threadpoolctl                     3.5.0
tifffile                          2024.7.24
tiktoken                          0.7.0
timm                              1.0.8
tinycss2                          1.3.0
tokenizers                        0.19.1
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.4.0
torchaudio                        2.4.0
torchmetrics                      1.4.1
torchvision                       0.19.0
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
transformers                      4.43.4
transformers-stream-generator     0.0.5
triton                            3.0.0
typeguard                         4.3.0
typer                             0.11.1
types-python-dateutil             2.9.0.20240316
typing_extensions                 4.12.2
tzdata                            2024.1
Unidecode                         1.3.8
uri-template                      1.3.0
uritemplate                       4.1.1
urllib3                           2.0.7
uvicorn                           0.30.5
uvloop                            0.19.0
vector-quantize-pytorch           1.15.6
virtualenv                        20.26.3
vllm                              0.5.4
vllm-flash-attn                   2.6.1
vocos                             0.1.0
watchfiles                        0.22.0
wcwidth                           0.2.13
webcolors                         24.6.0
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        11.0.3
Werkzeug                          3.0.3
WeTextProcessing                  1.0.3
wget                              3.2
wheel                             0.43.0
widgetsnbextension                4.0.11
wrapt                             1.16.0
xformers                          0.0.27.post2
xinference                        0.14.0.post1
xoscar                            0.3.2
xxhash                            3.4.1
yarl                              1.9.4
zipp                              3.19.2
zstandard                         0.23.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Name: xinference
Version: 0.14.0.post1
Summary: Model Serving Made Easy
Home-page: https://github.com/xorbitsai/inference
Author: Qin Xuye
Author-email: qinxuye@xprobe.io
License: Apache License 2.0
Location: /data/anaconda3/envs/xinference/lib/python3.10/site-packages
Requires: aioprometheus, async-timeout, click, fastapi, fsspec, gradio, huggingface-hub, modelscope, openai, opencv-contrib-python, passlib, peft, pillow, pydantic, pynvml, python-jose, requests, s3fs, sse-starlette, tabulate, timm, torch, tqdm, typer, typing-extensions, uvicorn, xoscar
Required-by: 

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

Traceback (most recent call last):
  File "/data/anaconda3/envs/xinference/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/__init__.py", line 17, in _install
    from .llm import _install as llm_install
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/__init__.py", line 20, in <module>
    from .core import (
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/core.py", line 26, in <module>
    from ...types import PeftModelConfig
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/types.py", line 482, in <module>
    CreateChatCompletionOpenAI = create_model_from_typeddict(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 504, in infer
    return cls(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 550, in prepare
    self._type_analysis()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 661, in _type_analysis
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 661, in <listcomp>
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 806, in _create_sub_type
    return self.__class__(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 555, in prepare
    self.populate_validators()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/validators.py", line 738, in find_validators
    yield make_typeddict_validator(type_, config)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/validators.py", line 624, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 504, in infer
    return cls(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 555, in prepare
    self.populate_validators()
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/validators.py", line 738, in find_validators
    yield make_typeddict_validator(type_, config)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/validators.py", line 624, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/main.py", line 186, in __new__
    validate_field_name(bases, ann_name)
  File "/data/anaconda3/envs/xinference/lib/python3.10/site-packages/pydantic/v1/utils.py", line 167, in validate_field_name
    raise NameError(
NameError: Field name "schema" shadows a BaseModel attribute; use a different field name with "alias='schema'".

### Expected behavior / 期待表现

正常启动

**Comment by hongchenxinxiang** [comment]
同样问题 我用pip install openai==1.39.0解决了

**Comment by Azesouth** [comment]
nb啊 ，找半天了，结果来得早不如来的巧

**Comment by lhs0627** [comment]
nb，怎么发现的啊

**Comment by xxxbbbbs-dev** [comment]
nb

**Comment by JumpNew** [comment]
nb,搞了5-6个小时

**Comment by bepisorconk** [comment]
hi, facing the same issue. Any resolution?

```
Successfully installed ChatTTS-0.1.1 Cython-3.0.11 FlagEmbedding-1.2.10 HyperPyYAML-1.2.2 Mako-1.3.5 PrettyTable-3.10.2 PySocks-1.7.1 Unidecode-1.3.8 WeTextProcessing-1.0.3 absl-py-2.1.0 accelerate-0.33.0 aiobotocore-2.7.0 aiofiles-23.2.1 aiohappyeyeballs-2.3.5 aiohttp-3.10.1 aioitertools-0.11.0 aioprometheus-23.12.0 aiosignal-1.3.1 alembic-1.13.2 altair-5.3.0 annotated-types-0.7.0 antlr4-python3-runtime-4.9.3 async-timeout-4.0.3 attrdict-2.0.1 audioread-3.0.1 auto-gptq-0.7.1 autoawq-0.2.5 autoawq-kernels-0.0.6 autopage-0.5.2 bcrypt-4.2.0 bibtexparser-2.0.0b7 bitsandbytes-0.43.3 boto3-1.28.64 botocore-1.31.64 cdifflib-1.2.6 cfgv-3.4.0 click-8.1.7 cliff-4.7.0 clldutils-3.22.2 cloudpickle-3.0.0 cmaes-0.11.0 cmake-3.30.2 cmd2-2.4.3 colorama-0.4.6 coloredlogs-15.0.1 colorlog-6.8.2 conformer-0.3.2 contourpy-1.2.1 controlnet-aux-0.0.7 csvw-3.3.0 cycler-0.12.1 datasets-2.20.0 diffusers-0.25.0 dill-0.3.8 diskcache-5.6.3 distlib-0.3.8 dlinfo-1.2.1 ecdsa-0.19.0 editdistance-0.8.1 einops-0.8.0 einx-0.3.0 encodec-0.1.1 fastapi-0.110.3 ffmpeg-python-0.2.0 ffmpy-0.4.0 flatbuffers-24.3.25 fonttools-4.53.1 frozendict-2.4.4 frozenlist-1.4.1 future-1.0.0 gdown-5.2.0 gekko-1.2.1 gradio-4.26.0 gradio-client-0.15.1 greenlet-3.0.3 grpcio-1.65.4 h11-0.14.0 hiredis-3.0.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 huggingface-hub-0.24.5 humanfriendly-10.0 hydra-colorlog-1.2.0 hydra-core-1.3.2 hydra-optuna-sweeper-1.2.0 identify-2.6.0 imageio-2.34.2 importlib-resources-6.4.0 inflect-7.3.1 iniconfig-2.0.0 interegular-0.3.3 isodate-0.6.1 jiter-0.5.0 jmespath-1.0.1 joblib-1.4.2 kiwisolver-1.4.5 language-tags-1.2.0 lark-1.1.9 lazy-loader-0.4 libnacl-2.1.0 librosa-0.10.2.post1 lightning-2.4.0 lightning-utilities-0.11.6 llama-cpp-python-0.2.87 llvmlite-0.43.0 lm-format-enforcer-0.10.3 markdown-3.6 markdown-it-py-3.0.0 matcha-tts-0.0.5.1 matplotlib-3.9.1.post1 mdurl-0.1.2 modelscope-1.17.0 msgpack-1.0.8 multidict-6.0.5 multiprocess-0.70.16 nemo-text-processing-1.0.2 ninja-1.11.1.1 nodeenv-1.9.1 numba-0.60.0 nvidia-cudnn-cu12-9.1.0.70 nvidia-ml-py-12.555.43 nvidia-nccl-cu12-2.20.5 omegaconf-2.3.0 onnxruntime-1.16.0 openai-1.40.1 openai-whisper-20230306 opencv-contrib-python-4.10.0.84 opencv-python-4.10.0.84 optimum-1.21.3 optuna-2.10.1 orjson-3.10.6 outlines-0.0.46 pandas-2.2.2 passlib-1.7.4 pbr-6.0.0 peft-0.12.0 phonemizer-3.3.0 piper-phonemize-1.1.0 pluggy-1.5.0 pooch-1.8.2 pre-commit-3.8.0 prometheus-fastapi-instrumentator-7.0.0 protobuf-4.25.4 py-cpuinfo-9.0.0 pyairports-2.1.1 pyarrow-17.0.0 pyarrow-hotfix-0.6 pyasn1-0.6.0 pybase16384-0.3.7 pycountry-24.6.1 pydantic-2.8.2 pydantic-core-2.20.1 pydub-0.25.1 pylatexenc-2.10 pynini-2.1.5 pynvml-11.5.3 pyperclip-1.9.0 pytest-8.3.2 python-dotenv-1.0.1 python-jose-3.3.0 python-multipart-0.0.9 pytorch-lightning-2.4.0 pytz-2024.1 quantile-python-1.1 ray-2.34.0 rdflib-7.0.0 redis-5.0.8 regex-2024.7.24 requests-2.32.3 rfc3986-1.5.0 rich-13.7.1 rootutils-1.0.7 rouge-1.0.1 rsa-4.9 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 ruff-0.5.6 s3fs-2023.10.0 s3transfer-0.7.0 sacremoses-0.1.1 safetensors-0.4.4 scikit-image-0.24.0 scikit-learn-1.5.1 scipy-1.14.0 seaborn-0.13.2 segments-2.2.1 semantic-version-2.10.0 sentence-transformers-3.0.1 sentencepiece-0.2.0 sglang-0.2.11 shellingham-1.5.4 soundfile-0.12.1 soxr-0.4.0 sqlalchemy-2.0.32 sse-starlette-2.1.3 starlette-0.37.2 stevedore-5.2.0 tabulate-0.9.0 tblib-3.0.0 tensorboard-2.17.0 tensorboard-data-server-0.7.2 tensorizer-2.9.0 threadpoolctl-3.5.0 tifffile-2024.7.24 tiktoken-0.7.0 timm-1.0.8 tokenizers-0.19.1 tomlkit-0.12.0 toolz-0.12.1 torch-2.4.0 torchaudio-2.4.0 torchmetrics-1.4.1 torchvision-0.19.0 tqdm-4.66.5 transformers-4.43.4 transformers-stream-generator-0.0.5 triton-3.0.0 typeguard-4.3.0 typer-0.11.1 typing-extensions-4.12.2 tzdata-2024.1 uritemplate-4.1.1 urllib3-2.0.7 uvicorn-0.30.5 uvloop-0.19.0 vector_quantize_pytorch-1.15.6 virtualenv-20.26.3 vllm-0.5.4 vllm-flash-attn-2.6.1 vocos-0.1.0 watchfiles-0.23.0 websockets-11.0.3 werkzeug-3.0.3 wget-3.2 wrapt-1.16.0 xformers-0.0.27.post2 xinference-0.14.0.post1 xoscar-0.3.2 xxhash-3.4.1 yarl-1.9.4 zstandard-0.23.0
```
root@4a229eaa4f06:/# xinference-local --host 0.0.0.0 --port 9997
Traceback (most recent call last):
  File "/usr/local/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/__init__.py", line 17, in _install
    from .llm import _install as llm_install
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/__init__.py", line 20, in <module>
    from .core import (
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/core.py", line 26, in <module>
    from ...types import PeftModelConfig
  File "/usr/local/lib/python3.10/dist-packages/xinference/types.py", line 482, in <module>
    CreateChatCompletionOpenAI = create_model_from_typeddict(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 504, in infer
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 550, in prepare
    self._type_analysis()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 661, in _type_analysis
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 661, in <listcomp>
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 806, in _create_sub_type
    return self.__class__(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 555, in prepare
    self.populate_validators()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/validators.py", line 738, in find_validators
    yield make_typeddict_validator(type_, config)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/validators.py", line 624, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 504, in infer
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 555, in prepare
    self.populate_validators()
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/fields.py", line 829, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/validators.py", line 738, in find_validators
    yield make_typeddict_validator(type_, config)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/validators.py", line 624, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/annotated_types.py", line 55, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 1024, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 186, in __new__
    validate_field_name(bases, ann_name)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/utils.py", line 167, in validate_field_name
    raise NameError(
NameError: Field name "schema" shadows a BaseModel attribute; use a different field name with "alias='schema'".
root@4a229eaa4f06:/#

**Comment by qinxuye** [comment]
The main branch has fixed this, for now, run `pip install 'openai<1.40'`.

**Comment by Linuxstyle** [comment]
@hongchenxinxiang  nb

**Comment by 1806150981** [comment]
pip install openai==1.39.0解决了 非常吊！！！

**Comment by FinTechCao** [comment]
> The main branch has fixed this, for now, run `pip install 'openai<1.40'`.

0.14.3在openai为1.42时好像又有问题
