### ISSUE TITLE
support fish speech TTS model

### ISSUE THREAD

**Issue by Tint0ri** [xorbitsai/inference#2033]
### Feature request / 功能建议

support the fish speech model. Which sounds better than ChatTTS and CosyVoice

### Motivation / 动机

Better TTS solution

### Your contribution / 您的贡献

https://huggingface.co/fishaudio/fish-speech-1.2-sft

**Comment by qinxuye** [comment]
Thanks, we need to some investigation first.

**Comment by Tint0ri** [comment]
According to my simple test, far more better than ChatTTS and CosyVoice

**Comment by qinxuye** [comment]
@codingl2k1 I think we can support this next week.

**Comment by Tint0ri** [comment]
I try to run fish speech tts on cpu. Get the error log:
hydra.errors.MissingConfigException: [address=0.0.0.0:34645, pid=158] Cannot find primary config 'firefly_gan_vq'. Check that it's in your config search path.

0.14.3

**Comment by qinxuye** [comment]
Could you open a new issue about it?

**Comment by Tint0ri** [comment]
open new issue: https://github.com/xorbitsai/inference/issues/2195
