### ISSUE TITLE
launch set : -ak, --api-key TEXT  is  invalid

### ISSUE THREAD

**Issue by HouLingLXH** [xorbitsai/inference#2034]
### System Info / 系統信息

windows 10
conda python=3.8

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

use pip install "xinference[transformers]" to install 
version 0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local

### Reproduction / 复现过程

1. $ xinference launch -n qwen2-1.5B-instruct -s 9 -f pytorch -q None --gpu-idx 0 -en Transformers -ak 123456
2. use " client = openai.Client(base_url=base_url, api_key="bbb") "   to chat  ,     bbb != 123456
3. Still working

### Expected behavior / 期待表现

report " api-key  is wrong"

**Comment by ChengjieLi28** [comment]
@HouLingLXH 
你的api-key使用方式是有问题的。请先完整看完此文档：https://inference.readthedocs.io/zh-cn/latest/user_guide/auth_system.html
然后再次尝试。
