### ISSUE TITLE
Support tool calling For Llama 3.1

### ISSUE THREAD

**Issue by ruifengma** [xorbitsai/inference#2045]
### System Info / 系統信息

CentOS7
python 3.10.14
torch 2.4.0
cuda 12.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -H 0.0.0.0 -port 8989

### Reproduction / 复现过程

1. launch xinference
2. launch llama3.1
3. request with function call

### Expected behavior / 期待表现

function call suppport

**Comment by qinxuye** [comment]
Thanks, @codingl2k1 Could you look at this issue?

**Comment by yebanliuying** [comment]
docker 运行也是不支持function call和tool call

**Comment by ruifengma** [comment]
not planned?

**Comment by qinxuye** [comment]
We have plan to support this.

**Comment by ruifengma** [comment]
any progress?
