### ISSUE TITLE
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynini)

### ISSUE THREAD

**Issue by yourengod** [xorbitsai/inference#2057]
## 环境：
```windows 11,conda python= 3.11.9.```
## 执行命令：
```pip install "xinference[all]"```
## bug 信息：
```
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/fc/a3c13ded7b3057680c8ae95a9b6cc83e63657c38e0005c400a5d018a33a7/pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Requirement already satisfied: mdurl~=0.1 in d:\users\admin\anaconda3\envs\llm\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<0.12.0->xinference[all]) (0.1.2)
Building wheels for collected packages: pynini
  Building wheel for pynini (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pynini
      copying pynini\__init__.py -> build\lib.win-amd64-cpython-311\pynini
      creating build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\__init__.py -> build\lib.win-amd64-cpython-311\pywrapfst
      creating build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\case.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak_model.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\dates.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\g2p.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\numbers.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\plurals.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\t9.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\weather.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\__init__.py -> build\lib.win-amd64-cpython-311\pynini\examples
      creating build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\export.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\__init__.py -> build\lib.win-amd64-cpython-311\pynini\export
      creating build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\byte.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\edit_transducer.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\features.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\paradigms.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\pynutil.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rewrite.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rule_cascade.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\tagger.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\utf8.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\__init__.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\__init__.pyi -> build\lib.win-amd64-cpython-311\pynini
      copying pynini\py.typed -> build\lib.win-amd64-cpython-311\pynini
      copying pywrapfst\__init__.pyi -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\py.typed -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pynini\examples\py.typed -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\export\py.typed -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-311\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\extensions
      "d:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Id:\Users\Admin\anaconda3\envs\llm\include -Id:\Users\Admin\anaconda3\envs\llm\Include "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-311\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl: 鍛戒护琛\x8c error D8021 :鏃犳晥鐨勬暟鍊煎弬鏁扳\x80\x9c/Wno-register鈥\x9d
      error: command 'd:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
  Running setup.py clean for pynini
Failed to build pynini
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynini)
```

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

通过命令安装：pip install "xinference[all]"，应该是最新的版本。

### The command used to start Xinference / 用以启动 xinference 的命令

没有到启动那一步呢

### Reproduction / 复现过程

1. pip install "xinference[all]"
2.   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/fc/a3c13ded7b3057680c8ae95a9b6cc83e63657c38e0005c400a5d018a33a7/pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Requirement already satisfied: mdurl~=0.1 in d:\users\admin\anaconda3\envs\llm\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<0.12.0->xinference[all]) (0.1.2)
Building wheels for collected packages: pynini
  Building wheel for pynini (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pynini
      copying pynini\__init__.py -> build\lib.win-amd64-cpython-311\pynini
      creating build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\__init__.py -> build\lib.win-amd64-cpython-311\pywrapfst
      creating build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\case.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak_model.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\dates.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\g2p.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\numbers.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\plurals.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\t9.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\weather.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\__init__.py -> build\lib.win-amd64-cpython-311\pynini\examples
      creating build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\export.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\__init__.py -> build\lib.win-amd64-cpython-311\pynini\export
      creating build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\byte.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\edit_transducer.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\features.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\paradigms.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\pynutil.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rewrite.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rule_cascade.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\tagger.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\utf8.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\__init__.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\__init__.pyi -> build\lib.win-amd64-cpython-311\pynini
      copying pynini\py.typed -> build\lib.win-amd64-cpython-311\pynini
      copying pywrapfst\__init__.pyi -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\py.typed -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pynini\examples\py.typed -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\export\py.typed -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-311\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\extensions
      "d:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Id:\Users\Admin\anaconda3\envs\llm\include -Id:\Users\Admin\anaconda3\envs\llm\Include "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-311\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl: 鍛戒护琛\x8c error D8021 :鏃犳晥鐨勬暟鍊煎弬鏁扳\x80\x9c/Wno-register鈥\x9d
      error: command 'd:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
  Running setup.py clean for pynini
Failed to build pynini
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynini)

### Expected behavior / 期待表现

请问我该怎么办？

**Comment by qinxuye** [comment]
conda install -c conda-forge pynini=2.1.5

**Comment by jinsans** [comment]
请问我执行完conda install -c conda-forge pynini=2.1.5，然后再pip install "xinference[all]"，还是出错，什么原因呢

**Comment by jinsans** [comment]
> conda install -c conda-forge pynini=2.1.5

请问我执行完conda install -c conda-forge pynini=2.1.5，然后再pip install "xinference[all]"，还是出错，什么原因呢

**Comment by jinsans** [comment]
> conda install -c conda-forge pynini=2.1.5

请问我执行完conda install -c conda-forge pynini=2.1.5，然后再pip install "xinference[all]"，还是出现相同的错误，什么原因呢

**Comment by qinxuye** [comment]
等下本周的版本，有些依赖升级上去导致的。

**Comment by jinsans** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tsxuzhiqiang** [comment]
![image](https://github.com/user-attachments/assets/9db66a8b-49e4-4d2b-89a0-07ecee9b335d)

**Comment by Cupcc** [comment]
> > conda install -c conda-forge pynini=2.1.5
> 
> 请问我执行完conda install -c conda-forge pynini=2.1.5，然后再pip install "xinference[all]"，还是出现相同的错误，什么原因呢

降级xinference，不要按照最新版
