### ISSUE TITLE
Could not run qwen2-moe-instruct-gptq-Int4

### ISSUE THREAD

**Issue by wingtch** [xorbitsai/inference#2066]
### System Info / 系統信息

cuda Verssion: 12.4
Driver Version: 550.54.14
xinference version:  0.14.1

(xinference) root@awgiuivnvwsxlvnv-wind-5dc99c8c59-f6pzw:/data# pip list
Package                           Version
--------------------------------- ------------
accelerate                        0.33.0
aiobotocore                       2.7.0
aiofiles                          23.2.1
aiohappyeyeballs                  2.3.5
aiohttp                           3.10.1
aioitertools                      0.11.0
aioprometheus                     23.12.0
aiosignal                         1.3.1
altair                            5.3.0
annotated-types                   0.7.0
anyio                             4.4.0
async-timeout                     4.0.3
attrdict                          2.0.1
attrs                             24.2.0
auto_gptq                         0.7.1
autoawq                           0.2.5
autoawq_kernels                   0.0.6
bcrypt                            4.2.0
bitsandbytes                      0.43.3
botocore                          1.31.64
certifi                           2024.7.4
cffi                              1.17.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
cmake                             3.30.2
colorama                          0.4.6
coloredlogs                       15.0.1
contourpy                         1.2.1
cryptography                      43.0.0
cycler                            0.12.1
datasets                          2.20.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
ecdsa                             0.19.0
einops                            0.8.0
exceptiongroup                    1.2.2
fastapi                           0.110.3
ffmpy                             0.4.0
filelock                          3.15.4
fonttools                         4.53.1
frozenlist                        1.4.1
fsspec                            2023.10.0
gekko                             1.2.1
gradio                            4.26.0
gradio_client                     0.15.1
h11                               0.14.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.24.5
humanfriendly                     10.0
idna                              3.7
importlib_resources               6.4.0
interegular                       0.3.3
Jinja2                            3.1.4
jiter                             0.5.0
jmespath                          1.0.1
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.5
lark                              1.1.9
llvmlite                          0.43.0
lm-format-enforcer                0.10.3
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matplotlib                        3.9.1.post1
mdurl                             0.1.2
modelscope                        1.17.0
mpmath                            1.3.0
msgpack                           1.0.8
multidict                         6.0.5
multiprocess                      0.70.16
nest-asyncio                      1.6.0
networkx                          3.3
ninja                             1.11.1.1
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.555.43
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.20
nvidia-nvtx-cu12                  12.1.105
openai                            1.39.0
opencv-contrib-python             4.10.0.84
optimum                           1.21.3
orjson                            3.10.6
outlines                          0.0.46
packaging                         24.1
pandas                            2.2.2
passlib                           1.7.4
peft                              0.12.0
pillow                            10.4.0
pip                               24.0
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
protobuf                          5.27.3
psutil                            6.0.0
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.6.0
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.8.2
pydantic_core                     2.20.1
pydub                             0.25.1
Pygments                          2.18.0
pynvml                            11.5.3
pyparsing                         3.1.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-jose                       3.3.0
python-multipart                  0.0.9
pytz                              2024.1
PyYAML                            6.0.2
pyzmq                             26.1.0
quantile-python                   1.1
ray                               2.34.0
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
rich                              13.7.1
rouge                             1.0.1
rpds-py                           0.20.0
rsa                               4.9
ruff                              0.5.6
s3fs                              2023.10.0
safetensors                       0.4.4
scikit-learn                      1.5.1
scipy                             1.14.0
semantic-version                  2.10.0
sentence-transformers             3.0.1
sentencepiece                     0.2.0
setuptools                        72.1.0
shellingham                       1.5.4
six                               1.16.0
sniffio                           1.3.1
sse-starlette                     2.1.3
starlette                         0.37.2
sympy                             1.13.1
tabulate                          0.9.0
tblib                             3.0.0
threadpoolctl                     3.5.0
tiktoken                          0.7.0
timm                              1.0.8
tokenizers                        0.19.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.4.0
torchvision                       0.19.0
tqdm                              4.66.5
transformers                      4.43.4
transformers-stream-generator     0.0.5
triton                            3.0.0
typer                             0.11.1
typing_extensions                 4.12.2
tzdata                            2024.1
urllib3                           2.0.7
uvicorn                           0.30.5
uvloop                            0.19.0
vllm                              0.5.4
vllm-flash-attn                   2.6.1
watchfiles                        0.23.0
websockets                        11.0.3
wheel                             0.43.0
wrapt                             1.16.0
xformers                          0.0.27.post2
xinference                        0.14.0.post1
xoscar                            0.3.2
xxhash                            3.4.1
yarl                              1.9.4
zstandard                         0.23.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

#/bin/bash

export XINFERENCE_HOME=/data/xhome
XINFERENCE_MODEL_SRC=modelscope xinference-local -H 0.0.0.0 --port 9997 --log-level=debug 1>runlog.log 2>&1 &

### Reproduction / 复现过程

1. Access xinference instance home page
2. Launch model > qwen2-moe-instruct
3. Model engine: vllm;  Model format: gptq; Model size: 14; Quantization: Int4; N-GPU: auto; Replica: 1
4. Press Launch
5. Got error loading the model. Please refer to log file.
[xinference.log.txt](https://github.com/user-attachments/files/16577085/xinference.log.txt)

### Expected behavior / 期待表现

Sucessfully load the model if GRAM capacity is OK, otherwise prompts error about OOM.

**Comment by qinxuye** [comment]
vllm does not support this model yet

**Comment by wingtch** [comment]
Ok, closing the issue.
