### ISSUE TITLE
[feature request] MiniCPM-2B-sft-bf16 support vllm inference

### ISSUE THREAD

**Issue by bao21987** [xorbitsai/inference#2070]
### Feature request / 功能建议

MiniCPM-2B-sft-bf16 not support vllm in xinference.
It's actually support vllm officially:
https://github.com/OpenBMB/MiniCPM/blob/main/inference/inference_vllm.py
and
https://docs.vllm.ai/en/latest/models/supported_models.html

### Motivation / 动机

please add vllm support for MiniCPM-2B-sft-bf16, openbmb/MiniCPM-2B-dpo-bf16,  etc.

### Your contribution / 您的贡献

NA

**Comment by qinxuye** [comment]
OK, we will support it ASAP.
