### ISSUE TITLE
希望SenseVoiceSmall支持传入额外的参数

### ISSUE THREAD

**Issue by leslie2046** [xorbitsai/inference#2075]
### Feature request / 功能建议

vad_model：表示开启 VAD，VAD 的作用是将长音频切割成短音频，此时推理耗时包括了 VAD 与 SenseVoice 总耗时，为链路耗时，如果需要单独测试 SenseVoice 模型耗时，可以关闭 VAD 模型。
vad_kwargs：表示 VAD 模型配置，max_single_segment_time: 表示 vad_model 最大切割音频时长，单位是毫秒 ms。
use_itn：输出结果中是否包含标点与逆文本正则化。
batch_size_s 表示采用动态 batch，batch 中总音频时长，单位为秒 s。
merge_vad：是否将 vad 模型切割的短音频碎片合成，合并后长度为 merge_length_s，单位为秒 s。
ban_emo_unk：禁用 emo_unk 标签，禁用后所有的句子都会被赋与情感标签。默认 False

### Motivation / 动机

需要测试性能指标时需要可以传入参数来决定是否开启VAD或者是否逆文本正则输出。

### Your contribution / 您的贡献

None

**Comment by qinxuye** [comment]
launch 加一些参数试下  

xinference launch xxx --vad_model xxx

vad_kwargs 会比较麻烦，其他的值是字符串的可以看下行不行。

**Comment by leslie2046** [comment]
@qinxuye 好的，我先试试

**Comment by leslie2046** [comment]
xinference launch --model-name SenseVoiceSmall --model-type audio --use_itn false
这样启动后，024-08-26 08:38:11,635 xinference.model.audio.funasr 64129 DEBUG    Loading FunASR model with kwargs: {'vad_model': 'fsmn-vad', 'vad_kwargs': {'max_single_segment_time': 30000}, 'use_itn': False}
但是调用SenseVoiceSmall还是
2024-08-26 08:39:05,328 xinference.model.audio.funasr 64129 DEBUG    Calling FunASR model with kwargs: {'use_itn': True, 'batch_size_s': 60, 'merge_vad': True, 'merge_length_s': 15}
