### ISSUE TITLE
gte-Qwen2没有支持fp16推理

### ISSUE THREAD

**Issue by Zzzz1111** [xorbitsai/inference#2076]
### System Info / 系統信息

python 3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference=0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1. 调整config.json 
![image](https://github.com/user-attachments/assets/86faef64-f75c-4f8d-8288-3b585737b6bc)
2. 运行模型
3. 显存占用和之前一样
![image](https://github.com/user-attachments/assets/87e2c56b-9dbc-4c55-bce0-4cc60e330a5e)

### Expected behavior / 期待表现

显存减少
![image](https://github.com/user-attachments/assets/b4687e18-f2d9-4dc2-9920-f9627d72557e)
![image](https://github.com/user-attachments/assets/097d1979-8d8b-4883-a1b1-44f186f2e899)
已经在本地修改，希望提交该修改

**Comment by qinxuye** [comment]
量化还未支持。后续我们看下。

**Comment by Zzzz1111** [comment]
gte-Qwen2 直接支持f使用fp16推理，不需要进行额外的量化操作 
![image](https://github.com/user-attachments/assets/e5d29f71-e65a-46d0-92b0-fe4ec226870f)

**Comment by qinxuye** [comment]
如何调用？

**Comment by Zzzz1111** [comment]
直接修改模型配置config.json就可以调用，然后修改xinference/model/embedding/core.py
![image](https://github.com/user-attachments/assets/77f79f0f-9fcf-40c1-a00c-57596c5ef937)
可以实现支持fp16推理

**Comment by qinxuye** [comment]
改 config.json 是不是有点麻烦，是不是不用改直接把 torch_dtype 传 float16 就行了？

**Comment by Zzzz1111** [comment]
可以的，我是因为使用了本地模型所以修改了config.json


---- 回复的原邮件 ----
| 发件人 | Xuye (Chris) ***@***.***> |
| 日期 | 2024年08月13日 18:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xorbitsai/inference] gte-Qwen2没有支持fp16推理 (Issue #2076) |

改 config.json 是不是有点麻烦，是不是不用改直接把 torch_dtype 传 float16 就行了？

**Comment by qinxuye** [comment]
那照理说其实就是能支持额外参数能传 --torch_dtype float16 把

**Comment by Zzzz1111** [comment]
是的



---- 回复的原邮件 ----
| 发件人 | Xuye (Chris) ***@***.***> |
| 日期 | 2024年08月13日 18:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xorbitsai/inference] gte-Qwen2没有支持fp16推理 (Issue #2076) |

那照理说其实就是能支持额外参数能传 --torch_dtype float16 把

**Comment by Zzzz1111** [comment]
ok，有兴趣的
---- 回复的原邮件 ----
| 发件人 | Xuye (Chris) ***@***.***> |
| 日期 | 2024年08月13日 18:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xorbitsai/inference] gte-Qwen2没有支持fp16推理 (Issue #2076) |

OK，实际上模型的 **kwargs 应该会被传过来的，相信不需要做多少代码改动。有兴趣来贡献吗：）

**Comment by Zzzz1111** [comment]
> OK，实际上模型的 **kwargs 应该会被传过来的，相信不需要做多少代码改动。有兴趣来贡献吗：）
xinference launch --model_path /model/gte_Qwen2-7B-instruct -t embedding -n  gte-Qwen2 --torch_dtype float32
![image](https://github.com/user-attachments/assets/5540f648-7f91-4ebd-8fcb-d5bac4232d6f)
尝试将torch_type 放入kwargs中，运行模型后出现该错误，是有哪些地方没有修改么？

![image](https://github.com/user-attachments/assets/607c4a94-e943-418c-bdd1-c0a29bba2a27)
![image](https://github.com/user-attachments/assets/33bc20c5-9876-41dc-bb3d-d6b755006eaf)

**Comment by qinxuye** [comment]
看样子需要修改 EmbeddingModel，让他支持传入 **kwargs，然后把 **kwargs 的值送给对应的类初始化，应该就能支持 torch_dtype。做下相应想改，试验下，可以的话发个 PR？
