### ISSUE TITLE
Llama 3.1 405B fp16 Support in Distributed Mode

### ISSUE THREAD

**Issue by allenzhangtju** [xorbitsai/inference#2077]
### Feature request / 功能建议

I would like to deploy Llama 3.1 405B fp16 (>640GB but <640GB x2) in distributed mode using two servers with 8x80GB GPUs each. However, even with distributed mode, it seems that I still have to place the model file on a single worker, which overwhelms the GPU memory of one server instead of **evenly distributing it across the memory of both workers**. Is there a way to **evenly or controllably distribute** a single replica across multiple workers when deploying such a large model for inference? If this is already an existing feature, please let me know how to do it. Thank you.

![image](https://github.com/user-attachments/assets/30a608b6-f192-46de-832a-2bcee583660f)

### Motivation / 动机

To support Llama 3.1 405B fp16 inference in distributed mode.

### Your contribution / 您的贡献

N/A

**Comment by qinxuye** [comment]
We are working on this feature.

**Comment by allenzhangtju** [comment]
Hi. Any update on this feature?

**Comment by allenzhangtju** [comment]
need cross-node distributed support again for deepseek v3/r1
