### ISSUE TITLE
to support `Qwen2-Audio` model

### ISSUE THREAD

**Issue by jaffe-fly** [xorbitsai/inference#2090]
### Feature request / 功能建议

Qwen2-Audio, which is capable of accepting audio and text inputs and generating text outputs. Qwen2-Audio has the following features:

- Voice Chat: for the first time, users can use the voice to give instructions to the audio-language model without ASR modules.

- Audio Analysis: the model is capable of analyzing audio information, including speech, sound, music, etc., with text instructions.

- Multilingual: the model supports more than 8 languages and dialects, e.g., Chinese, English, Cantonese, French, Italian, Spanish, German, and Japanese.

### Motivation / 动机

for more users to interact with Qwen2-Audio

### Your contribution / 您的贡献

https://qwenlm.github.io/blog/qwen2-audio/

**Comment by qinxuye** [comment]
Thanks, we will support it ASAP.
