### ISSUE TITLE
cosyvoice 基于指令的声音合成报错 TypeError: speech() got an unexpected keyword argument 'instruct_text'

### ISSUE THREAD

**Issue by reinforceli** [xorbitsai/inference#2091]
### System Info / 系統信息

服务端：python310, torch2.3.1+cu121, windows10
客户端使用python38调用 xinference-client

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference-client-0.14.1.post1
xinference  0.14.1.post1

### The command used to start Xinference / 用以启动 xinference 的命令

单节点启动
xinference-local

### Reproduction / 复现过程

基于手册指引测试
![image](https://github.com/user-attachments/assets/b938e3bc-5622-43de-aa9c-c75692bb6a85)
![image](https://github.com/user-attachments/assets/6d2ccd10-9e0d-4577-9a59-8da1fb78c43b)
![image](https://github.com/user-attachments/assets/13054297-b297-4655-9f42-0d14c8a8936a)

### Expected behavior / 期待表现

运行要正常

**Comment by qinxuye** [comment]
@codingl2k1 Can you help to look at this issue?

**Comment by reinforceli** [comment]
是我客户端xinference-client问题，我尝试用python310,安装就可以了，没报错
