### ISSUE TITLE
Which api is imagetotext for vision models?

### ISSUE THREAD

**Issue by jiusi9** [xorbitsai/inference#2092]
### System Info / 系統信息

python 3.8
cunda 12
xinference 0.14.0

Model: **MiniCPM-Llama3-V-2_5**
Could you tell me that which api I should use?

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -h 0.0.0.0

### Reproduction / 复现过程

Did not found api about image to text.

### Expected behavior / 期待表现

Could you tell me that which api I should use?

**Comment by qinxuye** [comment]
Refer to https://inference.readthedocs.io/en/latest/models/model_abilities/vision.html#vision .
