### ISSUE TITLE
启动模型replica参数貌似只能部署到不同卡上，replica大于卡数将会报错

### ISSUE THREAD

**Issue by mote0302** [xorbitsai/inference#2093]
### System Info / 系統信息

ubuntu 22.04
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
 NVIDIA-SMI 550.54.14              Driver Version: 550.67         CUDA Version: 12.4 
 A100 40G * 3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.14.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

# 部署xinference
version: '3'
services:
  xinfernece:
    image: "xprobe/xinference:latest"
    container_name: "xinference"
    restart: "always"
    ports:
      - "28251:9997"
    volumes:
      - "/home/xinference/cache:/root/.cache"
      - "/home/xinference/models:/root/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "2"
              capabilities: ["gpu"]
    command: "xinference-local -H 0.0.0.0 --log-level debug"

只挂了两张卡上去

### Reproduction / 复现过程

注册自定义模型
运行时参数replica填写3
gpu_memory_utilization 0.25

启动会报Server error: 503 - [address=0.0.0.0:13163, pid=118] No available slot found for the model

### Expected behavior / 期待表现

针对于小参数模型，在gpu资源充足情况下，应允许多实例运行在一张卡上

**Comment by mote0302** [comment]
我注册的模型是qwen2 7b 也试过qwen2 1.8b 也是只能一张卡上跑一个实例

**Comment by qinxuye** [comment]
需要我们先支持单卡多模型，这个正在开发。

**Comment by ruifengma** [comment]
> 需要我们先支持单卡多模型，这个正在开发。

这个大概什么时候会上
