### ISSUE TITLE
cosyvoice 300m instruct model lauch error  get tokenizer()got an unexpected keyword argument 'num_languages'

### ISSUE THREAD

**Issue by chenfolingithub** [xorbitsai/inference#2095]
### System Info / 系統信息

cuda 12.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.1.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local

### Reproduction / 复现过程

lauch cosyvoice 300m instruct
download from huggingface
File
"/root/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py",line 300,in load
self. model.load()
File
"/root/miniconda3/envs/xinference/lib/python3.10/site-pa
ckages/xinference/model/audio/cosyvoice.py",line 50,in
load
self. model=CosyVoice(self. model path)
File
"/root/miniconda3/envs/xinference/lib/python3.10/site-pa
ckages/xinference/model/audio/../../thirdparty/cosyvoice
/cli/cosyvoice.py",line 30,ininit
self.frontend=
CosyVoiceFrontEnd(configs['get tokenizer'],
File
/root/miniconda3/envs/xinference/lib/python3.10/site-pa
ckages/xinference/model/audio/../../thirdparty/cosyvoice
/cli/frontend.py",line 46,ininit
self.tokenizer =get tokenizer()
TypeError:[address=0.0.0.0:45995，pid-9980]
get tokenizer()got an unexpected keyword argument
'num_languages'

### Expected behavior / 期待表现

正常使用

**Comment by qinxuye** [comment]
```
pip install --no-deps 'openai-whisper== v20231117'
```

**Comment by orangeclk** [comment]
I'm using Docker and I also encountered this issue. How can I make it work?

**Comment by qinxuye** [comment]
> I'm using Docker and I also encountered this issue. How can I make it work?

In the docker you can run `pip install --no-deps 'openai-whisper==v20231117'`.
