### ISSUE TITLE
是不是没有生成图片后用来请求图片数据的API

### ISSUE THREAD

**Issue by Valdanitooooo** [xorbitsai/inference#2098]
看文档里只是返回了图片的文件路径
https://inference.readthedocs.io/en/latest/user_guide/client_api.html#id4

现在是不是没有API用来请求图片数据
有必要在 xinference 里加这个 API 吗
还是拆开来处理更合理，跑个代理服务提供访问图片的功能

**Comment by qinxuye** [comment]
可以传 response_format='b64_json'，会返回 base64 编码的图片。
