### ISSUE TITLE
在Transformers下以8-bit无法启动qwen2模型

### ISSUE THREAD

**Issue by ZCravenQ** [xorbitsai/inference#2099]
### System Info / 系統信息

cuda=12.6.41 transformers=4.43.4 python version=3.10 Windows 10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference=0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 127.0.0.1 --port 9997

### Reproduction / 复现过程

1.以xinference-local --host 127.0.0.1 --port 9997 启动xinference，在9997端口上用ui界面交互
2.在启动qwen2-instruct模型时勾选参数Moedel Engine =Transformers、Model Format=pytorch、Model Size=7、Quantization=8-bit、N-GPU=auto、Replica=1
3.在命令行得到报错KeyError: [address=127.0.0.1:60735, pid=10304] 'model.embed_tokens.weight'

### Expected behavior / 期待表现

期望能得到如何解决这个问题的方案

**Comment by ZCravenQ** [comment]
已解决：方案如下
在你的anaconda虚拟环境中找到\Lib\site-packages\xinference\model\llm\pytorch文件夹，在内找到compression.py文件。
找到其中第135行，修改为
base_pattern = os.path.join(model_path, "pytorch_model*.bin","pytorch_model*.safetensors")
找到其中第139行，修改为
base_pattern = os.path.join(model_path, "pytorch_model*.bin","pytorch_model*.safetensors")
问题即可解决

**Comment by qinxuye** [comment]
修改前后写的一样的啊

**Comment by ZCravenQ** [comment]
> 修改前后写的一样的啊

修改前只有.bin的部分吧，我是在后边加上了“pytorch_model*.safetensors”
或者是我没有更新到最新版本的问题？

**Comment by ZCravenQ** [comment]
> > 修改前后写的一样的啊
> 
> 修改前只有.bin的部分吧，我是在后边加上了“pytorch_model*.safetensors” 或者是我没有更新到最新版本的问题？

怪事 我再复现就又报错了 我再去看看
