### ISSUE TITLE
未设置密码，访问会显示登录界面

### ISSUE THREAD

**Issue by YSblack** [xorbitsai/inference#2100]
### System Info / 系統信息

docker

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

所有版本都有，14 和14.1

### The command used to start Xinference / 用以启动 xinference 的命令

docekr

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/9a2b3b32-9b13-4b96-976a-12431d5d9d0b)
第一次访问正常，后面再访问就需要账号密码，界面是闪动状态

网站放到无痕浏览器又正常

### Expected behavior / 期待表现

麻烦修复一下

**Comment by YSblack** [comment]
https://github.com/user-attachments/assets/c62e7c56-da73-4484-98f5-991cd513047b

**Comment by qinxuye** [comment]
应该被 #2039 修复了，试验下 0.14.2 是否解决。
