### ISSUE TITLE
Dash-infer support maybe?

### ISSUE THREAD

**Issue by ZB052-A** [xorbitsai/inference#2107]
### Feature request / 功能建议

Is there a subsequent version that can support the Dash-infer inference framework?

### Motivation / 动机

I feel that the Dash-infer inference framework can get better performance than llama.cpp inference frameworks, but compatibility can be a bottleneck.
[https://github.com/modelscope/dash-infer](url)

**Comment by qinxuye** [comment]
PR welcomed for this feature.
