### ISSUE TITLE
benchmark异步并行测试报错

### ISSUE THREAD

**Issue by zhangyanbo2007** [xorbitsai/inference#2111]
### System Info / 系統信息

内部使用引擎：vllm==0.5.3.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

部署框架：xinference==0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

python benchmark/benchmark_serving.py --dataset xinference_project/data/ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer /data/public/hub_repository/modelscope/hub/qwen/Qwen2-72B-Instruct  --num-prompt 100 --model-uid qwen--Qwen2-72B-Instruct --concurrency 50  --port 9999

### Reproduction / 复现过程

执行：
python benchmark/benchmark_serving.py --dataset xinference_project/data/ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer /data/public/hub_repository/modelscope/hub/qwen/Qwen2-72B-Instruct  --num-prompt 100 --model-uid qwen--Qwen2-72B-Instruct --concurrency 50  --port 9999
结果：
python benchmark/benchmark_serving.py --dataset xinference_project/data/ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer /data/public/hub_repository/modelscope/hub/qwen/Qwen2-72B-Instruct  --num-prompt 100 --model-uid qwen--Qwen2-72B-Instruct --concurrency 50
Namespace(host='localhost', port=9997, dataset='xinference_project/data/ShareGPT_V3_unfiltered_cleaned_split.json', tokenizer='/data/public/hub_repository/modelscope/hub/qwen/Qwen2-72B-Instruct', num_prompts=100, prompt_len_limit=1024, concurrency=50, request_rate=inf, seed=0, trust_remote_code=False, model_uid='qwen--Qwen2-72B-Instruct')
INFO:__main__:Preparing for benchmark.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Token indices sequence length is longer than the specified maximum sequence length for this model (221043 > 131072). Running this sequence through the model will result in indexing errors
INFO:__main__:Benchmark starts.
Traceback (most recent call last):
  File "/code/project/tras/tras-atomictech/inference_framework/xinference/benchmark/benchmark_serving.py", line 183, in <module>
    main(args)
  File "/code/project/tras/tras-atomictech/inference_framework/xinference/benchmark/benchmark_serving.py", line 115, in main
    asyncio.run(benchmark.run())
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/code/project/tras/tras-atomictech/inference_framework/xinference/benchmark/benchmark_serving.py", line 64, in run
    await self.queue.put(req)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/asyncio/queues.py", line 128, in put
    await putter
RuntimeError: Task <Task pending name='Task-1' coro=<BenchmarkRunner.run() running at /code/project/tras/tras-atomictech/inference_framework/xinference/benchmark/benchmark_serving.py:64> cb=[_run_until_complete_cb() at /root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop

### Expected behavior / 期待表现

输出正常的指标结果

**Comment by qinxuye** [comment]
@Dawnfz-Lenfeng 有时间看下这个问题吗？

**Comment by Dawnfz-Lenfeng** [comment]
> @Dawnfz-Lenfeng 有时间看下这个问题吗？

了解了，大概是异步队列的问题，更改异步队列初始化时机应该就能行了https://github.com/xorbitsai/inference/blob/9804c550f2eaaf2d1756c53596a54953955ec0f8/benchmark/benchmark_serving.py#L51
这一行放在 `warm_up()` 中

**Comment by qinxuye** [comment]
@Dawnfz-Lenfeng 要不发个 PR 修复下？

**Comment by Dawnfz-Lenfeng** [comment]
> @Dawnfz-Lenfeng 要不发个 PR 修复下？

已提 https://github.com/xorbitsai/inference/pull/2113
