### ISSUE TITLE
Xinference 推理时间性能与CPU推理相差不大

### ISSUE THREAD

**Issue by huangjun11** [xorbitsai/inference#2112]
### System Info / 系統信息

Python3.10  ， CUDA12.4，Ubuntu

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.14.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference launch --model-name bce-embedding-base --model-type embedding

### Reproduction / 复现过程

1.启动Embedding模型；
2.运行接口调用脚本；

### Expected behavior / 期待表现

经过测试，发现使用Xinference 部署推理bce-embedding模型时，耗时与CPU推理相差不大，大概都为500ms左右，且调用模型时，GPU负载最多为4%，大部分时候为0，是不是没有调起来GPU。

**Comment by qinxuye** [comment]
python -c "import torch; print(torch.cuda.device_count())" 看下是否大于0

**Comment by huangjun11** [comment]
> python -c "import torch; print(torch.cuda.device_count())" 看下是否大于0
(/data/conda-envs/embedding) szzt@dev-gpu-rtx4090-8:/data/huangjun/xinference_test$ python -c "import torch; print(torch.cuda.device_count())"
8
结果为8

**Comment by huangjun11** [comment]
能不能解决一下呀

**Comment by cauwulixuan** [comment]
发现同样的问题，GPU没有效利用
