### ISSUE TITLE
官方容器启动sglang时报错flashinfer版本太低

### ISSUE THREAD

**Issue by 315930399** [xorbitsai/inference#2115]
### System Info / 系統信息

0.14.1, 0.14.2均遇到该问题
![微信图片_20240819172858](https://github.com/user-attachments/assets/1184dcab-86b3-44fa-aa51-76204c2e9371)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.1, 0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

launch时报错

### Reproduction / 复现过程

launch模型时指定engine为sglang

### Expected behavior / 期待表现

正常启动模型

**Comment by 948024326** [comment]
请问解决了吗？
