### ISSUE TITLE
增加多case request请求前缀kv-cache加速机制

### ISSUE THREAD

**Issue by zhangyanbo2007** [xorbitsai/inference#2117]
### Feature request / 功能建议

xinference部署内置了vllm引擎，其内置kv-cache加速机制，在单case request请求中起到了编码加速作用，除了这种单case request编码加速机制，还可以针对不同case request请求相同的前缀通过配置enable_prefix_caching=True进行编码加速，这在多轮对话场景以及长prompt前缀输入的场景（比如RAG生成的prompt前缀，特别图谱RAG生成的prompt前缀特别长）将大大节省成本并且提高推理速度，相关的应用案例如下：
1. [DeepSeek API 创新采用硬盘缓存，价格再降一个数量级](https://mp.weixin.qq.com/s/zPz8U-F8PAovhG-FbAOzLA)
2. [上下文缓存定价与计费](https://platform.moonshot.cn/docs/pricing/caching#%E4%BA%A7%E5%93%81%E5%AE%9A%E4%BB%B7)
目前的enable_prefix_caching=True ，其对应的kv-cache缓存每次用户访问都会累计缓存，这对于同一个用户连续多轮对话，或者连续RAG问答的情况，后续的对话是会起到明显加速效果的，但是如果不同用户以不同的prompt前缀频繁访问服务可能存在爆显存的风险，如果用户想存储特定前缀的KV-cache，可以参考KIMI官方的上下文缓存机制。看这块儿怎么进一步优化集成！

### Motivation / 动机

多轮对话场景以及长prompt前缀输入的场景（比如RAG生成的prompt前缀，特别图谱RAG生成的prompt前缀特别长）将大大节省成本并且提高推理速度

### Your contribution / 您的贡献

我的贡献是提出该问题，还望做一下优化！

**Comment by bao21987** [comment]
部署时添加vllm参数 --enable_prefix_caching=True 是不是就可以了

**Comment by zhangyanbo2007** [comment]
> 部署时添加vllm参数 --enable_prefix_caching=True 是不是就可以了

它这个每次新的请求过来覆盖之前保存的prompt前缀KV-cache信息，需要参考类似kimi的机制做个指定prompt前缀有选择性的缓存。
