### ISSUE TITLE
向语音模型发送请求

### ISSUE THREAD

**Issue by XiaoTongDeng** [xorbitsai/inference#2118]
### System Info / 系統信息

如何通过openai client向xinference拉起的Belle-whisper-large-v3-zh发送请求，Belle-whisper-large-v3-zh接收哪些参数呢

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.12.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference -p 9997

### Reproduction / 复现过程

.

### Expected behavior / 期待表现

希望给出发送请求的demo，或者告诉我向语音模型发送请求携带的参数是什么

**Comment by qinxuye** [comment]
openai client 参考 OpenAI 的官网。
