### ISSUE TITLE
仍然可复现

### ISSUE THREAD

**Issue by Alex-Zuo-One** [xorbitsai/inference#2121]
### System Info / 系統信息

#2074  
仍然可复现

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

如上

### Reproduction / 复现过程

如上

### Expected behavior / 期待表现

正常调用

**Comment by qinxuye** [comment]
Reopen 之前的 issue，没必要重新开一个。
