### ISSUE TITLE
How do I use PyTorch to register a model, and then find that there is no quantization option when I start it up?

### ISSUE THREAD

**Issue by PolarPeak** [xorbitsai/inference#2123]
### System Info / 系統信息

I remember that I could choose quantization when I started it up before. Is it necessary to select quantization during the training and export process since my model is trained locally?

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

14.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-loca -h 0.0.0.0

### Reproduction / 复现过程

I remember that I could choose quantization when I started it up before. Is it necessary to select quantization during the training and export process since my model is trained locally?

### Expected behavior / 期待表现

After registering the model in PyTorch, can I choose quantization when starting up?

**Comment by jackleeforce** [comment]
same issue for me .

**Comment by PolarPeak** [comment]
> same issue for me .

You can use the corresponding model in the launch model, and then fill in the path of your own model in the model path of the optional configuration.
