### ISSUE TITLE
xinference经常丢失模型

### ISSUE THREAD

**Issue by sdytzjp** [xorbitsai/inference#2128]
### System Info / 系統信息

(base) [root@gpu cache]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
(base) [root@gpu cache]# uname -r
3.10.0-1160.el7.x86_64

NVIDIA-SMI 535.183.06
 Driver Version: 535.183.06   CUDA Version: 12.2   
NVIDIA A30

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -H 0.0.0.0

### Reproduction / 复现过程

xinference重启后模型丢失，需要重新下载

### Expected behavior / 期待表现

1、UI界面不要丢失模型
2、之前已经下载的模型，能够加载出来

**Comment by qinxuye** [comment]
下载的模型是 cached，你可以在 launch 里过滤，只有加载的模型才是 running 的。

**Comment by qinxuye** [comment]
上面load config 叉掉试下，这是前端bug已经修复了。

**Comment by 13725102796** [comment]
@goactiongo 怎么解决的，我现在叉掉last config也不行，还是会出现丢失模型的现象 docker日志是提示 Worker dead. address: 0.0.0.0:39400, influenced models: [] 先是这样，然后出现模型丢失。webUi 里面的Running Models也不见了

**Comment by Kenwwww** [comment]
> [@goactiongo](https://github.com/goactiongo) 怎么解决的，我现在叉掉last config也不行，还是会出现丢失模型的现象 docker日志是提示 Worker dead. address: 0.0.0.0:39400, influenced models: [] 先是这样，然后出现模型丢失。webUi 里面的Running Models也不见了

 我也是这个问题，长时间部署后就会报错worker dead，现在解决了吗？
