### ISSUE TITLE
加载lora glm4-chat 没按微调的模型回答

### ISSUE THREAD

**Issue by reinforceli** [xorbitsai/inference#2132]
### System Info / 系統信息

python310, torch2.3.1+cu121, windows10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Xinference-v0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local 单节点 

### Reproduction / 复现过程

https://github.com/THUDM/GLM-4/tree/main/finetune_demo
我按glm4官方微调成功后，调官方的脚本能按我训练的数据回答
![image](https://github.com/user-attachments/assets/e285fa64-32f1-461d-ac90-68d8fc30e7db)
但在xinference就没调用lora来回答
已确认模型启动有配置加载lora,
![image](https://github.com/user-attachments/assets/e550109f-f29b-42fd-9030-07cc6c00390b)
回答时也有选lora
![image](https://github.com/user-attachments/assets/c39a41ca-f226-4836-ad8d-b34ed05800ff)

### Expected behavior / 期待表现

能按lora训练的内容回答

**Comment by qinxuye** [comment]
用的哪个引擎？

**Comment by reinforceli** [comment]
1。在glm4微调和测试时用的是 transformers-4.44.0
2。xinference用的是  transformers-4.42.4

**Comment by reinforceli** [comment]
在xinference项目中用 transformers 4.42  4.43 4.44 都不生效。
在官方中的  transformers-4.44.0 是成功的，估计跟transformers版本无关

**Comment by reinforceli** [comment]
@qinxuye 大佬，知道是什么问题吗？

**Comment by qinxuye** [comment]
> @qinxuye 大佬，知道是什么问题吗？

lora加载成功了吗

**Comment by reinforceli** [comment]
要怎么看加载有无成功？
![image](https://github.com/user-attachments/assets/b8d427d0-b0fd-480e-b70e-88a6f43f63a6)
我启动是成功的，模型也可回答，但没按微调的回答。

**Comment by reinforceli** [comment]
![image](https://github.com/user-attachments/assets/e3d182cb-6c28-4433-9946-2e64f06c4a68)
glm官方微调后的测试脚本可按微调后的回答

**Comment by qinxuye** [comment]
有没有微调的权重能供我们测试下？

**Comment by reinforceli** [comment]
权重是什么不太懂

训练环境：
python3.10, transformers-4.44.0,windows10,torch 2.4.0+cu121，无安装deepspeed模块，

单机单卡训练，训练命令：
python finetune.py  data\fzd  D:\xinferencemodel\modelscope\hub\ZhipuAI\glm-4-9b-chat  configs/lora.yaml


这是我微调的参数配置，其它的配置文件都是按默认：
#lora.yaml
data_config:
  train_file: train.jsonl
  val_file: dev.jsonl
  test_file: dev.jsonl
  num_proc: 1

combine: True
max_input_length: 512
max_output_length: 512

training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 3000
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 8
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 500
  # settings for logging
  log_level: debug
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 8
  eval_strategy: steps
  eval_steps: 500
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 512
  # set your absolute deepspeed path here
    deepspeed: configs/ds_zero_3.json
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["query_key_value"]

**Comment by qinxuye** [comment]
或者说有没有说放出来了这个 lora 在 modelscope 或者 huggingface 上，我们能下载试下。

**Comment by reinforceli** [comment]
https://www.modelscope.cn/models/reinforce/glm4loartest/files
这个微调模型，可输入”分之道介绍“做测试

**Comment by reinforceli** [comment]
@qinxuye 已提供了微调的lora,帮忙分析下

**Comment by qinxuye** [comment]
应该已经修复了，可以再测试下。
