### ISSUE TITLE
MiniCPM v2.6 支持并發

### ISSUE THREAD

**Issue by HSIAOKUOWEI** [xorbitsai/inference#2135]
### Feature request / 功能建议

![image](https://github.com/user-attachments/assets/ed1f988d-b987-4c46-b289-c2ceac0136b1)

### Motivation / 动机

![image](https://github.com/user-attachments/assets/0e503276-bcd3-4ce4-bb4d-a497c8b6b01e)

### Your contribution / 您的贡献

![image](https://github.com/user-attachments/assets/955ef801-a70d-44bc-938b-0d16abdbaeee)

**Comment by ChengjieLi28** [comment]
take
