### ISSUE TITLE
自定义的rerank模型gte_Qwen2-1.5B-instruct，在接口调用时，输入参数不匹配

### ISSUE THREAD

**Issue by XinyeDu77** [xorbitsai/inference#2136]
### System Info / 系統信息

linux

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

使用pip install "xinference[transformers]"下载的xinference

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_DISABLE_HEALTH_CHECK=1 xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

在postman中输入参数：
{
  "model": "gte_Qwen2-1.5B-instruct",
  "query": "What is Deep Learning?",
  "documents": [
    "Deep Learning is ...",
    "oh"
  ]
}

报错：
{
	"detail": "[address=0.0.0.0:34081, pid=57017] Cannot handle batch sizes > 1 if no padding token is defined."
}

### Expected behavior / 期待表现

能够使用自定义rerank模型

**Comment by qaqrt** [comment]
遇到了同样的问题，请问解决了吗
