### ISSUE TITLE
910B部署，加载模型报错

### ISSUE THREAD

**Issue by zhangliangrr** [xorbitsai/inference#2142]
### System Info / 系統信息

910B部署
python3.10
依赖：
accelerate                0.33.0
aiofiles                  23.2.1
aioprometheus             23.12.0
altair                    5.4.0
annotated-types           0.7.0
anyio                     4.4.0
async-timeout             4.0.3
attrs                     24.2.0
auto-tune                 0.1.0
bcrypt                    4.2.0
certifi                   2024.7.4
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
contourpy                 1.2.1
cryptography              43.0.0
cycler                    0.12.1
dataflow                  0.0.1
decorator                 5.1.1
distro                    1.9.0
ecdsa                     0.19.0
exceptiongroup            1.2.2
fastapi                   0.110.3
ffmpy                     0.4.0
filelock                  3.15.4
fonttools                 4.53.1
fsspec                    2024.6.1
gradio                    4.26.0
gradio_client             0.15.1
h11                       0.14.0
hccl                      0.1.0
hccl-parser               0.1
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.24.6
idna                      3.7
importlib_resources       6.4.4
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
modelscope                1.17.1
mpmath                    1.3.0
msadvisor                 1.0.0
narwhals                  1.5.2
networkx                  3.3
numpy                     1.26.4
op-compile-tool           0.1.0
op-gen                    0.1
op-test-frame             0.1
opc-tool                  0.1.0
openai                    1.39.0
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.2
passlib                   1.7.4
peft                      0.12.0
pillow                    10.4.0
pip                       24.2
psutil                    6.0.0
pyasn1                    0.6.0
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.3
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-jose               3.3.0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.2
quantile-python           1.1
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.20.0
rsa                       4.9
ruff                      0.6.1
safetensors               0.4.4
schedule-search           0.0.1
scipy                     1.14.1
semantic-version          2.10.0
setuptools                72.1.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
sse-starlette             2.1.3
starlette                 0.37.2
sympy                     1.13.2
tabulate                  0.9.0
tblib                     3.0.0
te                        0.4.0
timm                      1.0.8
tokenizers                0.19.1
tomlkit                   0.12.0
torch                     2.1.0
torch-npu                 2.1.0.post3
torchvision               0.16.0
tqdm                      4.66.5
transformers              4.44.1
typer                     0.11.1
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.30.6
uvloop                    0.20.0
websockets                11.0.3
wheel                     0.43.0
xinference                0.14.2
xoscar                    0.3.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference:0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

(x1) root@dl-ac05a4c2d22135ada2a24db28592332d-r0-e2f03755cdff-0:~/work/filestorage/zhangliang/xinference# xinference list
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/.local/conda/envs/x1/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/.local/conda/envs/x1/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/.local/conda/envs/x1/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 943, in model_list
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
  File "/root/.local/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 788, in __init__
    self._check_cluster_authenticated()
  File "/root/.local/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 813, in _check_cluster_authenticated
    f"Failed to get cluster information, detail: {response.json()['detail']}"
  File "/root/.local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Expected behavior / 期待表现

可以正常加载运行模型

**Comment by qinxuye** [comment]
这个是因为代理，检查下机器上的代理并关闭。
