### ISSUE TITLE
Xinference不支持llama3.1的tools_call和function_call

### ISSUE THREAD

**Issue by yebanliuying** [xorbitsai/inference#2146]
### System Info / 系統信息

llama3.1
Xinference v0.14.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

  raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': "Only ['gorilla-openfunctions-v1', 'qwen-chat', 'qwen1.5-chat', 'qwen1.5-moe-chat', 'qwen2-instruct', 'qwen2-moe-instruct', 'glm4-chat', 'glm4-chat-1m'] support tool calls"}

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

运行langgreph的多agent例子就不行

### Expected behavior / 期待表现

正常相应

**Comment by qinxuye** [comment]
目前正在整体重构这一块，预计 0.15.0 开始会开始支持所有函数调用的模型。

**Comment by caofei88** [comment]
glm4-chat-1m 使用function_call也是有问题 ，错误如下： 
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/0e82c371-5b1c-4254-8045-e8acf56c49cd">
![image](https://github.com/user-attachments/assets/9b45b290-6970-448c-af86-9db7d2b8d2c3)

**Comment by caofei88** [comment]
> upport tool call。 glm4-chat-1m 使用function_call issue 如下

**Comment by ruifengma** [comment]
why Llama3.1 is removed from the plan?

**Comment by qinxuye** [comment]
Duplicated with #2045
