### ISSUE TITLE
Xinference能否在AMD GPU上进行模型推理？

### ISSUE THREAD

**Issue by linqingxu** [xorbitsai/inference#2148]
### Feature request / 功能建议

Xinference能否在AMD GPU上进行模型推理？

### Motivation / 动机

Xinference能否在AMD GPU上进行模型推理？

### Your contribution / 您的贡献

Xinference能否在AMD GPU上进行模型推理？

**Comment by qinxuye** [comment]
应该可以的，有碰到问题吗？

**Comment by linqingxu** [comment]
你好，想问下是否有在AMD GPU上docker部署xinference服务的教程，我看官网只有Nvidia显卡的教程

**Comment by linqingxu** [comment]
> 应该可以的，有碰到问题吗？

你好，想问下是否有在AMD GPU上docker部署xinference服务的教程，我看官网只有Nvidia显卡的教程

**Comment by linqingxu** [comment]
![image](https://github.com/user-attachments/assets/f7501560-a8b4-4c23-83dd-3ca259905355)
Xinference找不到amd gpu，rocm6.1.2
![image](https://github.com/user-attachments/assets/9cae588a-da14-4742-939c-7d9b3d7b124f)

**Comment by githust66** [comment]
> 应该可以的，有碰到问题吗？

我的也是，识别不到gpu
![image](https://github.com/user-attachments/assets/9bba597a-71b1-4e17-badb-6bd81e22d4fc)
![image](https://github.com/user-attachments/assets/72850a0b-f9d1-45ff-ad82-9e139b09402a)

**Comment by qinxuye** [comment]
这个位置没关系，主要看加载的时候能不能识别到

**Comment by githust66** [comment]
> 这个位置没关系，主要看加载的时候能不能识别到

加载的时候也不能识别到，这是使用的cpu嘛？
![image](https://github.com/user-attachments/assets/fcf16592-ee11-49d4-b1ef-089d944d9740)
运行内存用了20g

**Comment by linqingxu** [comment]
如果用docker起xinference 想切成amd的gpu 应该如何修改docker run命令

**Comment by linqingxu** [comment]
> > 这个位置没关系，主要看加载的时候能不能识别到
> 
> 可以了， llama.cpp不行，用 Transformers可以，感谢

请问你是用docker运行的xinference，还是用pip安装的xinference

**Comment by yuanbaobaoo** [comment]
+1

**Comment by kittyzero520** [comment]
> > 这个位置没关系，主要看加载的时候能不能识别到
> 
> 可以了， llama.cpp不行，用 Transformers可以，感谢

你好，我也是7900xtx，启动服务后，web界面显卡还是0，能帮我看下吗
https://github.com/xorbitsai/inference/issues/3182

**Comment by yaaisinile** [comment]
> 我的也是amdgpu，想用sglang跑deepseek，也是gpu调不起来，请问下要怎么操作才能用amdgpu跑起来

sglang现在只支持mi系列的显卡，7900xtx可以用vllm
