### ISSUE TITLE
xinference 0.14.1-0.14.3版本xinference与matcha-tts需要的库版本冲突

### ISSUE THREAD

**Issue by zjx140** [xorbitsai/inference#2158]
### System Info / 系統信息

cuda=11.8 Python3.10 Linux

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference=0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

pip install xinference[all]==0.14.3

### Reproduction / 复现过程

使用pip安装时提示xinference与matcha-tts需要的gradio库版本冲突
ERROR: Cannot install xinference and xinference[all]==0.14.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    xinference 0.14.3 depends on gradio==4.26.0
    xinference[all] 0.14.3 depends on gradio==4.26.0
    matcha-tts 0.0.7.0 depends on gradio==3.43.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Expected behavior / 期待表现

能够解决这个库使用版本的冲突

**Comment by qinxuye** [comment]
我们正在解决。

**Comment by 100ZZ** [comment]
`ERROR: Could not find a version that satisfies the requirement opencc==1.1.6; extra == "all" (from xinference[all]) (from versions: 0.1, 0.2, 1.1.8, 1.1.9)
ERROR: No matching distribution found for opencc==1.1.6; extra == "all"`
依赖的opencc版本
