### ISSUE TITLE
docker模式运行集群，不显示video模型

### ISSUE THREAD

**Issue by YSblack** [xorbitsai/inference#2168]
### System Info / 系統信息

docker

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

14.3

### The command used to start Xinference / 用以启动 xinference 的命令

version: '3.8'
services:
  xinference:
    container_name: xinference-supervisor
    image: xprobe/xinference:v0.14.3
    restart: always
    ports:
      - "9997:9997"
      - "11111:11111"
#      - "9995:9995"
    network_mode: host
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
    volumes:
      - /public/AI/xinference/.cache/modelscope:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    command: xinference-supervisor -H 192.168.30.186 -p 9997

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/cc3b3403-764c-4a9e-926f-d3cef5aadff8)
![image](https://github.com/user-attachments/assets/65b7285c-5dfa-4efe-a5f8-8641678cea7e)

### Expected behavior / 期待表现

集群模式不显示video模型

**Comment by qinxuye** [comment]
@codingl2k1 感觉这是个 BUG，需要修复。
