### ISSUE TITLE
How to load the model into memory instead of VRAM 如何将模型加载到内存而不是显存

### ISSUE THREAD

**Issue by pkunight** [xorbitsai/inference#2178]
### Feature request / 功能建议

We hope to load the LLM model, embedding model, and rerank model simultaneously on Xinference. Additionally, we would like the LLM model to be loaded onto the GPU, while the embedding model and rerank model should be loaded into memory and processed by the CPU. However, we haven't found relevant configuration options and are unsure how to achieve this.

我们希望在xinference上同时加载llm模型, embedding模型和rerank模型. 同时, 我们希望只有llm模型被加载到gpu, 而embedding模型和rerank模型都被加载到内存, 且经由cpu进行推理. 但是我们没有看到有相关的配置, 不知道该怎么实现?

### Motivation / 动机

When GPU memory is insufficient, we need to load only part of the model into the GPU memory, while keeping the rest of the model in system memory.

在显存不足时, 需要仅将部分模型加载进显存, 其余模型放在内存

### Your contribution / 您的贡献

None

**Comment by qinxuye** [comment]
页面上 N-GPU 或者 device 选择 CPU 即可，命令行 --n-gpu None 可以加载到 CPU。
