### ISSUE TITLE
Couldn't load fish speech

### ISSUE THREAD

**Issue by Tint0ri** [xorbitsai/inference#2195]
### System Info / 系統信息

Ubuntu 20.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.3 
:latest-cpu

### The command used to start Xinference / 用以启动 xinference 的命令

sudo docker run -d  -p 9997:9997  --name xinference xprobe/xinference:latest-cpu xinference-local -H 0.0.0.0

### Reproduction / 复现过程

load fish speech from webui with cpu
show error  in log:

hydra.errors.MissingConfigException: [address=0.0.0.0:34645, pid=158] Cannot find primary config 'firefly_gan_vq'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///opt/conda/lib/python3.11/site-packages/xinference/thirdparty/fish_speech/fish_speech/configs
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://

### Expected behavior / 期待表现

working and show running model

**Comment by qinxuye** [comment]
@codingl2k1 Could you look at this issue?

**Comment by zhanghx0905** [comment]
同样的问题
