### ISSUE TITLE
在压测大模型流式接口时，疑似存在内存泄漏？

### ISSUE THREAD

**Issue by lyq-feeling** [xorbitsai/inference#2198]
### System Info / 系統信息

python 3.11.9

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

0.11.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local.py

### Reproduction / 复现过程

压测流式接口大约10000次后，内存增加约到4个多G；未压测之前不到1G

压测方式jmeter，压测内容：
![Snipaste_2024-08-30_16-02-43](https://github.com/user-attachments/assets/a4bc0e97-e40f-4322-8ea9-ebe615e16921)

内存大小：
![Snipaste_2024-08-30_16-09-18](https://github.com/user-attachments/assets/282ecf63-d511-4de5-9a17-10627d44abb0)

初步分析：
采用tracemalloc分析：
![Snipaste_2024-08-30_16-10-42](https://github.com/user-attachments/assets/9ada1cc0-2bea-4c8a-84b1-f697fe54cedd)

### Expected behavior / 期待表现

是xinference中流式接口使用不当？还是asyncio类库自身的问题，如何修复？

**Comment by 100ZZ** [comment]
> ### System Info / 系統信息
> python 3.11.9
> 
> ### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？
> * [ ]  docker / docker
> * [ ]  pip install / 通过 pip install 安装
> * [x]  installation from source / 从源码安装
> 
> ### Version info / 版本信息
> 0.11.3
> 
> ### The command used to start Xinference / 用以启动 xinference 的命令
> xinference-local.py
> 
> ### Reproduction / 复现过程
> 压测流式接口大约10000次后，内存增加约到4个多G；未压测之前不到1G
> 
> 压测方式jmeter，压测内容： ![Snipaste_2024-08-30_16-02-43](https://private-user-images.githubusercontent.com/61812360/363092091-a4bc0e97-e40f-4322-8ea9-ebe615e16921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDc1MTgsIm5iZiI6MTcyNTAwNzIxOCwicGF0aCI6Ii82MTgxMjM2MC8zNjMwOTIwOTEtYTRiYzBlOTctZTQwZi00MzIyLThlYTktZWJlNjE1ZTE2OTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4NDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzBkY2Y3NDcwOGI4ZTRlNTBkMzM3Njk4ZGFkOWQ1YThkNDEyMjRkNjA0ZmU4ZDczM2FlMDYzZDJhZmQyNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgPtXAA6I-Tre5GH2f8D8NVybLfhcERHZMWIrzybMjs)
> 
> 内存大小： ![Snipaste_2024-08-30_16-09-18](https://private-user-images.githubusercontent.com/61812360/363094034-282ecf63-d511-4de5-9a17-10627d44abb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDc1MTgsIm5iZiI6MTcyNTAwNzIxOCwicGF0aCI6Ii82MTgxMjM2MC8zNjMwOTQwMzQtMjgyZWNmNjMtZDUxMS00ZGU1LTlhMTctMTA2MjdkNDRhYmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4NDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDJjNTllNzkxMDY3OTdjMWY3ODI2NTVjOGFlNDFmMDkyOWU4OGE1MzljZjQ0ZDA2Mjg5MDJjOGQ3NGUzZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpYk6os_zbEUk8CnXG0mJFL9ldAhmH81YNSSj-XtDeM)
> 
> 初步分析： 采用tracemalloc分析： ![Snipaste_2024-08-30_16-10-42](https://private-user-images.githubusercontent.com/61812360/363094385-9ada1cc0-2bea-4c8a-84b1-f697fe54cedd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDc1MTgsIm5iZiI6MTcyNTAwNzIxOCwicGF0aCI6Ii82MTgxMjM2MC8zNjMwOTQzODUtOWFkYTFjYzAtMmJlYS00YzhhLTg0YjEtZjY5N2ZlNTRjZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4NDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMTU0YTljNjYxNWNiMzNmZWZhMjRkOGU4YTI3Y2U0YjA5MTgxMDIzN2JhYjU4YjhjZTQ0ZDY1ZWI4YjgwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._IeCDfCor3UUIE9nW4Kyo2FEddPR0ebOlPiYP3-xx1g)
> 
> ### Expected behavior / 期待表现
> 是xinference中流式接口使用不当？还是asyncio类库自身的问题，如何修复？

你好，
请问下是单机还是集群部署
JMeter压测逻辑是啥样的，多用户并发么，10000次请求；我压测过，但只关注模型的进程

**Comment by lyq-feeling** [comment]
单机部署，10并发。
xinference有多个python进程，通过进程进程号看，内存泄漏的进程不是运行大模型的进程。
