### ISSUE TITLE
0.14.4版本因校验自定义模型有效性导致启动不成功

### ISSUE THREAD

**Issue by leoterry-ulrica** [xorbitsai/inference#2201]
### System Info / 系統信息

CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A
OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference：0.14.4

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope XINFERENCE_HOME=/data/llm/xin-conda nohup xinference-local --host 0.0.0.0 --port 6006 --log-level debug > /mnt/llm/xin_llm.log 2>&1 &

### Reproduction / 复现过程

1. 启动：XINFERENCE_MODEL_SRC=modelscope XINFERENCE_HOME=/data/llm/xin-conda nohup xinference-local --host 0.0.0.0 --port 6006 --log-level debug > /mnt/llm/xin_llm.log 2>&1 &
2. 校验自定义模型路径不存在：ValueError: [address=0.0.0.0:48516, pid=3387590] Invalid model URI /data/llm/models/xxx
![ca3361b9fea8d91e2aa5811d4a9998b](https://github.com/user-attachments/assets/a093f1a5-372a-4355-a5df-f2e4902ec24c)

### Expected behavior / 期待表现

希望启动校验模型路径有效性的时候，只需要给出警告信息，至少不能影响xinference服务本身的启动。

**Comment by leeyis** [comment]
我也遇到了同样的问题，WSL2 Ubuntu22.04安装了最新的xinference以后执行xinference-local报错：ValueError: Invalid model URI /mnt/x/xxx/models/THUDM/chatglm3-6b


蹲一个解决方案

**Comment by leoterry-ulrica** [comment]
> 我也遇到了同样的问题，WSL2 Ubuntu22.04安装了最新的xinference以后执行xinference-local报错：ValueError: Invalid model URI /mnt/x/xxx/models/THUDM/chatglm3-6b
> 
> 蹲一个解决方案

用前一个版本启动，然后修正自定义注册的模型路径，再用新版本启动就行了。

**Comment by leeyis** [comment]
> > 我也遇到了同样的问题，WSL2 Ubuntu22.04安装了最新的xinference以后执行xinference-local报错：ValueError: Invalid model URI /mnt/x/xxx/models/THUDM/chatglm3-6b
> > 蹲一个解决方案
> 
> 用前一个版本启动，然后修正自定义注册的模型路径，再用新版本启动就行了。

降级版本到0.14.0解决了，先这样用吧，不折腾了
`pip install -U xinference==0.14.0`

**Comment by amumu96** [comment]
在~/.xinference/model路径下删除出错的注册模型，重新用有效的路径注册模型

**Comment by qinxuye** [comment]
我们修复下，在启动的时候路径不存在的改成 warning 而不会失败。注册的时候会检查。

**Comment by qinxuye** [comment]
Solved by #2208 .
