### ISSUE TITLE
文档笔误（pip install 'xinference[sglang]'）在win10下执行失败——建议统一改为双引号

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#2206]
### System Info / 系統信息

win10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.x

### The command used to start Xinference / 用以启动 xinference 的命令

安装阶段，执行出错。

### Reproduction / 复现过程

根据文档：https://inference.readthedocs.io/zh-cn/latest/getting_started/installation.html#installation
安装失败：
补充：采用单引号，在linux下可执行成功，但在windows下执行出现如下错误。
建议：统一改为双引号（sglang和mlx两处）

(py310) admin@DESKTOP-K0UT5D3 G:\>pip install 'xinference[sglang]' -U
ERROR: Invalid requirement: "'xinference[sglang]'"

(py310) admin@DESKTOP-K0UT5D3 G:\>pip install 'xinference[mlx]'
ERROR: Invalid requirement: "'xinference[mlx]'"

### Expected behavior / 期待表现

修改文档：https://inference.readthedocs.io/zh-cn/latest/getting_started/installation.html#installation
兼顾linux和windows环境，确保都能执行成功。

pip install 'xinference[sglang]' 
——改为 pip install "xinference[sglang]" -U

pip install 'xinference[mlx]'
——改为：pip install “xinference[mlx]” -U

**Comment by qinxuye** [comment]
欢迎提交 PR。
