### ISSUE TITLE
前端页面{"detail":"Not Found"} 

### ISSUE THREAD

**Issue by 401557122** [xorbitsai/inference#2218]
### System Info / 系統信息

cuda12.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.4阿里镜像

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -dit -v /data1/llms0.14.4:/root/.xinference -e XINFERENCE_HOME=/root/.xinference -p 9999:9997 --gpus all --shm-size 20g --ipc=host registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.4 xinference-local -H 0.0.0.0  --log-level debug

### Reproduction / 复现过程

1.docker run
2.http://192.168.246.71:9999/
{"detail":"Not Found"}

### Expected behavior / 期待表现

网页正常运行

**Comment by yinmin2020** [comment]
我和你遇到了一样的情况，也是 0.14.4 版本的 现在切到 0.14.3 我试试看～

**Comment by yinmin2020** [comment]
我用了 0.14.3 就没有问题了～你可以试试看
![image](https://github.com/user-attachments/assets/4b723775-2467-403e-a4cd-e30de4155f31)

**Comment by linssbf** [comment]
删除所有日志

**Comment by Halfknow** [comment]
我也是用了v0.14.3就好了
