### ISSUE TITLE
aliyun镜像延后

### ISSUE THREAD

**Issue by 401557122** [xorbitsai/inference#2222]
### Feature request / 功能建议

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.4.post1 不存在，后续可以和原版镜像同时上传吗

### Motivation / 动机

。

### Your contribution / 您的贡献

。

**Comment by qinxuye** [comment]
由于我们的 push 是走的 github CI，目前 aliyun push 会超时，我们还在看怎么解决。

**Comment by oubeichen** [comment]
> 由于我们的 push 是走的 github CI，目前 aliyun push 会超时，我们还在看怎么解决。

看了下这次的被取消了：
https://github.com/xorbitsai/inference/actions/runs/10956422310

之后的CI，阿里云的都没推上去
