### ISSUE TITLE
多卡启动模型卡住

### ISSUE THREAD

**Issue by Root970103** [xorbitsai/inference#2223]
### System Info / 系統信息

vllm 0.5.5
transformers 4.43.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1. 客户端执行`xinference launch -e http://localhost:9997 --model_path /work/LLM/OpenGVLab/InternVL2-8B/ --model-engine transformers -n internvl2  --quantization none --model-uid InternVL2-8B-2p --n-gpu 2`
2. 模型一直未加载成功

### Expected behavior / 期待表现

期待多卡正常加载

额外想请教几个问题:
1. n-gpu 参数实现的多卡推理是基于哪种方式：tensor parallel / pipeline parallel 还是其他？没有在代码中看到具体实现
2. 不同引擎该参数是否都支持？实现方式是否一致？

**Comment by qinxuye** [comment]
Transformers 的多卡是 pp 并行。

我们部署过2卡的并行，没有碰到过问题。有没有相关日志？

**Comment by qinxuye** [comment]
不合理，应该是要相对均匀的分散到两卡上的
