### ISSUE TITLE
WIN10下无法使用GPU（启动第一个模型时识别GPUs就为[]）

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#2224]
### System Info / 系統信息

操作系统：Windows 10-22H2(19045.4780)
nvidia-smi显示：Driver Version: 551.61 | CUDA Version: 12.4
nvcc版本显示：Cuda compilation tools, release 12.4, V12.4.99 | Build cuda_12.4.r12.4/compiler.33961263_0
llama_cpp_python 0.2.90
vllm 无

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 10.10.83.104 --port 9997

### Reproduction / 复现过程

0，设备信息：GPU - V100-32GB * 4 / GPU Info | Total: 4.00 / GPU Memory Info | Usage: 84480.75MiB | Total: 131072.00 MiB

1，启动服务：xinference-local --host 10.10.83.104 --port 9997

2，启动模型：选择任意文生图模型（如 stable-diffusion-xl-base-1.0，Device选择GPU；GPU-IDX选择0,1,2,3）
错误：ValueError: [address=10.10.83.104:13708, pid=23124] Worker 10.10.83.104:13708 cannot use the GPUs with these indexes: [0, 1, 2, 3]. Worker 10.10.83.104:13708 can only see these GPUs: [].

补充，如果在启动模型时，Device选择GPU；但不填写GPU-IDX值，能启动，但实际只是用了CPU，出图很慢。

### Expected behavior / 期待表现

1，能用上GPU，加快出图速度。
2，能在文档中明确识别GPUs为[]的判断依据（因为GPU硬件/CUDA都正常，xinf也是刚启动，无其他模型）

**Comment by linssbf** [comment]
系统环境是否启用
CUDA_DEVICE_ORDER = PCI_BUS_ID
显卡参数是否启用
CUDA_VISIBLE_DEVICES =

**Comment by nikelius** [comment]
> 系统环境是否启用 CUDA_DEVICE_ORDER = PCI_BUS_ID 显卡参数是否启用 CUDA_VISIBLE_DEVICES =

之前在文档（https://inference.readthedocs.io/zh-cn/latest/getting_started/index.html）中没看到对应环境变量说明。
增加环境变量后，至少在“Running Models”的"GPU Indexes“栏可以看到对应设置值了，但还是有点慢，我再测测。
set CUDA_DEVICE_ORDER=PCI_BUS_ID
set CUDA_VISIBLE_DEVICES=0,1,2,3

**Comment by linssbf** [comment]
set CUDA_DEVICE_ORDER=PCI_BUS_ID  这是将硬件pci-id映射
set CUDA_VISIBLE_DEVICES=0,1,2,3   这是设置运行的ID
"GPU Indexes“栏的设置ID还是单卡运行的设置的，你需要的是并发运行方案吧

**Comment by nikelius** [comment]
> set CUDA_DEVICE_ORDER=PCI_BUS_ID 这是将硬件pci-id映射 set CUDA_VISIBLE_DEVICES=0,1,2,3 这是设置运行的ID "GPU Indexes“栏的设置ID还是单卡运行的设置的，你需要的是并发运行方案吧

目前还只是自测：单用户、单模型、单请求、在多卡上推理。还是很慢，感觉没用上GPU，不知道是不是win下装不上vllm的缘故。
2024-09-05 10:15:48,721 xinference.core.worker 8992 INFO     You specify to launch the model: FLUX.1-schnell on GPU index: [0, 1, 2, 3] of the worker: 10.10.83.104:14300, xinference will automatically ignore the `n_gpu` option.
Keyword arguments {'lora_model_paths': None} are not expected by FluxPipeline and will be ignored
2024-09-05 10:17:11,926 transformers.models.t5.tokenization_t5_fast 25148 WARNING  You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
...
2024-09-05 10:17:36,525 transformers.modeling_utils 25148 INFO     loading weights file G:\.xinference\cache\FLUX.1-schnell\text_encoder\model.safetensors
2024-09-05 10:17:36,551 transformers.modeling_utils 25148 INFO     Instantiating CLIPTextModel model under default dtype torch.float16.
2024-09-05 10:17:37,480 transformers.modeling_utils 25148 INFO     All model checkpoint weights were used when initializing CLIPTextModel.
2024-09-05 10:17:37,480 transformers.modeling_utils 25148 INFO     All the weights of CLIPTextModel were initialized from the model checkpoint at G:\.xinference\cache\FLUX.1-schnell\text_encoder.
If your task is similar to the task the model of the checkpoint was trained on, you can already use CLIPTextModel for predictions without further training.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [01:27<00:00, 12.46s/it]
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------

**Comment by nikelius** [comment]
更新torch和diffusers后，启动失败了。
torch                                    2.4.1+cu124
torchaudio                               2.4.1+cu124
torchvision                              0.19.1+cu124
diffusers                                0.30.2
错误信息：
RuntimeError: Failed to import diffusers.pipelines.aura_flow.pipeline_aura_flow because of the following error (look up to see its traceback):
Failed to import diffusers.models.transformers.auraflow_transformer_2d because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。

**Comment by linssbf** [comment]
@nikelius 还是驱动问题啊，用自定义模型另说

**Comment by nikelius** [comment]
0，驱动看上去正常（其他组AI绘图也是正常使用）
(py310) D:\>nvidia-smi   # NVIDIA-SMI 551.61       Driver Version: 551.61     CUDA Version: 12.4
(py310) D:\>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

1，之前pip安装，后改用conda更新torch及相关依赖，又有新的错。
D:\>pip install torch torchvision torchaudio -U --index-url https://download.pytorch.org/whl/cu124
D:\>conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia

2，启动报错：
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the
 process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes
 or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

2，增加环境变量：KMP_DUPLICATE_LIB_OK=TRUE，还是启动报错
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\xinference\model\llm\__init__.py", line 119, in _install
    from .pytorch.cogvlm2 import CogVLM2Model
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\xinference\model\llm\pytorch\cogvlm2.py", line 24, in <module>
    from PIL import Image
  File "G:\miniconda\envs\py310\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by linssbf** [comment]
官方对软件的要求也是驱动环境，你升级了，那么版本匹配呢，代码就是屎山，在难也不要去动，只能围着它转。
单卡运行用环境来配置，并发运行用nvlink。

**Comment by nikelius** [comment]
回退到 torch==2.2.1+cu121 恢复。

**Comment by nikelius** [comment]
回退到 torch==2.2.1+cu121 恢复。
