### ISSUE TITLE
GPU扩容

### ISSUE THREAD

**Issue by mandone** [xorbitsai/inference#2226]
### System Info / 系統信息

V100 * 8

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

13.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 8080

### Reproduction / 复现过程

目前在机器上用了两张V100卡部署GLM4，现在发现显存不太够用，如何无缝衔接的再添加两张显卡

### Expected behavior / 期待表现

目前在机器上用了两张V100卡部署GLM4，现在发现显存不太够用，如何无缝衔接的再添加两张显卡

**Comment by qinxuye** [comment]
n-gpu 指定卡的个数。

**Comment by mandone** [comment]
那是要重新启动后台服务？ @qinxuye

**Comment by mandone** [comment]
也就是模型短暂是不可以的对吧

**Comment by xiaoyesoso** [comment]
如何不停模型服务，直接扩容呢？
