### ISSUE TITLE
xinference服务kill掉后，模型服务并未被杀死，xinference重启后在running model中未发现该模型，且无法被访问，手动杀死模型进程，模型会重启

### ISSUE THREAD

**Issue by oldpiao** [xorbitsai/inference#2235]
### System Info / 系統信息

cuda：12.1

transformers: 4.43.4
vllm: 0.6.0
vllm-flash-attn: 2.6.1
python: 3.10
linux: centos7.8

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference: 0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1. 启动服务：xinference-local --host 0.0.0.0 --port 9997
2. 启动模型：
3. 停止服务：kill XXXX
    - 发现模型服务未停止
4. 停止模型服务：kill 模型显存进程号
    - 模型服务自动重启
6. 启动服务：xinference-local --host 0.0.0.0 --port 9997
    - 模型服务不在，但可以看到worker信息
8. 停止模型服务：kill 模型显存进程号
    - 模型服务自动重启

![image](https://github.com/user-attachments/assets/2f817202-20b4-4b73-a731-b336a0b12e88)
![image](https://github.com/user-attachments/assets/ef5f9988-4e0b-49f6-9970-ab7e5de922b6)
![image](https://github.com/user-attachments/assets/b7fda1be-be87-4b98-b608-98b7a6cd9870)
![image](https://github.com/user-attachments/assets/ecacb624-7533-43cf-8d80-da87e8e189a0)

### Expected behavior / 期待表现

xinference重启后模型服务在running中可以查到，或xinference停止时可以停止模型服务，或者worker处可以停止模型服务

**Comment by qinxuye** [comment]
xinference stop-cluster -e http://<ip>:9997

用命令停止试试。

**Comment by oldpiao** [comment]
不行，感觉是服务启动时启动了一个守护进程，但服务停止时守护进程还在，但主进程已经监控不到它了。

![Uploading image.png…]()


> xinference stop-cluster -e http://:9997
> 
> 用命令停止试试。

**Comment by oldpiao** [comment]
应该就是使用kill 停止服务导致子服务变成僵尸进程了，我把名为【pt_main_t】的几个服务停掉后就好了。

![image](https://github.com/user-attachments/assets/de05ae17-5bc2-4bd8-b78d-07a108b5da15)

**Comment by qinxuye** [comment]
后续可以考虑用 stop-cluster 命令而不是直接 kill

**Comment by oldpiao** [comment]
官方文档可以考虑把这个命令【stop-cluster】放在更醒目的位置，我是根据文档部署的，没有看到服务停止的命令。

**Comment by oldpiao** [comment]
官方文档可以考虑把这个命令【stop-cluster】放在更醒目的位置，我是根据文档部署的，没有看到服务停止的命令。

**Comment by skytodmoon** [comment]
遇到相同的问题
