### ISSUE TITLE
基础镜像中是否可以增加flash-attn模块？

### ISSUE THREAD

**Issue by ConleyKong** [xorbitsai/inference#2240]
### Feature request / 功能建议

建议镜像中增加flash-attn加速器，自己进去安装出现问题，找不到nvcc

### Motivation / 动机

运行gte-qwen2-1.5b的模型提示未安装flash-attn但是pip没有与当前cuda兼容的包，从源码安装又提示无法找到nvcc

### Your contribution / 您的贡献

flash-attn项目地址：https://github.com/Dao-AILab/flash-attention/releases

**Comment by ConleyKong** [comment]
启动gte-qwen2-1.5b报错：ImportError: [address=0.0.0.0:38651, pid=163] This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

**Comment by jim1997** [comment]
同问 建议镜像中增加flash-attn加速器
