### ISSUE TITLE
0.14.4.post1 docker 镜像版本模型引擎没有vllm,transformer引擎推理速度极慢

### ISSUE THREAD

**Issue by mote0302** [xorbitsai/inference#2243]
### System Info / 系統信息

Fri Sep  6 07:33:35 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:82:00.0 Off |                    0 |
| N/A   48C    P0             50W /  400W |   27114MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

# 部署xinference
version: '3'
services:
  xinfernece:
    image: "xprobe/xinference:latest"
    container_name: "xinference"
    restart: "always"
    ports:
      - "28251:9997"
    volumes:
      - "/home/xinference/cache:/root/.cache"
      - "/home/xinference/models:/root/models"
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["2"]
              driver: "nvidia"
              #count: "all"
              capabilities: ["gpu"]
    command: "xinference-local -H 0.0.0.0 --log-level debug"

### Reproduction / 复现过程

1. 注册模型
{
    "version": 1,
    "context_length": 2048,
    "model_name": "qwen1_5-32b",
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "generate",
        "chat"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "qwen1.5-chat",
    "model_specs": [
        {
            "model_format": "awq",
            "model_size_in_billions": 32,
            "quantizations": [
                "Int4"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/root/models/Qwen1___5-32B-Chat-AWQ",
            "model_revision": null
        }
    ],
    "prompt_style": {
        "style_name": "QWEN",
        "system_prompt": "You are a helpful assistant.",
        "roles": [
            "user",
            "assistant"
        ],
        "intra_message_sep": "\n",
        "inter_message_sep": "",
        "stop": [
            "<|endoftext|>",
            "<|im_start|>",
            "<|im_end|>"
        ],
        "stop_token_ids": [
            151643,
            151644,
            151645
        ]
    },
    "is_builtin": false
}

2. Launch Model 中model engine 只有SGLang Transformers

### Expected behavior / 期待表现

能够提供vllm引擎

**Comment by qinxuye** [comment]
python -m "import vllm" 看下有没有报错

**Comment by mote0302** [comment]
> python -m "import vllm" 看下有没有报错

着急用，docker-compose切换回xinference, version 0.14.0.post1  镜像了，之前的镜像版本都有vLLM引擎
有时间试一下

**Comment by ConleyKong** [comment]
> python -m "import vllm"

我在本地启动的0.14.4.post1里面执行了下你的命令提示无python，换成python3后:

python3 -m "import vllm" 
/usr/bin/python3: No module named import vllm

另外，直接使用python内部import也有问题：

Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vllm
WARNING 09-06 01:26:32 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 6, in <module>
    from vllm.entrypoints.llm import LLM
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 8, in <module>
    from vllm.entrypoints.chat_utils import (ChatCompletionMessageParam,
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/chat_utils.py", line 17, in <module>
    from openai.types.chat import (ChatCompletionContentPartRefusalParam,
ImportError: cannot import name 'ChatCompletionContentPartRefusalParam' from 'openai.types.chat' (/usr/local/lib/python3.10/dist-packages/openai/types/chat/__init__.py)

**Comment by ConleyKong** [comment]
的确没有了vllm，最常用的qwen2以前是有vllm的，现在没了：
![image](https://github.com/user-attachments/assets/1e6a0497-e6d7-49c2-a602-4cfe714fcf67)

**Comment by haibinwang9** [comment]
0.15.0修复了 升级下
