### ISSUE TITLE
也许有个简单的下载管理界面会更好

### ISSUE THREAD

**Issue by tigflanker** [xorbitsai/inference#2252]
### Feature request / 功能建议

inference挺赞的，但是当我下载一个大模型的时候，点击按钮就会在后台持续下载
有的时候我重启docker容器以后，他仍会下载，只有在log中看到了下载进度
期望能给个下载界面，可以看到是否某个模型正在下载，也可以有操作能暂停/放弃下载当前的任务
感谢🙏

### Motivation / 动机

例如glm4-vl的模型，以为很小，结果下载的时候看到一个权重碎片就有1.8G，而且一共有15个
可是找不到中止的地方，重启了docker，竟然还在继续下

### Your contribution / 您的贡献

暂无

**Comment by sdytzjp** [comment]
咋解决的
