### ISSUE TITLE
可以在有多余显存的GPU上再跑模型吗？

### ISSUE THREAD

**Issue by unsw-luopan** [xorbitsai/inference#2260]
### Feature request / 功能建议

User specified GPU index 0 has been occupied with a vLLM model: xxx, therefore cannot allocate GPU memory for a new model.
现在一张卡上有部署了模型就被独占了，对于embedding模型和rerank模型，可以支持在这张卡剩下的显存上部署吗

### Motivation / 动机

GPU资源紧张，独占一张卡有点浪费，想要调低gpu_memory_utilization，把剩余显存用来部署小一点的模型

### Your contribution / 您的贡献

暂无

**Comment by sdytzjp** [comment]
咋解决的

**Comment by unsw-luopan** [comment]
> 咋解决的

没用xinference管理，直接CMD跑模型指定卡
