### ISSUE TITLE
Model qwen2-instruct cannot be run on engine vLLM

### ISSUE THREAD

**Issue by danialcheung** [xorbitsai/inference#2262]
### System Info / 系統信息

CUDA v12.1, Transformers 4.44.2, vllm 0.6.0, vllm-flash-attn 2.6.1, flashinfer 0.1.6+cu121torch2.4, Python 3.11.9, Red Hat Enterprise Linux 9.4 (Plow)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9999

## Run with xInference vLLM Model Engine (Unsuccessful)
1. Create `conda env` with `Python=3.11.9`
2. `pip install xinference[vllm]`
3. Lauch xinference with `xinference-local --host 0.0.0.0 --port 9999`
4. Launch gptq model with `xinference launch --model-engine vllm --model-name qwen2-instruct --size-in-billions 72 --model-format gptq --quantization Int4`
5. Get the following error: `RuntimeError: Failed to launch model, detail: [address=0.0.0.0:58248, pid=3691355] Model qwen2-instruct cannot be run on engine vllm.`
6. Try launching with awq instead  `xinference launch --model-engine vllm --model-name qwen2-instruct --size-in-billions 72 --model-format awq --quantization Int4`
7. Get the same previous error as before with GPTQ

## Run with xInference Transformers Model Engine (Successful)
8. Try launching with transformers model engine instead  `xinference launch --model-engine Transformers--model-name qwen2-instruct --size-in-billions 72 --model-format gptq --quantization Int4`
9. Model is launched successfully.

## Run with vLLM (Successful)
10.  Run  `python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-72B-Instruct-GPTQ-Int4 --model /path/to/your/model --tensor-parallel-size <your_parallel_size> --max-model-len <your_size>`
11. Model is hosted successfully

### Expected behavior / 期待表现

Successful launch of the qwen2-instruct 72B GPTQ and/or AWQ model, since it's stated as compatible [here](https://inference.readthedocs.io/en/latest/models/builtin/llm/qwen2-instruct.html#model-spec-8-gptq-72-billion).

**Comment by qinxuye** [comment]
Can you successfully run `python -c "import vllm"`?

**Comment by danialcheung** [comment]
Yes, I can successfully run it with no issues or errors.

**Comment by danialcheung** [comment]
Closing my own issue, I discovered it was to do with the endpoint configuration defaulting to `9997` instead of `9999`, once I set it then the model loaded

**Comment by kidcad1412** [comment]
> Closing my own issue, I discovered it was to do with the endpoint configuration defaulting to `9997` instead of `9999`, once I set it then the model loaded

where to set it？
