### ISSUE TITLE
注册whisper的时候出错

### ISSUE THREAD

**Issue by zyh3826** [xorbitsai/inference#2267]
### System Info / 系統信息

python 3.11.0
cuda 12.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.4

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local -H 0.0.0.0 -p 8013 > $log_file 2>&1 &

### Reproduction / 复现过程

1. 启动xinference
2. 在前端注册whisper

### Expected behavior / 期待表现

正常注册whisper，现在出现如下错误
![企业微信截图_17259592261103](https://github.com/user-attachments/assets/296343d4-b6ad-46db-9478-2bfe6689babd)

**Comment by qinxuye** [comment]
直接通过自带的 whisper large ，指定 model path（optional 选项里）跑就可以。

**Comment by zyh3826** [comment]
> 直接通过自带的 whisper large ，指定 model path（optional 选项里）跑就可以。

解决
