### ISSUE TITLE
安装成功后（能显示版本号和安装地址），运行提示xinference: command not found

### ISSUE THREAD

**Issue by ak-2019** [xorbitsai/inference#2270]
### System Info / 系統信息

- ubuntu20.4
- Python 3.10.12

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.0
![1725982977004](https://github.com/user-attachments/assets/9e490c65-17be-40b3-9074-88cb3843b64d)

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997
运行就提示xinference: command not found
![1725982977004](https://github.com/user-attachments/assets/11c4ba4d-6b68-4da9-a620-9a3f5a96c37d)

### Reproduction / 复现过程

1. 安装：pip install "xinference[all]" -i https://pypi.mirrors.ustc.edu.cn/simple/
2.  查看路径和版本：pip show xinference
3.  启动：xinference-local --host 0.0.0.0 --port 9997
4. 报错，提示：xinference-local: command not found
5. 检查：xinference --help
6. 报错：xinference: command not found

### Expected behavior / 期待表现

启动成功

**Comment by qinxuye** [comment]
`python -m xinference.deploy.cmdline` 替换 xinference-local 看下。

**Comment by ak-2019** [comment]
> 4\. 报错，提示：xinference-local: command not found
感谢大佬！启动成功了，再请问一下， 什么命令可以替换xinference呢？

**Comment by qinxuye** [comment]
也是这个
