### ISSUE TITLE
0.15.0视觉模型存在问题，最近会修复吗

### ISSUE THREAD

**Issue by 401557122** [xorbitsai/inference#2272]
### System Info / 系統信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.15.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.0 

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -dit -v /data1/llms0.15.0:/root/.xinference -e XINFERENCE_HOME=/root/.xinference -p 9999:9997 --gpus all --shm-size 20g --ipc=host registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.15.0 xinference-local -H 0.0.0.0  --log-level debug

### Reproduction / 复现过程

1.运行qwenvl2模型出现transformer的'Qwen2VLForConditionalGeneration'问题，更新transformer到最新版又出现self._tokenizer = self._processor.tokenizer需要修改为self._tokenizer = self._processor._tokenizer才能部署成功的问题，最后部署成功了，调用又出现参数输入的错误Failed to generate chat completion, detail: [address=0.0.0.0:39506, pid=1510] can only concatenate str (not "list") to str

### Expected behavior / 期待表现

请问这是阿里云镜像错误还是这个版本的xinferece有问题

**Comment by qinxuye** [comment]
@Minamiyama 知道是什么问题吗？

**Comment by Minamiyama** [comment]
> @Minamiyama 知道是什么问题吗？

不知道，官网的demo代码也没见有改

**Comment by mikck** [comment]
遇到加一

**Comment by monk-after-90s** [comment]
+1

**Comment by qinxuye** [comment]
最好是等待 transformers 发版。

**Comment by 401557122** [comment]
@Minamiyama 能把镜像更新成您的可用的transformer版本吗

**Comment by Minamiyama** [comment]
> @Minamiyama 能把镜像更新成您的可用的transformer版本吗

最好是等待 transformers 发版。

**Comment by liduang** [comment]
+1，都不敢升级用了

**Comment by TideDra** [comment]
+1

**Comment by qinxuye** [comment]
Transformers 已经发版。

```
pip install transformers==4.45.1
```
