### ISSUE TITLE
Server error: 400 - [address=0.0.0.0:36057, pid=4539] Trying to set a tensor of shape torch.Size([2048, 128]) in "weight" (which has shape torch.Size([2048, 1024])), this looks incorrect.

### ISSUE THREAD

**Issue by tigflanker** [xorbitsai/inference#2275]
### System Info / 系統信息

操作系统：ubuntu，部署方式：docker

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

镜像版本：xinference, version 0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

通过 localhost:9997/ui 进行自定义模型部署报错，截图详见复现过程

### Reproduction / 复现过程

计划加载的模型来自：https://hf-mirror.com/mlx-community/deepseek-vl-7b-chat-4bit
The model planned to be loaded comes from: ⬆️

加载时填写的配置如下：
The configuration filled during loading is as follows: ⬇️
![001](https://github.com/user-attachments/assets/ca6f6fc7-2400-48a8-8a4f-0cca27c01442)

报错如下：
Met error like this:⬇️
![002](https://github.com/user-attachments/assets/f587a9ea-6b25-4206-bfb8-9895285b7481)

### Expected behavior / 期待表现

不知道为啥会出现tensor shape不匹配的情况，请大佬帮忙，感谢
I'm not sure why there is a mismatch in tensor shapes. Could someone please help? Thank you.

**Comment by qinxuye** [comment]
这个需要能支持跑 MLX 的 VL 模型，目前 MLX 后端还没适配视觉模型。需要先适配。

**Comment by tigflanker** [comment]
> 这个需要能支持跑 MLX 的 VL 模型，目前 MLX 后端还没适配视觉模型。需要先适配。

感谢您的回复，主要是我看到 xinference 也是支持 deepseek-vl-chat 非压缩的版本
但是跑起来太费劲，尝试了量化版本
那我就等后续版本对配置文件的更新啦
