### ISSUE TITLE
launch audio model-cosyvoice-300M-sft ERROR 

### ISSUE THREAD

**Issue by DoItEric** [xorbitsai/inference#2276]
### System Info / 系統信息

env: docker 27.2.0   // ubuntu 22.04 LTS
image: xprobe/xinference:v0.15.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

env: docker 27.2.0   // ubuntu 22.04 LTS
image: xprobe/xinference:v0.15.0
devices: NVIDIA 3090 * 2

### The command used to start Xinference / 用以启动 xinference 的命令

    docker run --name "$CONTAINER_NAME" -d \
        -p 9997:9997 \
        -e XINFERENCE_HOME=/data \
        -v /root/apps/xinference/data:/data \
        -e HF_ENDPOINT="https://hf-mirror.com" \
        --gpus all \
        xprobe/xinference:v0.15.0 \
        xinference-local -H 0.0.0.0

### Reproduction / 复现过程

1. run docker image
2. launch cosyvoice-300M-sft
3. get error : Server error: 500 - [address=0.0.0.0:41795, pid=968] ('Invalid argument to class cosyvoice.llm.llm.TransformerLM', "TransformerLM.__init__() missing 1 required positional argument: 'sampling'")

looks like code error? i guess is code version conflict？

### Expected behavior / 期待表现

just no bug

**Comment by leslie2046** [comment]
you need to update the models from huggingface/modelscope which is updated last week
