### ISSUE TITLE
Fish Speech 1.4 was released

### ISSUE THREAD

**Issue by Tint0ri** [xorbitsai/inference#2277]
### Feature request / 功能建议

FishSpeech 1.2 was supported. With FishSpeech 1.4 released today, please support the new release in the next milestone. 
And support FishSpeech stream mode as well.
Thanks

### Motivation / 动机

FishSpeech is a sota model in chinese TTS

### Your contribution / 您的贡献

https://huggingface.co/fishaudio/fish-speech-1.4

There is no break changes between 1.2 and 1.4.

**Comment by qinxuye** [comment]
@codingl2k1 Do you have time to see this?

**Comment by qinxuye** [comment]
Fixed by #2295
