### ISSUE TITLE
Xinference  launch 不能指定一个端口启动模型

### ISSUE THREAD

**Issue by HGladiator** [xorbitsai/inference#2281]
### System Info / 系統信息

xinference, version 0.15

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.15.

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 32588

### Reproduction / 复现过程

xinference launch  只有设置xinference的端口    -e, --endpoint TEXT             Xinference endpoint.
没有启动模型服务的指定端口。  

### Expected behavior / 期待表现

对于容器服务， 每次启动模型端口不确定， 不能事先确定容器需要开放哪些端口，，对外提供的端口不可控， 每次重启需要有很多维护成本。

**Comment by yh7109** [comment]
请问这个问题解决了吗，我也遇到了，看xinference launch --help中现在有一个--port参数，但是加上后依然报错
![image](https://github.com/user-attachments/assets/6b6d5797-f00b-44de-9024-b485f04a7eec)
