### ISSUE TITLE
xinference launch --help 中没有制定模型启动后的端口

### ISSUE THREAD

**Issue by HGladiator** [xorbitsai/inference#2282]
### System Info / 系統信息

Python 3.11.9

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 32588

### Reproduction / 复现过程

xinference launch [OPTIONS] 无法指定 端口， 只有  Xinference endpoint.    -e, --endpoint TEXT           

### Expected behavior / 期待表现

在容器中，需要在容器启动前才能指定暴露哪些端口。 而xinference 模型在启动后才能知道端口，  停下容器后， 暴露的端口在重新启动后又可能会变更，
在对外提供服务的时候， 因为重启后， 端口不能控制，调用方需要更新端口，  而有一定的维护成本，

**Comment by 3togo** [comment]
Below line won't work. At present, I cannot find anyway to use xinference launch on server port other than 9997. Any input?
 xinference -p 9999 launch --model-type embedding --model-name bge-large-zh-v1.5 --model-format pytorch
