### ISSUE TITLE
xinfer会话接口并发时，响应时间和并发数成比例 期望解答

### ISSUE THREAD

**Issue by 948024326** [xorbitsai/inference#2284]
### System Info / 系統信息

tesla v100 32g pcie 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

webui 9997

### Reproduction / 复现过程

我两张32g的卡，挂载了qwen1.5的7b模型
![image](https://github.com/user-attachments/assets/15880f88-eb86-41fb-b632-16a415320fd3)

然后我用postman调用会话接口
![image](https://github.com/user-attachments/assets/cb760f2e-6e09-46b2-81cd-f2943824343f)

单个的时候是3-4秒左右， 然后我同时并发同时调用两个或者三个时，时间和个数成比例上升，下面是同时调3个的
![image](https://github.com/user-attachments/assets/ab5ca5d9-2a6f-414a-ac6e-c9bf39a5a9a3)

我想问下这个是正常的吗？ 还是和我的显卡有关，或者我没有设置什么参数？ 我64g，同时跑的时候也只有22g，显存是足够的

### Expected behavior / 期待表现

希望应该多个同时请求时，在不OOM的情况下，可以接受时间稍微多用些，但不应该是和同一时刻请求个数成比例这样的效果

**Comment by viewhang** [comment]
我理解的，你使用的不是流式的，每次请求都等全部的回答完毕再返回结果。当并发大的时候，需要返回的 token就会变大很多。显卡生成 token 的速度却不会增加，因此响应时间变慢

**Comment by 948024326** [comment]
> 我理解的，你使用的不是流式的，每次请求都等全部的回答完毕再返回结果。当并发大的时候，需要返回的 token就会变大很多。显卡生成 token 的速度却不会增加，因此响应时间变慢

好的，请问有没有什么解决方法呢？  上vllm吗？ 或者用集群？

**Comment by 948024326** [comment]
@qinxuye  大佬可以帮忙看看吗

**Comment by qinxuye** [comment]
是什么引擎？

**Comment by 948024326** [comment]
> 是什么引擎？

![image](https://github.com/user-attachments/assets/64e82258-1148-4161-9b0c-b65b4aff4ee4)

**Comment by qinxuye** [comment]
Transformers 可以参考 https://inference.readthedocs.io/zh-cn/latest/user_guide/continuous_batching.html#usage

打开持续批处理。

另外，我注意到你对 7b 用了两个显卡，你的显卡多大显存？如果1卡能放下的话，不妨考虑 n-gpu 设置 1，replica 设置2，这样能提高并发，降低延迟。

**Comment by 948024326** [comment]
> Transformers 可以参考 https://inference.readthedocs.io/zh-cn/latest/user_guide/continuous_batching.html#usage
> 
> 打开持续批处理。
> 
> 另外，我注意到你对 7b 用了两个显卡，你的显卡多大显存？如果1卡能放下的话，不妨考虑 n-gpu 设置 1，replica 设置2，这样能提高并发，降低延迟。

好的感谢回答， transformer的配置我等下试试，我的卡是32g的，我是会进行agent会话，大概一次调用会增加10g左右，所以还是希望能两张卡都能用到，还有想请问下replica是什么意思？

**Comment by qinxuye** [comment]
同一模型有多少个副本。
