### ISSUE TITLE
无法使用vllm

### ISSUE THREAD

**Issue by jnzbfgjd** [xorbitsai/inference#2286]
### System Info / 系統信息

a10显卡

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local方式启动

### Reproduction / 复现过程

register model glm4-9b-1m后，无法选择vllm
<img width="520" alt="捕获" src="https://github.com/user-attachments/assets/90c9eaea-9b28-4775-82e7-774bb90a2d3c">

### Expected behavior / 期待表现

能够选择vllm

**Comment by yuntong613** [comment]
相同问题，自定义模型，不支持vllm选项

**Comment by WuXiaochengGG** [comment]
同问

**Comment by zxx20231119** [comment]
同问
