### ISSUE TITLE
一张大显存的显卡（一个slot）可以运行多个语言模型

### ISSUE THREAD

**Issue by gzGRQup** [xorbitsai/inference#2298]
### Feature request / 功能建议

我希望在我24G显存的显卡上同时运行两个语言模型

### Motivation / 动机

显卡显存算力的充分利用

### Your contribution / 您的贡献

无

**Comment by qinxuye** [comment]
正在搞。

**Comment by sdytzjp** [comment]
gpu index手动指定可以吗

**Comment by qinxuye** [comment]
可以试下。
