### ISSUE TITLE
Launch bce-embedding-base_v1 model failed:Failed to launch model, detail: [address=0.0.0.0:44301, pid=12678] __init__() got an unexpected keyword argument 'model_kwargs' 

### ISSUE THREAD

**Issue by zhangever** [xorbitsai/inference#2299]
### System Info / 系統信息

CUDA Version: 12.4
OS: Ubuntu 22.04.3 LTS
xinference: 0.15.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference: 0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997 -mp 8777 --log-level debug 

### Reproduction / 复现过程

在xinference ui上加载bce-embedding-base_v1
或者命令行: xinference launch --model-name bce-embedding-base_v1 --model-type embedding

### Expected behavior / 期待表现

正常加载模型

**Comment by qinxuye** [comment]
我这里使用正常。

没有完整的错误栈，没有办法定位问题。

**Comment by zhangever** [comment]
![image](https://github.com/user-attachments/assets/9c31012d-96c8-4fe8-aba5-efd7c23e08d4)

麻烦再帮忙看看， @qinxuye

**Comment by qinxuye** [comment]
不是这个，是服务端的错误

**Comment by zhangever** [comment]
执行下面指令后， 可以正常加载了:
pip install sentence-transformers --upgrade

**Comment by zhangyanbo2007** [comment]
确实可以了
