### ISSUE TITLE
Qwen2-VL如何启用Flash-attention2？

### ISSUE THREAD

**Issue by docShen** [xorbitsai/inference#2304]
### Feature request / 功能建议

看到其它ISSUE中有指导如何修改Qwen2-VL代码，以启用flash attention，修改后，在使用Xinference-local启动GUI界面时，没有看到哪里有可启用flash attention的选项，请问是默认设置吗？还是需要手动开启？

### Motivation / 动机

看到其它ISSUE中有指导如何修改Qwen2-VL代码，以启用flash attention，修改后，在使用Xinference-local启动GUI界面时，没有看到哪里有可启用flash attention的选项，请问是默认设置吗？还是需要手动开启？

### Your contribution / 您的贡献

看到其它ISSUE中有指导如何修改Qwen2-VL代码，以启用flash attention，修改后，在使用Xinference-local启动GUI界面时，没有看到哪里有可启用flash attention的选项，请问是默认设置吗？还是需要手动开启？

**Comment by LaureatePoet** [comment]
目前xinference==0.15.1 对于 Qwen2-VL 已经增加了“检测环境是否有flash_attn，如果有则开启，没有则不开启”。

具体细节见 #2289

**Comment by docShen** [comment]
> 目前xinference==0.15.1 对于 Qwen2-VL 已经增加了“检测环境是否有flash_attn，如果有则开启，没有则不开启”。
> 
> 具体细节见 #2289
已经解决 感谢

**Comment by FinTechCao** [comment]
> 目前xinference==0.15.1 对于 Qwen2-VL 已经增加了“检测环境是否有flash_attn，如果有则开启，没有则不开启”。
> 
> 具体细节见 #2289

请问一下这个是全局的设定，还是只针对Qwen的，比如加载Jina Embeddings V3的时候是否支持
