### ISSUE TITLE
xinference==0.15.0版本的vLLM引擎报错

### ISSUE THREAD

**Issue by CEfanmin** [xorbitsai/inference#2307]
详情：
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
4张4090卡
Qwen2-72B-AWQ

**Comment by qinxuye** [comment]
vllm 什么版本？

**Comment by CEfanmin** [comment]
> vllm 什么版本？

vLLM==0.6.1，maybe 0.5.5？

**Comment by qinxuye** [comment]
试下 0.5.5 可以不可以

**Comment by CEfanmin** [comment]
> 试下 0.5.5 可以不可以

好，下周试一下，到时候反馈，感谢！

**Comment by CEfanmin** [comment]
> > 试下 0.5.5 可以不可以
> 
> 好，下周试一下，到时候反馈，感谢！

尝试了vllm==0.6.1.post2
vllm-flash-attn==2.6.1
问题解决！

**Comment by CEfanmin** [comment]
> 试下 0.5.5 可以不可以

尝试了vllm==0.6.1.post2
vllm-flash-attn==2.6.1
问题解决！
