### ISSUE TITLE
Using LoRA adapters by OpenAI API

### ISSUE THREAD

**Issue by zhipeng9802** [xorbitsai/inference#2309]
### Feature request / 功能建议

Compatible with OpenAI when using LoRA adapters
eg. http://localhost:9997/v1/chat/completions ...

In addition:
Dynamically serving LoRA Adapters

### Motivation / 动机

Uniform request protocol and use xinf platform

### Your contribution / 您的贡献

vllm official document
https://docs.vllm.ai/en/latest/models/lora.html

**Comment by leoterry-ulrica** [comment]
@qinxuye REST方式请求说的就是这个feature。

**Comment by qinxuye** [comment]
> @qinxuye REST方式请求LoRA模型，说的就是这个feature。

收到，我看下

**Comment by leoterry-ulrica** [comment]
> This issue was closed because it has been inactive for 5 days since being marked as stale.

@qinxuye 这个issue被关了，是已经支持了吗？

**Comment by qinxuye** [comment]
lora支持的，但openai接口是不是支持要确认。

**Comment by oubeichen** [comment]
OpenAI 接口不支持的话，其他工具都没法用啊
