### ISSUE TITLE
MiniCPM-V-2.6 多卡部署，实际运行只使用了一张卡，从而导致显存不足

### ISSUE THREAD

**Issue by zt449569708** [xorbitsai/inference#2321]
### System Info / 系統信息

transformer-4.44.2，python-3.11，os-ubuntu18.04_x64

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

![1726627264046](https://github.com/user-attachments/assets/9e4cc266-556a-432f-956f-a9044f2f10bd)
如图，配置使用的是2个GPU（每个GPU显存为16GB），但是运行的时候提示显存不足，通过GPU监控看只运行在1个GPU上，如图：
![image](https://github.com/user-attachments/assets/36a58192-f424-4cd5-990d-05d5fee839ab)

### Expected behavior / 期待表现

Xinfernece 支持MiniCPM-V-2.6多卡推理

**Comment by 948024326** [comment]
n-gpu设置为auto试一下？

**Comment by zt449569708** [comment]
> n-gpu设置为auto试一下？

试过了，还是只在一张GPU卡上运行

**Comment by dlluckboy** [comment]
> > n-gpu设置为auto试一下？
> 
> 试过了，还是只在一张GPU卡上运行

大神们，我想问下，你们是如何升级xinference的，我是用docker部署的，多谢了啊

**Comment by sdytzjp** [comment]
> > n-gpu设置为auto试一下？
> 
> 试过了，还是只在一张GPU卡上运行

同样的问题
