### ISSUE TITLE
请问一下xinference怎么更新版本，通过pip安装的Xinference，是卸载旧版本然后重新安装最新版本的方式吗？

### ISSUE THREAD

**Issue by dingidng** [xorbitsai/inference#2337]
### System Info / 系統信息

xinference                        0.14.1.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference                        0.14.1.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference                        0.14.1.post1

### Reproduction / 复现过程

xinference                        0.14.1.post1

### Expected behavior / 期待表现

xinference                        0.14.1.post1

**Comment by xianqiliu** [comment]
`pip install --upgrade "xinference[all]"`
