### ISSUE TITLE
使用xinference框架部署qwen2-vl-2b-instruct疑似推理时精度下降

### ISSUE THREAD

**Issue by neusoftliang** [xorbitsai/inference#2338]
### System Info / 系統信息

cuda:12.4 transformers:4.45.0.dev0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

sudo docker run -e XINFERENCE_MODEL_SRC=modelscope -p 6998:6997 --gpus all registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference xinference-local -H 0.0.0.0 -p 6997 --log-level debug

### Reproduction / 复现过程

1、web端下载并运行qwen2-vl-instruct 2billion 多模态大模型；
2、使用图片：https://img2018.cnblogs.com/blog/881235/201901/881235-20190116103044221-1319797554.png 提问：请给出图片左侧的菜单列表
大模型回答结果：图片左侧的菜单列表显示的是一个名为“本地策略管理”的界面。界面中有一个红色的“+”图标，点击该图标可以进入策略管理页面。页面中显示了不同的策略选项，包括“一般”、“核心”、“1小时”、“1小时”、“6分钟”等。这些选项可能用于管理不同的安全策略，例如账户策略、密码策略等。
3、改为使用qwen2-vl-2b官网给到的代码运行，使用同样的图片和问题
大模型回答结果：图片左侧的菜单列表如下：\n\n1. 仪表面板\n2. 保护策略管理\n3. 本地策略管理\n4. 异地策略管理\n5. 虚拟化保护\n6. 在线挂载\n7. 系统\n8. 日志\n9. 报表
官网代码如下：
model_dir = snapshot_download("qwen/Qwen2-VL-2B-Instruct")
# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_dir, torch_dtype="auto", device_map="auto"
)

# default processer
processor = AutoProcessor.from_pretrained(model_dir)
messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": 'https://img2018.cnblogs.com/blog/881235/201901/881235-20190116103044221-1319797554.png',
                    },
                    {"type": "text", "text": "请给出图片左侧的菜单列表"},
                    
                ],
            }
        ]

        # Preparation for inference
        text = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )
        inputs = inputs.to("cuda")

        # Inference: Generation of the output
        generated_ids = model.generate(**inputs, max_new_tokens=128)
        generated_ids_trimmed = [
            out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = processor.batch_decode(
            generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )
        print(output_text)

两种部署方式结果不同，官网的明显比较准确

### Expected behavior / 期待表现

两种部署方式结果一致

**Comment by qinxuye** [comment]
图片打不开了，请提供图片。

**Comment by neusoftliang** [comment]
![881235-20190116103044221-1319797554](https://github.com/user-attachments/assets/3d8da0ed-5849-43e9-a3f3-5d81ca79d19f)
