### ISSUE TITLE
FEAT: Qwen2.5 support function calling

### ISSUE THREAD

**Issue by a2382625920** [xorbitsai/inference#2347]
### Feature request / 功能建议

希望可以尽快支持关于Qwen2.5系列模型的推理，感谢作者和所有开发团队

### Motivation / 动机

1

### Your contribution / 您的贡献

1

**Comment by lm970585581** [comment]
是不支持工具调用吧，我测试也不支持

**Comment by yellowbig** [comment]
是的，我测试也是不支持qwen2.5的tool calls，但是正常推理还是可以的

**Comment by a2382625920** [comment]
好的

**Comment by wz96cj** [comment]
自主册的qwen2.5 能选择vllm吗

**Comment by monk-after-90s** [comment]
> 我们正在解决。

期待

**Comment by Songjiadong** [comment]
期待
