### ISSUE TITLE
建议增加对嵌入模型 jina-embeddings-v3 的支持

### ISSUE THREAD

**Issue by dongkuang** [xorbitsai/inference#2349]
### Feature request / 功能建议

建议增加对嵌入模型 jina-embeddings-v3 的支持

### Motivation / 动机

jina-embeddings-v3据说效果不错

### Your contribution / 您的贡献

https://huggingface.co/jinaai/jina-embeddings-v3

**Comment by qinxuye** [comment]
Thanks, we will support it ASAP.
