### ISSUE TITLE
启动qwen2.5 14B vllm int8 版本ValueError: [address=0.0.0.0:37961, pid=352437] Marlin does not support weight_bits = uint8b128. Only types = [] are supported (for group_size = 128, min_capability = 70, zp = False)

### ISSUE THREAD

**Issue by dingidng** [xorbitsai/inference#2350]
### System Info / 系統信息

* xinference                        0.15.2
* torch                             2.4.0
torch-complex                     0.4.4
torchaudio                        2.4.0
torchmetrics                      1.4.1
torchvision                       0.19.0
* python   3.11.9
* nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

* xinference                        0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

![image](https://github.com/user-attachments/assets/686b35b2-25fb-47ab-8617-54f8029916b7)

启动qwen2.5 14B vllm int8 版本ValueError: [address=0.0.0.0:37961, pid=352437] Marlin does not support weight_bits = uint8b128. Only types = [] are supported (for group_size = 128, min_capability = 70, zp = False)

硬件是nvidia v100

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/fc64e8e9-a90a-4087-9f6f-6f8783a46352)

### Expected behavior / 期待表现

修复bug

**Comment by qinxuye** [comment]
试下加额外选项：quantization，值 GPTQ
