### ISSUE TITLE
SGlang部署qwen2.5失败Exception: Capture cuda graph failed: BatchPrefillWithPagedKVCache failed with error code no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by dingidng** [xorbitsai/inference#2351]
### System Info / 系統信息

xinference 0.15.2
torch 2.4.0
torch-complex 0.4.4
torchaudio 2.4.0
torchmetrics 1.4.1
torchvision 0.19.0
python 3.11.9
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

SGlang部署qwen2.5失败Exception: Capture cuda graph failed: BatchPrefillWithPagedKVCache failed with error code no kernel image is available for execution on the device

![image](https://github.com/user-attachments/assets/bece7080-e1b1-4351-b530-c26cba5a0d91)

### Reproduction / 复现过程

SGlang部署qwen2.5失败Exception: Capture cuda graph failed: BatchPrefillWithPagedKVCache failed with error code no kernel image is available for execution on the device

![image](https://github.com/user-attachments/assets/bece7080-e1b1-4351-b530-c26cba5a0d91)

### Expected behavior / 期待表现

进行解答

**Comment by 948024326** [comment]
啥卡跑的？

**Comment by dingidng** [comment]
> 啥卡跑的？
V100-32G

**Comment by 948024326** [comment]
> > 啥卡跑的？
> > V100-32G

一样， 我去sglang官网看了下，好想说不支持v100卡， 要算力8.0以上的卡

**Comment by dingidng** [comment]
> > > 啥卡跑的？
> > > V100-32G
> 
> 一样， 我去sglang官网看了下，好想说不支持v100卡， 要算力8.0以上的卡

那只能放弃了，v100 算力能力才7.0  那就用vllm了

我用vllm 量化版本还遇到这个错误

启动qwen2.5 14B vllm int8 版本ValueError: [address=0.0.0.0:37961, pid=352437] Marlin does not support weight_bits = uint8b128. Only types = [] are supported (for group_size = 128, min_capability = 70, zp = False)

**Comment by 948024326** [comment]
> > > > 啥卡跑的？
> > > > V100-32G
> > 
> > 
> > 一样， 我去sglang官网看了下，好想说不支持v100卡， 要算力8.0以上的卡
> 
> 那只能放弃了，v100 算力能力才7.0 那就用vllm了
> 
> 我用vllm 量化版本还遇到这个错误
> 
> 启动qwen2.5 14B vllm int8 版本ValueError: [address=0.0.0.0:37961, pid=352437] Marlin does not support weight_bits = uint8b128. Only types = [] are supported (for group_size = 128, min_capability = 70, zp = False)

我有印象我也碰到这个问题了  在以前旧版的时候      我跑了个 qwen2.5 7b  vllm   没报错

**Comment by dingidng** [comment]
> > > > > 啥卡跑的？
> > > > > V100-32G
> > > 
> > > 
> > > 一样， 我去sglang官网看了下，好想说不支持v100卡， 要算力8.0以上的卡
> > 
> > 
> > 那只能放弃了，v100 算力能力才7.0 那就用vllm了
> > 我用vllm 量化版本还遇到这个错误
> > 启动qwen2.5 14B vllm int8 版本ValueError: [address=0.0.0.0:37961, pid=352437] Marlin does not support weight_bits = uint8b128. Only types = [] are supported (for group_size = 128, min_capability = 70, zp = False)
> 
> 我有印象我也碰到这个问题了 在以前旧版的时候 我跑了个 qwen2.5 7b vllm 没报错

这波更新后遇到问题不少，我先用ollama了，本来想着SGlang 推理速度更快想试一试

**Comment by qinxuye** [comment]
试下加载模型加 extra 选项：disable_cuda_graph 值为 True。
