### ISSUE TITLE
XF提示exceed limit

### ISSUE THREAD

**Issue by SDAIer** [xorbitsai/inference#2355]
### System Info / 系統信息

NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

docker run ...

### Reproduction / 复现过程

使用qwen2.5-instruct
![image](https://github.com/user-attachments/assets/d4b562dd-c422-48ad-9fd0-36e9884c0b69)

fastgpt config.json配置如下,maxContent设置为32000

为什么xf报错： Input prompt (120511 tokens) is too long and exceeds limit of 4096
fastgpt报错：LLM model response empty

![image](https://github.com/user-attachments/assets/a1dcc8e6-d3e0-47f2-8681-948fc68af74f)

![image](https://github.com/user-attachments/assets/1813ef9a-a903-4b98-bf93-2c2a0e14f74c)

### Expected behavior / 期待表现

正常运行

**Comment by Valdanitooooo** [comment]
xinference vllm 启动 max_model_len 默认是 4096
https://github.com/xorbitsai/inference/blob/3369106b6320a212b93d8fb3f716354491131f5b/xinference/model/llm/vllm/core.py#L307

在 xinference启动模型时把 max_model_len 调大就行，同时需要的显存也会增多

**Comment by SDAIer** [comment]
多谢回复。


我是docker运行的xf。oneapi直接调用xf模型，这样的话，怎么改这个max_model_len


改每个模型的代码吗

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月26日(周四) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xorbitsai/inference] XF提示exceed limit (Issue #2355)




 
xinference vllm 启动 max_model_len 默认是 4096
 https://github.com/xorbitsai/inference/blob/3369106b6320a212b93d8fb3f716354491131f5b/xinference/model/llm/vllm/core.py#L307
 
在 xinference启动模型时把 max_model_len 调大就行，同时需要的显存也会增多

**Comment by Valdanitooooo** [comment]
@SDAIer docker 怎么运行的 就是 xinference launch --max_model_len 32768 这一步设置

**Comment by SDAIer** [comment]
> @SDAIer docker 怎么运行的 就是 xinference launch --max_model_len 32768 这一步设置
只是通过docker run启动xf，通过oneapi调用xf的模型。所以您提到的更改max_model_len这一步是不是需要oneapi那边处理这个参数

docker run \
  -v /root/.xinference:/root/.xinference \
  -v /root/.cache/huggingface:/root/.cache/huggingface \
  -v /root/.cache/modelscope:/root/.cache/modelscope \
  -p 9997:9997 \
  --name xinference_cpu \
  -d \
  -e XINFERENCE_MODEL_SRC=modelscope \
  -e XINFERENCE_HOME=/root/.xinference \
  registry.cn-hangzhou.aliyuncs.com/sdytai/xprobe_xinference_cpu:latest \
  xinference-local -H 0.0.0.0 --log-level DEBUG

**Comment by SDAIer** [comment]
不好意思,我刚才了解错了,是不是这个意思(如图)
参数名字对吧?

![image](https://github.com/user-attachments/assets/da4f420d-4b82-4c99-ada2-94ea7f3d2703)

**Comment by Valdanitooooo** [comment]
@SDAIer 是的

**Comment by SDAIer** [comment]
了解了，thanks bro





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xorbitsai/inference"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月26日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xorbitsai/inference] XF提示exceed limit (Issue #2355)






@SDAIer 是的
