### ISSUE TITLE
vllm方式多卡加载模型卡住，GPU占用率100%

### ISSUE THREAD

**Issue by Dax-Zhang-pxy** [xorbitsai/inference#2360]
### System Info / 系統信息

cuda版本12.3，卡为4090，python10，本地运行非docker方式。

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.0和0.15.2均存在相同问题

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/data/program/xinference XINFERENCE_MODEL_SRC=modelscope   xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

双卡加载模型就会出现。
![Uploading 微信图片_20240924195713.jpg…]()
![Uploading 微信图片_20240924195729.png…]()

### Expected behavior / 期待表现

期望能找到有效的解决办法。

**Comment by Dax-Zhang-pxy** [comment]
最后解决办法是设置环境变量：
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1

**Comment by RuiNov1st** [comment]
> 最后解决办法是设置环境变量： export NCCL_IB_DISABLE=1 export NCCL_P2P_DISABLE=1

遇到相同问题，卡了好久！非常感谢！
