### ISSUE TITLE
Can not deploy qwen2-vl

### ISSUE THREAD

**Issue by wangzuohao** [xorbitsai/inference#2361]
### System Info / 系統信息

Default docker latest images without any customization

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Latest version from docker image

### The command used to start Xinference / 用以启动 xinference 的命令

docker run --name xinference -d -p 9997:9997 -e XINFERENCE_MODEL_SRC=modelscope -e XINFERENCE_HOME=/data -v /data:/data --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

### Reproduction / 复现过程

1, deploy the qwen2-vl models. 
2. The issue happen for any model format and model size.
3. The error message is attached
![xinferenceerror](https://github.com/user-attachments/assets/892a8251-301a-4990-86e1-8d38e68bfd0e)

### Expected behavior / 期待表现

The model should be deployed without error

**Comment by kandada** [comment]
我也有同样的问题，怎么解决？
Server error: 500 - [address=0.0.0.0:35907, pid=2717359] cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers'...

**Comment by SDAIer** [comment]
一样。
ImportError: [address=0.0.0.0:38381, pid=406] cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

**Comment by 1234563536** [comment]
下载transformers-21fac7abba2a37fae86106f87fcf9974fd1e3830/  然后pip install . 安装新版本的transformers即可
