### ISSUE TITLE
推荐一个效果好的图片信息识别模型

### ISSUE THREAD

**Issue by SDAIer** [xorbitsai/inference#2366]
### System Info / 系統信息

1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

 v0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

docker run

### Reproduction / 复现过程

使用fastgpt--onapi调用xf本地模型，下载了好几个多模态的模型，图片识别效果都不准确。
有没有好一点的可以识别图片信息的模型

### Expected behavior / 期待表现

有没有好一点的可以识别图片信息的模型

**Comment by qinxuye** [comment]
qwen2-vl、minicpm3-v 和 internvl2
