### ISSUE TITLE
Qwen2.5 7b显存占用过大

### ISSUE THREAD

**Issue by mengxianglong123** [xorbitsai/inference#2368]
为什么使用xinference启动qwen2.5 7b instruct模型（直接在页面使用qwen2.5 instruct的选项启动），显存直接占了40多个g，这是为啥，显卡是a6000 48g，是上下文长度是32k导致的吗，引擎选择的是vllm

**Comment by Valdanitooooo** [comment]
gpu_memory_utilization默认是 0.9，可以自己调整参数

比如
max_model_len: 32768
gpu_memory_utilization: 0.8

**Comment by mengxianglong123** [comment]
> gpu_memory_utilization默认是 0.9，可以自己调整参数
> 
> 比如 max_model_len: 32768 gpu_memory_utilization: 0.8

您好，xinference在launch模型的时候，可以指定vllm的这个参数么，在文档中没有找到

**Comment by Valdanitooooo** [comment]
> 您好，xinference在launch模型的时候，可以指定vllm的这个参数么，在文档中没有找到

可以的，文档可能不完善，--gpu_memory_utilization 0.8 这样

**Comment by SDAIer** [comment]
请问我是oneapi直接调用xf模型，怎么指定maxcontent



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月26日(周四) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xorbitsai/inference] Qwen2.5 7b显存占用过大 (Issue #2368)




  
您好，xinference在launch模型的时候，可以指定vllm的这个参数么，在文档中没有找到
  
可以的，文档可能不完善，--gpu_memory_utilization 0.8 这样

**Comment by bigbrother666sh** [comment]
> > 您好，xinference在launch模型的时候，可以指定vllm的这个参数么，在文档中没有找到
> 
> 可以的，文档可能不完善，--gpu_memory_utilization 0.8 这样

gpu_memory_utilization这个参数的具体解释是什么？

**Comment by Valdanitooooo** [comment]
> gpu_memory_utilization这个参数的具体解释是什么？

来自 vllm 的参数
https://github.com/vllm-project/vllm/blob/8eeb85708428b7735bbd1156c81692431fd5ff34/vllm/entrypoints/llm.py#L105

**Comment by bigbrother666sh** [comment]
thx

**Comment by SDAIer** [comment]
请问所有参数都在这个文档中吗，没看到max_model_len



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月9日(周三) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xorbitsai/inference] Qwen2.5 7b显存占用过大 (Issue #2368)




 
thx

**Comment by bigbrother666sh** [comment]
是不是显存里面本来就有其他东西，nvtop 或者 nvitop 查查
