### ISSUE TITLE
How can I use Multi-vector retrieval embedding throught xinference client?

### ISSUE THREAD

**Issue by HuuHuy227** [xorbitsai/inference#2371]
### Feature request / 功能建议

I saw BAAI/bge-m3 has 3 retrieval methods:
- Dense retrieval
- Sparse retrieval 
- Multi-vector retrieval
I want use Multi-vector retrieval. So how could i use it through xinference?

### Motivation / 动机

.

### Your contribution / 您的贡献

.

**Comment by qinxuye** [comment]
Thanks, we need to do some investigation to see how to support.
