### ISSUE TITLE
[Feature] Support for Llama 3.2 Multi-modal and Lightweight Models

### ISSUE THREAD

**Issue by vikrantrathore** [xorbitsai/inference#2372]
### Feature request / 功能建议

This feature request proposes adding support for Meta's newly released Llama 3.2 models to lmdeploy. Llama 3.2 introduces exciting capabilities, including vision LLMs (11B & 90B) for image understanding and reasoning, and lightweight, edge-optimized models (1B & 3B) ideal for on-device AI applications. Integrating these models into lmdeploy would unlock new possibilities for developers, enabling them to build and deploy powerful, multi-modal AI solutions across diverse environments, from the cloud to resource-constrained devices. This aligns with lmdeploy's mission to provide a versatile and robust platform for deploying large language models.  We believe this addition would significantly enhance the value and reach of lmdeploy within the AI community. 

## Motivation for Implementing Llama 3.2 Inference Engine Support

Llama 3.2's release presents a strong case with dedicated support:

* **Multi-modal Capabilities:** Llama 3.2 introduces vision LLMs (11B & 90B) enabling image understanding and reasoning alongside text. Lmdeploy integration unlocks applications like document analysis, image captioning, and visual grounding.
* **Edge & Mobile Deployment:** Lightweight 1B & 3B models are tailored for on-device use cases (summarization, instructions, rewriting). Lmdeploy can facilitate faster, private, and offline AI on resource-constrained hardware.
* **Enhanced Performance:** Pruning and distillation techniques in Llama 3.2 result in improved efficiency. Lmdeploy users would benefit from faster inference and reduced resource consumption with these models.
* **Open Innovation:** Supporting Llama 3.2 aligns with lmdeploy's open-source ethos, fostering a wider ecosystem and accelerating AI application development.

### Related resources

* [Llama 3.2: Revolutionizing edge AI and vision with open, customizable models](https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/)
* [Llama 3.2 Huggingface](https://huggingface.co/collections/meta-llama/llama-32-66f448ffc8c32f949b04c8cf)
* [Download Llama Models](https://www.llama.com/llama-downloads)

### Your contribution / 您的贡献

Waiting for vLLM and sglang to implement it so that can update the version and then change model_family.json and prompts to support it.

**Comment by qinxuye** [comment]
Thanks, PR is also welcomed if you are interested.

**Comment by vikrantrathore** [comment]
> Thanks, PR is also welcomed if you are interested.
Done. Submitted the pull request.
#2376

**Comment by vikrantrathore** [comment]
@qinxuye This needs to be reopened as pull request #2376 is not yet merged.
