### ISSUE TITLE
help! qwen2-72b stream output empty in tool use 

### ISSUE THREAD

**Issue by XinWangg** [xorbitsai/inference#2378]
### System Info / 系統信息

absl-py                           2.1.0
accelerate                        0.33.0
aiofiles                          23.2.1
aiohappyeyeballs                  2.3.4
aiohttp                           3.10.1
aioprometheus                     23.12.0
aiosignal                         1.3.1
alembic                           1.13.2
aliyun-python-sdk-core            2.15.1
aliyun-python-sdk-kms             2.16.4
altair                            5.4.0
annotated-types                   0.7.0
anthropic                         0.34.1
antlr4-python3-runtime            4.9.3
anyio                             4.4.0
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
async-lru                         2.0.4
async-timeout                     4.0.3
attrdict                          2.0.1
attrs                             24.1.0
audioread                         3.0.1
auto_gptq                         0.7.1
autoawq                           0.2.5
autoawq_kernels                   0.0.6
autopage                          0.5.2
av                                12.3.0
babel                             2.16.0
bcrypt                            4.2.0
beautifulsoup4                    4.12.3
bibtexparser                      2.0.0b7
bitsandbytes                      0.43.3
bleach                            6.1.0
boto3                             1.28.64
botocore                          1.31.85
causal-conv1d                     1.4.0
cdifflib                          1.2.6
certifi                           2019.11.28
cffi                              1.17.0
cfgv                              3.4.0
chardet                           3.0.4
charset-normalizer                3.3.2
chattts                           0.1.1
click                             8.1.7
cliff                             4.7.0
clldutils                         3.22.2
cloudpickle                       3.0.0
cmaes                             0.11.1
cmake                             3.30.2
cmd2                              2.4.3
colorama                          0.4.6
coloredlogs                       15.0.1
colorlog                          6.8.2
comm                              0.2.2
conformer                         0.3.2
contourpy                         1.2.1
controlnet-aux                    0.0.7
crcmod                            1.7
cryptography                      43.0.0
csvw                              3.3.0
ctranslate2                       4.3.1
cycler                            0.12.1
Cython                            3.0.11
datasets                          2.20.0
dbus-python                       1.2.16
debugpy                           1.8.5
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.30.1
dill                              0.3.8
diskcache                         5.6.3
distlib                           0.3.8
distro                            1.9.0
distro-info                       0.23+ubuntu1.1
dlinfo                            1.2.1
ecdsa                             0.19.0
editdistance                      0.8.1
einops                            0.8.0
einx                              0.3.0
encodec                           0.1.1
eva-decord                        0.6.1
exceptiongroup                    1.2.2
executing                         2.0.1
fastapi                           0.110.3
faster-whisper                    1.0.3
fastjsonschema                    2.20.0
ffmpeg-python                     0.2.0
ffmpy                             0.4.0
filelock                          3.15.4
FlagEmbedding                     1.2.11
flashinfer                        0.1.5+cu124torch2.4
flatbuffers                       24.3.25
fonttools                         4.53.1
fqdn                              1.5.1
frozendict                        2.4.4
frozenlist                        1.4.1
fsspec                            2024.5.0
funasr                            1.1.6
future                            1.0.0
fvcore                            0.1.5.post20221221
gdown                             5.2.0
gekko                             1.2.1
gradio                            4.26.0
gradio_client                     0.15.1
greenlet                          3.0.3
grpcio                            1.66.0
h11                               0.14.0
hf_transfer                       0.1.8
hiredis                           3.0.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.24.5
humanfriendly                     10.0
hydra-colorlog                    1.2.0
hydra-core                        1.3.2
hydra-optuna-sweeper              1.2.0
HyperPyYAML                       1.2.2
identify                          2.6.0
idna                              2.8
imageio                           2.35.1
imageio-ffmpeg                    0.5.1
importlib_metadata                8.4.0
importlib_resources               6.4.4
inflect                           7.3.1
iniconfig                         2.0.0
interegular                       0.3.3
iopath                            0.1.10
ipykernel                         6.29.5
ipython                           8.26.0
ipywidgets                        8.1.5
isodate                           0.6.1
isoduration                       20.11.0
jaconv                            0.4.0
jamo                              0.4.1
jedi                              0.19.1
jieba                             0.42.1
Jinja2                            3.1.4
jiter                             0.5.0
jj-pytorchvideo                   0.1.5
jmespath                          0.10.0
joblib                            1.4.2
json5                             0.9.25
jsonpointer                       3.0.0
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
jupyter_client                    8.6.2
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_terminals          0.5.3
jupyterlab                        4.2.4
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
kaldiio                           2.18.0
kiwisolver                        1.4.5
language-tags                     1.2.0
lark                              1.1.9
lazy_loader                       0.4
libnacl                           2.1.0
librosa                           0.10.2.post1
lightning                         2.4.0
lightning-utilities               0.11.6
litellm                           1.43.1
llama_cpp_python                  0.2.88
llvmlite                          0.43.0
lm-format-enforcer                0.10.3
loguru                            0.7.2
loralib                           0.1.2
lxml                              5.3.0
Mako                              1.3.5
mamba-ssm                         2.2.2
Markdown                          3.7
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matcha-tts                        0.0.7.0
matplotlib                        3.9.2
matplotlib-inline                 0.1.7
mdurl                             0.1.2
mistune                           3.0.2
modelscope                        1.17.0
more-itertools                    10.4.0
mpmath                            1.3.0
msgpack                           1.0.8
multidict                         6.0.5
multiprocess                      0.70.16
narwhals                          1.5.5
natsort                           8.4.0
nbclient                          0.10.0
nbconvert                         7.16.4
nbformat                          5.10.4
nemo_text_processing              1.1.0
nest-asyncio                      1.6.0
networkx                          3.3
ninja                             1.11.1.1
nodeenv                           1.9.1
notebook                          7.2.1
notebook_shim                     0.2.4
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.555.43
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.20
nvidia-nvtx-cu12                  12.1.105
omegaconf                         2.3.0
onnxruntime                       1.19.0
onnxruntime-gpu                   1.16.0
openai                            1.39.0
openai-whisper                    20230306
OpenCC                            1.1.6
opencv-contrib-python-headless    4.10.0.84
opencv-python                     4.10.0.84
optimum                           1.21.4
optuna                            2.10.1
orjson                            3.10.7
oss2                              2.18.6
outlines                          0.0.46
overrides                         7.7.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.1
parameterized                     0.9.0
parso                             0.8.4
passlib                           1.7.4
pbr                               6.0.0
peft                              0.12.0
pexpect                           4.9.0
phonemizer                        3.3.0
pillow                            10.4.0
pip                               24.2
platformdirs                      4.2.2
pluggy                            1.5.0
plumbum                           1.8.3
pooch                             1.8.2
portalocker                       2.10.1
pre-commit                        3.8.0
prettytable                       3.11.0
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.47
protobuf                          5.27.3
psutil                            6.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.6.0
pybase16384                       0.3.7
pycountry                         24.6.1
pycparser                         2.22
pycryptodome                      3.20.0
pydantic                          2.8.2
pydantic_core                     2.20.1
pydub                             0.25.1
Pygments                          2.18.0
PyGObject                         3.36.0
pylatexenc                        2.10
pynini                            2.1.6.post1
pynndescent                       0.5.13
pynvml                            11.5.3
pyparsing                         3.1.3
pyperclip                         1.9.0
PySocks                           1.7.1
pytest                            8.3.2
python-apt                        2.0.1+ubuntu0.20.4.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-jose                       3.3.0
python-json-logger                2.0.7
python-multipart                  0.0.9
pytorch-lightning                 2.4.0
pytorch-wpe                       0.0.1
pytz                              2024.1
PyYAML                            6.0.1
pyzmq                             26.1.0
quantile-python                   1.1
ray                               2.34.0
rdflib                            7.0.0
redis                             5.0.8
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
requests-unixsocket               0.2.0
rfc3339-validator                 0.1.4
rfc3986                           1.5.0
rfc3986-validator                 0.1.1
rich                              13.7.1
rootutils                         1.0.7
rouge                             1.0.1
rpds-py                           0.19.1
rpyc                              6.0.0
rsa                               4.9
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruff                              0.6.2
s3transfer                        0.7.0
sacremoses                        0.1.1
safetensors                       0.4.4
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.14.1
seaborn                           0.13.2
segments                          2.2.1
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentence-transformers             3.0.1
sentencepiece                     0.2.0
setuptools                        73.0.1
sglang                            0.2.13
shellingham                       1.5.4
six                               1.14.0
sniffio                           1.3.1
soundfile                         0.12.1
soupsieve                         2.6
soxr                              0.4.0
SQLAlchemy                        2.0.32
sse-starlette                     2.1.3
stack-data                        0.6.3
starlette                         0.37.2
stevedore                         5.3.0
sympy                             1.13.1
tabulate                          0.9.0
tblib                             3.0.0
tensorboard                       2.17.1
tensorboard-data-server           0.7.2
tensorboardX                      2.6.2.2
tensorizer                        2.9.0
termcolor                         2.4.0
terminado                         0.18.1
threadpoolctl                     3.5.0
tifffile                          2024.8.10
tiktoken                          0.7.0
timm                              1.0.9
tinycss2                          1.3.0
tokenizers                        0.19.1
tomli                             2.0.1
tomlkit                           0.12.0
torch                             2.4.0
torch-complex                     0.4.4
torchaudio                        2.4.0
torchmetrics                      1.4.1
torchvision                       0.19.0
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
transformers                      4.43.4
transformers-stream-generator     0.0.5
triton                            3.0.0
typeguard                         4.3.0
typer                             0.11.1
types-python-dateutil             2.9.0.20240821
typing_extensions                 4.12.2
tzdata                            2024.1
umap-learn                        0.5.6
unattended-upgrades               0.1
Unidecode                         1.3.8
uri-template                      1.3.0
uritemplate                       4.1.1
urllib3                           2.0.7
uvicorn                           0.30.5
uvloop                            0.19.0
vector-quantize-pytorch           1.16.1
virtualenv                        20.26.3
vllm                              0.5.4+cu124
vllm-flash-attn                   2.6.1
vocos                             0.1.0
watchfiles                        0.22.0
wcwidth                           0.2.13
webcolors                         24.8.0
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        11.0.3
Werkzeug                          3.0.4
WeTextProcessing                  0.1.10
wget                              3.2
wheel                             0.34.2
widgetsnbextension                4.0.13
wrapt                             1.16.0
xformers                          0.0.27.post2
xinference                        0.14.3
xoscar                            0.3.3
xxhash                            3.4.1
yacs                              0.1.8
yarl                              1.9.4
zipp                              3.20.0
zmq                               0.0.0
zstandard                         0.23.0
 Ubuntu 22.04.4 LTS 
8卡H100

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker stop xinference
docker rm xinference
docker run --rm --name xinference -e XINFERENCE_MODEL_SRC=modelscope -v /home/test/wx/model_hub:/model -v /home/test/wx/code:/code  -p 9997:9997 --gpus all registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.3  xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程

1. 使用xinference部署qwen2-72b-chat，使用4卡，vllm backend，模型命名为Qwen2-72B-Instruct

2. 发送请求
{
    "model": "Qwen2-72B-Instruct",
    "temperature": 0.01,
    "max_tokens": 18900,
    "stream": true,
    "messages": [
        {
            "role": "system",
            "content": "任务背景：\n你是AI知识库助手， 当用户询问问题时，请搜索知识库并结合搜索结果进行问题回复。\n任务要求：\n1、在输出知识库提供的信息，如其中有图片、图片链接、网址链接，请务必输出 ，输出内容中的  ![] (/api/system/img/***) 中格式字符串，需更改为 ![](http://172.28.97.105:3000/api/system/img/*** )  正确的格式输出图片。\n2、如问题包括 \"请问大模型” 或“LLM ”字样 ，仅以大模型自身知识回复 。\n3、如问题仅包括“help” 或 “帮助” 或“AI知识库” 或“你能做什么”  ，请修改问题为 “AI知识库操作使用简要说明”  。\n输出格式：\n1、如在知识库中获取了相关答案，在输出时，如用户未要求简要回复，请按照【总结】和【详情】两部分格式结构化输出 \n2、如未检索到知识库答案，应回复 “您的问题内部知识库可能无相关答案 ，如需帮助请回复 “help“ ，如您希望大模型提供参考答案，请在提问时以  “LLM”  或 \"请问大模型\" 作为前缀 ！ ” ， 无需回复其他任何信息，也不要按 总结、详情、摘自的格式回复 。\n3、 输出时字段间要换行，确保有条理，结构清晰，简明扼要 。 \n4、请在输出结尾处，说明 以上回复信息来源于AI知识库 还是外部大模型自身知识，并提示详细内容请检索阅读原文。” "
        },
        {
            "role": "user",
            "content": "GPON 终端管理协议主要有几种协议，请简介 ？"
        },
        {
            "role": "assistant",
            "tool_calls": [
                {
                    "id": "qfS6G9R1O2Oq",
                    "type": "function",
                    "function": {
                        "name": "iKBoX2vIzETU",
                        "arguments": "{\"userChatInput\": \"GPON 终端管理协议主要有几种协议，请简介 ？\"}"
                    }
                }
            ]
        },
        {
            "tool_call_id": "qfS6G9R1O2Oq",
            "role": "tool",
            "name": "iKBoX2vIzETU",
            "content": "[\n  {\n    \"id\": \"66ea852dd11343eb7644bfe1\",\n    \"text\": \"【华为GPON业务开通配置指导】\\n\\n# **GPON终端管理**\\n\\nGPON终端管理协议主要有OMCI、XML、TR069三种协议。\\n\\nONT分为桥接型、桥接+语音型和网关型三种类型：\\n\\n-   桥接型ONT提供二层数据和二层组播业务；\\n-   桥接+语音型ONT提供二层数据、二层组播和VoIP语音业务；\\n-   网关型ONT提供三层数据、三层组播和VoIP语音业务。\\n\\n![](/api/system/img/66ea852cd11343eb7644bf64.png)图4 GPON终端管理方案协议交互示意图\\n\\n不同的终端管理协议对业务的管理范围不一样，根据终端类型，共支持“OMCI”、“OMCI+XML”、“OMCI+TR069”三种GPON终端管理方案，各方案对应的协议交互示意图如图4所示。\\n\\nOMCI方式主要用于管理二层业务、语音业务和PON链路层，采用方式一无法管理三层业务。XML主要用于管理三层和语音业务，采用方式二可以实现二层业务、语音业务和三层业务。TR069可以管理三层业务和语音业务，以及远程故障诊断，但其二层业务和PON链路层仍需要通过OMCI进行管理。\"\n  },\n  {\n    \"id\": \"66ea449dd11343eb76448a55\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n### 管理和业务发放\\n\\n系统的管理和业务发放作为一个完整的解决方案，为运营商提供部署规划、建设、运维等全流程建议，包括ODN的规划和建设，OLT和ONT的业务规划和部署、业务发放，运维管理等。\\n\\n由于协议只定义了OLT与ONT之间的透明管理通道，对于其他领域并没有定义，因此这是一个开放系统，需要根据实际的应用场景确定具体的解决方案。其中：\\n\\nODN规划和建设，目前尚无完整解决方案，后续会有专题介绍；\\n\\nOLT、ONT业务发放和运维管理，会涉及到OSS、网管，需要和终端管理、业务发放流程配合使用，需要全局考虑。详细的解决方案，本文不做介绍，后续将通过专题形式进行介绍。\"\n  },\n  {\n    \"id\": \"66ea449cd11343eb76448a33\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n# 导读\\n\\n本专题可以视作对GPON标准学习的笔记，内容尽可能的详尽并忠实反映ITU－T G.984.x标准的内容，学习完本专题的全部内容，您应该可以达到对GPON特性的全面了解。\\n\\n由于本文定位是原理专题，对于大多数技术支持工程师而言，因为涉及到协议栈、帧结构等内容，可能会略显深涩，阅读时可以择要进行了解，建议您先参考配套胶片，并对感兴趣的模块进行选择并深入学习。\\n\\n-   概要性的了解，请直接参考本文第5章的总结部分，这部分尽量用最简练的语言总结出GPON原理特性\\n-   需要对GPON解决方案有所了解，可以参考3.2和3.3章节\\n-   花边新闻，可以参考第6章内容\\n-   可以参考的胶片和文档\\n    -   《华为技术》(2006－10 固网专刊)\\n    -   《FTTx网络配置方案》 访问路径：support知识中心> 接入网> 光接入> 光接入公共\\n    -   《GPON QoS专题介绍》 访问路径：support知识中心> 接入网> 光接入> 光接入公共\"\n  },\n  {\n    \"id\": \"66ea449dd11343eb76448a8c\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n## APON、EPON（GEPON）与GPON\\n\\nAPON: ATM Passive Optical Networks\\n\\nEPON: Ethernet Passive Optical Networks\\n\\nGE-PON: Giga-bit Ethernet Passive Optical Networks\\n\\nGPON: Gigabit-capable Passive Optical Networks\\n\\nAPON、EPON与GPON对比\\n\\n|     |     |     |     |     |\\n| --- | --- | --- | --- | --- |\\n|     |     | APON | EPON | GPON |\\n| 标准化组织 |     | ITU－T（FSAN） | IEEE | ITU－T SG15（FSAN） |\\n| 推动标准的主体 |     | 运营商 | 设备商 | 运营商 |\\n| 速率  |     | 155/622 Mbps | 1 Gbps | 2.488 Gbps |\\n| 基本协议 |     | ATM | Ethernet | ATM |\\n| 线路编码 |     | NRZ | 8B/10B | NRZ |\\n| 线路编码效率 |     | 100％ | 80％ | 100％ |\\n| 分光比 |     | 1：32 | 1：16～1：32 | 1：64～1：128 |\\n| IP协议开销 |     | 大   | 小   | 中   |\\n| 组成  |     | ATM | IP/Ethernet | IP/Ethernet/ATM |\\n| QoS |     | 可靠  | 不可靠 | 可靠  |\\n| 总体效率 | 10％TDM，<br><br>90％ Data | 71％ | 49％ | 93％ |\\n| 20％TDM，<br><br>80％ Data | 72％ | 49％ | 94％ |\\n\\n##\"\n  },\n  {\n    \"id\": \"66ea449dd11343eb76448a87\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n# What’ more\\n\\n## 关于FSAN和GPON的提出\\n\\nFSAN是一个客户驱动的研究组，通常先由电信业务提供商来设定业务要求，然后它再把这些要求转化为所提方案的基础。这与EFM的工作方式完全相反，后者更多的是由设备商驱动的，目标是寻找符合以太网的简单方案，而不是针对现有业务和网络需求的不足问题。作为GPON工作的一部分，FSAN先汇集了其所有成员（包括世界各地的主要运营商）的要求，然后在此基础上写成名为千兆比业务要求（GSR）的文件，并作为正式建议（G.GPON.GSR）提交给ITU-T。GSR中的主要要求包括如下：\\n\\n-   支持全业务－包括话音（TDM、SONET和SDH）、以太网（工作在对绞线对上的10/100 BaseT – 10或100 Mb/s）、ATM、租用线与其它；\\n-   覆盖的物理距离至少为20 km，逻辑距离限于60 km以内；\\n-   用同一协议可支持各种比特率，包括对称622 Mb/s、对称1.25 Gb/s、下行2.5 Gb/s与上行1.25 Gb/s以及其它比特率；\\n-   能提供端到端业务管理的OAM&P强大功能\\n-   由于PON的多播性质，要在协议层面保证下行业务安全性。\\n\\nGPON系统就是在GSR设定的全部要求的基础上进行标准化的，因此它是一个全面体现业务提供商需要的方案。\"\n  },\n  {\n    \"id\": \"66ea449dd11343eb76448a48\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n### 业务承载能力\\n\\n在GPON系统中，其业务承载主要分为三层：GTC、GEM、Ethernet/TDM。\\n\\n![](/api/system/img/66ea449bd11343eb76448999.x-emf)GPON系统业务构架\\n\\n#### GTC层\\n\\n主要负责GEM帧的传输，完成GEM帧的成帧和适配处理，以及上行业务的QoS和下行数据安全性保证。其主要传送数据的控制单元是T-CONT。\\n\\n#### GEM层\\n\\n通过GEM Port来标识ONU/ONT不同的业务流，每个GEM Port即可以承载单业务，也可以支持承载多业务方式。所有的业务转发和QoS处理均基于GEM Port承载的每个业务流来处理，GEM Port可以仅做为标识用户业务流的逻辑承载管道。\\n\\n在GEM Port支持多业务的方式下，可以解决ONU/ONT不能对用户业务进行精细流分类问题，即使ONU/ONT使用一个GEM Port把所有的用户业务流发送给OLT，OLT也能对用户业务流重新进行分类识别，并进行相应的转发和QoS处理。同时，这种多业务方式可以将OLT和ONU/ONT的业务配置完全分离开，两者之间在配置操作上没有约束关系，极大降低系统处理的复杂度。\\n\\n#### Ethernet/TDM层\\n\\n以太网层主要是基于VLAN Tag进行业务转发和QoS处理，TDM层主要是处理E1/T1端口和业务的转发。\"\n  },\n  {\n    \"id\": \"66ea449dd11343eb76448a9d\",\n    \"text\": \"【GPON原理介绍-华为】\\n\\n# 总结\\n\\nGPON原理就是基于ITU－T G.984标准而来，标准对网络参数、物理参数、帧结构、管理进行了全面阐述：\\n\\n-   Ｇ．９８４．１ 指出了 ＧＰＯＮ 系统的综合特性， 包括服务的举例、网络运营商所要求的用户网络接口和服务节点接口及原理图。标准尽可能多地包括了Ｇ．９８２ 和 Ｇ．９８３．ｘ 系列的特性， 以提高它的兼容性。\\n-   Ｇ．９８４．２ 意在描述一种使用光纤技术的灵活的接入系统， 焦点在于支持网络的服务、ＯＡＮ 的 ＰＭＤ层的性质及 ＯＡＮ 具有在用户网络接口和服务接点接口间传输多种服务的能力。\\n-   Ｇ．９８４．３ 描述一个能支持数据、视频、专用线及ＰＳＴＮ 业务的网络。标准介绍了能够在用户网络和图 １ ＦＳＡＮ 及 ８０２．３ＥＦＭ框架服务节点间运送各种服务的无源光网络的性质、传输汇聚、处理有关帧格式、介质接入控制方法及ＯＡＭ的功能和安全的问题。\\n-   Ｇ．９８４．４ 规 定 了 ＯＮＴ 管 理 和 控 制 接 口 规 范（ＯＭＣＩ）， 给出了能管理 ＯＮＴ 结构、故障、性能和安全的标准， 重点在 ＦＴＴｘ 光网络的终端（ＯＮＴ／ＯＮＵ）。标准规定了 ＯＮＴ 的管理实体， 模拟了 ＯＬＴ 和 ＯＮＴ间的信息交换， 涵盖了 ＯＮＴ 管理控制信道、协议等详细信息。\\n\\nGPON不是产品，而是一种技术，PON是无源光网络的简称，包括OLT、ONT/ONU以及相关的ODN；\\n\\n光网络意味着具备光传输的长距离传输和高带宽，但也带来工程规范性要求；\\n\\n无源意味着信号传输过程的无源，维护简单（几乎是免维护），环境适应性强，不存在线路间串扰；\\n\\nGPON的工程化，归根结底就是对光功率预算的设计最优化；\\n\\nGEM帧只见于OLT和ONU之间；\\n\\nT－CONT只用于上行，T-CONT是业务流量的集合体，通过Alloc-ID标识，T－CONT可以配置，但是Alloc－ID是由OLT系统自动生成；\\n\\nT-CONT是从带宽的角度标识各种业务流的类型，而Port ID标识的是ONU的业务虚端口（虚连接），即标识是具体的业务流承载的通道，这种通道是虚拟的，PortID能起到地址的作用；\"\n  }\n]"
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "iKBoX2vIzETU",
                "description": "调用“语义检索”和“全文检索”能力，从“知识库”中查找可能与问题相关的参考内容",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "userChatInput": {
                            "type": "string",
                            "description": "需要检索的内容"
                        }
                    },
                    "required": [
                        "userChatInput"
                    ]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "readFiles",
                "description": "解析对话中所有上传的文档，并返回对应文档内容",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "iGKqn1",
                "description": "获取用户当前时区的时间。",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        }
    ],
    "tool_choice": "auto"
}
3.请求结果
data: {"id": "chat51a9ecda-7cac-11ef-ba72-0242ac110002", "model": "Qwen2-72B-Instruct", "created": 1727426508, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"role": "assistant", "content": ""}, "finish_reason": null}]}

data: {"id": "chat51a9ecda-7cac-11ef-ba72-0242ac110002", "model": "Qwen2-72B-Instruct", "created": 1727426508, "object": "chat.completion.chunk", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": "stop"}]}

data: [DONE]
发现结果中没有回复

### Expected behavior / 期待表现

stream输出对应的结果（结合知识库获取的结果做出回答）

**Comment by CEfanmin** [comment]
希望支持Qwen-72B-ins工具调用流式返回

**Comment by XinWangg** [comment]
> 希望支持Qwen2.5-72B-ins工具调用流式返回

Qwen2-72B-ins的流式工具调用好像也有点问题，有时候会不回复

**Comment by CEfanmin** [comment]
> > 希望支持Qwen2.5-72B-ins工具调用流式返回
> 
> Qwen2-72B-ins的流式工具调用好像也有点问题，有时候会不回复

嗯，期望国庆后就可以完美支持Qwen2.5-ins的工具调用和流式返回了

**Comment by monk-after-90s** [comment]
> > > 希望支持Qwen2.5-72B-ins工具调用流式返回
> > 
> > 
> > Qwen2-72B-ins的流式工具调用好像也有点问题，有时候会不回复
> 
> 嗯，期望国庆后就可以完美支持Qwen2.5-ins的工具调用和流式返回了

期待

**Comment by CEfanmin** [comment]
> > 希望支持Qwen2.5-72B-ins工具调用流式返回
> 
> Qwen2-72B-ins的流式工具调用好像也有点问题，有时候会不回复

Qwen2-72B-ins的流式调用我没成功，是需要什么参数传入么?
