### ISSUE TITLE
transformers 4.45.1版本下通过gpu_idx指定加载模型的npu无效

### ISSUE THREAD

**Issue by StephenZKCurry** [xorbitsai/inference#2392]
### System Info / 系統信息

操作系统：CTyunOS 22.06（基于openEuler）
CANN版本：8.0.RC2
Python版本：3.10.15
transformers版本：4.45.1
torch版本：2.3.1
torch-npu版本：2.3.1
npu数量：8

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1.启动本地LLM，指定gpu_idx=3（服务器共8块npu设备）
2.模型加载启动成功后，使用`npu-smi info`查看npu占用信息，发现显存平均分配到了8块显卡上
![image](https://github.com/user-attachments/assets/7aba39fc-f759-4012-90fb-384942f217f6)

**注：测试发现，将transformers版本降低至4.44.2后，gpu_idx会生效**

### Expected behavior / 期待表现

希望确定该问题是xinference框架导致的，还是transformers库导致的

**Comment by qinxuye** [comment]
如果切换版本就可以工作应该是 transformers 的问题。

**Comment by windcandle** [comment]
xinference在昇腾服务器上运行非常慢。不支持NPU，一堆坑。  推理框架Asecend服务器只能使用MindIE或Ascend vLLM...

**Comment by qinxuye** [comment]
> xinference在昇腾服务器上运行非常慢。不支持NPU，一堆坑。 推理框架Asecend服务器只能使用MindIE或Ascend vLLM...

transformers 在 NPU 上是很慢的，Xinference 企业版会有更好的昇腾支持。
