### ISSUE TITLE
xinference does not support simultaneous output of multiple Gpus

### ISSUE THREAD

**Issue by Weishaoya** [xorbitsai/inference#2396]
### System Info / 系統信息

os: ubuntu 22.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host xx --port xx

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/ec2deebb-f222-4e15-af5b-fa3f5e8408c5)
I have deployed the qwen1.5-chat-4b model on two v100 Gpus respectively. In the real usage scenario, we hope to call the model concurrently to answer, but I found that it can only answer questions sequentially.

### Expected behavior / 期待表现

Xinference supports copying multiple models to multiple Gpus. How do I implement the same model on different Gpus to answer multiple user questions simultaneously.

**Comment by qinxuye** [comment]
Which gradio version do you have?

**Comment by Weishaoya** [comment]
> Which gradio version do you have?
gradio  4.26.0
gradio_client  0.15.1

**Comment by qinxuye** [comment]
Try to set `GRADIO_DEFAULT_CONCURRENCY_LIMIT` environment variable.

```
GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 xinference-local xxx
```

This is a limitation from gradio.

**Comment by Weishaoya** [comment]
> Try to set `GRADIO_DEFAULT_CONCURRENCY_LIMIT` environment variable.
> 
> ```
> GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 xinference-local xxx
> ```
> 
> This is a limitation from gradio.

![image](https://github.com/user-attachments/assets/d9f4f8b1-9e8c-4715-96fa-18892f1cb7f5)
![image](https://github.com/user-attachments/assets/76b48434-51f1-4ec3-8625-b4405ea0e459)
I have tried it according to your method. I copied four identical models on four v100 respectively through xinference. Although the concurrency is set to 10, it still can only process two requests at the same time, which cannot meet the requirement. This problem is very important to me. I hope you can help me.
