### ISSUE TITLE
0.15.2版本在k8s的节点上无法感知到gpu节点

### ISSUE THREAD

**Issue by flightefore** [xorbitsai/inference#2397]
### System Info / 系統信息

k8s：1.24.10
gpu:4090*6
k8s-device-plugin:0.14.3
使用官方给的hlm方式安装

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

helm install xinference xinference/xinference -n xinference --version v0.15.2
### Reproduction / 复现过程

无法感知到gpu，如下图所示没有gpu![image](https://github.com/user-attachments/assets/b82e9ca5-052f-4a18-95bd-4f31670a1181)
但是当前节点是有gpu的并且已经安装了gpu插件，如下图所示
![1581acb0fb6bcecfd5157bc43491b2b8](https://github.com/user-attachments/assets/a3e13576-249b-4451-92bb-ed9c0de4bb1e)
其他单卡gpu应用是可以在集群中运行的说明，插件是生效的，这个xinference是否对gpu插件和k8s版本有要求

### Expected behavior / 期待表现

能感知到gpu卡的信息

**Comment by qinxuye** [comment]
能进到节点内执行：python -c "import torch; print(torch.cuda.is_available())"
