### ISSUE TITLE
请问支持曙光的dcu推理吗？

### ISSUE THREAD

**Issue by Cnzboy** [xorbitsai/inference#2401]
### System Info / 系統信息

NAME="NFSChina Server"
VERSION="4.0 (RTM3 OEM-S)"
ID="NFS"
ID_LIKE="NFSChina"
VERSION_ID="4.0"
SYSTEM_VERSION="4.0.220613"
PRETTY_NAME="NFSChina Server 4.0 (RTM3 OEM-S)"
ANSI_COLOR="0;31"
HOME_URL="http://www.nfschina.com"

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

请问支持曙光的dcu推理吗？

### Reproduction / 复现过程

请问支持曙光的dcu推理吗？

### Expected behavior / 期待表现

曙光的dcu

**Comment by lipish** [comment]
支持，可以去DCU 的超算互联网下载镜像:https://www.scnet.cn/ui/mall/detail/goods?type=software&common1=APP_SOFTWARE&id=1823174465122316290&resource=APP_SOFTWARE&keyword=xinference+
或者加我企业微信：
<img width="131" alt="image" src="https://github.com/user-attachments/assets/3c93b1b9-f8af-4046-bbbb-5f41879fa286">

**Comment by andylzming** [comment]
> 支持，可以去DCU 的超算互联网下载镜像:https://www.scnet.cn/ui/mall/detail/goods?type=software&common1=APP_SOFTWARE&id=1823174465122316290&resource=APP_SOFTWARE&keyword=xinference+ 或者加我企业微信： <img alt="image" width="131" src="https://private-user-images.githubusercontent.com/383066/374543725-3c93b1b9-f8af-4046-bbbb-5f41879fa286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MzcxMzUsIm5iZiI6MTczNjczNjgzNSwicGF0aCI6Ii8zODMwNjYvMzc0NTQzNzI1LTNjOTNiMWI5LWY4YWYtNDA0Ni1iYmJiLTVmNDE4NzlmYTI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QwMjUzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDA3ZGZmOTEzZTc5MzFjZDM2YmY3NmEzY2E5ZDY1ZDVjMGQ1ZDM2OGIwZGY0MGMzNDUyOTRiZTY0YTliZDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vkTvyjnycpDVdw-tt_c9HHZRAkpGdF_kJvGLlW06MJU">

请问从哪里可以下载？
