### ISSUE TITLE
openai接口支持response_format参数

### ISSUE THREAD

**Issue by 315930399** [xorbitsai/inference#2407]
### Feature request / 功能建议

希望openai接口能支持response_format参数进行json结构化输出。vllm / sglang 原生openai接口已支持该参数

### Motivation / 动机

希望openai接口能支持response_format参数进行json结构化输出。vllm / sglang 原生openai接口已支持该参数

### Your contribution / 您的贡献

vllm / sglang 已实现

**Comment by ZanePoe** [comment]
@qinxuye 这周的版本会有支持么

**Comment by qinxuye** [comment]
@wxiwnd 兼容 openai 接口本周来得及吗？

**Comment by wxiwnd** [comment]
> @wxiwnd 兼容 openai 接口本周来得及吗？

应该没问题。
