### ISSUE TITLE
安装模型Qwen2.5后，访问模型问答页面显示错误信息：{"detail":"Not Found"}

### ISSUE THREAD

**Issue by chenzhizhuan** [xorbitsai/inference#2413]
### System Info / 系統信息

![微信截图_20241010023731](https://github.com/user-attachments/assets/2fba6f82-ab30-450c-aa6e-968004693c70)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

非分布式场景，直接启动：xinference-local --host 127.0.0.1 --port 9997

### Reproduction / 复现过程

1、安装Qwen2.5模型，7b，transformers 引擎，无量化；
2、安装完成模型后，点击问与答，也就是访问http://127.0.0.1:9997/qwen2.5，出现{"detail":"Not Found"}，
3、后端报错日志如图
![微信截图_20241010024325](https://github.com/user-attachments/assets/454f1849-0b0c-4e85-b73d-dc04c23b8182)
![微信截图_20241010024450](https://github.com/user-attachments/assets/cbff46ee-9990-4349-8c93-2e134e9a1b34)

### Expected behavior / 期待表现

期待知道如何才能在Xinference中，正确运行Qwen2.5 7b 无量化 模型，显示出来问与答页面
![微信截图_20241010024602](https://github.com/user-attachments/assets/7dace22e-0c94-4b97-9e74-cbc42901ad3b)
。

**Comment by chenzhizhuan** [comment]
pip install "xinference[transformers]" 的安装指令。

**Comment by CharmingDaiDai** [comment]
我也遇到过 Not Found 的情况，但是报错好像和你的不一样
我的解决方法： pip install gradio==4.26.0

**Comment by chenzhizhuan** [comment]
> 我也遇到过 Not Found 的情况，但是报错好像和你的不一样 我的解决方法： pip install gradio==4.26.0

试过了，居然可以喔，厉害。感谢您的协助，谢谢！
