### ISSUE TITLE
supervisor方式启动，无cache_status这个字段，导致前端cache筛选无法显示出已经缓存的模型

### ISSUE THREAD

**Issue by Unexpectedlyc** [xorbitsai/inference#2424]
### System Info / 系統信息

win10,python3.10,xinferencev0.15.0,其余环境均为xinference使用该命令pip install "xinference[transformers]" 安装的版本

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinferencev0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

 xinference-supervisor --host 127.0.0.1
 xinference-worker --host 127.0.0.1

### Reproduction / 复现过程

![微信图片_20241011154744](https://github.com/user-attachments/assets/7dd14ff2-a6c3-47aa-a375-999d6bc4b0ed)
![微信图片_20241011154751](https://github.com/user-attachments/assets/4a598866-5b4f-4165-b65f-610712869d91)
这是local启动的，supervisor启动的时候也是调这个接口，但是返回的结果没有cache_status这个字段

![微信图片_20241011154756](https://github.com/user-attachments/assets/f936991e-b1bc-40b7-a395-18874c8ee376)

### Expected behavior / 期待表现

supervisor启动时能正常显示cache的模型

**Comment by Unexpectedlyc** [comment]
在core/supervisor.py文件中有个todo,方便问下集群部署的时候是会出现什么问题导致无法这么做呢？
`    async def _to_llm_reg(
        self, llm_family: "LLMFamilyV1", is_builtin: bool
    ) -> Dict[str, Any]:
        from ..model.llm import get_cache_status

        instance_cnt = await self.get_instance_count(llm_family.model_name)
        version_cnt = await self.get_model_version_count(llm_family.model_name)

        if self.is_local_deployment():
            specs = []
            # TODO: does not work when the supervisor and worker are running on separate nodes.
            for spec in llm_family.model_specs:
                cache_status = get_cache_status(llm_family, spec)
                specs.append({**spec.dict(), "cache_status": cache_status})
            res = {**llm_family.dict(), "is_builtin": is_builtin, "model_specs": specs}
        else:
            print(llm_family)
            res = {**llm_family.dict(), "is_builtin": is_builtin}
        res["model_version_count"] = version_cnt
        res["model_instance_count"] = instance_cnt
        return res`

**Comment by Unexpectedlyc** [comment]
这个还没解决吗

**Comment by qinxuye** [comment]
有兴趣来解这个问题吗？

**Comment by Unexpectedlyc** [comment]
> 有兴趣来解这个问题吗？

有兴趣解决这个问题
但我想知道导致这个问题的原因，以确定我是否有能力来解决它
# TODO: does not work when the supervisor and worker are running on separate nodes.

**Comment by Unexpectedlyc** [comment]
> 因为直接从本地拿的 cache 的信息，supervisor 上可能没有，需要从 worker 上收集所有的。

好的，了解，我有空会尝试解决这个问题

**Comment by Unexpectedlyc** [comment]
> 因为直接从本地拿的 cache 的信息，supervisor 上可能没有，需要从 worker 上收集所有的。

好的，了解，我有空会尝试解决这个问题!
