### ISSUE TITLE
基于glm4工具调用失败

### ISSUE THREAD

**Issue by wkw1542673895** [xorbitsai/inference#2426]
### System Info / 系統信息

> Entering new AgentExecutor chain...
Traceback (most recent call last):
  File "/data/ml-dl/llm/project/qa3/Langchain-Chatchat-master/libs/chatchat-server/chatchat/my_agent/oa_agent.py", line 371, in <module>
    result = oa_agent.run_agent('我的假期余额',[])
  File "/data/ml-dl/llm/project/qa3/Langchain-Chatchat-master/libs/chatchat-server/chatchat/my_agent/oa_agent.py", line 344, in run_agent
    res = self.agent_chain.invoke({
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/chains/base.py", line 170, in invoke
    raise e
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/chains/base.py", line 160, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/agents/agent.py", line 1629, in _call
    next_step_output = self._take_next_step(
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/agents/agent.py", line 1335, in _take_next_step
    [
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/agents/agent.py", line 1335, in <listcomp>
    [
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/agents/agent.py", line 1363, in _iter_next_step
    output = self._action_agent.plan(
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain/agents/agent.py", line 580, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3407, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3394, in transform
    yield from self._transform_stream_with_config(
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2197, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 3357, in _transform
    yield from final_pipeline
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1413, in transform
    for ichunk in input:
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 5561, in transform
    yield from self.bound.transform(
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1431, in transform
    yield from self.stream(final, config, **kwargs)
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 420, in stream
    raise e
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 400, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 639, in _stream
    chunk = chunk.model_dump()
  File "/root/miniconda3/envs/lc/lib/python3.10/site-packages/pydantic/main.py", line 390, in model_dump
    return self.__pydantic_serializer__.to_python(
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

15.2

### The command used to start Xinference / 用以启动 xinference 的命令

# from langchain.agents import AgentExecutor,create_tool_calling_agent,tool
from langchain_core.tools import tool
import requests
from typing import get_origin, Annotated

@tool
def last_holidays(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           ):
    """
    查询假期余额，假期剩余天数，还有几天假
    """
    # data = {"bip": BIP}

    result = '' 

    url = 'http://10.192.151.118:7003/robot/vacation/balance'
    
    data = {"bip":'wangshanhua'}

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)
    
    if response['code']==200:
        if response['data']:
            for d in response['data']:
                DESCR = d["DESCR"] 
                LASTYEARLEFT =  d["LASTYEARLEFT"]
                CURRENTLEFT =  d["CURRENTLEFT"]
                CURRENTYEARLEFT =  d["CURRENTYEARLEFT"]

                result += f"{DESCR}明细如下：上年结转{LASTYEARLEFT}天，当前年份剩余{CURRENTYEARLEFT}天，剩余{CURRENTLEFT}天\n\n"
        else:
            result += '系统信息为空'
    else:
        result += response['msg']

    return result
    # return 'last_holidays'

@tool
def yccs(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           CALPRDID: Annotated[str, '年-月;(如xxxx-xx);查询的月份;', True],
           ):
    """
    查询补卡次数，异常申诉的次数
    """
    flag = False
    # data = {"bip": BIP,"CALPRDID":CALPRDID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/exception/appeal'
    
    data = {"bip":'wangshanhua',"CALPRDID":CALPRDID}

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)

    if response['code']==200:
        if response['data']:
            result += f'{CALPRDID}可补卡次数为：' + response['data']['CARDNUMLEFT']
        else:
            result += '系统信息为空'
        flag = True
    else:
        result += response['msg']
    return '系统操作成功:\n\n'+result if flag else result
    # return 'yccs'

#待验证
@tool
def sbcq(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           CAL_PRD_ID: Annotated[str, '年-月;(如2024-08);查询的月份;', True],
        #    C_HALF_MON: Annotated[str, '范围;(1代表上半月,2代表下半月);查询的月份的范围是上半月还是下半月', True],
           ):
    """
    上班天数，正常出勤天数，上班的天数统计，出勤天数，通勤的天数，出勤了几天
    """
    flag = False
    # data = {"bip": BIP,"CAL_PRD_ID":CAL_PRD_ID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/attendance'
    
    for n in [1,2]:
        data = {"bip":'wangshanhua',"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}
        # data = {"bip":BIP,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}

        result += '\n上半月:' if n==1 else '\n下半月:'
        response = requests.post(url, json=data)
        response = response.json()
        print('response====>',response)

        if response['code']==200:
            if response['data']:
                result += f'{CAL_PRD_ID}出勤详情:\n'
                for k,v in response['data'].items():
                    if k != '确认状态':
                        result += f'{k}:{v}\n'      
            else:
                result += '系统信息为空'
            flag = True
        else:
            result += response['msg']
        
    return '系统操作成功:\n\n'+result if flag else result
    # return 'wdkq'

#待验证  旷工、迟到、早退、加班、请假、出差
@tool
def kqxq(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           TYPE: Annotated[str, '考勤类型;(类型可选旷工，缺卡，早退，迟到，正常出勤);考勤类型', True],
           CAL_PRD_ID: Annotated[str, '年-月;(如2024-08);查询的月份;', True],
        #    C_HALF_MON: Annotated[str, '范围;(1代表上半月,2代表下半月);查询的月份的范围是上半月还是下半月', True],
           ):
    """
    我的考勤，考勤详情，旷工，缺卡，早退，迟到
    """
    flag = False
    # data = {"bip": BIP,"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/attendance/detail'
    

    for n in [1,2]:
        data = {"bip":'zhenghaonan01',"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}
        # data = {"bip":BIP,"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}

        result += '\n上半月:' if n==1 else '\n下半月:'
        response = requests.post(url, json=data)
        response = response.json()
        print('response====>',response)

        if response['code']==200:
            if response['data']:
                for d in response['data']:
                    C_WORK_DATE = d["C_WORK_DATE"] 
                    C_ABSENCE_NUM =  d["C_ABSENCE_NUM"]
                    result += f"{C_WORK_DATE}有记录：{TYPE} {C_ABSENCE_NUM}次，\n"
            else:
                result += '系统信息为空'
            flag = True
        else:
            result += response['msg']
    return '系统操作成功:\n\n'+result if flag else result
    # return 'kqxq'

#待验证s
@tool
def qjlc(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           type: Annotated[str, '请假类型(类型可选事假、年假、调休假、育儿假、三八假等);假期类型', True],
           start_date: Annotated[str, '请假开始日期(如2024-09-12);请假开始日期', True],
           start_bc: Annotated[str, '请假开始日期的班次(上半个班次为1、下半个班次为2);上午还是下午', True],
           end_date: Annotated[str, '请假结束日期(如2024-09-13);请假结束日期', True],
           end_bc: Annotated[str, '请假结束日期的班次(上半个班次为1、下半个班次为2);上午还是下午', True],
           reason_type: Annotated[str, '请假原因类别(个人原因、家庭原因、身体原因、其他);个人原因、家庭原因、身体原因、其他', True],
           leaveDescr: Annotated[str, '请假理由详细说明;原因是什么,为什么请假', True],
           
           ):
    """
    休假，员工请假，发起请假流程
    """

    unkonw = [ i for i in [type,start_date,start_bc,end_date,end_bc,reason_type,leaveDescr] if not i]
    if unkonw:
        for i in unkonw:
            return f'缺少{i}参数，请提供{i}的信息'

    flag = False

    if type not in ['事假','年假','调休假','育儿假','三八假']:
        return  '系统操作成功:\n\n'+'您好，可到I碧服进行操作：\n\n'+'https://hcm-ess.bgyfw.com/#/vacationApply'
    data = {
            "bip": 'wangshanhua',#BIP,
            "beginClasses":start_bc,# "1",
            # "beginClassesText": "上半个班次",
            "beginDate": start_date,#"2024-09-12",
            "beginTime": "",
            "endClasses": end_bc,#"2",
            # "endClassesText": "下半个班次",
            "endDate": end_date,#"2024-09-12",
            "endTime": "",
            # "holidayType": "60",  # qiaoxia提供
            "holidayTypeText": type,
            # "epHoliday": "",
            # "epHolidayText": "",
            # "leaveDays": 1,
            "leaveDescr": leaveDescr,
            # "leaveHours": "",
            # "leaveReason": "1",
            # "visible": "20",
            # "dayOrHour": "天",
            # "formId": 1726329398926,    # 当前时间戳，13位 毫秒级
            # "cendTmText": "",   # 
            "leaveReasonText": reason_type,#"个人原因",
            # "otherVisible": "false"
}

    result = '' 

    url = 'http://10.192.151.118:7003/robot/leave/apply'

#     data = {
#             "bip": "wangshanhua",
#             "beginClasses": "1",
#             "beginClassesText": "上半个班次",
#             "beginDate": "2024-09-12",
#             "beginTime": "",
#             "endClasses": "2",
#             "endClassesText": "下半个班次",
#             "endDate": "2024-09-12",
#             "endTime": "",
#             "holidayType": "60",
#             "holidayTypeText": "年假",
#             "epHoliday": "",
#             "epHolidayText": "",
#             "leaveDays": 1,
#             "leaveDescr": "请假",
#             "leaveHours": "",
#             "leaveReason": "1",
#             "visible": "20",
#             "dayOrHour": "天",
#             "formId": 1726329398926,
#             "cendTmText": "",
#             "leaveReasonText": "个人原因",
#             "otherVisible": "false"
# }  

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)

    if response['code']==200:
        flag = True

    result += response['msg']

    u = 'https://hcm-esstest.bgyfw.com/#/login'
    return '系统操作成功:\n\n'+result + f'，请登陆查看详情：\n\n{u} 'if flag else result

#-------------------------------------------------------------------------

from langchain.agents import AgentExecutor,create_tool_calling_agent,tool
# from chatchat.my_agent.tool_test import *

# from chatchat.settings import Settings
from langchain.callbacks import AsyncIteratorCallbackHandler,StdOutCallbackHandler
from langchain_openai.chat_models import ChatOpenAI
# from langchain.llms import Xinference
# llm = Xinference(server_url='http://127.0.0.1:9997', model_uid='glm4-chat')

callback = StdOutCallbackHandler()
callbacks = [callback]

from langchain_core.prompts import ChatPromptTemplate,MessagesPlaceholder

params = {'streaming': True, 'verbose': True, 'callbacks': callbacks, 'model_name': 'glm4-chat', 'temperature': 0.01, 'openai_api_base': 'http://127.0.0.1:9997/v1', 'openai_api_key': 'EMPTY', 'openai_proxy': ''}

class OA_Agent:
    def __init__(self):
        # self.modelname = Settings.model_settings.DEFAULT_LLM_MODEL
        # self.chatmodel = get_ChatOpenAI(
        #                                 model_name=self.modelname,
        #                                 temperature=0.01,
        #                                 max_tokens=None,
        #                                 callbacks=callbacks,
        #                                 )
        self.chatmodel = ChatOpenAI(**params)
        # self.chatmodel = Xinference(server_url='http://127.0.0.1:9997', model_uid='glm4-chat')
        
        self.tools = [last_holidays,yccs,sbcq,kqxq,qjlc]
        # self.chatmodel.bind(self.tools)

        self.memorykey = "chat_history"

        self.SystemPrompt = """你是个人助手，以上是历史会话信息，你要仔细阅读历史会话数据，然后仔细分辨用户的意图，选择合适的工具进行协助。引导用户提供信息，最终输出所需要的工具与对应的参数，不要去调用参数"""
        self.prompt = ChatPromptTemplate.from_messages(
            [
                ("system","{chat_history}"),
                ("system",self.SystemPrompt),
                ("user","{input}"),
                MessagesPlaceholder(variable_name="agent_scratchpad")
            ]
        )

        self.agent = create_tool_calling_agent(
            self.chatmodel,
            self.tools,
            self.prompt,
        )
        self.agent_chain = None
    
    def run_agent(self,input,history):
        self.agent_chain = AgentExecutor(
            agent=self.agent,
            tools=self.tools,
            verbose=True
        )

        res = self.agent_chain.invoke({
            "input": input,"chat_history":history
        })
        return 'OA_Agent:'+ '\n\n' +res['output']
    
    # async def run_agent_ws(self,input):
    #     self.agent_chain = AgentExecutor(
    #         agent=self.agent,
    #         tools=self.tools,
    #         memory=self.memory,
    #         verbose=True
    #     )
    #     # run emotion sensing
    #     self.feeling = self.emotion.Emotion_Sensing(input)
    #     async for event in self.agent_chain.astream_events({"input": input,"chat_history":self.memory},version="v2"):
    #         kind = event["event"]
    #         if kind == "on_chat_model_stream":
    #             content = event["data"]["chunk"].content
    #             if content:
    #                 print(content, end="|")
    #                 yield content           

oa_agent = OA_Agent()

if __name__=="__main__":

    result = oa_agent.run_agent('我的假期余额',[])
    print('oa_agent.prompt=====>',oa_agent.prompt)
    print('result=====>',result)

### Reproduction / 复现过程

# from langchain.agents import AgentExecutor,create_tool_calling_agent,tool
from langchain_core.tools import tool
import requests
from typing import get_origin, Annotated

@tool
def last_holidays(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           ):
    """
    查询假期余额，假期剩余天数，还有几天假
    """
    # data = {"bip": BIP}

    result = '' 

    url = 'http://10.192.151.118:7003/robot/vacation/balance'
    
    data = {"bip":'wangshanhua'}

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)
    
    if response['code']==200:
        if response['data']:
            for d in response['data']:
                DESCR = d["DESCR"] 
                LASTYEARLEFT =  d["LASTYEARLEFT"]
                CURRENTLEFT =  d["CURRENTLEFT"]
                CURRENTYEARLEFT =  d["CURRENTYEARLEFT"]

                result += f"{DESCR}明细如下：上年结转{LASTYEARLEFT}天，当前年份剩余{CURRENTYEARLEFT}天，剩余{CURRENTLEFT}天\n\n"
        else:
            result += '系统信息为空'
    else:
        result += response['msg']

    return result
    # return 'last_holidays'

@tool
def yccs(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           CALPRDID: Annotated[str, '年-月;(如xxxx-xx);查询的月份;', True],
           ):
    """
    查询补卡次数，异常申诉的次数
    """
    flag = False
    # data = {"bip": BIP,"CALPRDID":CALPRDID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/exception/appeal'
    
    data = {"bip":'wangshanhua',"CALPRDID":CALPRDID}

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)

    if response['code']==200:
        if response['data']:
            result += f'{CALPRDID}可补卡次数为：' + response['data']['CARDNUMLEFT']
        else:
            result += '系统信息为空'
        flag = True
    else:
        result += response['msg']
    return '系统操作成功:\n\n'+result if flag else result
    # return 'yccs'

#待验证
@tool
def sbcq(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           CAL_PRD_ID: Annotated[str, '年-月;(如2024-08);查询的月份;', True],
        #    C_HALF_MON: Annotated[str, '范围;(1代表上半月,2代表下半月);查询的月份的范围是上半月还是下半月', True],
           ):
    """
    上班天数，正常出勤天数，上班的天数统计，出勤天数，通勤的天数，出勤了几天
    """
    flag = False
    # data = {"bip": BIP,"CAL_PRD_ID":CAL_PRD_ID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/attendance'
    
    for n in [1,2]:
        data = {"bip":'wangshanhua',"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}
        # data = {"bip":BIP,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}

        result += '\n上半月:' if n==1 else '\n下半月:'
        response = requests.post(url, json=data)
        response = response.json()
        print('response====>',response)

        if response['code']==200:
            if response['data']:
                result += f'{CAL_PRD_ID}出勤详情:\n'
                for k,v in response['data'].items():
                    if k != '确认状态':
                        result += f'{k}:{v}\n'      
            else:
                result += '系统信息为空'
            flag = True
        else:
            result += response['msg']
        
    return '系统操作成功:\n\n'+result if flag else result
    # return 'wdkq'

#待验证  旷工、迟到、早退、加班、请假、出差
@tool
def kqxq(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           TYPE: Annotated[str, '考勤类型;(类型可选旷工，缺卡，早退，迟到，正常出勤);考勤类型', True],
           CAL_PRD_ID: Annotated[str, '年-月;(如2024-08);查询的月份;', True],
        #    C_HALF_MON: Annotated[str, '范围;(1代表上半月,2代表下半月);查询的月份的范围是上半月还是下半月', True],
           ):
    """
    我的考勤，考勤详情，旷工，缺卡，早退，迟到
    """
    flag = False
    # data = {"bip": BIP,"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID}

    result = '' 
    

    url = 'http://10.192.151.118:7003/robot/attendance/detail'
    

    for n in [1,2]:
        data = {"bip":'zhenghaonan01',"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}
        # data = {"bip":BIP,"TYPE": TYPE,"CAL_PRD_ID":CAL_PRD_ID,"C_HALF_MON":n}

        result += '\n上半月:' if n==1 else '\n下半月:'
        response = requests.post(url, json=data)
        response = response.json()
        print('response====>',response)

        if response['code']==200:
            if response['data']:
                for d in response['data']:
                    C_WORK_DATE = d["C_WORK_DATE"] 
                    C_ABSENCE_NUM =  d["C_ABSENCE_NUM"]
                    result += f"{C_WORK_DATE}有记录：{TYPE} {C_ABSENCE_NUM}次，\n"
            else:
                result += '系统信息为空'
            flag = True
        else:
            result += response['msg']
    return '系统操作成功:\n\n'+result if flag else result
    # return 'kqxq'

#待验证s
@tool
def qjlc(
        #    BIP: Annotated[str, 'bip账号;(用户的员工bip账号);', False],
           type: Annotated[str, '请假类型(类型可选事假、年假、调休假、育儿假、三八假等);假期类型', True],
           start_date: Annotated[str, '请假开始日期(如2024-09-12);请假开始日期', True],
           start_bc: Annotated[str, '请假开始日期的班次(上半个班次为1、下半个班次为2);上午还是下午', True],
           end_date: Annotated[str, '请假结束日期(如2024-09-13);请假结束日期', True],
           end_bc: Annotated[str, '请假结束日期的班次(上半个班次为1、下半个班次为2);上午还是下午', True],
           reason_type: Annotated[str, '请假原因类别(个人原因、家庭原因、身体原因、其他);个人原因、家庭原因、身体原因、其他', True],
           leaveDescr: Annotated[str, '请假理由详细说明;原因是什么,为什么请假', True],
           
           ):
    """
    休假，员工请假，发起请假流程
    """

    unkonw = [ i for i in [type,start_date,start_bc,end_date,end_bc,reason_type,leaveDescr] if not i]
    if unkonw:
        for i in unkonw:
            return f'缺少{i}参数，请提供{i}的信息'

    flag = False

    if type not in ['事假','年假','调休假','育儿假','三八假']:
        return  '系统操作成功:\n\n'+'您好，可到I碧服进行操作：\n\n'+'https://hcm-ess.bgyfw.com/#/vacationApply'
    data = {
            "bip": 'wangshanhua',#BIP,
            "beginClasses":start_bc,# "1",
            # "beginClassesText": "上半个班次",
            "beginDate": start_date,#"2024-09-12",
            "beginTime": "",
            "endClasses": end_bc,#"2",
            # "endClassesText": "下半个班次",
            "endDate": end_date,#"2024-09-12",
            "endTime": "",
            # "holidayType": "60",  # qiaoxia提供
            "holidayTypeText": type,
            # "epHoliday": "",
            # "epHolidayText": "",
            # "leaveDays": 1,
            "leaveDescr": leaveDescr,
            # "leaveHours": "",
            # "leaveReason": "1",
            # "visible": "20",
            # "dayOrHour": "天",
            # "formId": 1726329398926,    # 当前时间戳，13位 毫秒级
            # "cendTmText": "",   # 
            "leaveReasonText": reason_type,#"个人原因",
            # "otherVisible": "false"
}

    result = '' 

    url = 'http://10.192.151.118:7003/robot/leave/apply'

#     data = {
#             "bip": "wangshanhua",
#             "beginClasses": "1",
#             "beginClassesText": "上半个班次",
#             "beginDate": "2024-09-12",
#             "beginTime": "",
#             "endClasses": "2",
#             "endClassesText": "下半个班次",
#             "endDate": "2024-09-12",
#             "endTime": "",
#             "holidayType": "60",
#             "holidayTypeText": "年假",
#             "epHoliday": "",
#             "epHolidayText": "",
#             "leaveDays": 1,
#             "leaveDescr": "请假",
#             "leaveHours": "",
#             "leaveReason": "1",
#             "visible": "20",
#             "dayOrHour": "天",
#             "formId": 1726329398926,
#             "cendTmText": "",
#             "leaveReasonText": "个人原因",
#             "otherVisible": "false"
# }  

    response = requests.post(url, json=data)
    response = response.json()
    print('response====>',response)

    if response['code']==200:
        flag = True

    result += response['msg']

    u = 'https://hcm-esstest.bgyfw.com/#/login'
    return '系统操作成功:\n\n'+result + f'，请登陆查看详情：\n\n{u} 'if flag else result

#-------------------------------------------------------------------------

from langchain.agents import AgentExecutor,create_tool_calling_agent,tool
# from chatchat.my_agent.tool_test import *

# from chatchat.settings import Settings
from langchain.callbacks import AsyncIteratorCallbackHandler,StdOutCallbackHandler
from langchain_openai.chat_models import ChatOpenAI
# from langchain.llms import Xinference
# llm = Xinference(server_url='http://127.0.0.1:9997', model_uid='glm4-chat')

callback = StdOutCallbackHandler()
callbacks = [callback]

from langchain_core.prompts import ChatPromptTemplate,MessagesPlaceholder

params = {'streaming': True, 'verbose': True, 'callbacks': callbacks, 'model_name': 'glm4-chat', 'temperature': 0.01, 'openai_api_base': 'http://127.0.0.1:9997/v1', 'openai_api_key': 'EMPTY', 'openai_proxy': ''}

class OA_Agent:
    def __init__(self):
        # self.modelname = Settings.model_settings.DEFAULT_LLM_MODEL
        # self.chatmodel = get_ChatOpenAI(
        #                                 model_name=self.modelname,
        #                                 temperature=0.01,
        #                                 max_tokens=None,
        #                                 callbacks=callbacks,
        #                                 )
        self.chatmodel = ChatOpenAI(**params)
        # self.chatmodel = Xinference(server_url='http://127.0.0.1:9997', model_uid='glm4-chat')
        
        self.tools = [last_holidays,yccs,sbcq,kqxq,qjlc]
        # self.chatmodel.bind(self.tools)

        self.memorykey = "chat_history"

        self.SystemPrompt = """你是个人助手，以上是历史会话信息，你要仔细阅读历史会话数据，然后仔细分辨用户的意图，选择合适的工具进行协助。引导用户提供信息，最终输出所需要的工具与对应的参数，不要去调用参数"""
        self.prompt = ChatPromptTemplate.from_messages(
            [
                ("system","{chat_history}"),
                ("system",self.SystemPrompt),
                ("user","{input}"),
                MessagesPlaceholder(variable_name="agent_scratchpad")
            ]
        )

        self.agent = create_tool_calling_agent(
            self.chatmodel,
            self.tools,
            self.prompt,
        )
        self.agent_chain = None
    
    def run_agent(self,input,history):
        self.agent_chain = AgentExecutor(
            agent=self.agent,
            tools=self.tools,
            verbose=True
        )

        res = self.agent_chain.invoke({
            "input": input,"chat_history":history
        })
        return 'OA_Agent:'+ '\n\n' +res['output']
    
    # async def run_agent_ws(self,input):
    #     self.agent_chain = AgentExecutor(
    #         agent=self.agent,
    #         tools=self.tools,
    #         memory=self.memory,
    #         verbose=True
    #     )
    #     # run emotion sensing
    #     self.feeling = self.emotion.Emotion_Sensing(input)
    #     async for event in self.agent_chain.astream_events({"input": input,"chat_history":self.memory},version="v2"):
    #         kind = event["event"]
    #         if kind == "on_chat_model_stream":
    #             content = event["data"]["chunk"].content
    #             if content:
    #                 print(content, end="|")
    #                 yield content           

oa_agent = OA_Agent()

if __name__=="__main__":

    result = oa_agent.run_agent('我的假期余额',[])
    print('oa_agent.prompt=====>',oa_agent.prompt)
    print('result=====>',result)

### Expected behavior / 期待表现

尽快解决

**Comment by qinxuye** [comment]
@codingl2k1 能看下这个问题吗？
