### ISSUE TITLE
离线无法成功运行自定义模型 jina-embeddings-v2-base-code

### ISSUE THREAD

**Issue by moqimoqidea** [xorbitsai/inference#2429]
### System Info / 系統信息

* CUDA Version: 12.4 
* NVIDIA-SMI 535.54.03
* NVIDIA A800-SXM4-80GB 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference launch --model-name jina-embeddings-v2-base-code --model-type embedding --model_path /root/.cache/modelscope/hub/jinaai/jina-embeddings-v2-base-code

### Reproduction / 复现过程

1. 下载模型：modelscope download --model jinaai/jina-reranker-v2-base-multilingual
2. 制作 model.json

{
    "model_name": "jina-embeddings-v2-base-code",
    "dimensions": 768,
    "max_tokens": 8192,
    "language": ["zh", "en"],
    "model_id": "jinaai/jina-embeddings-v2-base-code",
    "model_uri": "file:///root/.cache/modelscope/hub/jinaai/jina-embeddings-v2-base-code"
}

3. 进行注册：xinference register --model-type embedding --file /root/.cache/customer-models/jina-embeddings-v2-base-code.json --persist
4. 验证注册成功：

xinference registrations --model-type embedding | grep "jina-embeddings-v2"
Type       Name                              Language        Dimensions  Is-built-in
---------  --------------------------------  ------------  ------------  -------------
......
embedding  jina-embeddings-v2-base-code      ['zh', 'en']           768  False
embedding  jina-embeddings-v2-base-en        ['en']                 512  True
embedding  jina-embeddings-v2-base-zh        ['zh', 'en']           768  True
embedding  jina-embeddings-v2-small-en       ['en']                 512  True
embedding  jina-embeddings-v3                ['zh', 'en']          1024  True
......

5. 进行启动：xinference launch --model-name jina-embeddings-v2-base-code --model-type embedding --model_path /root/.cache/modelscope/hub/jinaai/jina-embeddings-v2-base-code 报错如下：

xinference launch --model-name jina-embeddings-v2-base-code --model-type embedding --model_path /root/.cache/modelscope/hub/jinaai/jina-embeddings-v2-base-code

Launch model name: jina-embeddings-v2-base-code with kwargs: {'model_path': '/root/.cache/modelscope/hub/jinaai/jina-embeddings-v2-base-code'}
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 901, in model_launch
    model_uid = client.launch_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 940, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:19589, pid=4308] We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like jinaai/jina-bert-v2-qk-post-norm is not the path to a directory containing a file named configuration_bert.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

6. 尝试设置环境变量 HF_DATASETS_OFFLINE=1 报错依旧

### Expected behavior / 期待表现

期待在离线环境中运行 jinaai/jina-embeddings-v2-base-code 模型

**Comment by qinxuye** [comment]
参考：

https://github.com/xorbitsai/inference/issues/1842#issuecomment-2366840471

**Comment by moqimoqidea** [comment]
可以运行了，非常感谢。

**Comment by moqimoqidea** [comment]
麻烦请教下 @qinxuye 这两个文件是下载固定版本的 https://github.com/xorbitsai/inference/issues/1842#issuecomment-2366840471 snapshot，还是下载官方维护仓库的新版本，谢谢？

https://huggingface.co/jinaai/jina-bert-v2-qk-post-norm/tree/main

**Comment by qinxuye** [comment]
我理解不影响使用应该都可以
