### ISSUE TITLE
Based on the Xinference local environment, there will be ping messages when receiving messages, which is not compatible.

### ISSUE THREAD

**Issue by androidsr** [xorbitsai/inference#2438]
### Feature request / 功能建议

![376008795-627fe9f6-e8e6-46f1-9ef4-0100d027bc76](https://github.com/user-attachments/assets/65f58584-53ee-4657-86a9-a5d9575a6392)

### Motivation / 动机

Based on the Xinference local environment, there will be ping messages when receiving messages, which is not compatible.

### Your contribution / 您的贡献

Based on the Xinference local environment, there will be ping messages when receiving messages, which is not compatible.

**Comment by ymjnana** [comment]
Could you please tell me if the issue has been resolved yet?
