### ISSUE TITLE
Any support for ocr models?

### ISSUE THREAD

**Issue by wy96f** [xorbitsai/inference#2441]
### Feature request / 功能建议

support the ocr model

### Motivation / 动机

OCR (Optical Character Recognition) can play an important role in LLM (Large Language Model) applications(e.g., extracting
 information from documents like invoices or financial statements)

### Your contribution / 您的贡献

haven't done yet

**Comment by qinxuye** [comment]
@codingl2k1 Do you have interest to add this feature?

**Comment by waterlyx** [comment]
got-ocr2 models 👍🏻
