### ISSUE TITLE
v1/chat/completions 接口 logprobs 参数无效

### ISSUE THREAD

**Issue by Sun-Qiming** [xorbitsai/inference#2456]
### System Info / 系統信息

引擎：transformers
cuda：12.4
python：3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

界面launch的时候，Additional parameters passed to the inference engine增加logits_all为true
模型：qwen2.5-7b-instruct

### Reproduction / 复现过程

请求接口参数：
{
    "model": "xxxx",
    "max_tokens": 1024,
    "top_p": 1.0,
    "temperature": 0.1,
    "stream": false,
    "logprobs": true,
    "messages": [
        {
            "content": "你知道李白么",
            "role": "user"
        }
    ]
}

### Expected behavior / 期待表现

输出包含logprobs信息

是否是我参数设置问题？

**Comment by qinxuye** [comment]
可能没有实现，我们确认下。

**Comment by Sun-Qiming** [comment]
> 可能没有实现，我们确认下。

扫了一眼源码，很多地方logprobs直接赋值NONE了，估计是没有实现吧。
这个功能还是挺重要的，可以做为很多场景下的判断条件，建议增加
