### ISSUE TITLE
transformer引起的数据精度问题

### ISSUE THREAD

**Issue by Erincrying** [xorbitsai/inference#2462]
### System Info / 系統信息

python 3.10
torch 2.4.0
transformer 4.45.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference v15.4.0

### The command used to start Xinference / 用以启动 xinference 的命令

网页启动qwen2-vl-struct（transformer引擎，gptq）。

### Reproduction / 复现过程

1.本地部署xinference v15.4.0，运行qwen2-vl-struct（transformer引擎，gptq，无论量化选择哪一项）。
2.集成至dify，当在dify应用中同时调用2个及以上的相同应用（应用中对应qwen2模型），dify报错[xinference] Error: An error occurred during streaming。
3.xinference报错probability tensor contains either 'inf', 'nan' or elemen < 0，位置索引是transfomer文件夹下。

### Expected behavior / 期待表现

可解决同时调用同一个模型的问题

**Comment by Valdanitooooo** [comment]
我用 v0.16.0 没问题

**Comment by Erincrying** [comment]
> 我用 v0.16.0 没问题

现在应该是更新解决了
