### ISSUE TITLE
支持minicpm-Embedding 

### ISSUE THREAD

**Issue by he-bowen** [xorbitsai/inference#2464]
### Feature request / 功能建议

支持minicpm-Embedding
https://huggingface.co/openbmb/MiniCPM-Embedding

### Motivation / 动机

minicpm-Embedding + minicpm --Reranker 发挥性能最佳，希望支持。
![image](https://github.com/user-attachments/assets/19137aae-af2f-487e-b861-19e99a10e99c)

### Your contribution / 您的贡献

https://huggingface.co/openbmb/MiniCPM-Embedding

**Comment by qinxuye** [comment]
Thanks, we will support it later, PR welcomed as well.
