### ISSUE TITLE
调用chattts报错chat object has no attribute speaker

### ISSUE THREAD

**Issue by Jarvanen** [xorbitsai/inference#2469]
### System Info / 系統信息

vllm 0.6.3
chattts 0.2.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local

### Reproduction / 复现过程

dify接入xinference   播放语音时xinference报错

### Expected behavior / 期待表现

正常播放语音

**Comment by qinxuye** [comment]
0.16.0 及之前的版本还没有支持 chattts 0.2.0，本周发布的版本会支持。
