### ISSUE TITLE
gte-Qwen2 Incorrect model information / 模型信息有误

### ISSUE THREAD

**Issue by JinCheng666** [xorbitsai/inference#2471]
### System Info / 系統信息

无关

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local --host 0.0.0.0 --port 49640 --log-level DEBUG &

### Reproduction / 复现过程

xinference官方文档显示，gte-qwen2的维度为3584
https://inference.readthedocs.io/en/latest/models/builtin/embedding/gte-qwen2.html
![image](https://github.com/user-attachments/assets/495223a1-e048-4cf0-839e-603c0492ac32)

hf官方xian显示，gte-qwen2的维度为4096
https://huggingface.co/Alibaba-NLP/gte-Qwen1.5-7B-instruct

modelscope显示结果与hf相同，均为4096
https://modelscope.cn/models/iic/gte_Qwen1.5-7B-instruct/summary
![image](https://github.com/user-attachments/assets/58418e8e-730e-4d52-9c64-b518e1831799)

### Expected behavior / 期待表现

修正文档及相关配置

**Comment by qinxuye** [comment]
HF 配置（错误）：

https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec.json#L236C1-L237C1

Modelscope（正确的）：

https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec_modelscope.json#L238

应该可以提交一个 PR 修复下 HF 的配置，有兴趣提交 PR 吗？

**Comment by JinCheng666** [comment]
> HF 配置（错误）：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec.json#L236C1-L237C1
> 
> Modelscope（正确的）：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec_modelscope.json#L238
> 
> 应该可以提交一个 PR 修复下 HF 的配置，有兴趣提交 PR 吗？

非常乐意。由于我是新手，我先学习下PR的规则，稍晚点我把PR提上去。

**Comment by JinCheng666** [comment]
我提交了一个PR
https://github.com/xorbitsai/inference/pull/2479

由于我是第一次提交PR，而且我并没有找到项目的PR说明，我按自己的理解提交了这个PR。
如有不合适的地方还请指出。

**Comment by qinxuye** [comment]
赞。正确做法是用 PR 来关联这个 issue，PR 合并的时候 issue 会被 close。
