### ISSUE TITLE
客户端代码 from xinference.client import Client 失效，需要统一修改为 from xinference_client import RESTfulClient as Client

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#2472]
### System Info / 系統信息

无关（win，linux都存在同样问题）

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

客户端：xinference-client         0.16.0
服务端：xinference                   0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 10.10.83.104 --port 9997

### Reproduction / 复现过程

原来的代码：from xinference.client import Client  
错误：1）找不到 xinference.client；2）找不到 Client
需要修改为：from xinference_client import RESTfulClient as Client

所涉及的地址包括——
https://inference.readthedocs.io/zh-cn/latest/reference/index.html
https://inference.readthedocs.io/zh-cn/latest/examples/index.html
https://inference.readthedocs.io/zh-cn/latest/user_guide/client_api.html
https://github.com/xorbitsai/inference/blob/main/examples/gradio_chatinterface.py
https://github.com/xorbitsai/inference/blob/main/examples/...

### Expected behavior / 期待表现

编写客户端代码时，无需再修改。

**Comment by qinxuye** [comment]
如果只安装 xinference_client 是错误的，安装了 xinference 可以正常使用。
