### ISSUE TITLE
再实际使用的过程中发现，等部署再xinference上的模型再被调用一段时间后再次请求就会没有回答。

### ISSUE THREAD

**Issue by Joker-sad** [xorbitsai/inference#2474]
### System Info / 系統信息

请求

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference=0.5.2

### The command used to start Xinference / 用以启动 xinference 的命令

啊

### Reproduction / 复现过程

a

### Expected behavior / 期待表现

期待将这个问题解决，不然投入生产中使用会是一个麻烦

**Comment by 948024326** [comment]
我0.15.2版本没有问题啊？ 一直都正常

**Comment by Joker-sad** [comment]
> 我0.15.2版本没有问题啊？ 一直都正常

那可能是我部署的原因吗，因为我经常碰到。模型被调用一段时间后，模型可以调用成功但是一直没有回复

**Comment by deific** [comment]
我也遇到了，我的版本是：0.14.2。通过xinference只部署m3e嵌入模型和bge-reranker-v2-m3重排模型。
通过主机的监控发现，正常的时候，GPU的显存使用大概11G(总共16G),CPU使用率为2%上下波动。
使用了大约20多天，突然不正常了，查看监控发现GPU显存大幅降低(11多G降为3M)，CPU使用率明显升高(0.2升为60%）。

**Comment by Joker-sad** [comment]
> > 我也遇到了，我的版本是：0.14.2。通过xinference只部署m3e嵌入模型和bge-reranker-v2-m3重排模型。 通过主机的监控发现，正常的时候，GPU的显存使用大概11G(总共16G),CPU使用率为2%上下波动。 使用了大约20多天，突然不正常了，查看监控发现GPU显存大幅降低(11多G降为3M)，CPU使用率明显升高(0.2升为60%）。
> 
> 进程还在吗？感觉像worker挂了？


进程是还在的就是不工作了

**Comment by deific** [comment]
进程还在，就是不工作了。杀掉进程重新部署就好了
