### ISSUE TITLE
Unable to launch web UI

### ISSUE THREAD

**Issue by rememberBr** [xorbitsai/inference#2475]
### System Info / 系統信息

cuda12.1 
python3.10
transformers                  4.45.2
llama_cpp_python              0.3.1
win10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/9942b630-7f46-4392-9f3b-8ec7bea2b7e3)
Xinference local startup environment, deployment model, tried llama-3.1, qwen2.5, prompt:
![532ef15fae1f509bfe58bfa52c2212e](https://github.com/user-attachments/assets/3e444049-1c52-4373-a2e7-564e344c1ba7)

### Expected behavior / 期待表现

If the configuration when deploying the model is unreasonable, I hope it can be further clarified in the document. If it is not a difference in my configuration, I hope the problem can be fixed so that the deployment can be completed completely according to the usage guide

**Comment by qinxuye** [comment]
gradio 问题，目前需要安装 gradio<3.39.0

**Comment by rememberBr** [comment]
@qinxuye 不行，出现了新的错误：
![image](https://github.com/user-attachments/assets/51a7f2dc-933e-45a4-990b-04ec9d2e6bb2)

**Comment by liuyingtao941212** [comment]
> @qinxuye 不行，切换为gradio==3.38.0和3.37.0后出现了新的错误： ![image](https://private-user-images.githubusercontent.com/34575670/379630288-51a7f2dc-933e-45a4-990b-04ec9d2e6bb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTg0MTcsIm5iZiI6MTcyOTc1ODExNywicGF0aCI6Ii8zNDU3NTY3MC8zNzk2MzAyODgtNTFhN2YyZGMtOTMzZS00NWE0LTk5MGItMDRlYzlkMmU2YmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4MjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZTQyNmVhZGIzMTE3Mjc2ZmE3Mjc0ZmQwODg1ZGY3ZDQ5OWNhMmUyYzMxYmQ4ZTMxOTYyZjk4MDcwNDUwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SnNw5Hk9WtNZ_e4SyXnrshUjPqIUjyQf2frzpCjCf6k)

我也遇到了这个问题

**Comment by qinxuye** [comment]
Fixed in #2459
