### ISSUE TITLE
Tool response dicts require a 'name' key indicating the name of the called function!

### ISSUE THREAD

**Issue by andylzming** [xorbitsai/inference#2477]
### System Info / 系統信息

CUDA Version: 12.0
Python Version: 3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference v0.15.4

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local -H 192.22.139.188 -p 59997 &

### Reproduction / 复现过程

XInference 加载 Qwen2- 72B-Instruct 模型，使用 Dify （version 0.10.0）Agent 模式调用该大模型报错。

- 错误信息如下：
Tool response dicts require a 'name' key indicating the name of the called function!

### Expected behavior / 期待表现

期待解决。

**Comment by qinxuye** [comment]
考虑使用 Qwen2.5-72b-instruct。

**Comment by andylzming** [comment]
> 考虑使用 Qwen2.5-72b-instruct。

是Qwen2模型的问题吗？Qwen2.5是否已经验证？

**Comment by Timmy-web** [comment]
同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。
ERROR    Can't parse single qwen tool call output: 
中间是回答结果
 Error: Expecting value: line 1 column 1 (char 0)

**Comment by andylzming** [comment]
> 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)

意思是qwen2.5也不行吗？

**Comment by Timmy-web** [comment]
> > 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)
> 
> 
> 
> 意思是qwen2.5也不行吗？

大概率可以正常出结果到dify，但xinference的log会有上面说的error，偶尔可能无法成功

**Comment by qinxuye** [comment]
> 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)

详细日志能贴下吗

**Comment by Timmy-web** [comment]
> > 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)
> 
> 
> 
> 详细日志能贴下吗

```
xinference-1  | INFO 10-23 19:12:30 async_llm_engine.py:206] Added request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
xinference-1  | INFO 10-23 19:12:31 metrics.py:351] Avg prompt throughput: 172.6 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%.
xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
xinference-1  | 2024-10-23 19:12:35,644 xinference.model.llm.utils 94 ERROR    Can't parse single qwen tool call output: 最新的iPhone型号是iPhone 16系列，具体包括：
xinference-1  | 
xinference-1  | - iPhone 16
xinference-1  |   - 128GB: 5999元
xinference-1  |   - 256GB: 6999元
xinference-1  |   - 512GB: 8999元
xinference-1  | 
xinference-1  | - iPhone 16 Plus
xinference-1  | - iPhone 16 Pro
xinference-1  | - iPhone 16 Pro Max
xinference-1  | 
xinference-1  | 更多详细信息和具体配置，可以访问 [Apple 官方网站](https://www.apple.com_cn/iphone/compare/) 进行查看。如果您需要了解其他型号的具体价格和配置，也可以告诉我，我会为您查询。. Error: Expecting value: line 1 column 1 (char 0)
#xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
```

**Comment by qinxuye** [comment]
> > > 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)
> > 
> > 
> > 详细日志能贴下吗
> 
> ```
> xinference-1  | INFO 10-23 19:12:30 async_llm_engine.py:206] Added request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> xinference-1  | INFO 10-23 19:12:31 metrics.py:351] Avg prompt throughput: 172.6 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%.
> xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> xinference-1  | 2024-10-23 19:12:35,644 xinference.model.llm.utils 94 ERROR    Can't parse single qwen tool call output: 最新的iPhone型号是iPhone 16系列，具体包括：
> xinference-1  | 
> xinference-1  | - iPhone 16
> xinference-1  |   - 128GB: 5999元
> xinference-1  |   - 256GB: 6999元
> xinference-1  |   - 512GB: 8999元
> xinference-1  | 
> xinference-1  | - iPhone 16 Plus
> xinference-1  | - iPhone 16 Pro
> xinference-1  | - iPhone 16 Pro Max
> xinference-1  | 
> xinference-1  | 更多详细信息和具体配置，可以访问 [Apple 官方网站](https://www.apple.com_cn/iphone/compare/) 进行查看。如果您需要了解其他型号的具体价格和配置，也可以告诉我，我会为您查询。. Error: Expecting value: line 1 column 1 (char 0)
> #xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> ```

看上去模型没有按 function call 的格式输出。

**Comment by andylzming** [comment]
> > > > 同样的问题，而且用qwen2.5的话在diy虽然能成功call出function，但是回答的log好像有以下的error。 ERROR Can't parse single qwen tool call output: 中间是回答结果 Error: Expecting value: line 1 column 1 (char 0)
> > > 
> > > 
> > > 详细日志能贴下吗
> > 
> > 
> > ```
> > xinference-1  | INFO 10-23 19:12:30 async_llm_engine.py:206] Added request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> > xinference-1  | INFO 10-23 19:12:31 metrics.py:351] Avg prompt throughput: 172.6 tokens/s, Avg generation throughput: 11.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%.
> > xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> > xinference-1  | 2024-10-23 19:12:35,644 xinference.model.llm.utils 94 ERROR    Can't parse single qwen tool call output: 最新的iPhone型号是iPhone 16系列，具体包括：
> > xinference-1  | 
> > xinference-1  | - iPhone 16
> > xinference-1  |   - 128GB: 5999元
> > xinference-1  |   - 256GB: 6999元
> > xinference-1  |   - 512GB: 8999元
> > xinference-1  | 
> > xinference-1  | - iPhone 16 Plus
> > xinference-1  | - iPhone 16 Pro
> > xinference-1  | - iPhone 16 Pro Max
> > xinference-1  | 
> > xinference-1  | 更多详细信息和具体配置，可以访问 [Apple 官方网站](https://www.apple.com_cn/iphone/compare/) 进行查看。如果您需要了解其他型号的具体价格和配置，也可以告诉我，我会为您查询。. Error: Expecting value: line 1 column 1 (char 0)
> > #xinference-1  | INFO 10-23 19:12:35 async_llm_engine.py:174] Finished request 6c1d9f6a-91ad-11ef-ab88-0242ac120002.
> > ```
> 
> 看上去模型没有按 function call 的格式输出。

请问，怎么解决呢？

**Comment by qinxuye** [comment]
模型问题。

**Comment by DCJsenior** [comment]
这个问题有后续吗，好像我遇到了同样的问题

**Comment by qinxuye** [comment]
使用 qwen2.5 系列，qwen 1.5 和 2 会有这个问题。
