### ISSUE TITLE
修复模型对话 Web UI 的 AttributeError：'Blocks' object has no attribute 'startup_events'报错

### ISSUE THREAD

**Issue by bllxk** [xorbitsai/inference#2483]
### System Info / 系統信息

cuda=12.1
python=3.11
gradio=5.0.1
Linux Mint 21.1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.4

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local

## 请按以下步骤复现此问题
1. 启动 Xinference 并点击访问模型对话 Web UI。
2. 观察到web页面无法正常显示，只有{"detail":"Not Found"}，终端报错，报错信息为 `AttributeError: 'Blocks' object has no attribute 'startup_events'`。

## 问题分析 
该问题应该是由 gradio 版本导致的。亲测在 5.0 及以上版本中，startup_events() 方法被替换为run_startup_events()，因此在新版本下运行会报错。

## 修改建议
问题代码位置：`inference/xinference/core/chat_interface.py` 文件的 第 77 行。
``` python

# 当前代码：
interface.startup_events()

# 改进建议：
if hasattr(interface, "startup_events"):
    # Gradio < 5.0
    interface.startup_events()
else:
    # Gradio >= 5.0
    interface.run_startup_events()
```

### Expected behavior / 期待表现

希望在不同版本的 gradio 环境中，模型对话 Web UI 都能正常运行，不再出现该报错。

**Comment by qinxuye** [comment]
Fixed in #2459
