### ISSUE TITLE
Always need to re-launch models after docker container restart

### ISSUE THREAD

**Issue by benamazing** [xorbitsai/inference#2484]
### System Info / 系統信息

CUDA Version: 12.4
Running with the official xinference image

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

/usr/local/bin/xinference-local -H 0.0.0.0

### Reproduction / 复现过程

docker restart <container_id>

then when viewing the running models from UI, all previous running models are gone. I need to relaunch those models.

### Expected behavior / 期待表现

I hope previous running models can be launched automatically after container restart

**Comment by nadirvishun** [comment]
临时的解决方法可以参考：[#1431](https://github.com/xorbitsai/inference/issues/1431)
