### ISSUE TITLE
使用 vLLM 启动 qwen2.5-32b-instruct 推理结果都是感叹号

### ISSUE THREAD

**Issue by andylzming** [xorbitsai/inference#2487]
### System Info / 系統信息

```
(xinference) [root@gpu-server xinference_160]# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:12:58_PDT_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0
(xinference) [root@gpu-server xinference_160]# python --version
Python 3.10.6
(xinference) [root@gpu-server xinference_160]# pip list | grep torch
torch                             2.3.0+cu121
torchaudio                        2.3.0+cu121
torchvision                       0.18.0+cu121
(xinference) [root@gpu-server xinference_160]# pip list | grep vllm
vllm                              0.4.2
vllm-nccl-cu12                    2.18.1.0.4.0
(xinference) [root@gpu-server xinference_160]# pip list | grep transformer
ctransformers                     0.2.27
sentence-transformers             2.7.0
transformers                      4.43.1
transformers-stream-generator     0.0.4
```

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

```
(xinference) [root@gpu-server xinference_160]# pip list | grep xinference
xinference                        0.16.0
xinference-client                 0.16.0
```

### The command used to start Xinference / 用以启动 xinference 的命令

```
nohup xinference-local -H 172.22.149.188 -p 59997 &
```

### Reproduction / 复现过程

- 通过 vLLM 启动 qwen2.5-32b-instruct 模型，在 xinference 提供的测试页面对话，推理结果如截图：

![1](https://github.com/user-attachments/assets/f984a57b-0da3-4c4a-a667-1484793dd153)

### Expected behavior / 期待表现

正常推理结果。

**Comment by qinxuye** [comment]
GPTQ 老问题，可以换 AWQ 试下。

**Comment by andylzming** [comment]
> GPTQ 老问题，可以换 AWQ 试下。

模型是没有量化版本

**Comment by qinxuye** [comment]
换个 system prompt 可以解决，不过 xinf 自带的聊天界面不一定有修改系统提示词的位置，你可以试下用 API。

**Comment by andylzming** [comment]
> 啥显卡啊，老的显卡有这样的问题我的p100有，但是4090ok。你把prompt搞长一点，或者继续输入就好

A800

**Comment by andylzming** [comment]
> 换个 system prompt 可以解决，不过 xinf 自带的聊天界面不一定有修改系统提示词的位置，你可以试下用 API。

有提示词也不行
![1](https://github.com/user-attachments/assets/0bcd937f-ba3a-4643-9e0f-f6c34a0e8e7d)

**Comment by qinxuye** [comment]
系统提示词，system prompt

**Comment by andylzming** [comment]
> system prompt

Dify 在哪里设置 system prompt。另外，有其他解决方法吗？

**Comment by 948024326** [comment]
> > 啥显卡啊，老的显卡有这样的问题我的p100有，但是4090ok。你把prompt搞长一点，或者继续输入就好
> 
> A800

哥们现在还有问题吗？ 我后面也是配置a800的显卡  害怕   我v100现在是ok的
