### ISSUE TITLE
Qwen2-VL-instruct总是无法导入启动

### ISSUE THREAD

**Issue by kaji331** [xorbitsai/inference#2488]
### System Info / 系統信息

CUDA 12.4，K8s部署的docker镜像，NVIDIA L40

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

K8s启动的yaml文件内容

apiVersion: apps/v1
kind: Deployment
metadata:
  name: xinference-deployment
  labels:
    app: xinference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xinference
  template:
    metadata:
      labels:
        app: xinference
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname  # 使用 hostname 作为选择条件
                operator: In
                values:
                - 172.182.8.1  # 指定要调度的节点
      containers:
      - name: xinference-container
        image: hub.west.com:50301/xinference:v0.16.0
        ports:
        - containerPort: 9997
        env:
        - name: XINFERENCE_MODEL_SRC
          value: "modelscope"
        - name: XINFERENCE_HOME
          value: "/xinference_home"
        volumeMounts:
        - mountPath: /xinference_home
          name: xinference-volume
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["xinference-local"]
        args: ["-H", "0.0.0.0", "--log-level", "debug"]
      volumes:
      - name: xinference-volume
        nfs:
          server: 172.182.201.101
          path: /data/kube/ling/xinference/data/models
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: xinference-service
spec:
  selector:
    app: xinference
  type: NodePort
  ports:
  - protocol: TCP
    port: 9998
    targetPort: 9997
    nodePort: 50315

### Reproduction / 复现过程

无论选择pytorch还是gptq还是awq，模型size都是7b。pytorch的quantization是none，gptq是int8，awq是int4。gpu都是auto，replica都是1。

结果都是
Server error: 500 - [address=0.0.0.0:39195, pid=1806] cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

### Expected behavior / 期待表现

正常启动模型

**Comment by kaji331** [comment]
> 看着像transformers版本问题，可以更新一下试试？

感谢回复，不知道docker镜像怎么更新transformers？

**Comment by Valdanitooooo** [comment]
我的服务器没外网，重新打了镜像

```Dockerfile
FROM xprobe/xinference:v0.16.0

RUN pip install tokenizers==0.20.1 transformers==4.45.2
```

**Comment by kaji331** [comment]
> 我的服务器没外网，重新打了镜像
> 
> ```dockerfile
> FROM xprobe/xinference:v0.16.0
> 
> RUN pip install tokenizers==0.20.1 transformers==4.45.2
> ```

感谢🙏，问题解决了
