### ISSUE TITLE
xinference 的 Qwen2-VL-Instruct 测试页效果比 qwen 官方还好，又找不到原因

### ISSUE THREAD

**Issue by Valdanitooooo** [xorbitsai/inference#2493]
### 测试过程

用xinference部署 Qwen2-VL-7B-Instruct-GPTQ-Int4

1. 从测试页上传图片

我看到上传的文件在：
/root/.xinference/tmp/gradio/272d52056ba8d8deb9b7bce1d3b4785f0f7d695d/test222.jpg
200k 大小

2. 执行推理，看到日志：

Add text, text: 识别图中内容, image: /root/.xinference/tmp/gradio/05892020837003fd7c1a703211aff24f9d7f200c/test222.jpeg, video: None

使用的图片地址变了
这个图片 /root/.xinference/tmp/gradio/05892020837003fd7c1a703211aff24f9d7f200c/test222.jpeg
36k 大小

图片变小了，但是效果非常精准，100% 正确

### 问题

我仔细看了Qwen2-VL仓库的代码
https://github.com/QwenLM/Qwen2-VL/blob/3bf7dbd7877892934bd7f8f4b00cd23cc2b35e4a/qwen-vl-utils/src/qwen_vl_utils/vision_process.py#L82

和xinference gradio 测试页代码(在处理图片之前，图片路径已经变成 36k 那个了)
https://github.com/xorbitsai/inference/blob/d4cd7b15104c16838e3c562cf2d33337e3d38897/xinference/core/chat_interface.py#L239

在我的应用里怎么改都达不到 xinference 测试页的效果
开始以为是参数的问题，其实没关系，就是图片的问题
下载那个 36k 的图片在我的应用里就能识别出最佳效果

即使模仿 gradio 上传的图片，也重现不出来 😅 
```
    image = gr.Image(type="filepath",value='/Users/valdanito/Downloads/test222.jpg')
    x = image.value
    response = await image_sense_qa(prompt, [x["path"]])
```

看上去这个 36k 的图片来自 gradio 的 Chatbot 对象
![image](https://github.com/user-attachments/assets/e35fdcb7-f14e-4c3c-bbc3-b9c4abd9ed3c)

但是代码里明明取的 imagebox = gr.Image(type="filepath") 对象里的值

所以很疑惑，有没有人了解这是咋回事？

**Comment by Valdanitooooo** [comment]
又测了一下，没想到真的跟 gradio 有关，而且和 gradio 版本还有关，最新版 gradio 还不行，得用 4.xx.xx 的

下面得研究下 gradio 对图片做了什么...

**Comment by cyhasuka** [comment]
> 又测了一下，没想到真的跟 gradio 有关，而且和 gradio 版本还有关，最新版 gradio 还不行，得用 4.xx.xx 的
> 
> 下面得研究下 gradio 对图片做了什么...

您好， 我也发现了该问题，请问您找到原因了吗

**Comment by Valdanitooooo** [comment]
> 您好， 我也发现了该问题，请问您找到原因了吗

@cyhasuka 我做了一些测试，还没找到根本原因，只能说跟 xinference 无关，gradio效果好只是恰好用 Pillow 库处理了一下图片

我们在gradio 社区的一些讨论 https://discord.com/channels/879548962464493619/1025174734427656283/threads/1301002234963820604

我把gradio这部分代码拿出来了 https://github.com/Valdanitooooo/chat_with_qwen2_vl_test 放在我的系统里用起来了
之前 hf 比 vllm 效果好很多，现在这样处理后即使用 vllm 效果也大幅提升

**Comment by cyhasuka** [comment]
> > 您好， 我也发现了该问题，请问您找到原因了吗
> 
> @cyhasuka 我做了一些测试，还没找到根本原因，只能说跟 xinference 无关，gradio效果好只是恰好用 Pillow 库处理了一下图片
> 
> 我们在gradio 社区的一些讨论 https://discord.com/channels/879548962464493619/1025174734427656283/threads/1301002234963820604
> 
> 我把gradio这部分代码拿出来了 https://github.com/Valdanitooooo/chat_with_qwen2_vl_test 放在我的系统里用起来了 之前 hf 比 vllm 效果好很多，现在这样处理后即使用 vllm 效果也大幅提升

我研究一下，非常感谢🎉！！
