### ISSUE TITLE
request limit限制可以设置成一个队列吗

### ISSUE THREAD

**Issue by jasinliu** [xorbitsai/inference#2496]
### Feature request / 功能建议

request limit限制可以设置成一个队列吗

### Motivation / 动机

现在的request limit到达上限后直接抛出错误，可以设置成队列，让后续请求排队等待，这样可以充分榨干显卡

### Your contribution / 您的贡献

暂时没有，如果提供一些指导的话，可以尝试做贡献

**Comment by qinxuye** [comment]
目前还不支持，欢迎贡献。目前已经引入队列了，但是没有和 request_limit 打通。

cc：https://github.com/xorbitsai/inference/pull/2473
