### ISSUE TITLE
Jetson 可不可以部署xinference？我在信息上发现xinference没有获取到GPU的信息，在对话的时候明显发现很慢，应该是只调用了cpu的算力

### ISSUE THREAD

**Issue by GengyuXu** [xorbitsai/inference#2499]
### System Info / 系統信息

Jetson AGX Orin 64GB
jetpack 6.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

0.16.1

### The command used to start Xinference / 用以启动 xinference 的命令

X_INFERENCE_HOME=/mnt/data/x_inference_data/data XINFERENCE_MODEL_SRC=modelscope xinference-local --host 127.0.0.1 --port 9997

### Reproduction / 复现过程

![微信图片_20241030204704](https://github.com/user-attachments/assets/4a6f4061-1597-4f6e-8bfa-56dc3a9ff6d4)

### Expected behavior / 期待表现

希望调用gpu，提高对话速度

**Comment by qinxuye** [comment]
看下 

```
import torch
print(torch.cuda.is_available())
```

结果。

**Comment by 3109607298** [comment]
请问你是怎么在jeston上部署的xinference的？
