### ISSUE TITLE
cl: 命令行 error D8021 :无效的数值参数“/Wno-register”

### ISSUE THREAD

**Issue by tsxuzhiqiang** [xorbitsai/inference#2507]
### System Info / 系統信息

![image](https://github.com/user-attachments/assets/ea91df95-3353-48f4-be1e-8b8db1f28b52)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Version 0.16.1

### The command used to start Xinference / 用以启动 xinference 的命令

pip install "xinference[all]"  -i https://pypi.tuna.tsinghua.edu.cn/simple

### Reproduction / 复现过程

安装
pip install "xinference[all]"  -i https://pypi.tuna.tsinghua.edu.cn/simple

### Expected behavior / 期待表现

![image](https://github.com/user-attachments/assets/2a2d53e3-e805-443e-bdd2-a1ba33710dca)

**Comment by qinxuye** [comment]
```
conda install -c conda-forge pynini=2.1.5
```

先安装这个再安装 xinference。
