### ISSUE TITLE
xinference[vllm]无法单机多卡启动一个模型

### ISSUE THREAD

**Issue by Weishaoya** [xorbitsai/inference#2513]
### System Info / 系統信息

ubuntu 22.04
python 3.11.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference[vllm] 0.16.2

### The command used to start Xinference / 用以启动 xinference 的命令

 GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 xinference-local --host 0.0.0.0 --port 10860

### Reproduction / 复现过程

我直接用vllm框架在两张v100 16g上启动一个7b的模型，是没有问题的，而且可以正常对话。
当我用xinference[vllm]在两张v100 16g上启动一个7b的模型，它报错了，以下是我的参数设置和报错信息：
![image](https://github.com/user-attachments/assets/2f3722fd-1605-4165-bd4f-62da14d39209)
![image](https://github.com/user-attachments/assets/ea9181d1-2e5b-4e4d-96b7-bd426aa879ce)
![image](https://github.com/user-attachments/assets/11e48965-a623-4170-a532-e5e7266e6b69)

### Expected behavior / 期待表现

我现在在用ragflow框架，推理服务接的xinference, 这对我很重要，希望官方能重视这个bug.

**Comment by Weishaoya** [comment]
> 不需要设置tensor_parallel_size，去掉试试。
![image](https://github.com/user-attachments/assets/2337e200-77dc-4688-8a45-a403e6938298)
![image](https://github.com/user-attachments/assets/86a1bc9f-f771-418b-8c6d-5c9327bb37cb)
![image](https://github.com/user-attachments/assets/4c2cec4b-94bb-4f18-91a8-0dc4d345bf43)
我去掉了tensor_parallel_size参数设置，它报另外一个错误，以上是报错信息。希望你们能修复这个bug，感谢！

**Comment by redreamality** [comment]
same issue
