### ISSUE TITLE
An error was reported importing the image2tex model

### ISSUE THREAD

**Issue by ZxnSnowy** [xorbitsai/inference#2518]
### System Info / 系統信息

linux

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1、XINFERENCE_MODEL_SRC=modelscop xinference launch --model-name GOT-OCR2_0 --model-type image --gpu-idx 3
2、导入成功但报错
![image](https://github.com/user-attachments/assets/7cccc314-02cf-4b0b-b2ad-91eacb33ced7)
3、python能使用模型client.get_model("GOT-OCR2_0")
4、但是导入ragflow中报错：Fail to access model(GOT-OCR2_0).HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
5、在ragflow中导入ChatTTS不会报错

### Expected behavior / 期待表现

我希望可以成功导入ragflow中image2text模型

**Comment by ZxnSnowy** [comment]
@codingl2k1 请问您知道如何处理这个问题吗？

**Comment by DankerMu** [comment]
我在导入qwen2-vl时同样遇到了这个问题
