### ISSUE TITLE
xinference部署的qwen模型怎样在后台看到request请求的日志及问的内容

### ISSUE THREAD

**Issue by wangyongpenga** [xorbitsai/inference#2521]
### Feature request / 功能建议

xinference部署的qwen模型怎样在后台看到request请求的日志及问的内容

### Motivation / 动机

xinference部署的qwen模型怎样在后台看到request请求的日志及问的内容

### Your contribution / 您的贡献

xinference部署的qwen模型怎样在后台看到request请求的日志及问的内容

**Comment by qinxuye** [comment]
启动的时候指定 --log-level DEBUG 可以看到
