### ISSUE TITLE
部署glm-4v-9b模型后，模型可以加载但是无法进行对话，报[address=0.0.0.0:33271, pid=892267] ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by GengyuXu** [xorbitsai/inference#2523]
### System Info / 系統信息

jetson agx orin

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

0.16.1

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/mnt/data/xinference_data XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/743386cb-7405-410b-a169-fc8c8556c536)

### Expected behavior / 期待表现

能够进行正常的对话

**Comment by Erincrying** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by GengyuXu** [comment]
> 我也遇到了同样的问题，请问你解决了吗

更新hugging face上最新的tokenization_chatglm.py文件再试一下，但是我报了另外的错误

**Comment by Erincrying** [comment]
> > 我也遇到了同样的问题，请问你解决了吗
> 
> 更新hugging face上最新的tokenization_chatglm.py文件再试一下，但是我报了另外的错误

请问是直接改的安装的hugging face的源码吗，后来又解决不

**Comment by GengyuXu** [comment]
> > > 我也遇到了同样的问题，请问你解决了吗
> > 
> > 
> > 更新hugging face上最新的tokenization_chatglm.py文件再试一下，但是我报了另外的错误
> 
> 请问是直接改的安装的hugging face的源码吗，后来又解决不

直接修改那个py程序，不会报padding_size的报错，但是报其他的错误，你可以试着更新一下看看会不会报其他错误
