### ISSUE TITLE
vllm后端启动不支持异步

### ISSUE THREAD

**Issue by prettyprettyboy** [xorbitsai/inference#2529]
在xinference选择用vllM后端启动，不能支持异步输出多个人。同时问的时候只有一个人回答，完了之后另一个人才回答。但是直接用vl LM的API server启动模型可以支持异步

**Comment by prettyprettyboy** [comment]
vllm 0.6默认支持异步，不应该啊，难道xinference还把这个功能特地关了

**Comment by qinxuye** [comment]
可以回答，你说的是我们自带的聊天界面吧？

**Comment by qinxuye** [comment]
哦，你说的是async api？

**Comment by prettyprettyboy** [comment]
http://0.0.0.0:9997/v1不支持。不过我看debug log时候,vllm就是启动的asyncengine，不知道为啥不支持，单独用vllm镜像启动就可以并发

**Comment by qinxuye** [comment]
并发显然可以支持，这是最基本的。

**Comment by 949600981** [comment]
@prettyprettyboy  我也遇到了xinference选择用transformers引擎启动后，模型不支持异步，不知道您是否已解决这个问题？
