### ISSUE TITLE
加载 qwen2-vl-instruct 报错：cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers'

### ISSUE THREAD

**Issue by EthanKk** [xorbitsai/inference#2549]
### System Info / 系統信息

docker 镜像 0.16.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

docker 镜像 0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

通过 WebUI 启动 qwen2-vl-instruct

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/6bf49418-3399-411f-887c-132b67303b9d)

### Expected behavior / 期待表现

启动成功

**Comment by qinxuye** [comment]
镜像里更新下 transformers 版本。
