### ISSUE TITLE
启动FLUX.1-schnell 报错，

### ISSUE THREAD

**Issue by James-Dao** [xorbitsai/inference#2557]
### System Info / 系統信息

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/f3e8bab4-9ad2-46c3-b1e8-2631ee1ca394">

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

页面部署

### Reproduction / 复现过程

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/20553c7e-67be-40d5-b413-fd796431ee9c">

### Expected behavior / 期待表现

应该可以正常启动

**Comment by qinxuye** [comment]
刚刚更新 1.0.0 修复了这个问题，可以尝试新版本

**Comment by qinxuye** [comment]
Close first, feel free to reopen if you have any issue.
