### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ChengRuiLiang** [xorbitsai/inference#2560]
### System Info / 系統信息

xinference, version 0.16.3
Ubuntu 22.04.5 LTS

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

![1732016175468](https://github.com/user-attachments/assets/15ab157d-d34f-4619-b138-e8938079b8b3)
![1732016476595](https://github.com/user-attachments/assets/8eb1e465-905d-49df-a0b8-46dd485c5442)

### Expected behavior / 期待表现

能正常返回处理结果

**Comment by ChengRuiLiang** [comment]
没有开代理

**Comment by workcode-del** [comment]
请问解决了吗，我也碰到了这个问题

**Comment by zachary-zheng** [comment]
Same here, how to deal with it?
