### ISSUE TITLE
rerank模型不返回document信息

### ISSUE THREAD

**Issue by mengxianglong123** [xorbitsai/inference#2566]
### System Info / 系統信息

Ubuntu 22

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.16.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1. 启动rerank模型
2. 按照官网文档调用接口

### Expected behavior / 期待表现

document字段有内容，但是实际为null

**Comment by mengxianglong123** [comment]
参考的命令如下
```
curl -X 'POST' \
  'http://<XINFERENCE_HOST>:<XINFERENCE_PORT>/v1/rerank' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "<MODEL_UID>",
    "query": "A man is eating pasta.",
    "documents": [
        "A man is eating food.",
        "A man is eating a piece of bread.",
        "The girl is carrying a baby.",
        "A man is riding a horse.",
        "A woman is playing violin."
    ]
  }'
```

**Comment by ljqiff** [comment]
rerank API 定义与 cohere rerank api 接口兼容，如果需要返回 Document，需要指定 return_documents=True
https://github.com/xorbitsai/inference/blob/main/xinference/model/rerank/core.py#L229-L246
