### ISSUE TITLE
Add download progress management or optimizing logs

### ISSUE THREAD

**Issue by redreamality** [xorbitsai/inference#2567]
### Feature request / 功能建议

Add download progress management, which is useful for pulling large models from hubs.

### Motivation / 动机

The status of the models that are being downloaded cannot be observed.

### Your contribution / 您的贡献

TBD

**Comment by qinxuye** [comment]
This is reasonable, actually, we introduce progress API(#2395 ) already, but it's for image generation only for now, we can support progress for launching, and use some way to illustrate it on the web. 

Any feedback is welcomed.
