### ISSUE TITLE
加载本地ChatGLM2-6b报错，找不到generation_config.json

### ISSUE THREAD

**Issue by congge27** [xorbitsai/inference#2568]
### System Info / 系統信息

Cuda12.4
centos stream 9
python 3.12.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

python -m xinference-cmdline 。。。。。。

### Reproduction / 复现过程

1.加载模型
2.在webui页面使用对话功能
3.提示在本地模型文件夹找不到generation_config.json文件，ChatGLM2-6b没有这个文件，所以是不支持吗还是

### Expected behavior / 期待表现

不知道是不是不支持chatglm2-6b

**Comment by qinxuye** [comment]
ChatGLM2 太老了，Xinference 不再支持。
