### ISSUE TITLE
Xinference use chattts BUG

### ISSUE THREAD

**Issue by NieSf** [xorbitsai/inference#2570]
### System Info / 系統信息

curl -X 'POST' \
  'http://192.168.100.251:9997/v1/audio/speech' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "ChatTTS",
    "input": "你好",
    "voice": "Echo",
    "response_format":"wav"
  }'

By using WAV format, speech can be generated very successfully. But if the request format is changed to mp3, only the following garbled code will be obtained:
ID3#TSSELavf60.16.100ÿ俉nfoLavf

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 192.168.100.251 --port 9997 --log-level debug

### Reproduction / 复现过程

curl -X 'POST' \
  'http://192.168.100.251:9997/v1/audio/speech' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "ChatTTS",
    "input": "你好",
    "voice": "Echo",
    "response_format":"mp3"
  }'

### Expected behavior / 期待表现

This problem has been bothering me for a long time, and I hope some friends can give me some help

**Comment by NieSf** [comment]
When requesting MP3 format, the correct response cannot be obtained. In this case, xinference debug mode does not output any errors
![111](https://github.com/user-attachments/assets/640a98aa-add6-4274-bd37-4c110d918616)

**Comment by qinxuye** [comment]
@codingl2k1 Can you help?

**Comment by NieSf** [comment]
I requested MP3 format through the curl command above, but xinference only provided me with this information, and the specific content seems to be missing. However, requesting in WAV format is a normal return. I don't know if it's because I'm missing any components on my end

ID3#TSSELavf60.16.100ÿ俉nfoLavf
