### ISSUE TITLE
/v1/completions prompt输入无效

### ISSUE THREAD

**Issue by alvinlee518** [xorbitsai/inference#2572]
### System Info / 系統信息

release '24.04.1 LTS' 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

CPU Info | Usage: 0.04Total: 8.00
-- | --
CPU Memory Info | Usage: 5189.59MiBTotal: 29692.38MiB
GPU Info | Total: 1.00
GPU Memory Info | Usage: 5868.06MiBTotal: 23028.00MiB
Version | Release: v0.16.3Commit: 85ab86bf1c0967e45fbec995534cd5a0c9a9c439

### The command used to start Xinference / 用以启动 xinference 的命令

通过pip install --upgrade "xinference[all]"执行升级到版本v0.16.3

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/acdfdce4-e11f-402c-aac5-3acef6fe43b1)
![image](https://github.com/user-attachments/assets/f0d245aa-39ed-4d8b-a38b-1023f40956ae)

无论输入任何提示词都只返回模型的自我介绍网页上模拟是正常的

### Expected behavior / 期待表现

不同的提示词能有不同表现

**Comment by alvinlee518** [comment]
![image](https://github.com/user-attachments/assets/465f8a23-3813-46cb-b472-3a381c6ca20c)
更换模型后也不行

**Comment by qinxuye** [comment]
不是这么用的，https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/chat.html#chat-api

**Comment by alvinlee518** [comment]
![image](https://github.com/user-attachments/assets/e5f1ca65-0f08-4fba-8f08-afc7ed987689)
限制了chat 模型 不能使用Generate API 吗 
@qinxuye

**Comment by qinxuye** [comment]
chat可以用generate

**Comment by alvinlee518** [comment]
目前测试下来 Model Ability为 Chat的模型用不了 Generate API 

如果选择Model Ability为Generate 可以使用

**Comment by qinxuye** [comment]
那可以开个新的issue。
