### ISSUE TITLE
xinference v1.0.0及以下版本需要升级transformer 4.45或以上，才可以正常启动qwen2-VL-instruct 模型

### ISSUE THREAD

**Issue by cnrbi1** [xorbitsai/inference#2573]
### System Info / 系統信息

容器镜像中的transformers版本是4.44.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference v1.0.0、xinference v0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker run --name xinference -d -p 9997:9997  --restart always -e XINFERENCE_HOME=/data  -e XINFERENCE_MODEL_SRC=modelscope  -v xinference_data:/data --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

### Reproduction / 复现过程

启动中报错：Server error. 500 - [address=0.0.0.0.44775, pid=952] cannot import name 'Qwen2VLForconditionalGeneration'
from "transformers' (/usr/local/lib/python3.10/distpackages/transformers/ init .py)

### Expected behavior / 期待表现

xinference v1.0.0及以下版本需要升级transformer 4.45或以上，才可以正常启动qwen2-VL-instruct 模型。建议容器对镜像中的transformer版本升级到4.45以上，当前是4.46可正常运行

**Comment by qinxuye** [comment]
欢迎提 PR 修改：

https://github.com/xorbitsai/inference/blob/f2b22bb4fde28270e26c44960086a28d5d16516b/xinference/deploy/docker/requirements.txt#L28
