### ISSUE TITLE
xinference-client rerank has some bug

### ISSUE THREAD

**Issue by swy0915** [xorbitsai/inference#2574]
### System Info / 系統信息

Running rerank demo code error
![pic1](https://github.com/user-attachments/assets/ce958623-10ad-4a8e-9f47-8d6795035069)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker start

### Reproduction / 复现过程

I checked the source code and found that there may be an issue with this section of code
![pic2](https://github.com/user-attachments/assets/6fc29aad-c72e-4741-afc1-9baa05a058d7)

### Expected behavior / 期待表现

I commented out a piece of code, it's correct
![pic3](https://github.com/user-attachments/assets/ac4b505b-31c8-4cb2-a05f-01bcfa56f111)

**Comment by qinxuye** [comment]
Which version of `xinference-client` do you have?

**Comment by swy0915** [comment]
v0.16.3



---- Replied Message ----
| From | Xuye ***@***.***> |
| Date | 11/24/2024 00:54 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xorbitsai/inference] xinference-client rerank has some bug (Issue #2574) |

Which version of xinference-client do you have?

**Comment by swy0915** [comment]
你可以看源代码



---- Replied Message ----
| From | Xuye ***@***.***> |
| Date | 11/24/2024 00:54 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xorbitsai/inference] xinference-client rerank has some bug (Issue #2574) |

Which version of xinference-client do you have?
