### ISSUE TITLE
Dify调用xinfer中的rerank模型正常，ragflow调用xinfer中的rerank模型就OOM了

### ISSUE THREAD

**Issue by cnrbi1** [xorbitsai/inference#2575]
### System Info / 系統信息

xinfer官方标准docker容器镜像运行，宿主机环境ubuntu 24.04 A10双卡 Driver Version: 565.57.01

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xiner 0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker run --name xinference -d -p 9997:9997  --restart always -e XINFERENCE_HOME=/data  -e XINFERENCE_MODEL_SRC=modelscope  -v xinference_data:/data --gpus all xprobe/xinference:v0.16.3 xinference-local -H 0.0.0.0

### Reproduction / 复现过程

ragflow中使用xinfer的bge rarank v2 m3 检索测试，报keyerror(results)错误，此时发现xinfer中的rerank模型OOM重启；
DIFY环境中使用同样的模型检索测试，一切正常，也不会出现OOM现象。
[ragflow访问xinfer的rerank模型时xinfer显示oom日志信息.txt](https://github.com/user-attachments/files/17881965/ragflow.xinfer.rerank.xinfer.oom.txt)

### Expected behavior / 期待表现

如上

**Comment by qinxuye** [comment]
有没有能直接复现这个结果的文档或者之类的，可以脱敏。让我们能直接复现这个过程。
