### ISSUE TITLE
 pip install "xinference[all]"报错

### ISSUE THREAD

**Issue by liguoyu666** [xorbitsai/inference#2577]
### System Info / 系統信息

win10，cuda12.1，python3.11和python3.12

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

the latest

### The command used to start Xinference / 用以启动 xinference 的命令

conda新建的两个环境
python3.11环境报错
` Downloading http://mirrors.aliyun.com/pypi/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
---------------------------------------- 627.6/627.6 kB 5.9 MB/s eta 0:00:00
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\Administrator\AppData\Local\Temp\pip-install-x8gi9xxy\pynini_f0f67c39303240c3bde8139df9dc00bc\setup.py", line 22, in
from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

python3.12环境报错：
` import pkg_resources
File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-akf2gizd\overlay\Lib\site-packages\pkg_resources_init_.py", line 2172, in
register_finder(pkgutil.ImpImporter, find_on_path)
^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
[end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

### Reproduction / 复现过程

 pip install "xinference[all]"

### Expected behavior / 期待表现

是否支持windows

**Comment by qinxuye** [comment]
参考

https://github.com/xorbitsai/inference/issues/1702#issuecomment-2185586509

**Comment by liguoyu666** [comment]
> 参考
> 
> [#1702（评论）](https://github.com/xorbitsai/inference/issues/1702#issuecomment-2185586509)

谢谢，该方法有效，另外，貌似不支持python3.12，换成python3.11就成功运行了
