### ISSUE TITLE
模型无法选择gpu，只有cpu选项

### ISSUE THREAD

**Issue by wz96cj** [xorbitsai/inference#2578]
### System Info / 系統信息

cuda:12.4
操作系统：win--wsl2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference:0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/home/xxx/xinference/ xinference-local --host 0.0.0.0 --port 9997 --log-level debug

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/4a4585b8-2c2c-4123-bb0b-c2302d47b4c5)
![image](https://github.com/user-attachments/assets/f3567872-1e9a-4993-85e8-d6225b53fa8e)
![image](https://github.com/user-attachments/assets/b2a01408-0774-416d-9106-e53273c0a610)

### Expected behavior / 期待表现

可以选择gpu

**Comment by qinxuye** [comment]
```
python -c "import torch; print(torch.cuda.is_available())"
```

跑下看下。

**Comment by wz96cj** [comment]
> ```
> python -c "import torch; print(torch.cuda.is_available())"
> ```
> 
> 跑下看下。

输出也是true 不知道是win10--wsl的原因 在win11的wsl上跑了一套是正常的
