### ISSUE TITLE
 Model Ability为 Chat 的模型无法使用 Generate API

### ISSUE THREAD

**Issue by alvinlee518** [xorbitsai/inference#2586]
### System Info / 系統信息

release '24.04.1 LTS'

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

CPU Info | Usage: 0.02Total: 8.00
-- | --
CPU Memory Info | Usage: 2922.32MiBTotal: 29692.38MiB
GPU Info | Total: 1.00
GPU Memory Info | Usage: 14115.31MiBTotal: 23028.00MiB
Version | Release: v0.16.3Commit: 85ab86bf1c0967e45fbec995534cd5a0c9a9c439

### The command used to start Xinference / 用以启动 xinference 的命令

通过pip install --upgrade "xinference[all]"执行升级到版本v0.16.3

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/20e85783-4383-4a32-806e-65e6a171a4eb)
![image](https://github.com/user-attachments/assets/4288c864-5572-40dc-87a1-6f1406780393)

### Expected behavior / 期待表现

Generate API可以正常使用

**Comment by qinxuye** [comment]
Our resource is limited, PR and help welcomed to solve this issue.
