### ISSUE TITLE
Codestral v0.1 Pytorch Wrong Resource

### ISSUE THREAD

**Issue by danialcheung** [xorbitsai/inference#2588]
### System Info / 系統信息

Irrelevant

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

1.0.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 3000

### Reproduction / 复现过程

1. Try running: xinference launch --model-engine ${engine} --model-name codestral-v0.1 --size-in-billions 22 --model-format pytorch --quantization ${quantization}
2. Get mistral Instruct [instead](https://github.com/xorbitsai/inference/blob/760f31fe37853b81efb1516266e2436ef58a4a70/xinference/model/llm/llm_family.json#L3414)

### Expected behavior / 期待表现

To be able to pull from the correct URI

**Comment by qinxuye** [comment]
Thanks for pointing out, welcome to send a PR to fix it.

**Comment by danialcheung** [comment]
PR sent! https://github.com/xorbitsai/inference/pull/2590

**Comment by qinxuye** [comment]
Thanks, nice work.
