### ISSUE TITLE
Qwen2/2.5 with MLX engine miss Chinese character in each line. 

### ISSUE THREAD

**Issue by wanfade** [xorbitsai/inference#2591]
### System Info / 系統信息

python3.10, macos, installed with MLX engine.

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997 

### Reproduction / 复现过程

Install qwen2-instruct by xinference GUI, and test in gradio:
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/6deabed3-c9ff-424f-95d8-513b5f7d27b1">

### Expected behavior / 期待表现

Complete answer

**Comment by qinxuye** [comment]
I can reproduce, I will dive into to see what's going on.
