### ISSUE TITLE
官网文档提供的docker pull registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference，拉不下来

### ISSUE THREAD

**Issue by Weishaoya** [xorbitsai/inference#2596]
lw10052696@ubuntu-22:~$ docker pull registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference
Using default tag: latest
latest: Pulling from xprobe_xinference/xinference
80888bc6716f: Already exists 
fbcd35dc5bc3: Already exists 
c7232af9ae05: Already exists 
db6cdef1932a: Already exists 
56dc85502937: Already exists 
9f61b3db38d6: Waiting 
^Ccontext canceled
lw10052696@ubuntu-22:~$ docker pull registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference
Using default tag: latest
latest: Pulling from xprobe_xinference/xinference
80888bc6716f: Already exists 
fbcd35dc5bc3: Already exists 
c7232af9ae05: Already exists 
db6cdef1932a: Already exists 
56dc85502937: Already exists 
9f61b3db38d6: Waiting 
^Ccontext canceled
lw10052696@ubuntu-22:~$ 

公司不能连外网，官方文档提供的源拉不下来（这个9f61b...始终不下载），还有更好的方案吗

**Comment by Valdanitooooo** [comment]
层较大需要内存多，是不是拉镜像的机器内存不够

**Comment by Weishaoya** [comment]
> 层较大需要内存多，是不是拉镜像的机器内存不够

谢谢！应该是你说的原因，这台linux虚拟机只有4g内存，我重启一下，拉取成功了
