### ISSUE TITLE
Model Engine 使用 Transformers 参数max_tokens 无效 

### ISSUE THREAD

**Issue by alvinlee518** [xorbitsai/inference#2601]
### System Info / 系統信息

Count | 1
-- | --
CPU Info | Usage: 0.28Total: 4.00
CPU Memory Info | Usage: 6547.27MiBTotal: 7959.46MiB
Version | Release: v1.0.0Commit: 4c96475b8f90e354aa1b47856fda4db098b62b65

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

pip install tokenizers==0.20.1 transformers==4.45.2 qwen-vl-utils==0.0.8

### The command used to start Xinference / 用以启动 xinference 的命令

xinference launch -e http://127.0.0.1:9997 -en Transformers -t LLM -n qwen2.5-instruct -s 0_5 -f pytorch -q none

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/b5d6249d-e0db-4875-9b4d-a2468bccbf0a)

### Expected behavior / 期待表现

completion_tokens 返回正常

**Comment by qinxuye** [comment]
返回的 token 个数正确吗？

**Comment by alvinlee518** [comment]
不会，限制了 max_token=2 为什么还返回17呢

**Comment by qinxuye** [comment]
目前有decode round 的概念，我记得默认16，这个是为了减少decode调度开销。
