### ISSUE TITLE
Vllm inference with a Lora module on top of Qwen2.5-7B-Instruct prompts error.

### ISSUE THREAD

**Issue by wingtch** [xorbitsai/inference#2609]
### System Info / 系統信息

Cuda version: 12.6
transformers version: 4.44.2
vllm version: 0.6.0
python version: 3.10
OS version: Ubuntu 20.04.6 LTS \n \l (docker)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

`docker run -d -it -e XINFERENCE_MODEL_SRC=modelscope   -e XINFERENCE_HOME=/root/xhome   -v /home/huangyz/xhome:/root/xhome   -v /mnt/d/models:/mnt/models   -p 9998:9997 --gpus all   xprobe_xinference/xinference:v0.16.3 xinference-local -H 0.0.0.0 --log-level debug`

### Reproduction / 复现过程

1、使用LLmaFactory对Qwen2.5-7B-Instruct进行微调，得到一份adaptor(train_2024-11-29-14-10-24)
2、使用xinference拉起Qwen2.5-7B-Instruct模型（Transformers框架），界面填入lora配置：
lora_name=train_2024-11-29-14-10-24, local_path=/mnt/models/lora_adapt/train_2024-11-29-14-10-24
3、使用xinference的chatbot界面聊天，Additional Input中LoRA name填入：train_2024-11-29-14-10-24，可正常返回，且lora微调有效。
4、关闭模型，改用vllm拉起Qwen2.5-7B-Instruct模型，lora配置同上。使用chatbot界面聊天且填入LoRA name后报错：
data did not match any variant of untagged enum ModelWrapper at line 757443 column 3

请见附件日志。
[xinference_vllm_lora_0.16.3.log](https://github.com/user-attachments/files/17956356/xinference_vllm_lora_0.16.3.log)

### Expected behavior / 期待表现

能正常对话。

**Comment by qinxuye** [comment]
升级 transformers 试下。
