### ISSUE TITLE
文生图FLUX.1-dev多副本运行，但是调用接口生成图片依然是队列生成

### ISSUE THREAD

**Issue by turndown** [xorbitsai/inference#2617]
### System Info / 系統信息

操作系统"openEuler 20.03 (LTS-SP3)
Cuda V12.5.40
conda虚拟环境Python 3.11.9
transformers 4.46.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.15.3+1.g26b5097

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/data/inference/.xinference XINFERENCE_MODEL_SRC=modelscope nohup xinference-local --host 0.0.0.0 --port 30002 --log-level debug > output.log 2>&1 &

### Reproduction / 复现过程

文生图运行选择replica 为2，运行在2，3卡上
![image](https://github.com/user-attachments/assets/e19ba547-1ed0-49e8-9016-4bf336757dd6)
可以看到运行了两个副本：
![image](https://github.com/user-attachments/assets/7bf05631-7a32-49d0-ad92-6d56d45241d7)
然后通过postman调用接口，可以看到id并在后台执行：
http://10.36.162.18:30002/FLUX.1-dev/call/text_generate_image
{
  "data": [
    "A beautiful cat",
    1,
    1024,
    1024,
    7.5,
    50,
    "No urban elements, no people",
    "default"
  ]
}
![image](https://github.com/user-attachments/assets/70be2036-5298-40ef-874c-5b045a3071fb)
![image](https://github.com/user-attachments/assets/4b8f2d3e-7534-4ba4-839e-b98f4902e207)
我直接调用两次，但是并没有出现两个生图的进程，是队列形式的。

### Expected behavior / 期待表现

期望调用接口能实现两路并发生图，因为起了两个副本，理论上应该直接能两路同时生图才对吧。
大哥们帮忙看下，谢谢！

**Comment by qinxuye** [comment]
尝试去掉 gpu idx 的配置看下，目前这个应该是应用到单个 replica 的。

**Comment by turndown** [comment]
> 尝试去掉 gpu idx 的配置看下，目前这个应该是应用到单个 replica 的。

感谢答复。现在0卡和1卡在用，去掉index会报错，中午休息的时候我把0卡和1卡的模型停了我再试下。

另外，你后面说的         “目前这个应该是应用到单个 replica 的”       意思是文生图目前还不支持多副本是吗？

**Comment by turndown** [comment]
> 尝试去掉 gpu idx 的配置看下，目前这个应该是应用到单个 replica 的。

啊，我不小心点

**Comment by qinxuye** [comment]
支持多副本，gpu idx 是指定副本运行在哪个卡上，目前在 replica >=2 上不确定是什么行为，之前这个是给 replica=1，指定分配到哪个显卡用的。可以去掉这个设置，让 xinference 自动分配 2 个 replica。

**Comment by qinxuye** [comment]
> > 尝试去掉 gpu idx 的配置看下，目前这个应该是应用到单个 replica 的。
> 
> 但是我在配置多副本的情况下，他确实启动了两个，并占用了两张卡的显存。

先去掉看下。

**Comment by turndown** [comment]
> > > 尝试去掉 gpu idx 的配置看下，目前这个应该是应用到单个 replica 的。
> > 
> > 
> > 但是我在配置多副本的情况下，他确实启动了两个，并占用了两张卡的显存。
> 
> 先去掉看下。

直接去掉我试了，运行报这个错误：
![image](https://github.com/user-attachments/assets/d98eb4b5-5810-4ac6-b85e-57c63d41fc71)
Traceback (most recent call last):
  File "/data/inference/xinference/api/restful_api.py", line 1002, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/data/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/anaconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/inference/xinference/core/supervisor.py", line 1041, in launch_builtin_model
    await _launch_model()
  File "/data/inference/xinference/core/supervisor.py", line 1005, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/data/inference/xinference/core/supervisor.py", line 984, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/data/inference/xinference/core/utils.py", line 90, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/inference/xinference/core/worker.py", line 864, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(
  File "/data/inference/xinference/core/worker.py", line 555, in _create_subpool
    else self.allocate_devices(model_uid=model_uid, n_gpu=gpu_cnt)
  File "/data/inference/xinference/core/worker.py", line 453, in allocate_devices
    raise RuntimeError("No available slot found for the model")
RuntimeError: [address=0.0.0.0:57293, pid=30769] No available slot found for the model

**Comment by turndown** [comment]
> 支持多副本，gpu idx 是指定副本运行在哪个卡上，目前在 replica >=2 上不确定是什么行为，之前这个是给 replica=1，指定分配到哪个显卡用的。可以去掉这个设置，让 xinference 自动分配 2 个 replica。

我现在是四张卡，前两张卡被占用着，所以才会报这个错吧。
我之前指定的2、3卡，0、1卡现在人家在用还不能停，中午午休我再试下再反馈。

**Comment by qinxuye** [comment]
CUDA_VISIBLE_DEVICE=2,3 xinference-local xxxx

你可以启动 xinf 的时候限定好使用的卡。

**Comment by turndown** [comment]
> CUDA_VISIBLE_DEVICE=2,3 xinference-local xxxx
> 
> 你可以启动 xinf 的时候限定好使用的卡。

你好，0，1卡服务我停了，我现在不加index参数直接运行2个副本：
![image](https://github.com/user-attachments/assets/358092a8-155e-48b4-9b12-3e12431c1d5e)
然后调用接口或者web测试生图，还是排队的，没有两张图同时并发

**Comment by turndown** [comment]
> 支持多副本，gpu idx 是指定副本运行在哪个卡上，目前在 replica >=2 上不确定是什么行为，之前这个是给 replica=1，指定分配到哪个显卡用的。可以去掉这个设置，让 xinference 自动分配 2 个 replica。

请问多副本并行任务这个你们是怎么测试的呢？是不是我的调用方法有问题
我直接web端多开也试了，postman也试了，都是一样的排队效果
![image](https://github.com/user-attachments/assets/ac8a591d-1bcf-45a3-ab7d-d46431b99bfe)
![image](https://github.com/user-attachments/assets/347a2a22-e657-45bf-920f-42a16cc92c84)

**Comment by qinxuye** [comment]
哦，你用的我们界面测试的？这个是 gradio 的限制，他本身就一个并发，需要设置环境变量。

```
GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 xinference-local xxx
```

**Comment by turndown** [comment]
> 哦，你用的我们界面测试的？这个是 gradio 的限制，他本身就一个并发，需要设置环境变量。
> 
> ```
> GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 xinference-local xxx
> ```

我用postman测试接口也试了一样的，看的这个后台输出日志：
![image](https://github.com/user-attachments/assets/eb4e94c9-071d-4427-94e9-301b38292757)
![image](https://github.com/user-attachments/assets/c3b6b760-82ed-4d63-8cb5-5c03dcba55a6)
调用接口的形式并发也需要设置什么参数吗？

**Comment by qinxuye** [comment]
你 postman 调用的看上去是 gradio 的接口。

1. 你可以试验我说的环境变量。
2. Xinference  API 是调用：https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/image.html#text-to-image

**Comment by turndown** [comment]
> 你 postman 调用的看上去是 gradio 的接口。（因此依然受 gradio 并发约束）
> 
> 1. 你可以试验我说的环境变量。
> 2. Xinference  API 是调用：https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/image.html#text-to-image

噢，我以为页面上的那个接口就是api的调用。
我测试了你发的文档，这个接口可以实现并发！！！感谢！！
![image](https://github.com/user-attachments/assets/c95ec5fd-2b82-47d6-96d5-41f859b90e9d)
![image](https://github.com/user-attachments/assets/c68a7153-5069-4869-a907-dd1cddea76ba)

**Comment by qinxuye** [comment]
那先 close 这个 issue。

**Comment by turndown** [comment]
> GRADIO_DEFAULT_CONCURRENCY_LIMIT=10

好的，再附上这个参数内容，加上后web上的接口和生成图片也可以并发了。
GRADIO_DEFAULT_CONCURRENCY_LIMIT=10
但是有个问题，为什么我访问调用接口返回的链接会提示notfound，但是直接界面上f12上面的图片链接却能正常。
![image](https://github.com/user-attachments/assets/94b1d481-a5ef-422e-a3dc-3c9dcde7f583)
![image](https://github.com/user-attachments/assets/a77756bf-3357-4007-ac9f-4cac83d522d9)

**Comment by qinxuye** [comment]
不推荐直接用 gradio 的 API

**Comment by qinxuye** [comment]
可以返回 base64 编码的图片，这个和 openai 兼容的，可以参考 openai 的文档。
