### ISSUE TITLE
sglang 已经支持了qwen2vl，但xinference还是只能选择vllm和transformers进行qwen2vl的推理

### ISSUE THREAD

**Issue by ZanePoe** [xorbitsai/inference#2619]
### Feature request / 功能建议

如题：
![54fd1bf1f1d1f76421117149eb79c6c](https://github.com/user-attachments/assets/d72c9c92-0630-408b-be41-b4d60b559ab8)
sglang对你qwen2vl已经得到支持，
但xinference无法选择到sglang:
![0c9a4ef97dc1130af10a4c2c9418c7d](https://github.com/user-attachments/assets/d18ab534-87d5-4837-9262-ee5844439f5b)

### Motivation / 动机

sglang有更高的效率

### Your contribution / 您的贡献

建议增加qwen2vl的sglang引擎推理

**Comment by Timmy-web** [comment]
看到你这我才发现原来qwen vl支持vllm，很奇怪我用docker部署的版本甚至只有transformer，连vllm都没，更别说是sglang了

**Comment by qinxuye** [comment]
docker 版本里 vllm 没有更新，需要至少 0.6.3 的版本。

**Comment by LRCgtp** [comment]
vllm能支持单机多卡推理吗，我这边测试只能在一张卡上跑哎。
