### ISSUE TITLE
Server error: 500 - [address=0.0.0.0:41823, pid=1782322] __init__() missing 2 required positional arguments: 'supervisor_address' and 'replica_model_uid'

### ISSUE THREAD

**Issue by Joker-sad** [xorbitsai/inference#2622]
### System Info / 系統信息

xinference =1.0.1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

q

### The command used to start Xinference / 用以启动 xinference 的命令

q

### Reproduction / 复现过程

q

### Expected behavior / 期待表现

q

**Comment by qinxuye** [comment]
没有有用信息，错误栈也没有贴。
