### ISSUE TITLE
建议增加对 多模态嵌入模型 jinaai/jina-clip-v2 的支持

### ISSUE THREAD

**Issue by sevenold** [xorbitsai/inference#2628]
### Feature request / 功能建议

jina-clip-v2 is a general-purpose multilingual multimodal embedding model for text & images.

### Motivation / 动机

Multilingual Multimodal Embeddings for Texts and Images

### Your contribution / 您的贡献

https://huggingface.co/jinaai/jina-clip-v2

**Comment by qinxuye** [comment]
That's in our plan, we will support it ASAP.

**Comment by qinxuye** [comment]
But if anyone is interested in implementing this feature, please let us know.

**Comment by Second222None** [comment]
> But if anyone is interested in implementing this feature, please let us know.

We also have the same requirement and we'd like to contribute. After a quick review of the code, we think the following modifications are required:

**Comment by Second222None** [comment]
> But if anyone is interested in implementing this feature, please let us know.

We also have similar needs and we'd like to contribute. Any guidance would be greatly appreciated! After a quick review of the code, we identified the following potential modifications:

1. Create `model/multimodal_embedding` directory and implement functions to load/start, stop the object model. According to the developer doc, the model runs within the `actor`. Could you clarify how to integrate the model-loading operations with the `actor`?
2. Implement `RESTfulMultiEmbeddingModelHandle` class in `client/restful/restful_client.py` to handle requests directed toward multimodal embedding model.
3. import `RESTfulMultiEmbeddingModelHandle` as `MultiEmbeddingModelHandle` in `client/handlers.py`.

We’d appreciate any additional hints or recommendations. Thank you!

**Comment by qinxuye** [comment]
> > But if anyone is interested in implementing this feature, please let us know.
> 
> We also have similar needs and we'd like to contribute. Any guidance would be greatly appreciated! After a quick review of the code, we identified the following potential modifications:
> 
> 1. Create `model/multimodal_embedding` directory and implement functions to load/start, stop the object model. According to the developer doc, the model runs within the `actor`. Could you clarify how to integrate the model-loading operations with the `actor`?
> 2. Implement `RESTfulMultiEmbeddingModelHandle` class in `client/restful/restful_client.py` to handle requests directed toward multimodal embedding model.
> 3. import `RESTfulMultiEmbeddingModelHandle` as `MultiEmbeddingModelHandle` in `client/handlers.py`.
> 
> We’d appreciate any additional hints or recommendations. Thank you!

Is it possible to put the multimodel_embedding into the embedding directory, I think we don't need to create a new category.

I think there is possibility to integrate multimodel ability into create_embedding function, if not, we can create a new function.

**Comment by Second222None** [comment]
> > > But if anyone is interested in implementing this feature, please let us know.
> > 
> > 
> > We also have similar needs and we'd like to contribute. Any guidance would be greatly appreciated! After a quick review of the code, we identified the following potential modifications:
> > 
> > 1. Create `model/multimodal_embedding` directory and implement functions to load/start, stop the object model. According to the developer doc, the model runs within the `actor`. Could you clarify how to integrate the model-loading operations with the `actor`?
> > 2. Implement `RESTfulMultiEmbeddingModelHandle` class in `client/restful/restful_client.py` to handle requests directed toward multimodal embedding model.
> > 3. import `RESTfulMultiEmbeddingModelHandle` as `MultiEmbeddingModelHandle` in `client/handlers.py`.
> > 
> > We’d appreciate any additional hints or recommendations. Thank you!
> 
> Is it possible to put the multimodel_embedding into the embedding directory, I think we don't need to create a new category. A benefit is that you don't need to tackle with the actor part, the scaffold is built already.
> 
> I think there is possibility to integrate multimodel ability into create_embedding function, if not, we can create a new function.
> 
> Anyway, I am really glad you guys are willing to contribute, that's awesome.

That's great! We'd like to reuse the existing code as well.

**Comment by sevenold** [comment]
Refer to Jina's official API documentation?

```
import requests

url = 'https://api.jina.ai/v1/embeddings'
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer xxx'
}
data = {
    "model": "jina-clip-v2",
    "dimensions": 1024,
    "normalized": True,
    "embedding_type": "float",
    "input": [
        {
            "text": "A beautiful sunset over the beach"
        },
        {
            "image": "https://i.ibb.co/r5w8hG8/beach2.jpg"
        }
    ]
}

response = requests.post(url, headers=headers, json=data)
print(response.text)

```

```
@no_type_check
def _encode_clip(
    model: SentenceTransformer,
    sentences: Union[Dict, List[Dict]],
    normalized: bool = True,
    **kwargs
):
    from PIL import Image
    import base64
    from io import BytesIO
    import requests

    if isinstance(sentences, dict):
        sentences = [sentences]
    print(dimensions, embedding_type, normalized)
    data = []
    for item in sentences:
        if "image" in item:
            try:
                if item["image"].startswith(("http://", "https://")):
                    response = requests.get(item["image"])
                    image = Image.open(BytesIO(response.content))
                else:
                    image = Image.open(BytesIO(base64.b64decode(item["image"])))
                
                logger.info(f"Image found: {image.size}")
                data.append(image.convert('RGB'))
            except Exception as e:
                logger.error(f"Error processing image: {e}")
                continue
        elif "text" in item:
            data.append(item["text"])
        else:
            logger.warning(f"Skipping item without text or image: {item}")

        with torch.inference_mode():
            try:
                embeddings = model.encode(
                    data, 
                    normalize_embeddings=normalized, 
                    **kwargs
                )
                return embeddings, 0
            except Exception as e:
                logger.error(f"Encoding error: {e}")
                return None, 0

```
 set the truncate_dim 
 
 ```
 self._model = SentenceTransformer(
                self._model_path,
                device=self._device,
                model_kwargs=model_kwargs,
                trust_remote_code=True,
                truncate_dim=self._kwargs.get("truncate_dim", None),
            )
 ```
 
 
![image](https://github.com/user-attachments/assets/9f0dbfce-0020-4edb-9c6a-5834ac3b7790)


Client code

```
with httpx.Client() as client:
    response = client.post(
        host,
        json={"model": "jina-clip-v2", "input": [{"image": data}]},
        headers=header,
    )
    a = response.json()["data"][0]["embedding"]
    assert len(a) == 64
    print(a)

```
