### ISSUE TITLE
没有有用信息，错误栈也没有贴。

### ISSUE THREAD

**Issue by Joker-sad** [xorbitsai/inference#2630]
没有有用信息，错误栈也没有贴。

_Originally posted by @qinxuye in https://github.com/xorbitsai/inference/issues/2622#issuecomment-2516653247_
       

问题是这样的，我更新到1.0.1之后，运行我之前所推送到xinference中的模型的时候报错：Server error: 500 - [address=0.0.0.0:41823, pid=1782322] __init__() missing 2 required positional arguments: 'supervisor_address' and 'replica_model_uid'

**Comment by leeey111** [comment]
我更新后也这样了，你怎么解决的呀？
