### ISSUE TITLE
大模型（vllm引擎推理）运行时间久了显存会增加且无法下降

### ISSUE THREAD

**Issue by turndown** [xorbitsai/inference#2639]
### System Info / 系統信息

操作系统"openEuler 20.03 (LTS-SP3)
Cuda V12.5.40
conda虚拟环境Python 3.11.9
transformers 4.46.3
vllm  0.6.4.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.15.3+1.g26b5097

### The command used to start Xinference / 用以启动 xinference 的命令

HF_ENDPOINT=https://hf-mirror.com XINFERENCE_HOME=/data/inference/.xinference GRADIO_DEFAULT_CONCURRENCY_LIMIT=10 XINFERENCE_MODEL_SRC=modelscope nohup xinference-local --host 0.0.0.0 --port 30002 --log-level debug > output.log 2>&1 &

### Reproduction / 复现过程

运行方式如下，没有加额外的参数：
![image](https://github.com/user-attachments/assets/d8992ac2-297a-47be-804a-a3d1020d7bb5)
最开始启动大模型后占用显存卡2卡3各32g左右：
![image](https://github.com/user-attachments/assets/2d0f48f3-e1c0-456b-95db-c254d345006d)
但是运行了几天并通过dify调用后，显存从32g逐渐上升到37g，现在到了39g，并且没有下降的现象：
![image](https://github.com/user-attachments/assets/9769b0c2-44e4-4744-bf55-645c5adc9e27)

有几个问题请教下：
1.大模型加载后只是初步加载显存，后续使用是不是随着并发量的增多，显存也会波动？还是说一直会上升？
2.显存波动上升的范围能否做限制，如果没限制是不是最后会溢出崩溃，如何让显存能降回来？

### Expected behavior / 期待表现

调用少了之后，显存回归正常状态。

**Comment by turndown** [comment]
help，没有人遇到这类似的问题吗0.0

**Comment by 948024326** [comment]
> help，没有人遇到这类似的问题吗0.0

请问有方法解决嘛

**Comment by 948024326** [comment]
> > > help，没有人遇到这类似的问题吗0.0
> > 
> > 
> > 请问有方法解决嘛
> 
> 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95

我后面没遇到这个问题了

**Comment by turndown** [comment]
> > > > help，没有人遇到这类似的问题吗0.0
> > > 
> > > 
> > > 请问有方法解决嘛
> > 
> > 
> > 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95
> 
> 我后面没遇到这个问题了

啊，你咋解决的啊，我的还是一直在增加。问了群里的人员，说无法避免，只能重启。跑两周基本上要重启一次

**Comment by 948024326** [comment]
我的一直都稳着这么多了 调用后就释放了 没遇到过了
![image](https://github.com/user-attachments/assets/6a5dcb57-d2cd-4114-a0e6-36c070c8f771)

**Comment by turndown** [comment]
> 我的一直都稳着这么多了 调用后就释放了 没遇到过了 ![image](https://private-user-images.githubusercontent.com/59902823/399251227-6a5dcb57-d2cd-4114-a0e6-36c070c8f771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDc4NjgsIm5iZiI6MTczNTU0NzU2OCwicGF0aCI6Ii81OTkwMjgyMy8zOTkyNTEyMjctNmE1ZGNiNTctZDJjZC00MTE0LWEwZTYtMzZjMDcwYzhmNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmVmZDc2Nzc5Y2FjNGU4YzllYjc0YjMxMGM2YTFmNDAwNTFhMWMxMmQxYzc1YjE5MzcyYTRkZDAyMGM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01NC_D-tAVBxNJYhbcIR5cZ-hA1U14AlturE4de-w9c)

哇，你这跑的卡真多啊。那是不是你的并发量没有上来，或者token量不大
我跑了两周，马上要爆了
![image](https://github.com/user-attachments/assets/7a9f9413-9c7e-4dd2-a3d1-4777d970c4f6)

**Comment by 948024326** [comment]
> > 我的一直都稳着这么多了 调用后就释放了 没遇到过了 ![image](https://private-user-images.githubusercontent.com/59902823/399251227-6a5dcb57-d2cd-4114-a0e6-36c070c8f771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDc4NjgsIm5iZiI6MTczNTU0NzU2OCwicGF0aCI6Ii81OTkwMjgyMy8zOTkyNTEyMjctNmE1ZGNiNTctZDJjZC00MTE0LWEwZTYtMzZjMDcwYzhmNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmVmZDc2Nzc5Y2FjNGU4YzllYjc0YjMxMGM2YTFmNDAwNTFhMWMxMmQxYzc1YjE5MzcyYTRkZDAyMGM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01NC_D-tAVBxNJYhbcIR5cZ-hA1U14AlturE4de-w9c)
> 
> 哇，你这跑的卡真多啊。那是不是你的并发量没有上来，或者token量不大 我跑了两周，马上要爆了 ![image](https://private-user-images.githubusercontent.com/57825084/399252703-7a9f9413-9c7e-4dd2-a3d1-4777d970c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDgwMDgsIm5iZiI6MTczNTU0NzcwOCwicGF0aCI6Ii81NzgyNTA4NC8zOTkyNTI3MDMtN2E5Zjk0MTMtOWM3ZS00ZGQyLWEzZDEtNDc3N2Q5NzBjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YTE3YjVmMjBkMTM2NTU4ZjM0ZmEzMTBlMzY2ZDdkMDA1Njg0ZDQ5YTg4ZTIzMGE1NTFjY2ExOTkzZmU0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z9owvUpscSzUQsjUdF0GQG6JmspfdgLkpI0hRo1jbWU)

没有做过压测，token大概8k一次，但是确实并发量比较低

**Comment by sunjinguo** [comment]
> > 我的一直都稳着这么多了 调用后就释放了 没遇到过了 ![image](https://private-user-images.githubusercontent.com/59902823/399251227-6a5dcb57-d2cd-4114-a0e6-36c070c8f771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDc4NjgsIm5iZiI6MTczNTU0NzU2OCwicGF0aCI6Ii81OTkwMjgyMy8zOTkyNTEyMjctNmE1ZGNiNTctZDJjZC00MTE0LWEwZTYtMzZjMDcwYzhmNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmVmZDc2Nzc5Y2FjNGU4YzllYjc0YjMxMGM2YTFmNDAwNTFhMWMxMmQxYzc1YjE5MzcyYTRkZDAyMGM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01NC_D-tAVBxNJYhbcIR5cZ-hA1U14AlturE4de-w9c)
> 
> 哇，你这跑的卡真多啊。那是不是你的并发量没有上来，或者token量不大 我跑了两周，马上要爆了 ![image](https://private-user-images.githubusercontent.com/57825084/399252703-7a9f9413-9c7e-4dd2-a3d1-4777d970c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTMyMzEsIm5iZiI6MTczNTU1MjkzMSwicGF0aCI6Ii81NzgyNTA4NC8zOTkyNTI3MDMtN2E5Zjk0MTMtOWM3ZS00ZGQyLWEzZDEtNDc3N2Q5NzBjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEwMDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWNiNTZhMWFiOTNhYmUwY2FjZGUzYzdiMmFjZDJhYTM1NDAxNDJiZWY4MjQ5YmZiMWRjMWI2N2QwMDhmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mhUeb4j6u5_sk3ztB0HrM2Ob4n5lRle_owCboFdA5sU)



> > > > > help，没有人遇到这类似的问题吗0.0
> > > > 
> > > > 
> > > > 请问有方法解决嘛
> > > 
> > > 
> > > 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95
> > 
> > 
> > 我后面没遇到这个问题了
> 
> 啊，你咋解决的啊，我的还是一直在增加。问了群里的人员，说无法避免，只能重启。跑两周基本上要重启一次

我也担心显存溢出问题，不会真的只能重启吧，那对线上太不友好了

**Comment by turndown** [comment]
> > > 我的一直都稳着这么多了 调用后就释放了 没遇到过了 ![image](https://private-user-images.githubusercontent.com/59902823/399251227-6a5dcb57-d2cd-4114-a0e6-36c070c8f771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDc4NjgsIm5iZiI6MTczNTU0NzU2OCwicGF0aCI6Ii81OTkwMjgyMy8zOTkyNTEyMjctNmE1ZGNiNTctZDJjZC00MTE0LWEwZTYtMzZjMDcwYzhmNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmVmZDc2Nzc5Y2FjNGU4YzllYjc0YjMxMGM2YTFmNDAwNTFhMWMxMmQxYzc1YjE5MzcyYTRkZDAyMGM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01NC_D-tAVBxNJYhbcIR5cZ-hA1U14AlturE4de-w9c)
> > 
> > 
> > 哇，你这跑的卡真多啊。那是不是你的并发量没有上来，或者token量不大 我跑了两周，马上要爆了 ![image](https://private-user-images.githubusercontent.com/57825084/399252703-7a9f9413-9c7e-4dd2-a3d1-4777d970c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTMyMzEsIm5iZiI6MTczNTU1MjkzMSwicGF0aCI6Ii81NzgyNTA4NC8zOTkyNTI3MDMtN2E5Zjk0MTMtOWM3ZS00ZGQyLWEzZDEtNDc3N2Q5NzBjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEwMDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWNiNTZhMWFiOTNhYmUwY2FjZGUzYzdiMmFjZDJhYTM1NDAxNDJiZWY4MjQ5YmZiMWRjMWI2N2QwMDhmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mhUeb4j6u5_sk3ztB0HrM2Ob4n5lRle_owCboFdA5sU)
> 
> > > > > > help，没有人遇到这类似的问题吗0.0
> > > > > 
> > > > > 
> > > > > 请问有方法解决嘛
> > > > 
> > > > 
> > > > 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95
> > > 
> > > 
> > > 我后面没遇到这个问题了
> > 
> > 
> > 啊，你咋解决的啊，我的还是一直在增加。问了群里的人员，说无法避免，只能重启。跑两周基本上要重启一次
> 
> 我也担心显存溢出问题，不会真的只能重启吧，那对线上太不友好了

目前得到的回复是这样的，只能重启。不知道有没有那种脚本能一键重启，然后启动模型

**Comment by sunjinguo** [comment]
> > > > 我的一直都稳着这么多了 调用后就释放了 没遇到过了 ![image](https://private-user-images.githubusercontent.com/59902823/399251227-6a5dcb57-d2cd-4114-a0e6-36c070c8f771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDc4NjgsIm5iZiI6MTczNTU0NzU2OCwicGF0aCI6Ii81OTkwMjgyMy8zOTkyNTEyMjctNmE1ZGNiNTctZDJjZC00MTE0LWEwZTYtMzZjMDcwYzhmNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmVmZDc2Nzc5Y2FjNGU4YzllYjc0YjMxMGM2YTFmNDAwNTFhMWMxMmQxYzc1YjE5MzcyYTRkZDAyMGM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.01NC_D-tAVBxNJYhbcIR5cZ-hA1U14AlturE4de-w9c)
> > > 
> > > 
> > > 哇，你这跑的卡真多啊。那是不是你的并发量没有上来，或者token量不大 我跑了两周，马上要爆了 ![image](https://private-user-images.githubusercontent.com/57825084/399252703-7a9f9413-9c7e-4dd2-a3d1-4777d970c4f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTMyMzEsIm5iZiI6MTczNTU1MjkzMSwicGF0aCI6Ii81NzgyNTA4NC8zOTkyNTI3MDMtN2E5Zjk0MTMtOWM3ZS00ZGQyLWEzZDEtNDc3N2Q5NzBjNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDEwMDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWNiNTZhMWFiOTNhYmUwY2FjZGUzYzdiMmFjZDJhYTM1NDAxNDJiZWY4MjQ5YmZiMWRjMWI2N2QwMDhmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mhUeb4j6u5_sk3ztB0HrM2Ob4n5lRle_owCboFdA5sU)
> > 
> > 
> > > > > > > help，没有人遇到这类似的问题吗0.0
> > > > > > 
> > > > > > 
> > > > > > 请问有方法解决嘛
> > > > > 
> > > > > 
> > > > > 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95
> > > > 
> > > > 
> > > > 我后面没遇到这个问题了
> > > 
> > > 
> > > 啊，你咋解决的啊，我的还是一直在增加。问了群里的人员，说无法避免，只能重启。跑两周基本上要重启一次
> > 
> > 
> > 我也担心显存溢出问题，不会真的只能重启吧，那对线上太不友好了
> 
> 目前得到的回复是这样的，只能重启。不知道有没有那种脚本能一键重启，然后启动模型

那就写个shell 脚本，弄个定时任务，杀掉历史程序，重新起一下服务

**Comment by kidcad1412** [comment]
> > > > > help，没有人遇到这类似的问题吗0.0
> > > > 
> > > > 
> > > > 请问有方法解决嘛
> > > 
> > > 
> > > 我加了参数限制，但是好像没啥用，不知道怎么回事。 gpu_memory_utilization 0.95
> > 
> > 
> > 我后面没遇到这个问题了
> 
> 啊，你咋解决的啊，我的还是一直在增加。问了群里的人员，说无法避免，只能重启。跑两周基本上要重启一次

请问群能拉一下吗，hml_1412
