### ISSUE TITLE
在系统上部署bge-reranker-v2-m3一类的rerank模型，有的时候会报错server close

### ISSUE THREAD

**Issue by nopipifish** [xorbitsai/inference#2644]
### System Info / 系統信息

nvida 3090

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

报错：Failed to rerank documents, detail: Remote server 0.0.0.0:44441 closed

### Reproduction / 复现过程

1. 输入了10个检索列表
2. 报错：Failed to rerank documents, detail: Remote server 0.0.0.0:44441 closed
3. 减少至2个检索列表：没有报错了
4. 请问：这个报错的原因是什么？是否是长度过长？有办法能解决吗？我这里gpu资源是够用的，但是服务直接挂了，能否增大这个容纳限制呢？

### Expected behavior / 期待表现

在计算资源足够的情况下，rerank模型能够支持更长的语料输入。
两三个不够用。

**Comment by qinxuye** [comment]
这个是 OOM 了。你的 query 能分享下吗？

我们复现下。

**Comment by nopipifish** [comment]
> 这个是 OOM 了。你的 query 能分享下吗？
> 
> 我们复现下。

你好，经排查，确实oom了。bge-reranker-v2-m3 这个模型占用显存太高了，很快就占满了24G，而且显存也不会释放，我看到也有其他人说这个问题，可能是这个模型有问题？我后来使用jina-rerank就没再oom了，而且显存占用在2G左右，很稳定。

**Comment by qinxuye** [comment]
这个模型有很多这个反馈，我们需要查一下到底是什么导致的。

**Comment by luzhongqiu** [comment]
any update?

**Comment by WanliZhong** [comment]
@qinxuye 请问这个reranker模型的oom的问题有进展吗？
