### ISSUE TITLE
whisper的推理api报错

### ISSUE THREAD

**Issue by closer-finger** [xorbitsai/inference#2650]
### System Info / 系統信息

ubuntu22.04，L40显卡。docker镜像xinference版本0.15.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

docker镜像xinference版本0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

容器启动

### Reproduction / 复现过程

访问v1/audio/transcriptions。参数response_format为json返回正常
访问v1/audio/transcriptions。参数response_format为verbose_json时返回异常。
具体表现response_format为verbose_json时缺少一句话，没有完整的进行语音到文本任务。

### Expected behavior / 期待表现

参数response_format为verbose_json时正常

**Comment by qinxuye** [comment]
请贴出具体的复现过程，以及预期的结果。
