### ISSUE TITLE
Xinference 基于vLLM并不支持多卡推理

### ISSUE THREAD

**Issue by LRCgtp** [xorbitsai/inference#2651]
### System Info / 系統信息

cuda 12.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local --host 0.0.0.0 --port 9997 & > output.log

### Reproduction / 复现过程

1、web界面配置模型相关参数，推理引擎选择vllm
![1733816903800](https://github.com/user-attachments/assets/bca3b0dc-3ad6-45f5-9709-1066143adc5e)
![1733816924318](https://github.com/user-attachments/assets/fef07b6b-77e3-4b4e-b789-96d1bf77b42a)

### Expected behavior / 期待表现

部署模型，选择vllm推理引擎应该支持单机多卡推理

**Comment by qinxuye** [comment]
支持啊，碰到啥问题？

**Comment by LRCgtp** [comment]
通过vllm引擎web页面部署模型，发现只在一张卡上跑。
