### ISSUE TITLE
支持在对话补全请求中控制是否返回特殊标记

### ISSUE THREAD

**Issue by zjuyzj** [xorbitsai/inference#2656]
### Feature request / 功能建议

针对vLLM后端，正确处理对话补全请求中的额外参数`skip_special_tokens`。

### Motivation / 动机

使用Qwen2-VL做视觉定位任务，用户侧需要拿到`<|object_ref_start|>` `<|object_ref_end|>` `<|box_start|>` `<|box_end|>`这几个特殊标记，用于在绘制包围盒时定位有关字段。

因此，需要在解码时将tokenizer的`skip_special_tokens`参数设为`False`，参考 https://github.com/QwenLM/Qwen2-VL/issues/9#issuecomment-2322858680 。

针对这个问题，vLLM自带RESTful API中有处理，通过在对话补全请求体中增加额外字段，将对应参数传递给`SamplingParams`：https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html?ref=blog.mozilla.ai#extra-parameters-for-chat-completions-api

现考虑让Xinference也支持类似的功能，这样就可以在用户侧使用类似以下的代码进行控制：
`client.chat.completions.create(messages, model, stream=True, extra_body={"skip_special_tokens": False})`

### Your contribution / 您的贡献

#2655 修补了RESTful API和vLLM相关代码，让Xinference能将`skip_special_tokens`这个额外采样参数传给vLLM后端而不被丢弃。

**Comment by qinxuye** [comment]
#2655 完成可以关闭这个 issue 吗？

**Comment by zjuyzj** [comment]
> #2655 完成可以关闭这个 issue 吗？

#2655 是只针对vLLM backend的临时性小修改，解决了我的困惑。由于目前尚不清楚使用其他backend以及不同模型的用户有没有类似的需求，我认为可以暂时关闭issue，未来有需要再针对这个问题做系统性处理。

**Comment by qinxuye** [comment]
OK，先针对 vllm 支持。以后碰到别的 backend 的需求我们再 reopen 或者开新的 issue。
