### ISSUE TITLE
平台对接stable-diffusion-3.5-large 建议

### ISSUE THREAD

**Issue by zhangjianquan** [xorbitsai/inference#2664]
### Feature request / 功能建议

希望支持stable-diffusion-3.5-large 模型，在后续使用平台时能够支持更多的模型接入

### Motivation / 动机

私有化部署需要stable-diffusion-3.5-large

### Your contribution / 您的贡献

null

**Comment by qinxuye** [comment]
谢谢，我们尽快支持。
