### ISSUE TITLE
请求增加优先级参数，优先调度高优先级的请求

### ISSUE THREAD

**Issue by 781574155** [xorbitsai/inference#2669]
### Feature request / 功能建议

如题。我们在实际生产环境中，需要长时间跑一些文件处理任务（比如写摘要，且对于单个大文件又要拆分为很多小的请求）。与此同时，用户可能有大模型聊天的需求。如果没有优先级，会导致聊天请求要排队等待前面的文件处理任务执行完，才慢慢调度到聊天的请求。这显然是不能接受的。现在的情况是，我们一有文件在处理（比如几百个），就（基本）无法聊天了

### Motivation / 动机

我希望咱们能扩展openai的参数，增加一个priority的参数。我不希望是增加新的接口。我希望能够保持我的程序能随时切换到任何支持openai接口的大模型。

### Your contribution / 您的贡献

无

**Comment by 781574155** [comment]
vllm是支持优先级的：https://github.com/vllm-project/vllm/pull/8850

**Comment by qinxuye** [comment]
可以尝试在 generate_config 里支持 priority。

https://github.com/xorbitsai/inference/blob/b0b2fa604bc93507a910abd62823b4ada8bca06b/xinference/model/llm/vllm/core.py#L334-L404

**Comment by 781574155** [comment]
@qinxuye 大哥，这个需求应该很多人都需要。因为私有化部署，往往资源是有限的。不可能部署两套，一套做批处理任务，一套做实时任务。你就动动你的金手指，分分钟把它写了算了！我也想贡献个PR，但是我搞不懂啊！

**Comment by qinxuye** [comment]
这个是个企业级特性，我们只会在企业版上支持类似能力，不过开源欢迎社区贡献。
