### ISSUE TITLE
无法停止使用前端webui

### ISSUE THREAD

**Issue by nopipifish** [xorbitsai/inference#2677]
### System Info / 系統信息

3090

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v1.0.1

### The command used to start Xinference / 用以启动 xinference 的命令

不使用默认的前端webui。只使用命令行

### Reproduction / 复现过程

我想把直接前端给停了。我的前端暴露在网络上很不安全。我如何在启动时不使用前端webui呢？但是我需要正常使用api接口

### Expected behavior / 期待表现

正常关闭前端webui

**Comment by qinxuye** [comment]
https://inference.readthedocs.io/zh-cn/latest/user_guide/auth_system.html

可以设置鉴权。
