### ISSUE TITLE
报错Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by SKKKKYLAR** [xorbitsai/inference#2682]
### System Info / 系統信息

cuda12.1
python 3.10.16

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference:1.1.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 127.0.0.1 --port 9997 

### Reproduction / 复现过程

完成安装后，运行xinference-local --host 127.0.0.1 --port 9997 
会显示Segmentation fault (core dumped)
应该怎么解决呢？
After completing the installation, when running xinference-local --host 127.0.0.1 --port 9997, if you encounter a "Segmentation fault (core dumped)" error

### Expected behavior / 期待表现

how to address the issue

**Comment by qinxuye** [comment]
感觉你环境有问题，python 可能会 core dump。
