### ISSUE TITLE
OpenGVLab/InternVL2_5-78B 架构变了，导致不能注册至xinf  希望能集成InternVL2_5

### ISSUE THREAD

**Issue by Kevin-qwx** [xorbitsai/inference#2683]
### Feature request / 功能建议

![a05234c3-4d61-449e-903b-bfbd1e3d3b10](https://github.com/user-attachments/assets/221c1576-7ed2-46ca-a1c2-f425c04fb6ff)

### Motivation / 动机

Error
[address=0.0.0.0:40997,pid=120888]
"internvl2 5'

### Your contribution / 您的贡献

。

**Comment by qinxuye** [comment]
Duplicated with #2662 .
