### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by feifei05** [xorbitsai/inference#2687]
### System Info / 系統信息

NPU

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope nohup xinference launch -u my-llm -n qwen-chat -s 1_8 -f pytorch -en transformers -e "http://*.*.*.*:39997" > xinference.log 2>&1  &

### Reproduction / 复现过程

服务启动不了，报错Max retries exceeded with url，如图所示
<img width="1249" alt="bug" src="https://github.com/user-attachments/assets/6e053dec-6218-450f-b869-68399fd99758" />

### Expected behavior / 期待表现

能启动服务，且指定了具体的模型，地址端口号，希望给出正确的命令。

**Comment by qinxuye** [comment]
要先启动 xinference 服务再 launch。

**Comment by feifei05** [comment]
> 要先启动 xinference 服务再 launch。

在昇腾910上launch模型，这命令是不是存在问题，模型格式对吗，有没有正确的命令呀
XINFERENCE_MODEL_SRC=modelscope nohup xinference launch -n qwen2.5-instruct -s 0_5 -f pytorch -en transformers -e "http://...:9997" > model_start.log 2>&1  &
