### ISSUE TITLE
后面的版本minicpm3-4b会支持vllm推理吗

### ISSUE THREAD

**Issue by tu-160** [xorbitsai/inference#2693]
后面的版本minicpm3-4b会支持vllm推理吗

**Comment by qinxuye** [comment]
支持比较简单，只需在如下位置针对 vllm>=0.6.2 增加 minicpm3-4b 即可。

https://github.com/xorbitsai/inference/blob/fb97375cab91def4c0e9b32b58211ced4c89d1a8/xinference/model/llm/vllm/core.py#L189-L193

**Comment by qinxuye** [comment]
Resolved by #2697
