### ISSUE TITLE
qwen2-vl-7b vllm  设置默认显存

### ISSUE THREAD

**Issue by GXKIM** [xorbitsai/inference#2696]
### System Info / 系統信息

xinference== 0.16.1
vllm== 0.6.3

启动命令: xinference launch --model_path /models/Qwen2-VL-7B-Instruct --model-engine vllm -n qwen2-vl-instruct  -f pytorch -s 7 -u qwen2-vl-instruct_test --gpu-idx 2 --gpu-memory-utilization 0.9 -e http://xxxx:7009
报错 找不到--gpu-memory-utilization 0.9
是我启动版本不对吗

![image](https://github.com/user-attachments/assets/1ed0fc87-f3c7-4458-84db-fd0ac2951e4a)

**Comment by qinxuye** [comment]
--gpu_memory_utilization 0.9
