### ISSUE TITLE
支持CosyVoice2.0-0.5B

### ISSUE THREAD

**Issue by Wiziechen** [xorbitsai/inference#2701]
### Feature request / 功能建议

能否尽快支持CosyVoice语音生成大模型2.0-0.5B，且提供选项支持流式输入输出

### Motivation / 动机

为了更好实现realtime的语音大模型部署

### Your contribution / 您的贡献

？

**Comment by qinxuye** [comment]
Fixed by #2684

**Comment by wang-TJ-20** [comment]
@qinxuye ,我们inference加速下的cosyvoice2-0.5B有测试首包耗时吗，看官方给的是150ms，有实现这个吗
