### ISSUE TITLE
BUG: UnicodeDecodeError caused by xinference/model/llm/llm_family.json

### ISSUE THREAD

**Issue by HENScience** [xorbitsai/inference#292]
### Describe the bug
Windows cmd runned xinference found Error: "**UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 8905: illegal multibyte sequence**"

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. python version: 3.10
2. xinference version: v0.1.0

### Expected behavior
Edit the file: xinference/model/llm/__init__.py
Line number: 129
Add arg encoding: open(json_path, encoding='utf-8')

**Comment by UranusSeven** [comment]
Thanks for reporting this issue! This problem will be fixed in the next release.

Stay tuned!
