### ISSUE TITLE
FEAT: Disable Gradio Telemetry

### ISSUE THREAD

**Issue by arch-btw** [xorbitsai/inference#295]
Pull requests are disabled but see here:

https://github.com/arch-btw/inference/pull/1

**Comment by aresnow1** [comment]
Thanks for your feedback! Is there any problem with the pull request?

**Comment by UranusSeven** [comment]
@arch-btw Thanks for your contribution! 🤗 I've created a pull request according to your changes #299.

Please let us know more details about pull requests being disabled.
