### ISSUE TITLE
BUG: Mac m1 package "flash_attn" can't not be installed

### ISSUE THREAD

**Issue by eisneim** [xorbitsai/inference#298]
### Describe the bug
when use Qwen-7B model on Mac m1 a package "flash_attn" is required to install during the install process
how to bypass this "flash_attn" package?

1. Your Python version: 3.10
2. The version of xinference you use: 0.1.1
```
ImportError: [address=127.0.0.1:52814, pid=1630] This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
```

**Comment by UranusSeven** [comment]
Hi, thanks for reporting this issue.

`flash_attn` requires CUDA to run so it is not available for Mac.

I managed to reproduce this issue on my M1 mac. Here are the warnings I got when launching qwen-chat:

```bash
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention
```

These warnings do not prevent me from using qwen-chat.
