### ISSUE TITLE
QUESTION: The model automatically downloads failed, it is recommended to provide manual upload and manual configuration

### ISSUE THREAD

**Issue by ZanePoe** [xorbitsai/inference#301]
`  File "/home/zanepoe/miniconda3/lib/python3.11/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading pytorch_model.bin:  62%|██████▏   | 9.62G/15.4G [24:37<14:54, 6.51MB/s]`
系统自带的下载经常失败，非常容易失败，我的下载速读基本是20.51MB/s,平均也能保持10.51MB/s的速读，但xinference自带的下载依然容易超时失败，并且不能断点重试：
最好有详细的文档描述手动上传文件的方法，我看放到./xinference/cache的文件，你们都是有命名规则的，然后还有meta文件。ggml模型的命名规则我自己摸索出来了，但pytorch模型的命名规则，量化要怎么描述我还搞不清楚，
因为目前我从来没有完全下载成功一个pytorch模型，全都下载到一半失败，从新下载又是从头开始，到一半的时候失败。

**Comment by UranusSeven** [comment]
Hi, thanks for reporting this issue. Xinference utilizes Hugging Face for model downloading, which means you can cache the model manually with `huggingface_hub`.

Here's what I do when the network is poor:
```python
import huggingface_hub

huggingface_hub.snapshot_download(
    "meta-llama/Llama-2-7b-chat-hf",
    resume_download=True  # enabling resume_download helps when downloading is interrupted 
)
```
