### ISSUE TITLE
BUG: Fails to install on Win 11

### ISSUE THREAD

**Issue by dillfrescott** [xorbitsai/inference#303]
https://0.0g.gg/?15fb7c2c548c2dc1#3CYN8aZPG2DBaQVnc6jR1sMN2b2R9VLkkXNTLLAbSoiK

Is there a simple fix to this?

**Comment by dillfrescott** [comment]
And yes its a huge error thats why i had to use a pastebin

**Comment by UranusSeven** [comment]
This error is because chatglmcpp sometimes doesn't work with Windows.

If you don't need to run models in GGML format,pip install xinference[pytorch] should be enough.

**Comment by dillfrescott** [comment]
Oh okay. Thank you for the info!
