### ISSUE TITLE
ENH: avoid loading same model repeatedly in web UI

### ISSUE THREAD

**Issue by IamWWT** [xorbitsai/inference#311]
### Is your feature request related to a problem? Please describe
after i switched to another model (suppose model 'ggmlA' ) and then go back to the model (suppose model 'pytorchA') loaded before, the model 'pytorchA' will be loaded for the second time which is occupation of GPU resources repeatedly.

### Describe the solution you'd like
it will be addressed by adding a gradio webui button to avoiding this problem. more, source code can be optimized by adding logic to avoid loading the same model 

further, It doesn't seem to be working of model quantization (i just test chatglm2 pytorch format), and i found the quantization directory is not created.

**Comment by UranusSeven** [comment]
Thanks for your suggestion! We'll fix this problem in the next release.
