### ISSUE TITLE
QUESTION: llama-2 embedding model？

### ISSUE THREAD

**Issue by tonylin52** [xorbitsai/inference#346]
Hi,

I like this project!! One question is that when I type
`xinference list --all`
The results include
`llama-2          ['en']        ['embed', 'generate']` 

May I ask which parts of the llama2 model do the embedding be extracted from? Thanks

**Comment by aresnow1** [comment]
We provide embedding api compatible with OpenAI API.
```
curl http://{your-xinference-endpoint}/v1/embedding \
  -d '{
     "model": "yourt-model-uid",
     "input": "your sentences"
  }'
```

**Comment by tonylin52** [comment]
> We provide embedding api compatible with OpenAI API.
> 
> ```
> curl http://{your-xinference-endpoint}/v1/embedding \
>   -d '{
>      "model": "yourt-model-uid",
>      "input": "your sentences"
>   }'
> ```

Thanks! But my question is that Embedding model is usually encode model, while how to use decode model (such as llama2, chatglm etc.) as Embedding model?

**Comment by aresnow1** [comment]
> > We provide embedding api compatible with OpenAI API.
> > ```
> > curl http://{your-xinference-endpoint}/v1/embedding \
> >   -d '{
> >      "model": "yourt-model-uid",
> >      "input": "your sentences"
> >   }'
> > ```
> 
> Thanks! But my question is that Embedding model is usually encode model, while how to use decode model (such as llama2, chatglm etc.) as Embedding model?

It only means that the model exposes embedding interface. Actually, the embedding results of llama2 are indeed not good.

**Comment by tonylin52** [comment]
Thanks a lot!!!
