### ISSUE TITLE
FEAT: A lightweight SDK that only supports LLM Generate HTTP Request WANTED

### ISSUE THREAD

**Issue by takatost** [xorbitsai/inference#372]
### Is your feature request related to a problem? Please describe

After we added the xinference package, the size of the packaged image increased by 200MB+. Our requirement is to only have access to the local xinference API Endpoint through the interface.
You can take a look at the screenshot below for additional context.

### Describe the solution you'd like

I hope we can create a separate HTTP client package that only provides the ability to call API endpoints. It should be lightweight and minimize the package size as much as possible.

### Describe alternatives you've considered

I might write the code myself and call the API Endpoint directly through an Http client.

### Additional context

Here are the sizes of the packages that inference depends on:

https://github.com/xorbitsai/inference/blob/302eca96dc63611f24b0625e80f4e6387fb6981d/setup.cfg#L26-L40

<img width="228" alt="image" src="https://github.com/xorbitsai/inference/assets/5485478/0e650fc4-1a4e-490a-ad1d-7c5e126dbbe4">

**Comment by UranusSeven** [comment]
https://github.com/xorbitsai/inference-client
