### ISSUE TITLE
FEAT: Support Paged Attention

### ISSUE THREAD

**Issue by Bojun-Feng** [xorbitsai/inference#375]
### Is your feature request related to a problem? Please describe
[VLLM](https://github.com/vllm-project/vllm) implements [paged attention](https://vllm.ai/) using Ray to significantly increase generation speed. We can implement paged attention without using Ray as a dependency.

This is a gif from VLLM's website demonstrating the generation process with paged attention:
![](https://vllm.ai/assets/figures/annimation1.gif)

**Comment by UranusSeven** [comment]
#445
