### ISSUE TITLE
QUESTION supporting GPTQ quantized model

### ISSUE THREAD

**Issue by Yuchen-Cao** [xorbitsai/inference#381]
Hi there! I noticed that you guys have already added many new models in v0.2.0, which helps a lot.

As of my current understanding, it seems that the quantized model registered in json are GGML version, is that true?

I am working on deploying a coding assistant LLM on one single GPU, and I tried starchat-beta. Unfortunately my VRAM is not large enough for FP16 precision. I found that TheBloke on huggingface also published a GPTQ quantized version of starchat-beta: https://huggingface.co/TheBloke/starchat-beta-GPTQ. So if Xinference supports GPTQ quantized model in addition to GGML ones?

**Comment by UranusSeven** [comment]
Hi! The format of a custom model can be GGML or PyTorch. GPTQ is not supported yet, but is definitly on our roadmap.

Do you think Starchat-beta GGML works for you? It should be easy to add GGML support since we have already supported it in PyTorch.

**Comment by Yuchen-Cao** [comment]
Oh, I would be more than happy that GPTQ version also adding to your model list~ Otherwise I will have to try adding it by myself

**Comment by pangyoki** [comment]
> it seems that the quantized model registered in json are GGML version, is that true?

GGML models support many quantization methods. At the same time, Pytorch model also supports `4-bit` and `8-bit` quantization.

If you use linux system and have gpu environment, you can try to use `4-bit` quantized Pytorch model first. Otherwise you can try 8-bit quantization.

please refer to: https://inference.readthedocs.io/en/latest/models/builtin/starchat-beta.html#models-builtin-starchat-beta

**Comment by Yuchen-Cao** [comment]
> > it seems that the quantized model registered in json are GGML version, is that true?
> 
> GGML models support many quantization methods. At the same time, Pytorch models also support `4-bit` and `8-bit` quantization.
> 
> If you use linux system and have gpu environment, you can try to use `4-bit` quantized Pytorch model first. Otherwise you can try 8-bit quantization.
> 
> please refer to: https://inference.readthedocs.io/en/latest/models/builtin/starchat-beta.html#models-builtin-starchat-beta

I run
```
xinference launch --model-name starchat-beta --size-in-billions 16 --model-format pytorch --quantization 8-bit
```
and the transformers module starts to cache the original starchat-beta model weights.
I think after all the downloading processes are finished, I still have to utilize my own device to fit the GPTQ quantized model... 

Let me see if my GPU device is able to fit that post training quantization. I'll update this post after I try it out.

**Comment by Yuchen-Cao** [comment]
I am able to launch the model after setting `--quantization 8-bit`. Thanks a lot.
