### ISSUE TITLE
QUESTION:can the model starchat-beta support chat history

### ISSUE THREAD

**Issue by gjm-anban** [xorbitsai/inference#392]
hello,can the model starchat-beta support chat history, if it can,how to write the format of chat_history.please give me an example, like chat_history [{"assistant":"test"}{...}]

chat_history = []
prompt = "What is the largest animal?"
model.chat(
            prompt,
            chat_history,
            generate_config={"max_tokens": 1024}
        )

**Comment by UranusSeven** [comment]
Hi! examples/chat.py may be helpful.

Please let me know if it works for you :)

**Comment by gjm-anban** [comment]
> Hi! examples/chat.py may be helpful.
> 
> Please let me know if it works for you :)

I tried it and get error message
![image](https://github.com/xorbitsai/inference/assets/73465248/25885fb8-5107-4e41-ae5b-9b01f05dd670)

and I load the model locally.
![image](https://github.com/xorbitsai/inference/assets/73465248/a8a391b6-a0be-460c-9dfb-111952770da4)

**Comment by gjm-anban** [comment]
> Hi! examples/chat.py may be helpful.
> 
> Please let me know if it works for you :)

it helps,thanks. Although starchat-beta's context-based generation doesn't work so well
