### ISSUE TITLE
BUG: web UI doesn't work for cloud deployment 

### ISSUE THREAD

**Issue by wangrg** [xorbitsai/inference#393]
Note that the issue tracker is NOT the place for general support.
<img width="891" alt="image" src="https://github.com/xorbitsai/inference/assets/1925650/9f1c9aa9-451c-45a5-9875-0ed4cf432c39">

1. Deploy on the cloud and execute "xinference -p 8443".
2. Error occurred after selecting the model, as shown in the figure above.

**Comment by UranusSeven** [comment]
Hi, thanks for reporting this issue! I've reproduced it and will fix it ASAP.

**Comment by UranusSeven** [comment]
With the recent updates to the web UI, this issue has been resolved.

To access the xinference instance deployed on my_host, follow the steps below from your laptop:

### Establish an SSH tunnel
`ssh -NL 1080:127.0.0.1:9997 jon@my_host`

### Open your preferred web browser
navigate to: `http://localhost:1080`

Upon doing so, you should be greeted with the "launch model" page, indicating that everything is set up correctly and you are ready to proceed.
