### ISSUE TITLE
QUESTION: How can I launch a gated model in a Dockerfile?

### ISSUE THREAD

**Issue by onesuper** [xorbitsai/inference#433]
I am using xinference to launch Llama-2-13b-chat-hf model in a Dockerfile:

The model file seems to be gated on huggingface

```
Cannot access gated repo for url https://huggingface.co/api/models/meta-llama/Llama-2-13b-chat-hf/revision/0ba94ac9b9e1d5a0037780667e8b219adde1908c.
pdf-chatbot-with-local-llm-chat_doc-1  | Repo model meta-llama/Llama-2-13b-chat-hf is gated. You must be authenticated to access it.
```

**Comment by onesuper** [comment]
I add a troubleshooting answer to this problem in #460

**Comment by UranusSeven** [comment]
To summarize, you need to **specify your hugging face token as an env var** when starting the container.
