### ISSUE TITLE
QUESTION: 手写的docker启动成功，但访问http://localhost:9997无法访问

### ISSUE THREAD

**Issue by ssseVennn** [xorbitsai/inference#467]
根据部署命令，手写了个dockerfile
![image](https://github.com/xorbitsai/inference/assets/47654022/7baf0a82-7c5a-4062-96af-b6cbf4aef1bd)
成功启动后，输出日志入下
![image](https://github.com/xorbitsai/inference/assets/47654022/ed66bb5d-9439-4955-a550-6e3178504c3e)
然而访问
http://localhost:9997是访问无效，如果我想访问webui，应该如何操作

**Comment by aresnow1** [comment]
Docker 启动时有没有映射端口？

**Comment by ssseVennn** [comment]
> Docker 启动时有没有映射端口？

有映射启动的。http://localhost:9997应该是api的ip，目前是想打开他的webUI页面，就不知道如何打开。

**Comment by aresnow1** [comment]
docker 启动命令发一下

**Comment by ssseVennn** [comment]
> docker 启动命令发一下

docker run -d -p 9997:9997 xinference

**Comment by UranusSeven** [comment]
`xinference -p 9997 -H 0.0.0.0`

**Comment by ssseVennn** [comment]
> 应该不能只监听 localhost，试试看：`xinference -p 9997 -H 0.0.0.0`

非常感谢你，果然是这样。
