### ISSUE TITLE
BUG: `llama-cpp` version dismatch

### ISSUE THREAD

**Issue by xmfbit** [xorbitsai/inference#468]
### Describe the bug

`llama-cpp` package version dismatch in `setup.cfg` and `llamacpp.py`

see:

[setup.cfg](https://github.com/xorbitsai/inference/blob/main/setup.cfg#L67)
[llamacpp.py](https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/ggml/llamacpp.py#L190)

### To Reproduce

No need

### Expected behavior

update version requirement in `setup.cfg`

**Comment by UranusSeven** [comment]
Thanks for reporting this issue! We'd fix it ASAP.
