### ISSUE TITLE
QUESTION: worker cannot connected to supervisor with PodIP

### ISSUE THREAD

**Issue by saisaizhou** [xorbitsai/inference#493]
Deploy supervisor and worker in different pods with k8s.
following is the yaml file:

Supervisor:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: xinference-supervisor-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xinference-supervisor
  template:
    metadata:
      labels:
        app: xinference-supervisor
    spec:
      containers:
      - name: xinference
        image: */ai-demo/xinference:4.2
        ports:
        - containerPort: 9997
        command: ["/bin/sh","-c"]
        args: ["xinference-supervisor -H $MY_POD_IP"]
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            nvidia.com/gpu: "1"`

Worker:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: xinference-worker-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xinference-worker
  template:
    metadata:
      labels:
        app: xinference-worker
    spec:
      containers:
      - name: xinference
        image: */ai-demo/xinference:4.2
        command: ["/bin/sh","-c"]
        args: ["xinference-worker -e http://xinference-supervisor-service:9997"]
        resources:
          limits:
            nvidia.com/gpu: "1"`

Service:
`apiVersion: v1
kind: Service
metadata:
  name: xinference-supervisor-service
  namespace: default
spec:
  selector:
    app: xinference-supervisor
  ports:
  - protocol: TCP
    name: http
    port: 9997
    targetPort: 9997
    nodePort: 30000
  type: NodePort `
  
  Erro code:
`ConnectionRefusedError: [address=192.168.1.28:31037, pid=7] [Errno 111] Connect call failed ('0.0.0.0', 18201)`

**Comment by aresnow1** [comment]
Thanks for your feedback, it appears that the port of the supervisor is not exposed. We will fix this issue in the next version.
