### ISSUE TITLE
QUESTION: How do I configure to use multiple GPUs? Llama 2 13B-chat

### ISSUE THREAD

**Issue by jianhuaz** [xorbitsai/inference#503]
The server is equipped with four P100GPUs, loaded with Llama2 13B-chat, and only one GPU is used.

![image](https://github.com/xorbitsai/inference/assets/22927505/ca11d083-6f8e-44a8-a130-faacee6fed72)

![image](https://github.com/xorbitsai/inference/assets/22927505/c60c822e-0105-4960-9d1c-f897b93e5dca)

![image](https://github.com/xorbitsai/inference/assets/22927505/a95c22ac-f9e5-48a5-8c12-a57e718a61ce)

**Comment by UranusSeven** [comment]
Hi! Currently you cannot specify the number of GPU using web UI, instead, you can manually run `xinference launch` to do it.

Here's an example of running llama-2-chat on 4 GPUs:
```bash
xinference launch --model-name llama-2-chat --size-in-billions 7 --model-format ggmlv3 --quantization none --n-gpu 4
```

You can run `xinference launch --help` for the usage:
```bash
$ xinference launch --help
Usage: xinference launch [OPTIONS]

  Launch a model with the Xinference framework with the given parameters.

Options:
  -e, --endpoint TEXT             Xinference endpoint.
  -n, --model-name TEXT           Provide the name of the model to be
                                  launched.  [required]
  -t, --model-type TEXT           Specify type of model, LLM as default.
  -s, --size-in-billions INTEGER  Specify the model size in billions of
                                  parameters.
  -f, --model-format TEXT         Specify the format of the model, e.g.
                                  pytorch, ggmlv3, etc.
  -q, --quantization TEXT         Define the quantization settings for the
                                  model.
  -r, --replica INTEGER           The replica count of the model, default is
                                  1.
  --n-gpu TEXT                    The number of GPUs used by the model,
                                  default is "auto".
  --trust-remote-code BOOLEAN     Whether or not to allow for custom models
                                  defined on the Hub in their own modeling
                                  files.
  --help                          Show this message and exit.
```

**Comment by jianhuaz** [comment]
If I use the xinreference launch command, how can I specify the model I have downloaded?

![image](https://github.com/xorbitsai/inference/assets/22927505/21dafbd9-e211-4bec-9707-6e032041dcf3)

**Comment by UranusSeven** [comment]
You need to firstly register the custom model and then launch it using the model name you just registered.

Let's say you named the model "my-llama". You can launch it by running:

```bash
xinference launch --model-name my-llama --n-gpus 4 --quantization none 
```

**Comment by UranusSeven** [comment]
Note that quantization needs to be set to none for better performance when using multiple GPUs.

**Comment by jianhuaz** [comment]
![image](https://github.com/xorbitsai/inference/assets/22927505/786c9fde-a9ed-4062-86a9-5f64f0d049f8)


![image](https://github.com/xorbitsai/inference/assets/22927505/9f5941c1-1378-4c68-90c0-ab4ae4c63a2c)


![image](https://github.com/xorbitsai/inference/assets/22927505/2efadf3c-9468-4246-b110-e2f211d9cce7)

**Comment by jianhuaz** [comment]
![image](https://github.com/xorbitsai/inference/assets/22927505/8a0a916f-d00c-4015-aefd-ca59a8f3f20f)

**Comment by jianhuaz** [comment]
![image](https://github.com/xorbitsai/inference/assets/22927505/82565830-50d3-4202-a600-51d79db9e937)


![image](https://github.com/xorbitsai/inference/assets/22927505/e69c8efc-fa99-472b-8d33-36c03c60ba2d)


![image](https://github.com/xorbitsai/inference/assets/22927505/c101189a-b64b-4bb5-978c-249561424fc8)


![image](https://github.com/xorbitsai/inference/assets/22927505/c2ea7314-169a-498e-a8b5-212cca36c508)


![image](https://github.com/xorbitsai/inference/assets/22927505/0ac4d8d9-23f4-46cf-9ba2-4b54608d3bee)

**Comment by UranusSeven** [comment]
Is your model format GGML?

**Comment by UranusSeven** [comment]
A GGML model is a single binary file, xinference will split the model path into 2 parts, the base dir and the filename.

If your model is a GGML/ file, please fill in the full path. If it is a PyTorch model, fill in the directory since the model is consisted of multiple files.

**Comment by UranusSeven** [comment]
![image](https://github.com/xorbitsai/inference/assets/109661872/96472855-919b-42e7-b796-332abab65dd3)

**Comment by jianhuaz** [comment]
![image](https://github.com/xorbitsai/inference/assets/22927505/1390065e-64b5-4f94-93f7-3aea45d72fee)


convert_llama_weights_to_hf.py --input_dir /opt/llama13b/llama --model_size 13B --output_dir /opt/llama13B/


![image](https://github.com/xorbitsai/inference/assets/22927505/0979023f-b20b-4c75-90d5-79d31fc1b22b)


Is it correct to convert three bin files using convert_llama_weights_to_hf. py? 
It still needs to be converted using other methods.

**Comment by UranusSeven** [comment]
The files under `/opt/llama13B` looks good. Register it as a pytorch model should work.

**Comment by UranusSeven** [comment]
Great! 

Join our slack or wechat community if there is any further problem using xinference: https://xorbits.cn/community
