### ISSUE TITLE
FEAT: Add BAAI/bge-large-en-v1.5 and other models of v1.5 family

### ISSUE THREAD

**Issue by iguy0** [xorbitsai/inference#512]
Please add native support for the newer bge v1.5 models from BAAI -> https://huggingface.co/BAAI

https://huggingface.co/BAAI/bge-large-en-v1.5, https://huggingface.co/BAAI/bge-large-zh-v1.5, etc...

**Comment by UranusSeven** [comment]
Thank you for your feature request! The new bge models will be included as built-ins in the upcoming version, scheduled for release by the end of next Friday (10/13).

Stay up-to-date with all the latest developments in xinference by joining our [Slack channel](https://join.slack.com/t/xorbitsio/shared_invite/zt-1o3z9ucdh-RbfhbPVpx7prOVdM1CAuxg). We look forward to sharing more exciting updates with you there!
