### ISSUE TITLE
QUESTION: CUDA out of memory when running baichuan-2-7b on 4090

### ISSUE THREAD

**Issue by chenmonster** [xorbitsai/inference#516]
环境：
  torch==2.0.1+cu117
  xinference==0.4.4
启动 baichuan-2-chat-7b 模型时，占用GPU内存大概13G，但是调用服务后，就显存溢出了，如下图：
![1696756920025](https://github.com/xorbitsai/inference/assets/34160512/b24d4878-8aa7-4c40-9435-d2897584af66)
![1696756938235](https://github.com/xorbitsai/inference/assets/34160512/2ba34e96-9f2d-4b6c-8473-35746d70a9d5)

**Comment by UranusSeven** [comment]
@chenmonster Hi，感谢对 xinference 的关注。

显存开销主要是由模型权重和 kv cache 两部分组成，kv cache 的大小和请求数量及生成文本长度正相关。

请问你在调用服务的时候，会有很大的负载吗？

**Comment by chenmonster** [comment]
就是使用 [flowise ](https://github.com/FlowiseAI/Flowise) 调用 xinference API服务，知识库文件就 17k 大小，不应该有这么大的内存开销吧？
![1696768790049](https://github.com/xorbitsai/inference/assets/34160512/609be3a3-69a8-4ec8-ac8e-38a9d6fdd5c5)

**Comment by UranusSeven** [comment]
首先，可以在 xinference 启动的时候，加上 --log-level debug，通过日志观察 flowise 具体发了哪些请求。

其次，从上图看，embedding 这一步也是在用 LLM 做，这个可能是导致 OOM 的关键。根据我们的经验，LLM 的 embedding 效果并不是很好，召回的文本与查询匹配度不是很高。因此推荐使用 xinference 内置的 embedding 模型来替代：https://inference.readthedocs.io/en/latest/models/builtin/index.html#embedding-models

**Comment by Minamiyama** [comment]
> 启动 embedding 模型 bge-large-zh 报错 ![image](https://user-images.githubusercontent.com/34160512/274186678-76403d35-9fe7-4cd6-9acb-b3d465f83ae9.png)

好像是目前不支持在一张卡上同时启多个模型，不知道能否放宽限制，至少给同时启一个LLM和一个embedding @UranusSeven

**Comment by UranusSeven** [comment]
@Minamiyama @chenmonster 下周五的 release 中会支持。
