### ISSUE TITLE
QUESTION: `No available slot found for the model` when launching multiple models

### ISSUE THREAD

**Issue by amulettneo** [xorbitsai/inference#530]
### Describe the bug
1，使用Web同一个机器无法开启多个模型
2，使用命令行启动提示no slot 
3，请给出如何将模型作为embedding模型的命令指南，web上最好能有功能按钮
4，embedding模型如m3e-base如何注册并启动 麻烦给出指南

麻烦并感谢🙏

**Comment by LixiangHello** [comment]
如何结果这个问题？ 24G显卡 一个模型16G  一个1.8G 不能同时运行

**Comment by sammichenVV** [comment]
> Hi，感谢对 xinference 的关注！
> 
> 前两个问题实际上是同一个问题。原因是为了降低 OOM 发生的概率，目前 xinference 的策略是每张卡上只能放一个模型。因此如果只有一块 GPU 时，启动第二个模型会报错 `No available slot found for the model`。
> 
> 你可以 terminate 当前模型，此时 GPU 空闲，就可以加载第二个模型了。
> 
> 另外，在一张卡上加载多个模型的策略正在开发中，到时如果显存足够，将能够在同一个 GPU 上加载多个模型。
> 
> 关于 embedding 模型的使用文档我们也将会在近期补充。

您好我遇到了个类似的问题，指定gpu-idx参数就报如下图的错，但是其实我没有运行任何LLM,不指定gpu-id就报错No available slot found for the model，也不知道怎么删除qwen这个模型，请问您知道如何解决么
![image](https://github.com/xorbitsai/inference/assets/22388079/70903b4b-3f2f-44b3-b9d2-460cffba84c0)

**Comment by jony4** [comment]
复现逻辑 https://github.com/xorbitsai/inference/issues/888#issuecomment-2198456521
