### ISSUE TITLE
在Dify平台中部署xinference本地模型，在符合Xinference embed模型的基础上，在配置框中选择Embeddings报错。

### ISSUE THREAD

**Issue by YinSonglin1997** [xorbitsai/inference#534]
通过xinference部署baichuan-2模型，在配置中选择文本生成没有问题，但是选择Embeddings报错。可Dify文档中说明支持Xinference embed模型作为 Embedding 模型使用。请问这是什么原因呢？
[https://github.com/xorbitsai/inference/blob/main/README.md#builtin-models](url)
![274783954-b9f8f6ef-0082-4aeb-9c10-a67c2ad0c509](https://github.com/xorbitsai/inference/assets/90330685/d7090417-0fba-440e-a01c-37a86c49f2c7)

**Comment by aresnow1** [comment]
选择什么模型做 embedding ？

**Comment by YinSonglin1997** [comment]
> 选择什么模型做 embedding ？

我尝试了baichuan-2和baichuan-2-chat模型，都不能做embedding

**Comment by aresnow1** [comment]
> > 选择什么模型做 embedding ？
> 
> 我尝试了baichuan-2和baichuan-2-chat模型，都不能做embedding

这类 LLM 模型不太适合做 embedding，可以尝试使用专门的 embedding 模型来做，https://inference.readthedocs.io/en/latest/models/builtin/index.html#embedding-models
