### ISSUE TITLE
FEAT: OpenAI drop in replacement for /v1/completions (i.e. chat completions).

### ISSUE THREAD

**Issue by bmwas** [xorbitsai/inference#564]
### Is your feature request related to a problem? Please describe
To  fully leverage an opensource language model, I would like to tap into langchain's ChatOpenAI in a drop manner (i.e. as it is). Langchain does provide drop in replacements with the vLLM package. 

https://python.langchain.com/docs/integrations/chat/vllm

### Describe the solution you'd like

Integrate ChatOpenAI drop in alternative provided with vLLM (see link above).

### Describe alternatives you've considered

Self hosting vLLM and exposing an endpoint but I consider the xinference approach much superior especially with the model registry. 

### Additional context

https://python.langchain.com/docs/integrations/chat/vllm
https://python.langchain.com/docs/integrations/llms/openai

**Comment by codingl2k1** [comment]
take

**Comment by aresnow1** [comment]
We have created a pull request: https://github.com/langchain-ai/langchain/pull/12702, waiting for it to be merged!
