### ISSUE TITLE
BUG: embedding models `bge-base-zh` and `bge-large-zh`  on modelscope have some problems

### ISSUE THREAD

**Issue by YinSonglin1997** [xorbitsai/inference#569]
I test the five embedding models of bge-base-zh, bge-large-zh, bge-base-zh-v1.5, bge-large-zh-v1.5 and bge-small-zh. The following errors occurred when testing the bge-base-zh and bge-large-zh respectively, and the other three models are normal.
![1698026787161](https://github.com/xorbitsai/inference/assets/90330685/b406281e-084b-47e1-a2ab-6914c72f0bee)
![1698026829622](https://github.com/xorbitsai/inference/assets/90330685/bede5319-f02a-4859-92da-fe0c1ce1cb5e)

**Comment by aresnow1** [comment]
For the first issue, was it tested with GPUs? It appears that no available GPU can be found. The second seems download failed, possibly due to a network issue.

**Comment by YinSonglin1997** [comment]
> For the first issue, was it tested with GPUs? It appears that no available GPU can be found. The second seems download failed, possibly due to a network issue.

Well, the other three embedding models worked fine, which doesn't sound like it.

**Comment by aresnow1** [comment]
We will attempt to reproduce it, and if there are any issues, we will fix them as soon as possible.

**Comment by ChengjieLi28** [comment]
Hi, @YinSonglin1997 . There have already an PR for next release to fix your issue. 
For the next release, you can clean your cache dir and retry.
modelscope cache dir: `<home>/.cache/modelscope/hub/Xorbits`
xinference cache dir: `<home>/.xinference/cache`

**Comment by YinSonglin1997** [comment]
> Hi, @YinSonglin1997 . There have already an PR for next release to fix your issue. For the next release, you can clean your cache dir and retry. modelscope cache dir: `<home>/.cache/modelscope/hub/Xorbits` xinference cache dir: `<home>/.xinference/cache`
