### ISSUE TITLE
After upgrading xinference to 0.5.4, an error occurred when accessing model chat on the Dify platform

### ISSUE THREAD

**Issue by YinSonglin1997** [xorbitsai/inference#574]
After upgrading xinference to 0.5.4, an error occurred when accessing the model chat on the Dify platform. When xinference==0.5.2, it was confirmed that there was no problem. Taking baichuan-2-chat as an example, the error was reported as follows:
![1698045345034](https://github.com/xorbitsai/inference/assets/90330685/9875ca01-9bdf-48f6-b5b2-87ca2790847b)
![1698044513065](https://github.com/xorbitsai/inference/assets/90330685/cb2a126a-01d8-4174-a712-a4f901e2daeb)

**Comment by codingl2k1** [comment]
Dify is using an old version of xinference which is not compatible with xinference 0.5.4

**Comment by aresnow1** [comment]
It should be resolved by latest dify.
