### ISSUE TITLE
QUESTION: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects 

### ISSUE THREAD

**Issue by shanton23** [xorbitsai/inference#577]
### Describe the bug
ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

### To Reproduce
My os is Ubuntu20.04lts, and i use miniconda to create a totally new environment.
When running 'pip install 'xinference[all]', I got this error.

**Comment by aresnow1** [comment]
Do you have GPU cards on your machine?

**Comment by UranusSeven** [comment]
Hello, this issue is typically caused by incompatible GCC versions. Could you please provide the full installation log?

**Comment by UranusSeven** [comment]
@shanton23 Hi, were you able to solve this problem? Is there anything I can help?

**Comment by shanton23** [comment]
> Do you have GPU cards on your machine?

I hava a 4090.

**Comment by shanton23** [comment]
> @shanton23 Hi, were you able to solve this problem? Is there anything I can help?



> Hello, this issue is typically caused by incompatible GCC versions. Could you please provide the full installation log?

My gcc version is 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1).

**Comment by bizheyandebing** [comment]
I also have the same problem, how can I solve it? It appeared when I installed llama-spp-python.

**Comment by bizheyandebing** [comment]
After I upgraded gcc through the following command “sudo apt install gcc-11 g++-11”, this problem has not been improved. I hope to get your help. Thank you very much.

**Comment by bizheyandebing** [comment]
Perhaps, can you directly share a requirements.txt or environment.yaml used to create a conda environment?

**Comment by kukuze** [comment]
You can follow this "https://zhuanlan.zhihu.com/p/592894910?utm_id=0"  up the gcc version to 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) (i am centos7)

**Comment by QiuZiXian** [comment]
升级到11了，还是不行
![image](https://github.com/xorbitsai/inference/assets/28780269/92321d34-cc7c-4aa9-ab27-30935192cf9a)

**Comment by bclovetkd** [comment]
我也有同样的问题，gcc 13，python 3.11，cuda 12.1

**Comment by ques666** [comment]
> 我也有同样的问题，gcc 13，python 3.11，cuda 12.1

估计是在编译过程中有权限问题，我conda  base安装会报这个错误，但是conda新建一个xinference环境，然后在新建的环境安装就OK了

**Comment by ques666** [comment]
> 我也有同样的问题，gcc 13，python 3.11，cuda 12.1

0.2.82太新了，编译不了，手动装一下老一点的版本 pip install llama-cpp-python==0.2.80

**Comment by ASan1527** [comment]
> > 我也有同样的问题，gcc 13，python 3.11，cuda 12.1
> 
> 0.2.82太新了，编译不了，手动装一下老一点的版本 pip install llama-cpp-python==0.2.80



大哥chatglm-cpp多少版本的合适呢

**Comment by ques666** [comment]
> > > 我也有同样的问题，gcc 13，python 3.11，cuda 12.1
> > 
> > 
> > 0.2.82太新了，编译不了，手动装一下老一点的版本 pip install llama-cpp-python==0.2.80
> 
> 大哥chatglm-cpp多少版本的合适呢

我用 0.4.0没问题，你的chatglm-cpp应该不是版本问题，可以新建一个conda环境试一下

**Comment by thinkinds** [comment]
> llama-cpp-python==0.2.80

为啥我用0.2.80还是不行呢

**Comment by ques666** [comment]
> > llama-cpp-python==0.2.80
> 
> 为啥我用0.2.80还是不行呢

新建的conda环境吗？
