### ISSUE TITLE
QUESTION: Could speculative decoding be used with vLLM?

### ISSUE THREAD

**Issue by zhaoyang-star** [xorbitsai/inference#578]
Hi, vLLM has high throughput and speculative decoding has low latency. So could both be used in xinference? Could you please give a demo for it? Thanks.

**Comment by UranusSeven** [comment]
Hello! That's an excellent question. Speculative decoding can be applied to vLLM, and the performance is expected to be promising. The vLLM community is actively working on this feature. And we will continue to monitor the progress and aim to implement this feature once it is released.

**Comment by zhaoyang-star** [comment]
So does the vLLM community has any plan on when to release this feature? Can't wait to try it.

**Comment by zhaoyang-star** [comment]
Another question: The impl of Speculative Decoding in Xinference is based PyTorch backend. Does the feature support mult-batching, as mult-batching is common in online case.
