### ISSUE TITLE
BUG: Error occurs when using xinference v0.5.6 on a dify chat app

### ISSUE THREAD

**Issue by JiaYaobo** [xorbitsai/inference#598]
### Describe the bug
After deploy dify@HEAD locally with docker, and start xinference with `xinference -p 9997 -H 0.0.0.0`, using a chatglm2 model. Encountering the following error:
<img width="704" alt="截屏2023-11-01 08 21 57" src="https://github.com/xorbitsai/inference/assets/59967634/ac4effcf-bdeb-4437-aa22-911d849d3676">

And xinference itself works fine on gradio web app.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 3.10
2. The version of xinference you use. v0.5.6
3. Versions of crucial packages. dify@HEAD and install xinference with `pip install xinference[all]`

### Additional context
Same issue is https://github.com/xorbitsai/inference/issues/574, seems it has been solved with xinference v0.5.4

**Comment by UranusSeven** [comment]
Thank you for reporting this issue! We will attempt to reproduce it and work on a fix.

**Comment by UranusSeven** [comment]
@JiaYaobo Hello, I was unable to reproduce this issue. Can you confirm if this problem is reproducible in your environment?
