### ISSUE TITLE
无法从Hugging Face上下载模型

### ISSUE THREAD

**Issue by Aunixtoyou** [xorbitsai/inference#599]
Hugging Face的仓库API好像改了，需要TOKEN了

![image](https://github.com/xorbitsai/inference/assets/17799702/06948fc4-9560-42ea-a4dc-538de33b53d0)

能不能出一个离线手动部署的教程呢？

**Comment by UranusSeven** [comment]
https://inference.readthedocs.io/en/latest/getting_started/troubleshooting.html#no-huggingface-repo-access
