### ISSUE TITLE
QUESTION : launch无法调用下载好的模型，依然要下载

### ISSUE THREAD

**Issue by pangpang97** [xorbitsai/inference#620]
大佬好，

我将之前下载好的baichuan-2的7B模型copy到/home/users/.xinference/cache/baichuan-2-pytorch-7b目录下，然后执行xinference launch --model-name chatglm3 --size-in-billions 6 --model-format pytorch --quantization '4-bit' -e "http://127.0.0.1:9997"  依然显示要要下载模型。

想请问下大佬，有什么办法让xinference直接调用我下载好的，而不是自己再下载一遍呢

多谢大佬

**Comment by UranusSeven** [comment]
https://inference.readthedocs.io/en/latest/models/custom.html

**Comment by pangpang97** [comment]
多谢大佬  我试一下

**Comment by UranusSeven** [comment]
不要 hack xinference 的 cache 目录，这个目录的组织结构和行为很可能随着版本发生变化，我们会尽可能保证向后兼容，但如果你 hack 了这个目录，就无法保证了。

**Comment by UranusSeven** [comment]
@pangpang97 另外不同的 chat & instruction following 模型有不同的 prompt template 对应，在 xinference 中被称作 prompt style，在写 custom model 配置文件的时候，prompt style 部分可以参考：https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/llm_family.py
