### ISSUE TITLE
BUG: xinference local start up failed

### ISSUE THREAD

**Issue by mioMare77** [xorbitsai/inference#627]
### Describe the bug
xinference start failed:
![image](https://github.com/xorbitsai/inference/assets/142886590/778c4951-b162-4d5e-98a1-c3938febd85f)
![image](https://github.com/xorbitsai/inference/assets/142886590/c3ccd17e-d88d-4833-83a1-84d5ad0d72dd)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.   3.11
2. The version of xinference you use.  0.6.1
3. Versions of crucial packages. cuda: 12.2
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by UranusSeven** [comment]
Hello, thank you for bringing this issue to our attention!

Could you please check if the following environment variables are set up correctly on your system?

```bash
CUDA_HOME=/path/to/cuda
export PATH="$CUDA_HOME/bin:$PATH"
export CPATH="$CUDA_HOME/targets/x86_64-linux/include:$CPATH"
export LD_LIBRARY_PATH="$CUDA_HOME/targets/x86_64-linux/lib:$LD_LIBRARY_PATH"
```

**Comment by mioMare77** [comment]
> Hello, thank you for bringing this issue to our attention!
> 
> Could you please check if the following environment variables are set up correctly on your system?
> 
> ```shell
> CUDA_HOME=/path/to/cuda
> export PATH="$CUDA_HOME/bin:$PATH"
> export CPATH="$CUDA_HOME/targets/x86_64-linux/include:$CPATH"
> export LD_LIBRARY_PATH="$CUDA_HOME/targets/x86_64-linux/lib:$LD_LIBRARY_PATH"
> ```

Yes，I checked these env variables as follow:
![image](https://github.com/xorbitsai/inference/assets/142886590/9f0331ba-c52b-4257-b245-145121ba3202)
But still get the same error:
![image](https://github.com/xorbitsai/inference/assets/142886590/224768e6-977c-4942-a7ae-97a2ac583981)
