### ISSUE TITLE
BUG：Embedding web ui abnormal display

### ISSUE THREAD

**Issue by ChengjieLi28** [xorbitsai/inference#632]
Note that the issue tracker is NOT the place for general support.
After launching embedding model on GPU:
<img width="1825" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/7e6328d5-7e6e-4369-8018-705685f5c330">

**Comment by UranusSeven** [comment]
You mean the address?

**Comment by ChengjieLi28** [comment]
> You mean the address?

<img width="1446" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/7179728b-075d-4fd8-a54a-1ea610200e08">
Does embedding model have the `Cached` mark?

**Comment by ChengjieLi28** [comment]
I cached `bge-base-en-v1.5` locally. But it is not shown here.
<img width="1448" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/182445c7-e232-4da8-a1fc-6284f8c13950">

**Comment by UranusSeven** [comment]
No, at present, the embedding model cards do not display the 'Cached' tag. While the cache status is provided by the API, modifications are required on the frontend to display this tag.
