### ISSUE TITLE
QUESTION: change the save path for models

### ISSUE THREAD

**Issue by yonghongwu** [xorbitsai/inference#635]
How can I set my own save path instead of ${user}/. xinreference/cache

**Comment by waltcow** [comment]
I have similar question too. I downloa models from huggingface via aria2, cause it can download with multi thread support. After downloaded, don't know how to put the models file to which directory

**Comment by aresnow1** [comment]
Refer to the documentation: https://inference.readthedocs.io/en/latest/getting_started/using_xinference.html#configure-xinference-home-path

**Comment by aresnow1** [comment]
> I have similar question too. I downloa models from huggingface via aria2, cause it can download with multi thread support. After downloaded, don't know how to put the models file to which directory

It is not recommended to copy the model to the cache directory. You can use the mechanism of registering models to use your own local model. Here's doc: https://inference.readthedocs.io/en/latest/models/custom.html, or you can register on Web UI.
