### ISSUE TITLE
QUESTION: 我起了xinference的服务后，怎么启用glm3 类openai api的服务呢

### ISSUE THREAD

**Issue by Cn-cpjl** [xorbitsai/inference#636]
我起了xinference的服务后，怎么启用glm3 类openai api的服务呢，直接启动resful api 不成功

**Comment by aresnow1** [comment]
Could you paste your error messages?

**Comment by Cn-cpjl** [comment]
我的操作步骤是这样的
1. xinference -p 9997
2. root@dsw-144070-55df97dc66-fbz7s:/mnt/workspace/inference/xinference/api# python restful_api.py
Traceback (most recent call last):
  File "restful_api.py", line 47, in <module>
    from ..constants import XINFERENCE_DEFAULT_ENDPOINT_PORT
ImportError: attempted relative import with no known parent package

**Comment by aresnow1** [comment]
需要 pip install xinference 或者从源码安装，不可以直接执行文件。可以参考 README 或者文档。
https://github.com/xorbitsai/inference#deployment
https://inference.readthedocs.io/en/latest/getting_started/using_xinference.html#using-xinference-locally

**Comment by UranusSeven** [comment]
@Cn-cpjl Hi，通过 `xinference -p 9997` 启动 xinference 之后，xinference 的 endpoint （默认为`http://localhost:9997`）就是一个 OpenAI compatible 的 API 服务。

**Comment by aresnow1** [comment]
先关闭了，有问题可以 reopen，或者开新的 issue
