### ISSUE TITLE
FEAT: Assign a custom ID to the model

### ISSUE THREAD

**Issue by Night-Quiet** [xorbitsai/inference#637]
### Is your feature request related to a problem? Please describe
Deploying a model always involves model update iterations. If the model ID can be customized, it will not change when replacing the model, the code that calls the model does not require any changes

### Describe the solution you'd like
Do not use a unique ID as a model specification. Alternatively, allow alias IDs for model specification.

### Describe alternatives you've considered
Do not use a unique ID as a model specification. Alternatively, allow alias IDs for model specification.

### Additional context
None

**Comment by codingl2k1** [comment]
Have you tried the `-u` param to specify custom model uid?

```text
Usage: xinference launch [OPTIONS]

  Launch a model with the Xinference framework with the given parameters.

Options:
  -e, --endpoint TEXT             Xinference endpoint.
  -n, --model-name TEXT           Provide the name of the model to be
                                  launched.  [required]
  -t, --model-type TEXT           Specify type of model, LLM as default.
  -u, --model-uid TEXT            Specify UID of model, default is None.
  -s, --size-in-billions INTEGER  Specify the model size in billions of
                                  parameters.
  -f, --model-format TEXT         Specify the format of the model, e.g.
                                  pytorch, ggmlv3, etc.
  -q, --quantization TEXT         Define the quantization settings for the
                                  model.
  -r, --replica INTEGER           The replica count of the model, default is
                                  1.
  --n-gpu TEXT                    The number of GPUs used by the model,
                                  default is "auto".
  --trust-remote-code BOOLEAN     Whether or not to allow for custom models
                                  defined on the Hub in their own modeling
                                  files.
  --help                          Show this message and exit.

```
For example, `xinference launch -n bge-base-en-v1.5 --model-type embedding -u my_embedding -r 2` specify the model uid as `my_embedding`.

**Comment by Night-Quiet** [comment]
Sorry, it's my problem. I'll give it a try, thank you.

**Comment by codingl2k1** [comment]
> Sorry, it's my problem. I'll give it a try, thank you.

Does it meet your needs?

**Comment by Night-Quiet** [comment]
> > Sorry, it's my problem. I'll give it a try, thank you.
> 
> Does it meet your needs?

Yes, it perfectly meets the requirements. Next time, I will carefully read the document before asking questions. Thank you.
