### ISSUE TITLE
BUG: model is launched but can not find any items in UI

### ISSUE THREAD

**Issue by waltcow** [xorbitsai/inference#639]
### Describe the bug
 model is launched via UI, but can not find any items in UI (Running model)

### To Reproduce

<img width="2180" alt="image" src="https://github.com/xorbitsai/inference/assets/3941174/a699d869-27fc-45e4-9fc0-e5a209a2b230">

**Comment by ChengjieLi28** [comment]
Hi, @waltcow . I have noticed that you have closed the current xinference service via ctrl-C:
<img width="705" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/8dec6d7d-d25b-4b92-bdce-aa3a09096f4e">
Please check that whether you open the UI of a xinference service that was started elsewhere.

**Comment by ChengjieLi28** [comment]
> Your quote block is just my tail log command.

In this case, please check the port of the web UI you open is the same as the cluster web port where you launch the model.

**Comment by waltcow** [comment]
> > Your quote block is just my tail log command.
> 
> In this case, please check the port of the web UI you open is the same as the cluster web port where you launch the model.

I have double check the UI and model launch in the same host

**Comment by UranusSeven** [comment]
Could you please verify if there are any error logs in the browser?

**Comment by waltcow** [comment]
<img width="1688" alt="image" src="https://github.com/xorbitsai/inference/assets/3941174/6e5707a9-6336-4b29-a5dd-63bf5f36e62c">


it seems like related to domain security

**Comment by ChengjieLi28** [comment]
> <img alt="image" width="1688" src="https://user-images.githubusercontent.com/3941174/282433309-6e5707a9-6336-4b29-a5dd-63bf5f36e62c.png">
> it seems like related to domain security

Currently we only support http services for xinference, the reason for this is that https servers make requests to http resources.

**Comment by UranusSeven** [comment]
@waltcow Hello, are you accessing the endpoint using https? You might want to try the following workaround mentioned here: https://stackoverflow.com/a/76909337/7098025
