### ISSUE TITLE
ENH: Choose number of cards when launching models via UI

### ISSUE THREAD

**Issue by aresnow1** [xorbitsai/inference#642]
### Is your feature request related to a problem? Please describe
Add a button for users to choose number of cards when launch models.

### Additional context

Related #640

**Comment by Bojun-Feng** [comment]
For this enhancement, do we just need to set the `n_gpu` parameter through the UI and pass it to API call? If so, I would be happy to implement the feature. Shouldn't take too long since I developed the UI and am familiar with it

**Comment by aresnow1** [comment]
> For this enhancement, do we just need to set the `n_gpu` parameter through the UI and pass it to API call? If so, I would be happy to implement the feature. Shouldn't take too long since I developed the UI and am familiar with it

It has been implemented in #730.
