### ISSUE TITLE
请问，能否提供Yi-200k模型加载后，调用接口的example，另外，请问量化加载的都是gptq的量化模型吧，tks

### ISSUE THREAD

**Issue by tfal-yan** [xorbitsai/inference#644]
请问，能否提供Yi-200k模型加载后，调用接口的example，多谢

**Comment by aresnow1** [comment]
可以查看我们的文档：https://inference.readthedocs.io/en/latest/getting_started/accessing_models.html#using-xinference-client
以及一些示例：https://inference.readthedocs.io/en/latest/examples/index.html#examples

**Comment by aresnow1** [comment]
如果是 pytorch 模型的话，目前量化用的是 bitsandbytes，后续会支持 gptq

**Comment by tfal-yan** [comment]
# Load model
    tokenizer = AutoTokenizer.from_pretrained(
        args.model, trust_remote_code=args.trust_remote_code
    )
    再请教下，Yi模型提供的awq量化方法（如下），如果gpu卡内存本身不够的话，是没法使用的吧^_^，有点自己抱自己的感觉 
   ^_^

   model = AutoAWQForCausalLM.from_pretrained(args.model)

    quant_config = {
        "zero_point": True,
        "q_group_size": args.group_size,
        "w_bit": args.bits,
    }
    # Quantize
    model.quantize(tokenizer, quant_config=quant_config)

    # Save quantized model
    model.save_quantized(args.output_dir, safetensors=True)
    tokenizer.save_pretrained(args.output_dir)

**Comment by tfal-yan** [comment]
下面Yi-200k的generate调用的，请问，是我用错了吗^_^
promptStr = "北京是哪个国家的首都"
outputs = model.generate(
    promptStr
)
print(outputs)
choices': [{'text': '。\n4.在德国，有人口超过百万的城市有（ ）个。\nA.2 B.5 C.8 D.10\n5.目前德国最大的港口城市是（ ）\nA.汉堡 B.不来梅 C.汉诺威 D.基尔\n6.在德国的东部，曾经有过一个国家，与德国合并成联邦德国的是（）\nA.民主德国 B.奥地利\nC.匈牙利 D.捷克斯洛伐克\n7.德国最大的河流莱茵河的发源地是（ ）\nA.瑞士 B.荷兰 C.', 'index': 0, 'logprobs': None, 'finish_reason': 'length'}]
