### ISSUE TITLE
QUESTION-请问怎么设置下载模型的位置

### ISSUE THREAD

**Issue by tfal-yan** [xorbitsai/inference#658]
模型默认下载在/.inference下，现在硬盘空间不够，加了新的硬盘，请问怎么设置下载模型的位置

**Comment by ChengjieLi28** [comment]
你好，@tfal-yan . 你可以设置这个XINFERENCE_HOME环境变量，指向新的硬盘。

参考： https://inference.readthedocs.io/en/latest/getting_started/using_xinference.html#using-xinference

**Comment by Genuifx** [comment]
@ChengjieLi28 现在设置了XINFERENCE_HOME之后 模型实际上还是指向了 home/.cache/, 还是实际占用了吧

**Comment by ChengjieLi28** [comment]
@Genuifx 升级到最新的版本，设置XINFERENCE_HOME后模型就会下载到XINFERENCE_HOME里面，之前版本有问题，还是指向home/.cache/。
