### ISSUE TITLE
FEAT: JSON mode for Llama.cpp

### ISSUE THREAD

**Issue by Bojun-Feng** [xorbitsai/inference#691]
### Is your feature request related to a problem? Please describe

Similar to OpenAI's JSON mode, we can use custom grammar files to ask Llama.cpp to generate a valid JSON array without filler text (e.g. "Sure! Here is your JSON file").

This should be useful for users trying to summarize large quantities of information in a guaranteed structured manner, even with small models unable to generate valid JSON from prompt alone.

### Describe the solution you'd like

https://til.simonwillison.net/llms/llama-cpp-python-grammars

This blog post describes how to use grammar files to generate JSON. Ideally, there would be a response_format field, similar to openAI JSON mode API. If the model is PyTorch or ChatGLM we can just return an error message stating that this model does not have the JSON mode feature, which is also what OpenAI is practicing.

Alternatively, we can also allow an input for users to inject their custom grammar file for Llama.cpp models, but that would be more of a hot fix.

### Additional context

Example input output format in OpenAI documentation:

```
import os
from openai import OpenAI
client = OpenAI()
OpenAI.api_key = os.getenv('OPENAI_API_KEY')

completion = client.chat.completions.create(
  model="gpt-4-1106-preview",
  messages=[
    {"role": "system", "content": "You are a helpful assistant. Your response should be in JSON format."},
    {"role": "user", "content": "Hello!"}
  ],
  response_format={"type": "json_object"}
)

print(completion)
```

```
ChatCompletion(
    id='chatcmpl-888ER1vWIT8l5FIJ4VxDFrKA1B2C3', 
    choices=[
        Choice(
            finish_reason='stop', 
            index=0, 
            message=ChatCompletionMessage(
                content='{\n  "response": "Hello! How can I assist you today?"\n}', 
                role='assistant', 
                function_call=None, 
                tool_calls=None
            )
        )
    ], 
    created=1600902535, 
    model='gpt-4-1106-preview', 
    object='chat.completion', 
    system_fingerprint='fp_b16r4k8341', 
    usage=CompletionUsage(
        completion_tokens=16, 
        prompt_tokens=27, 
        total_tokens=43
    )
)
```

If we change the model to `gpt-4` or other older models, we would get:

```
BadRequestError: Error code: 400 - {
    'error': 
    {
        'message': "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.", 
        'type': 'invalid_request_error', 
        'param': 'response_format', 
        'code': None
    }
}
```

**Comment by aresnow1** [comment]
We've supported grammar input for ggml models in https://github.com/xorbitsai/inference/pull/525, are you interested in implementing this API?

**Comment by Bojun-Feng** [comment]
> We've supported grammar input for ggml models in #525, are you interested in implementing this API?

Yes! It is currently finals week for me though so I might start working on ~Dec 9th when the semester is over. If the API is not an urgent issue I would be more than happy to implement it.
