### ISSUE TITLE
Support  `get_openai_callback` in Langchain (which is very useful for token usage counting)

### ISSUE THREAD

**Issue by onesuper** [xorbitsai/inference#693]
For example:

```
from langchain.callbacks import get_openai_callback

with get_openai_callback() as cb:
    result = llm.invoke(prompt, generate_config= {"max_tokens": max_tokens})
    print(cb.total_tokens)
```

**Comment by ishaan-jaff** [comment]
Hi @onesuper  I'm the maintainer of LiteLLM https://github.com/BerriAI/litellm we allow you to do cost tracking for 100+ LLMs 

## Usage
Docs: https://docs.litellm.ai/docs/#calculate-costs-usage-latency
```python
from litellm import completion, completion_cost
import os
os.environ["OPENAI_API_KEY"] = "your-api-key"

response = completion(
  model="gpt-3.5-turbo", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)

cost = completion_cost(completion_response=response)
print("Cost for completion call with gpt-3.5-turbo: ", f"${float(cost):.10f}")
```

We also allow you to create a self hosted OpenAI Compatible proxy server to make your LLM calls (100+ LLMs), track costs, token usage 
Docs: https://docs.litellm.ai/docs/simple_proxy 

I hope this is helpful, if not I'd love your feedback on what we can improve
