### ISSUE TITLE
QUESTION: How to use both gptq and vllm in qwen-14b model?

### ISSUE THREAD

**Issue by tms2003** [xorbitsai/inference#697]
The vllm version already supports gptq quantization of qwen 14b-4bit (in the quantization branch), so how do I use them in xinference?

**Comment by aresnow1** [comment]
We need to test it, some adaptation work may be required.

**Comment by aresnow1** [comment]
It seems vllm's support for gptq is in progress(https://github.com/vllm-project/vllm/pull/1580), how did you use vllm with GPTQ

**Comment by tms2003** [comment]
@aresnow1  The branch code of vllm can be found at https://github.com/chu-tianxiang/vllm-gptq/. It is a branch from vllm. All questions can be asked on the main branch of vllm, so it is the correct official one. The code, but due to many conflicts in the code, was not merged into the main branch. After testing, its code is usable.

**Comment by aresnow1** [comment]
It needs some changes to support passing quantization method, I'll create a PR to support this later.
