### ISSUE TITLE
Provide some authentication mechanism for UI and API

### ISSUE THREAD

**Issue by jeromeroussin** [xorbitsai/inference#698]
### Is your feature request related to a problem? Please describe
Currently anyone with the xinference URL can make requests and add/remove models. I need a little more control. It does not have to be necessarily very sophisticated initially, some sort of shared secret would do, although if you guys are willing to consider more full fledged authentication mechanisms that would certainly be welcome.

### Describe the solution you'd like
The simplest viable solution for me here would be a single shared secret, like a "root"/password type of credentials, with "password" being configurable

**Comment by aresnow1** [comment]
Yes, it's in our roadmap, and we plan to implement it within next two to three releases, suggestions are welcome.
