### ISSUE TITLE
QUESTION 我想指定具体一张GPU卡运行模型

### ISSUE THREAD

**Issue by luckfu** [xorbitsai/inference#720]
Note that the issue tracker is NOT the place for general support.
不知道怎样指定具体哪块GPU运行模型

**Comment by ChengjieLi28** [comment]
Hi, @luckfu . You can specify `CUDA_VISIBLE_DEVICES` environment variable when starting xinference. For example:
```
CUDA_VISIBLE_DEVICES=0 xinference-local 
```
Otherwise, if there are GPU cards on your machine, xinference will select one of them to launch a model.
