### ISSUE TITLE
QUESTION: how to register a custom rerank model ,and how to run a reank model

### ISSUE THREAD

**Issue by gqchen-dz** [xorbitsai/inference#734]
Inference 0.6.5
when I register a bge-reranker-large model by : xinference register -t rerank -f /path to the model/model.json -p
and ,get the error : RuntimeError: Failed to register model, detail: [address=0.0.0.0:38337, pid=34848] Unsupported model type: rerank

**Comment by aresnow1** [comment]
we have builtin support for `bge-reranker-large`: https://inference.readthedocs.io/en/latest/models/builtin/bge-reranker-large.html#models-builtin-bge-rerank-large
