### ISSUE TITLE
BUG: Service Unavailable for url

### ISSUE THREAD

**Issue by Grey0520** [xorbitsai/inference#745]
### Describe the bug
the localhost don't work

### To Reproduce
setup on my **server**:
`xinference -p 9997 -H 0.0.0.0`

then I launch  model 'qwen-chat' on my computer, use http://ip:9997

finished, and pop a web page, I go into the chat panel.

Input something , met the error:
```
Error
Failed to get the model description, detail: 503 Server Error: Service Unavailable for url: http://localhost:9997/v1/models/da7feda0-95aa-11ee-8c10-75a75f72ca7f
```

### Expected behavior
fix the error

### Additional context
A few days ago, I could access it normally.

**Comment by aresnow1** [comment]
Could you paste full error messages?

**Comment by Grey0520** [comment]
> Could you paste full error messages?

There is no need, beacuse I find the reason just now.

There are 
![image](https://github.com/xorbitsai/inference/assets/70519059/b361e9d9-a234-4654-bfcf-04db88874ffe)
proxy in my env, so met the erros.

When I unset them, it works!
