### ISSUE TITLE
Inquiry about Adding French and German Language Support in xInference

### ISSUE THREAD

**Issue by MrBrabus75** [xorbitsai/inference#750]
Hello,

I'm currently using xInference in a local setup and have been exploring its capabilities. I have a specific question regarding language support in the system:

Adding French and German Language Support: Is it possible to extend the language capabilities of xInference to include French and German? If this feature is available or can be implemented, I would appreciate guidance on how to proceed with this addition.

Including these languages would significantly enhance the utility of xInference in multilingual environments and cater to a broader user base. Any insights, documentation, or steps to achieve this would be extremely helpful.

Looking forward to your response and any assistance you can provide.

Best regards,

**Comment by aresnow1** [comment]
Hi, thanks for your suggestions. Does multilingual support refer to the ability to display the UI in French or German, or does it refer to support for these languages in the documentation?

**Comment by MrBrabus75** [comment]
The request is to support multilingual capabilities in the user interface, as well as in the model selection options. If a new model is added that supports French and German, currently only English and Chinese options are available. The goal is to have the ability to add German and/or French if possible.

**Comment by aresnow1** [comment]
If web UI support is required, we would need to introduce support for internationalization. We can consider adding this in the next version, and to support other languages, you only need to configure a JSON file. 

For multi-language support for LLM models, we can also add support for other languages by specifying the language in the JSON file for the supported models. The relevant fields can be found here: https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/llm_family.json#L6

**Comment by MrBrabus75** [comment]
Indeed, I had found this JSON file which I modified, but it would be better if the feature for multi-language support could be implemented directly on the website and the models. Anyway, it's not something crucial; I'll consider it for the future. Thank you very much for the work you are doing! Really, thank you.
