### ISSUE TITLE
Request for Support for Mistralai/Mixtral-8x7B-Instruct-v0.1 LLM

### ISSUE THREAD

**Issue by Grey0520** [xorbitsai/inference#751]
Dear maintainers of this awesome project,

link: https://mistral.ai/news/mixtral-of-experts/

I would like to submit a request for supporting the recently released Mixtral-8x7B-Instruct-v0.1 LLM by mistralai on Hugging Face. This LLM is particularly interesting due to its advanced reasoning and instruction following capabilities.

As a regular user of your project, I am excited about its convenience and ease of use, especially with its one-click deployment feature. However, right now, this LLM is not included in your supported models list. I believe this could benefit the wider community if implemented.

Please let us know if you need any further information or additional help from our side to make this happen. We appreciate any timely feedback from your end and look forward to working together towards making this project even more valuable.

Best Regards,
Kuan

**Comment by aresnow1** [comment]
PR is welcome, here's an example for adding support for a LLM model(https://github.com/xorbitsai/inference/pull/629), contact us if there are any issues during implementation.

**Comment by Bojun-Feng** [comment]
@Grey0520 This looks like an interesting model! I have submitted a PR but was unable to run the model and test it locally due to the large model size. Would you mind pulling the PR and testing it on your hardware? If there are any issues please let me know!
