### ISSUE TITLE
QUESTION: Any way to specify the worker to launch the model

### ISSUE THREAD

**Issue by YYLCyylc** [xorbitsai/inference#755]
Note that the issue tracker is NOT the place for general support.
I launch 2 workers in a cluster which are in different server, one have 2 A100 40g and the other have 2 A100 80g.
Now i launch qwen-chat-14b in the 40g A100 which use 1 gpu.
Then i want to launch Yi-chat-34b in A100 80g,but when i launch using cli , it default launch in the other A100 40g and there is not enough gpu mem for it , so i cant chat with it.
So is there any way to specify the worker to launch the model?

**Comment by qinxuye** [comment]
For this kind of scenario, could you please join our slack for a discussion? https://join.slack.com/t/xorbitsio/shared_invite/zt-1o3z9ucdh-RbfhbPVpx7prOVdM1CAuxg
