### ISSUE TITLE
QUESTION:  How to deploy as extensible docker  image

### ISSUE THREAD

**Issue by Loovelj** [xorbitsai/inference#761]
Now I am ready to make Xinference into an extensible image based on bge-reranker-large. How can I define the same model_id at startup and call it remotely through load balancing to create a pure GPU service like triton

#我现在准备将Xinference做成可扩展的镜像，基于bge-reranker-large的，如何统一在启动时定义好相同的model_id，通过负载均衡来远程调用，像triton一样制作一个单纯的GPU服务

**Comment by ChengjieLi28** [comment]
Hi, @Loovelj . You can specify `model_uid` when launching your model.
```
xinference launch -u <your_specific_model_uid> -n bge-reranker-large -t rerank
```

**Comment by Loovelj** [comment]
> Hi, @Loovelj . You can specify `model_uid` when launching your model.
> 
> ```
> xinference launch -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> ```
Thanks, I got it,  but this has a error execption,can you help me?


`
xinference launch --model-name bge-reranker-large --model-type rerank --model-uid my_model
2023-12-13 20:27:00,171 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-13 20:27:00,173 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-12-13 20:27:02,440 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed
Traceback (most recent call last):
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8242827c70>: Failed to establish a new connection: [Errno 111] Connection refused

`

**Comment by ChengjieLi28** [comment]
> > Hi, @Loovelj . You can specify `model_uid` when launching your model.
> > ```
> > xinference launch -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> > ```
> 
> Thanks, I got it, but this has an error execption,can you help me?
> 
> ` xinference launch --model-name bge-reranker-large --model-type rerank --model-uid my_model 2023-12-13 20:27:00,171 - modelscope - INFO - PyTorch version 2.1.1 Found. 2023-12-13 20:27:00,173 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2023-12-13 20:27:02,440 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request conn.request(method, url, **httplib_request_kw) File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output self.send(msg) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send self.connect() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8242827c70>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> `

Specify `-e` option to indicate the Xinference endpoint:
```
xinference launch -e <your_xinference_endpoint> -u <your_specific_model_uid> -n bge-reranker-large -t rerank
```

**Comment by Loovelj** [comment]
> > > Hi, @Loovelj . You can specify `model_uid` when launching your model.
> > > ```
> > > xinference launch -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> > > ```
> > 
> > 
> > Thanks, I got it, but this has an error execption,can you help me?
> > ` xinference launch --model-name bge-reranker-large --model-type rerank --model-uid my_model 2023-12-13 20:27:00,171 - modelscope - INFO - PyTorch version 2.1.1 Found. 2023-12-13 20:27:00,173 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2023-12-13 20:27:02,440 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request conn.request(method, url, **httplib_request_kw) File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output self.send(msg) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send self.connect() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8242827c70>: Failed to establish a new connection: [Errno 111] Connection refused
> > `
> 
> Specify `-e` option to indicate the Xinference endpoint:
> 
> ```
> xinference launch -e <your_xinference_endpoint> -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> ```

Same Error,    but  xinference-local success,but it is random id

**xinference launch -e http://localhost:12345 -u my_rerank -n bge-reranker-large -t rerank**
2023-12-13 21:04:46,706 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-13 21:04:46,709 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-12-13 21:04:48,804 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed
==>> prefix: https://
==>> adapter: <requests.adapters.HTTPAdapter object at 0x7f7ab1414400>
==>> prefix: http://
==>> adapter: <requests.adapters.HTTPAdapter object at 0x7f7ab1414340>
Traceback (most recent call last):
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7ab1414ca0>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by ChengjieLi28** [comment]
> > > > Hi, @Loovelj . You can specify `model_uid` when launching your model.
> > > > ```
> > > > xinference launch -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> > > > ```
> > > 
> > > 
> > > Thanks, I got it, but this has an error execption,can you help me?
> > > `xinference launch --model-name bge-reranker-large --model-type rerank --model-uid my_model 2023-12-13 20:27:00,171 - modelscope - INFO - PyTorch version 2.1.1 Found. 2023-12-13 20:27:00,173 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2023-12-13 20:27:02,440 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request conn.request(method, url, **httplib_request_kw) File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output self.send(msg) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send self.connect() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8242827c70>: Failed to establish a new connection: [Errno 111] Connection refused`
> > 
> > 
> > Specify `-e` option to indicate the Xinference endpoint:
> > ```
> > xinference launch -e <your_xinference_endpoint> -u <your_specific_model_uid> -n bge-reranker-large -t rerank
> > ```
> 
> Same Error, but xinference-local success,but it is random id
> 
> **xinference launch -e http://localhost:12345 -u my_rerank -n bge-reranker-large -t rerank** 2023-12-13 21:04:46,706 - modelscope - INFO - PyTorch version 2.1.1 Found. 2023-12-13 21:04:46,709 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2023-12-13 21:04:48,804 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4b2f06948d8e1e0227d48712befb1bbb and a total number of 946 components indexed ==>> prefix: https:// ==>> adapter: <requests.adapters.HTTPAdapter object at 0x7f7ab1414400> ==>> prefix: http:// ==>> adapter: <requests.adapters.HTTPAdapter object at 0x7f7ab1414340> Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request conn.request(method, url, **httplib_request_kw) File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1331, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1280, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 1040, in _send_output self.send(msg) File "/root/anaconda3/envs/bge/lib/python3.9/http/client.py", line 980, in send self.connect() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/root/anaconda3/envs/bge/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7ab1414ca0>: Failed to establish a new connection: [Errno 111] Connection refused

Just add the ``-u`` option to your successful `xinference-local` command.
