### ISSUE TITLE
BUG: [UI] when `model_format` and `model_size` have been selected, UI may crash when we search model then.

### ISSUE THREAD

**Issue by ChengjieLi28** [xorbitsai/inference#765]
Note that the issue tracker is NOT the place for general support.
Reproduce:
1. First of all:
select `model_format` and `model_size` in the **first** model card:
<img width="794" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/78ea9eeb-1311-4d58-a73b-6a9fd1c78259">

2. And then input `q` in the text search box (assume I want to search `qwen-chat`)
<img width="789" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/ba161fc0-66a7-4b07-b374-6f98704fed40">

3. The ui crashed.

**Comment by aresnow1** [comment]
@Bojun-Feng Hi, do you have time to take a look at this issue?

**Comment by Bojun-Feng** [comment]
@aresnow1 I found the issue and made a PR to fix it. Details of both the issue and the solution can be found in PR #772
