### ISSUE TITLE
BUG: the worker doesn't stop

### ISSUE THREAD

**Issue by YYLCyylc** [xorbitsai/inference#768]
### Describe the bug
I start a xinference-work in the 172.22.227.26:9996 and use ctrl+c stop it , when i try to start it again, it says the worker still exists
I can only restart the supervisor to avoid this problem. 

![image](https://github.com/xorbitsai/inference/assets/50295520/472aabb5-0739-4d33-b526-873d43e7adec)

![image](https://github.com/xorbitsai/inference/assets/50295520/008ee822-45f2-4ef1-b91a-6442f0eae04c)

python 3.11
xinference 0.7.1

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by aresnow1** [comment]
Thanks for you feedback, we will fix it in next version.
