### ISSUE TITLE
XINFERENCE_HOME环境变量问题

### ISSUE THREAD

**Issue by lichangW** [xorbitsai/inference#771]
hi , 我这边设置了XINFERENCE_HOME环境变量，但是去指定的目录下看到里面的模型都是软连接，这是什么原因，谢谢!

![image](https://github.com/xorbitsai/inference/assets/9452272/2dade7e0-b1b7-45e1-b1fa-a0ca52ef18e4)

**Comment by aresnow1** [comment]
目前下载是通huggingface 或者 modelscope 下载源文件，然后软链过去，这个逻辑我们下个版本修复下，确保模型文件在用户指定的目录。

**Comment by lichangW** [comment]
好的，谢谢
