### ISSUE TITLE
用pip下载最新版本的xinference耗时太长，依赖回溯检查太耗费时间

### ISSUE THREAD

**Issue by youqiang95** [xorbitsai/inference#774]
用pip下载最新版本的xinference耗时太长，依赖回溯检查太耗费时间，装了3个小时还没成功，还在报：INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
Collecting attrs

**Comment by aresnow1** [comment]
可以发一下完整日志吗

**Comment by youqiang95** [comment]
> 可以发一下完整日志吗

完整日志没有保存下，在python3.10环境下pip install xinference应该会复现，可以在新的虚拟环境中亲自安装试试，最后我是拉取docker镜像启动的

**Comment by Minamiyama** [comment]
> > 可以发一下完整日志吗
> 
> 完整日志没有保存下，在python3.10环境下pip install xinference应该会复现，可以在新的虚拟环境中亲自安装试试，最后我是拉取docker镜像启动的

先安装setuptools后就可以正常安装xinference了 ，可以参见 #811 中的dockerfile文件

**Comment by jerryliang122** [comment]
pip版本太低了。看看是不是22版本。升级成23版本就好了
