### ISSUE TITLE
BUG: cluster部署custom模型失败

### ISSUE THREAD

**Issue by YYLCyylc** [xorbitsai/inference#787]
### Describe the bug
用以下的json文件在local部署中可以成功注册并部署模型，但是在cluster worker中就不行，且注册失败后会提示模型名称冲突，且无法取消注册
xinference版本为0.7.2
```
{
  "version": 1,
  "context_length": 8192,
  "model_name": "Qwen-14B-Chat-city-v1-lora-sft",
  "model_lang": [
    "zh"
  ],
  "model_ability": [
    "chat"
  ],
  "model_specs": [
    {
      "model_format": "pytorch",
      "model_size_in_billions": 14,
      "quantizations": [
        "4-bit",
        "8-bit",
        "none"
      ],
      "model_id": "finetune/Qwen-14B-Chat-city-v1-lora-sft",
      "model_uri": "file://home/jingtianran/nlp/Qwen-14B-Chat-city-v1-lora-sft"
    }
  ],
  "prompt_style": {
    "style_name": "QWEN",
    "system_prompt": "You are a helpful assistant.",
    "roles": [
      "user",
      "assistant"
    ],
    "intra_message_sep": "\n",
    "stop_token_ids": [
      151643,
      151644,
      151645
    ],
    "stop": [
      "<|endoftext|>",
      "<|im_start|>",
      "<|im_end|>"
    ]
  }
}
``` 
![image](https://github.com/xorbitsai/inference/assets/50295520/13093bc2-5491-4bba-9458-57161a26e1f3)
![image](https://github.com/xorbitsai/inference/assets/50295520/9b539d69-eb5a-47db-bfeb-9b8438c122d3)
![image](https://github.com/xorbitsai/inference/assets/50295520/dce4b5a3-99c5-4cbc-922b-8c9e82c98c2b)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by ChengjieLi28** [comment]
@YYLCyylc . 这种分布式注册的话，需要保证你的每一个worker上都有`model_uri`配置的目录文件。

**Comment by ChengjieLi28** [comment]
@YYLCyylc  注册失败还占用名字的问题，我需要确认下，如果有bug，这周的release版本会修复，感谢提供信息。

**Comment by ChengjieLi28** [comment]
> @YYLCyylc 注册失败还占用名字的问题，我需要确认下，如果有bug，这周的release版本会修复，感谢提供信息。

这确实是个bug，我们将在这周修复

**Comment by YYLCyylc** [comment]
> @YYLCyylc . 这种分布式注册的话，需要保证你的每一个worker上都有`model_uri`配置的目录文件。

都需要有uri对应的相同绝对路径目录吗？那是否意味着所有服务器的用户名都需要是相同的

**Comment by ChengjieLi28** [comment]
> > @YYLCyylc . 这种分布式注册的话，需要保证你的每一个worker上都有`model_uri`配置的目录文件。
> 
> 都需要有uri对应的相同绝对路径目录吗？那是否意味着所有服务器的用户名都需要是相同的

uri路径worker和supervisor所有一样的，用户名未必，你的路径可以不是home路径（确保有权限读取即可）。

**Comment by YYLCyylc** [comment]
经尝试，0.7.2版本可在worker服务器先用xinference-local启动服务，注册模型，在.xinference/model目录生成相关json文件后，再启动xinference-worker，不需要再注册模型，直接启动即可，虽然xinference registrations不会显示，只会显示主服务器的模型信息，但是可以正常启动本地的模型
