### ISSUE TITLE
FEAT: UI for text2image

### ISSUE THREAD

**Issue by aresnow1** [xorbitsai/inference#792]
As we support stable diffusion model for text2image, a simple UI is needed to let users generate images on web pages. Like chat UI, we can launch a gradio page for a quick implementation.

**Comment by aresnow1** [comment]
@Bojun-Feng Hi, any interest? Or any suggestions we can discuss. :)

**Comment by Bojun-Feng** [comment]
@aresnow1  Sounds like an interesting feature! However, I am worried about locally testing the UI on my computer, as my laptop has no GPU support and has only 8GB of RAM. If there are any small text2image or image2image models I can run on my laptop, I would be more than happy to implement the UI for it!

**Comment by Bojun-Feng** [comment]
As for suggestions, we can probably look at [this open source repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui). 

I envision the end product to look something like [this Hugging Face space](https://huggingface.co/spaces/stabilityai/stable-diffusion), except with bigger input text box.

**Comment by aresnow1** [comment]
Hi, could you try this one(https://huggingface.co/stabilityai/sd-turbo ) on your laptop?

**Comment by codingl2k1** [comment]
I will create a PR to add sd turbo support.

**Comment by codingl2k1** [comment]
https://github.com/xorbitsai/inference/pull/797
