### ISSUE TITLE
离线环境下安装如何加载大模型？

### ISSUE THREAD

**Issue by andylzming** [xorbitsai/inference#795]
离线环境下安装如何加载大模型？
比如：把所需的大模型文件（chatglm3-6b, qweu-14b-chat）下载后，手动拷贝到离线服务器，xinference如何配置可以加载这些大模型？

**Comment by andylzming** [comment]
离线模型加载成功。对话页面无法打开
`{
    "detail": "Not Found"
}`
![12](https://github.com/xorbitsai/inference/assets/21255047/3ee60053-d633-4a3b-87bd-5b3000a111eb)
![13](https://github.com/xorbitsai/inference/assets/21255047/b1625f9f-a0fc-4c5c-9013-59240267cfa1)
![14](https://github.com/xorbitsai/inference/assets/21255047/b783ec65-179a-44c4-860a-e301133ef87d)

**Comment by ChengjieLi28** [comment]
> 离线模型加载成功。对话页面无法打开 `{ "detail": "Not Found" }` ![12](https://private-user-images.githubusercontent.com/21255047/292362195-3ee60053-d633-4a3b-87bd-5b3000a111eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTUzNTUsIm5iZiI6MTcwMzIxNTA1NSwicGF0aCI6Ii8yMTI1NTA0Ny8yOTIzNjIxOTUtM2VlNjAwNTMtZDYzMy00YTNiLTg3YmQtNWIzMDAwYTExMWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhY2I4MGRlMmY2YzU1Zjk0Y2E2NzJiODk5YTk3YjU0YTYwNTg3ZmYxZDg2YTUwNDljODlmMWQ2YzI2MTcyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GQ-c5A9YQ_O8-7p3NmE4JCsIJJEpDi_ip8dzoRPFv4A) ![13](https://private-user-images.githubusercontent.com/21255047/292362215-b1625f9f-a0fc-4c5c-9013-59240267cfa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTUzNTUsIm5iZiI6MTcwMzIxNTA1NSwicGF0aCI6Ii8yMTI1NTA0Ny8yOTIzNjIyMTUtYjE2MjVmOWYtYTBmYy00YzVjLTkwMTMtNTkyNDAyNjdjZmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwN2VlMDI3YWM3ZWQyMDJhNmU0MmM2NDc5NWFjNmQyNjBiYjk5YTc0OGRlMTIzNWEwMjMzZTEyOWQ5MjJiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7TuFOlsK3Bbu1u-CmjTHktDMQfwQ_CahH_v9AX1Xr1c) ![14](https://private-user-images.githubusercontent.com/21255047/292362222-b783ec65-179a-44c4-860a-e301133ef87d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTUzNTUsIm5iZiI6MTcwMzIxNTA1NSwicGF0aCI6Ii8yMTI1NTA0Ny8yOTIzNjIyMjItYjc4M2VjNjUtMTc5YS00NGM0LTg2MGEtZTMwMTEzM2VmODdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NmY4NzVmNWI4NzgxNTNmZmEzZTZiZjAxYmVjMjNhMjVlZGFiNDg0YjRjNzkwMWM2YThiMWQwZTc0MzNiMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gkeuEC_IWxXJjJQzmv4Xao0Vbzi6yfw23BwtlgHylI)

先确认有没有装gradio，然后试下刷新页面能不能打开，还不行的话，打开页面F12控制台和网络把里面详细报错贴出来看下

**Comment by andylzming** [comment]
已经可以了，我是把对应的模型卸载重新注册。
`{
  "version": 1,
  "context_length": 8192,
  "model_name": "custom-chatglm-3",
  "model_description": "ChatGLM3 is the third generation of ChatGLM, still open-source and trained on Chinese and English data.", 
  "model_lang": [
    "en",
    "zh"
  ],
  "model_ability": [
    "chat"
  ],
  "model_specs": [
    {
      "model_format": "pytorch",
      "model_size_in_billions": 6,
      "quantizations": [
        "4-bit",
        "8-bit",
        "none"
      ],
      "model_id": "THUDM/chatglm3-6b",
      "model_uri": "file:///home/models/chatglm3-6b"
    }
  ],
  "prompt_style": "chatglm3"
}`
