### ISSUE TITLE
BUG langchain stream not working

### ISSUE THREAD

**Issue by zhoujieli** [xorbitsai/inference#810]
llm = Xinference(
    server_url="http://0.0.0.0:9997",
    model_uid = {model_uid} # replace model_uid with the model UID return from launching the model
)

llm(
    prompt="Q: where can we visit in the capital of France? A:",
    generate_config={"max_tokens": 1024, "stream": True},
)

This does not provide streaming output

Version Number
xinference '0.7.3.1'
langchain '0.0.352'

**Comment by codingl2k1** [comment]
I have created a PR to langchain for supporting xinference chat with stream: https://github.com/langchain-ai/langchain/pull/12702.

**Comment by qinxuye** [comment]
Langchain team is slow at reviewing, you can shout out in the thread: https://github.com/langchain-ai/langchain/pull/12702
