### ISSUE TITLE
pip install show error

### ISSUE THREAD

**Issue by JonSmall** [xorbitsai/inference#814]
### Describe the bug

conda create -n xin
conda activate xin
pip install "xinference[all]"

I dont know what the problem is , and which xinference version show I use， or python version
It show errors below
---------------------------------------------------------------------------------------------------------------------------------

  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 15, in <module>
          import json
      ModuleNotFoundError: No module named 'json'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by ChengjieLi28** [comment]
@JonSmall You create a new python conda env, however, the error message shows that you used python from `/usr/local/lib/python3.8`. Please check this.
