### ISSUE TITLE
hot to convert llama-2 to pytorch.bin

### ISSUE THREAD

**Issue by JonSmall** [xorbitsai/inference#815]
I download the llama2 weight at this site https://modelscope.cn/models/shakechen/Llama-2-7b/files

I register the model as a custom model, but it show need pytorch.bin 

so how to convert llama-2  to pytorch.bin

**Comment by JonSmall** [comment]
Server error: 503 - [address=0.0.0.0:10632, pid=3777447] No available slot found for the model

**Comment by aresnow1** [comment]
> Server error: 503 - [address=0.0.0.0:10632, pid=3777447] No available slot found for the model

Not slot found means there has been a model launched on GPU device, in Xinference, one GPU can't be shared by multiple models.
