### ISSUE TITLE
Unable to open launch web ui

### ISSUE THREAD

**Issue by gubinjie** [xorbitsai/inference#817]
![136651d6dc7eed4fba48391d356a3a63](https://github.com/xorbitsai/inference/assets/37869445/bbb2183f-c160-4df6-88ce-06008f613d7a)
![a5970f9097fa8d5ce446e645ed8ef686](https://github.com/xorbitsai/inference/assets/37869445/626696f5-484b-4d2d-90d4-745d06b66e2f)

Is there any other way to operate？

**Comment by aresnow1** [comment]
Press F12 before opening and check if there are any other errors on the debug page.

**Comment by gubinjie** [comment]
![84bf52e4c1a46fea84b32ef1c371107f](https://github.com/xorbitsai/inference/assets/37869445/729dfe39-2de5-4b65-b037-c56cf7f88562)
![2759ae9b7ef8c0fed143301b4ee737d7](https://github.com/xorbitsai/inference/assets/37869445/9eec349e-8256-4545-a357-ec0c0ca5b837)

**Comment by gubinjie** [comment]
@aresnow1

**Comment by aresnow1** [comment]
what the output of `xinference list`?

**Comment by gubinjie** [comment]
![996c9e1a3c2da3700f9c76ead91643d2](https://github.com/xorbitsai/inference/assets/37869445/719f4cf2-f212-45e9-8813-fe7f4ea7bc77)
@aresnow1

**Comment by aresnow1** [comment]
`xinference list` will list all running models, not registration models. Or you can try to use client(https://inference.readthedocs.io/en/latest/user_guide/client_api.html#llm) to check if it works.

**Comment by gubinjie** [comment]
![853b317e786922e1f37c802470117614](https://github.com/xorbitsai/inference/assets/37869445/1b7a8752-9a7c-4f9a-ae02-3585dba4f86b)

**Comment by gubinjie** [comment]
![3cfb0e24ee685e6a5afbe6e3a9c0963e](https://github.com/xorbitsai/inference/assets/37869445/3712ae35-5e4a-47c9-b6c1-20e8b55bc423)
![3112a359d58f2a9462c39ead9a19c0d0](https://github.com/xorbitsai/inference/assets/37869445/f4169d08-d7d6-4789-b82b-22f43caa1ff9)
@aresnow1
