### ISSUE TITLE
在cpu上进行推理特别慢，一个问题几十秒才出几个字

### ISSUE THREAD

**Issue by loloxiaoz** [xorbitsai/inference#819]
当前使用32C64G的服务器，只有cpu, cpu型号为Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
当在界面上使用chatglm3进行提问时，回复特别慢，几十秒一个字，请问如何优化呢？ 当前看后台进程最多才使用200%的cpu
![sc_20231225184640](https://github.com/xorbitsai/inference/assets/6119077/1927d283-1342-4052-8618-76b5a1a3038b)
![sc_20231225184659](https://github.com/xorbitsai/inference/assets/6119077/b3c7df87-76bb-4932-b44f-3a4878c49601)
![sc_20231225184717](https://github.com/xorbitsai/inference/assets/6119077/2988f503-9bee-4f72-8bfb-17712e0e0807)

**Comment by loloxiaoz** [comment]
<img width="832" alt="image" src="https://github.com/xorbitsai/inference/assets/6119077/d266bdcd-761f-46c9-b9bb-f6856d1ba4de">
当前看只用了2个cpu

**Comment by loloxiaoz** [comment]
<img width="1436" alt="image" src="https://github.com/xorbitsai/inference/assets/6119077/6029ef31-09ba-4948-8d43-239b201d3b63">
上图为debug日志

**Comment by aresnow1** [comment]
chatglm-cpp 的版本是什么？

**Comment by loloxiaoz** [comment]
> chatglm-cpp 的版本是什么？

![image](https://github.com/xorbitsai/inference/assets/6119077/8ddaeaf1-84c7-4c05-8902-0704114ca36c)

**Comment by loloxiaoz** [comment]
> chatglm-cpp 的版本是什么？
![sc_20231226174918](https://github.com/xorbitsai/inference/assets/6119077/4d71fb45-459c-487e-8888-f04d8f61e232)

**Comment by aresnow1** [comment]
pip show chatglm-cpp 查看版本。另外回复中的截图看上去选的模型 format 是 pytorch，推荐使用 ggml 在 CPU 上运行。

**Comment by loloxiaoz** [comment]
<img width="498" alt="image" src="https://github.com/xorbitsai/inference/assets/6119077/8d710aa5-fed0-4e0e-be47-e24de5665599">
0.3.0 
我试试ggml

**Comment by loloxiaoz** [comment]
<img width="1144" alt="image" src="https://github.com/xorbitsai/inference/assets/6119077/ec358e44-b2fc-4a77-9d25-18eaa856100a">

**Comment by loloxiaoz** [comment]
> pip show chatglm-cpp 查看版本。另外回复中的截图看上去选的模型 format 是 pytorch，推荐使用 ggml 在 CPU 上运行。
当前使用ggml后，仍然很慢，使用的chatglm-cpp 0.3.0版本
<img width="1144" alt="image" src="https://github.com/xorbitsai/inference/assets/6119077/ec358e44-b2fc-4a77-9d25-18eaa856100a">
