### ISSUE TITLE
Unable to start xinference service

### ISSUE THREAD

**Issue by xraywu** [xorbitsai/inference#827]
### Describe the bug
Unable to start xinference service

### To Reproduce

1. Start the service by `xinference-local --host 0.0.0.0 --port 9997`
2. The process stucked at `2023-12-27 03:35:12,616 xinference.api.restful_api 77236 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997`

### Expected behavior
The service started normally

### Additional context
1. The virtual env is newly created and only "xinference[all]" was installed under this env.
 
![image](https://github.com/xorbitsai/inference/assets/2353828/bf8d6b89-7b2c-46d2-adb2-8bfd1073cd10)

**Comment by aresnow1** [comment]
It is a running process and has started successfully at this time, you can use client or open the url to launch models.

**Comment by xraywu** [comment]
ok, thanks. Restarted and now availble from web portal
