### ISSUE TITLE
启动 ChatGLM3 WebUI 后对话乱码

### ISSUE THREAD

**Issue by xraywu** [xorbitsai/inference#830]
### Describe the bug
启动 ChatGLM3 模型后，启动 WebUI 对话乱码

### To Reproduce
1.  启动 XInference
2. 启动 ChatGLM3 模型（pytorch，6b 无量化）
3. 启动 WebUI 并对话
4. 生成结果为乱码，如下图

![image](https://github.com/xorbitsai/inference/assets/2353828/bb9d6b1c-1186-4b0a-a0fd-ec84c00b847b)

### Expected behavior
正常对话

**Comment by aresnow1** [comment]
是用的默认的 chatglm3 模型吗，我本地没能复现。可以发一下 xinference, pytorch, transformers 对应的版本。

**Comment by xraywu** [comment]
> 是用的默认的 chatglm3 模型吗，我本地没能复现。可以发一下 xinference, pytorch, transformers 对应的版本。

是的，是从xinference拉的模型，从 HF 镜像站直接拉的

transformers==4.36.2
xinference==0.7.3.1
torch==2.1.2

**Comment by JonSmall** [comment]
我也有这个问题，用hf，或者ms下载的权重，配置pytorch后在乱回答

**Comment by JonSmall** [comment]
> 是用的默认的 chatglm3 模型吗，我本地没能复现。可以发一下 xinference, pytorch, transformers 对应的版本。

请问你这边的 xinference, pytorch, transformers 版本是多少的

**Comment by qinxuye** [comment]
pip install 'xinference==0.7.4' 

更新 xinference 到新版本看下是否还有这个问题。

**Comment by xraywu** [comment]
> pip install 'xinference==0.7.4'
> 
> 更新 xinference 到新版本看下是否还有这个问题。

还有问题，需要重新拉模型吗？

**Comment by qinxuye** [comment]
> > pip install 'xinference==0.7.4'
> > 更新 xinference 到新版本看下是否还有这个问题。
> 
> 还有问题，需要重新拉模型吗？

https://xorbits.cn/assets/images/wechat_pr.png

方便添加小助手，我们帮你解决下

**Comment by qinxuye** [comment]
Is this issue addressed or not? @aresnow1 @codingl2k1

**Comment by jiusi9** [comment]
想问下，这个对话是什么UI呀
