### ISSUE TITLE
BUG 自定义模型名字大小写判断问题导致pytorch模型generate方法调用错误

### ISSUE THREAD

**Issue by sarsmlee** [xorbitsai/inference#834]
### Describe the bug
自定义模型名字大小写判断问题导致pytorch模型generate方法调用错误

### To Reproduce
添加自定义模型，假设自定义模型名字为：Custom_ChatGLM3

[https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/pytorch/core.py](url)
中第259行代码没有判断model_name大小写，导致模型最终调用generate_stream方法而不是generate_stream_chatglm
导致chatglm模型输出结果乱码
修改为 elif "chatglm" in self.model_family.model_name.lower():后问题解决

### Expected behavior
类似其余LLM模型判断方式代码需要修正

**Comment by qinxuye** [comment]
分析很好了，有没有兴趣提一个PR来修改，欢迎成为contributor。

**Comment by sarsmlee** [comment]
> 分析很好了，有没有兴趣提一个PR来修改，欢迎成为contributor。
https://github.com/xorbitsai/inference/pull/835
已提交

**Comment by aresnow1** [comment]
Closed by #835
