### ISSUE TITLE
【SOLVED-QUESTION】RuntimeError: [address=0.0.0.0:36297, pid=1139] Failed to import transformers.generation.utils

### ISSUE THREAD

**Issue by sisuad** [xorbitsai/inference#836]
问题描述： 可以通过localhost:9997加载出web ui，但是在注册本地模型或者加载内置模型（包括LLM和embedding），下载完成后运行时都会报这个错
`RuntimeError: [address=0.0.0.0:36297, pid=1139] Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
/usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

另外xinference-local这个命令提示不存在。

![微信图片_20231227224708](https://github.com/xorbitsai/inference/assets/4243155/dc75dfb1-b11c-416e-a4ed-7c4eb6b77d83)

**Comment by aresnow1** [comment]
完整的报错发一下，并且发一下 `pip show xinference`, `pip show torch`, `pip show transformers` 这三个库的版本信息。

**Comment by sisuad** [comment]
`pip show xinference
Name: xinference
Version: 0.7.3.1
Summary: Model Serving Made Easy
Home-page: https://github.com/xorbitsai/inference
Author: Qin Xuye
Author-email: qinxuye@xprobe.io
License: Apache License 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: modelscope, pydantic, typing-extensions, requests, fastapi, uvicorn, fsspec, openai, xoscar, torch, gradio, sse-starlette, tabulate, s3fs, tqdm, huggingface-hub, click
Required-by:`

`pip show torch
Name: torch
Version: 2.1.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.8/dist-packages
Requires: nvidia-cuda-cupti-cu12, triton, fsspec, nvidia-cufft-cu12, nvidia-nccl-cu12, nvidia-cublas-cu12, networkx, nvidia-cuda-runtime-cu12, typing-extensions, nvidia-cusparse-cu12, filelock, nvidia-curand-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cusolver-cu12, nvidia-nvtx-cu12, nvidia-cudnn-cu12, sympy, jinja2
Required-by: xinference, xformers, vllm, torchvision, torchtext, torch-tensorrt, timm, sentence-transformers, controlnet-aux, accelerate`

`pip show transformers
Name: transformers
Version: 4.35.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /usr/local/lib/python3.8/dist-packages
Requires: packaging, numpy, pyyaml, tqdm, safetensors, huggingface-hub, regex, requests, tokenizers, filelock
Required-by: vllm, transformers-stream-generator, sentence-transformers`

上面截图是0.6.x的版本，今早升级到0.7.3.1最新版，也是这个报错。麻烦了
![QQ20231228-100206](https://github.com/xorbitsai/inference/assets/4243155/9e90911c-46a0-4fb8-9629-cee3d305c4dc)

**Comment by trexliu** [comment]
+1 有啥解法么

**Comment by aresnow1** [comment]
@trexliu @sisuad 可以确认下 pydantic 的版本吗，看上去是 transformers 和 pydantic>2 的版本有兼容性问题，pip install "pydantic<2" 安装小于 2 的版本试一下。

**Comment by sisuad** [comment]
`pip show pydantic
Name: pydantic
Version: 1.10.0
Summary: Data validation and settings management using python type hints
Home-page: https://github.com/pydantic/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: typing-extensions
Required-by: xinference, vllm, thinc, spacy, openai, gradio, fastapi, confection
`
确认了，还是一样的问题

**Comment by ChengjieLi28** [comment]
@sisuad `/usr/local/lib/python3.8`根据你的日志，你使用的python环境就是系统的3.8环境吗？

**Comment by ChengjieLi28** [comment]
> @sisuad `/usr/local/lib/python3.8`根据你的日志，你使用的python环境就是系统的3.8环境吗？

系统默认的python环境很可能缺少什么so之类的，我推荐使用anaconda或者miniconda创建python环境，再试试

**Comment by codingl2k1** [comment]
Similar issue: https://github.com/moymix/TaskMatrix/issues/116

**Comment by sisuad** [comment]
> Similar issue: [moymix/TaskMatrix#116](https://github.com/moymix/TaskMatrix/issues/116)

thanks a lots, that's actully my problem. I used the solution to solve my issue

by`pip uninstall transformer-engine`

by the way, I use the third-party docker images from `apecloud/xinference:latest-amd64`
