### ISSUE TITLE
Xinference Dify Integration Issue

### ISSUE THREAD

**Issue by Eng-AliKazemi** [xorbitsai/inference#860]
![dify issue](https://github.com/xorbitsai/inference/assets/98425433/079ac4ca-fdb4-48ad-8845-07e50812e8f1)
![xinference](https://github.com/xorbitsai/inference/assets/98425433/e0c8b7b8-4f81-4d24-a350-072a149942ea)
Dify and Xinference are both running and working separately, but when I try to connect to Xinference through Dify, I get this error:

`Xinference credentials validate failed: get xinference model extra parameter failed, url: http://127.0.0.1:9997/v1/models/mistral-instruct-v0.2, error: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/models/mistral-instruct-v0.2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb76ddeeb90>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Any help will be appreciated.

**Comment by aresnow1** [comment]
what's your version of dify?

**Comment by gubinjie** [comment]
It seems that the actual IP of the host should be used instead of 127.0.0.1

**Comment by lpy86786** [comment]
Same problem. Dify version = 0.5.4, and both Dify and xinference are installed with dockers on an Ubuntu 18.04. The Ubuntu 18.04 is installed in WSL2 of Windows 10.

![image](https://github.com/xorbitsai/inference/assets/37922084/67a8b544-c201-422b-8e97-1b0893b7ab49)
I have tried the following IPs but none of them work:
http://192.168.103.0:6006(the actual IP)     --get a timeout
![image](https://github.com/xorbitsai/inference/assets/37922084/1232bbc7-eed1-415d-bbbd-1e4f32875e8d)
http://127.0.0.1:6006                                    --immediately report the same error
![image](https://github.com/xorbitsai/inference/assets/37922084/acac3093-f734-4212-9621-e0b34e5f0b21)
http://localhost:6006                                    --immediately report the same error
![image](https://github.com/xorbitsai/inference/assets/37922084/d64dea4e-7845-4aa5-9428-220e18f84d74)

Besides, I also tried connecting that Dify with LMStudio(Windows). It works fine with IP = http://192.168.103.0:1234/v1, but it does not work with IP = http://localhost:1234/v1
![image](https://github.com/xorbitsai/inference/assets/37922084/1a62bd5d-1cc2-4280-920c-dbf727bd1dab)

**Comment by lpy86786** [comment]
I use ifconfig in Ubuntu terminal and tried all the IP addresses listed. Finally I found one capable of usage.

**Comment by oucyangshuai** [comment]
我有同样的问题
