### ISSUE TITLE
docker部署成功，在chatbox只能回答几个字。回复不完整

### ISSUE THREAD

**Issue by dhlsam** [xorbitsai/inference#867]
docke部署成功后，在web ui下载了chatglm3 和qwen-chat模型
在chatbox和netxchat 测试调用openai api格式进行对话，填写了自定义模型名称为model id
可以成功输出内容，但是只能输出是几个字，没有回答完
但是在web ui和dify里可以完整回复
<img width="770" alt="截屏2024-01-08 02 20 12" src="https://github.com/xorbitsai/inference/assets/390439/9eebc001-72c6-40eb-9d32-c0652468299d">

**Comment by aresnow1** [comment]
可能是这两个工具设置的 max_tokens 太小了
