### ISSUE TITLE
QUESTION: No available slot found for the model

### ISSUE THREAD

**Issue by yxybyq** [xorbitsai/inference#888]
Server error: 503 - [address=0.0.0.0:36042, pid=294316] No available slot found for the model

**Comment by aresnow1** [comment]
It means GPU has been used by other launched models, there's no slot left.

**Comment by SwarmKit** [comment]
使用以下方式运行，此问题依然存在：
`docker run -dit -p 8080:9997 -v /data/ModelFiles:/workspace --gpus all xprobe/xinference:v0.8.2  xinference-local -H 0.0.0.0`

![image](https://github.com/xorbitsai/inference/assets/23393026/ddda13fa-23a6-495d-889d-7deb0dcbb923)

![image](https://github.com/xorbitsai/inference/assets/23393026/06024f29-a558-420e-ae6e-42a9a39f8d41)

**Comment by aresnow1** [comment]
> 使用以下方式运行，此问题依然存在： `docker run -dit -p 8080:9997 -v /data/ModelFiles:/workspace --gpus all xprobe/xinference:v0.8.2 xinference-local -H 0.0.0.0`
> 
> ![image](https://private-user-images.githubusercontent.com/23393026/301179313-ddda13fa-23a6-495d-889d-7deb0dcbb923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTIwOTcsIm5iZiI6MTcwNjc1MTc5NywicGF0aCI6Ii8yMzM5MzAyNi8zMDExNzkzMTMtZGRkYTEzZmEtMjNhNi00OTVkLTg4OWQtN2RlYjBkY2JiOTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYTMwZGJlYTIxODc4YTg2MjM4ZTI4NjZkMTFhN2FiYmE4ZmFiNmJiMTg5ZjY4MzJlMTJmZmQ0YWM4OTA5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yT14SCESow6qhwJdBdqqeNFs8lJbNX2JeIx-ui-RoEQ)
> 
> ![image](https://private-user-images.githubusercontent.com/23393026/301179043-06024f29-a558-420e-ae6e-42a9a39f8d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTIwOTcsIm5iZiI6MTcwNjc1MTc5NywicGF0aCI6Ii8yMzM5MzAyNi8zMDExNzkwNDMtMDYwMjRmMjktYTU1OC00MjBlLWFlNmUtNDJhOWEzOWY4ZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxNDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYzIwMzA2ZTU2NjQ5YTgwYmM1ZDJhMzdhYTc5MWY2YzE5ZGViOTdiZDliOGFiNTJiNzM1MGYyNTgyN2YyMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JsvNcD4njFIBwOhekoKaZhNvMWKcVJ09laTHUz_0zCs)

Have you launched any models before?

**Comment by SwarmKit** [comment]
是的，我已经加载一个模型ChatGLM3-6B-32k，再次加载其他的模型时就会出现这个错误提示！！！

**Comment by SwarmKit** [comment]
目前就是这样的……

**Comment by jackleeforce** [comment]
> 意思是一块GPU只能运行一个模型？这有点浪费资源了吧



> 目前就是这样的……

This is incredible, if a GPU can only run one model

**Comment by jony4** [comment]
确实有些浪费

**Comment by Valdanitooooo** [comment]
持续关注，没想到会这样，先用回FastChat吧

**Comment by jony4** [comment]
我这边的复现逻辑

1. 创建一个可能启动不起来的模型，或者说加载时间很长的模型，或者在正常可以启动的模型启动中途去执行第二步
2. 然后通过接口删除掉这个模型 delete /v1/models/chatglm3-32k 接口
3. 再去创建模型实例，就出现 No available slot found for the model
4. /v1/models/instances 这个接口会看到第一步里边的模型依旧处于 creating 状态。通过查看代码貌似是这段中的 list 在第二5 步执行时候没有清理list 的某个值

```python
class StatusGuardActor(xo.StatelessActor):
    def __init__(self):
        super().__init__()
        self._model_uid_to_info: Dict[str, InstanceInfo] = {}  # type: ignore

```
