### ISSUE TITLE
xinference-local -H 0.0.0.0 Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by kukuze** [xorbitsai/inference#892]
### Describe the bug
I downloaded the Docker image from Windows 11 and copied it to a Linux server. When using the startup command provided by readme, Docker exit 132 was generated. When I removed xinreference local - H 0.0.0.0 and used it in the container, an Illegal instruction (core dumped) was generated. 

### To Reproduce
To help us to reproduce this bug, please provide information below:
**docker** version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:11:35 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:10:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 nvidia:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
**nvidia-smi**
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:00:0B.0 Off |                    0 |
| N/A   55C    P0              73W / 300W |  23197MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
1. Your Python version.Python 3.6.8
2. The version of xinference you use. xprobe/xinference:latest

4. Full stack of the error. Illegal instruction (core dumped) 
5. Minimized code to reproduce the error. no

### Expected behavior
正确启动容器并运行xinreference local - H 0.0.0.0

**Comment by qinxuye** [comment]
问题解决了吗？

**Comment by kukuze** [comment]
没解决，但我通过pip的方式安装了。

**Comment by Gaozizhong** [comment]
pip方式安装也报Illegal instruction了

**Comment by jihuacao** [comment]
你好，请问解决了吗？试了0.12和0.11.3也都是这个问题。

**Comment by Lakr233** [comment]
刚刚更新，遇到问题了。

inf-1  | CUDA Version 12.1.1
inf-1  | /root/boot.sh: line 19:    27 Illegal instruction     ( xinference-local -H 0.0.0.0 -p 9997 )

**Comment by Lakr233** [comment]
已解决 手动降级 依赖包

```
docker compose exec -it xinference bash -c "pip install llama-cpp-python==0.2.77"
```

```
root@663e8440819c:/workspace# xinference-local -H 0.0.0.0    
2024-06-17 11:51:07,255 xinference.core.supervisor 3384 INFO     Xinference supervisor 0.0.0.0:27207 started
2024-06-17 11:51:08,021 xinference.core.worker 3384 INFO     Starting metrics export server at 0.0.0.0:None
2024-06-17 11:51:08,023 xinference.core.worker 3384 INFO     Checking metrics export server...
2024-06-17 11:51:08,511 xinference.core.worker 3384 INFO     Metrics server is started at: http://0.0.0.0:35575
2024-06-17 11:51:08,511 xinference.core.worker 3384 INFO     Xinference worker 0.0.0.0:27207 started
2024-06-17 11:51:08,512 xinference.core.worker 3384 INFO     Purge cache directory: /root/.xinference/cache
```

**Comment by Lakr233** [comment]
As a temporary workaround, put following code in your boot script:

```
check_and_install_old_llama_cpp_python() {
    version=$(pip show llama-cpp-python | grep Version | cut -d ' ' -f 2)
    if [ "$version" == "0.2.78" ]; then
        echo "[*] detected llama-cpp-python version 0.2.78, installing version 0.2.77..."
        pip install llama-cpp-python==0.2.77
    fi
}
check_and_install_old_llama_cpp_python
```
