### ISSUE TITLE
XINFERENCE_MODEL_SRC variable not working as expected 

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#894]
### Describe the bug
Already set Environments Variable XINFERENCE_MODEL_SRC to “modelscope” but when trying to download qwen-vl, still using huggingface as download repo.

### To Reproduce
To help us to reproduce this bug, please provide information below:
1. open webui and change tab to 'MULTIMODAL MODELS'
2. filling all dropdown list, click download
3. the log shows the model download request is sent to hugging face repo.

1. Your Python version.
    3.10.10
2 The version of xinference you use. 
    --> 8.0
3. Full stack of the error.
   ```export XINFERENCE_MODEL_SRC ='modelscope'```
   2024-01-15 14:09:02,691 xinference.model.multimodal.core 28720 INFO     Caching from Hugging Face: Qwen/Qwen-VL-Chat
5. Minimized code to reproduce the error.
   export XINFERENCE_MODEL_SRC ='modelscope'
### Expected behavior
   xinferrence should use modelscope to download the target model

**Comment by qinxuye** [comment]
qwen-vl is not supported for downloading from modelscope for now, we will add support for it ASAP.

**Comment by codingl2k1** [comment]
Could you try `export HF_ENDPOINT=https://hf-mirror.com`? I will add modelscope support as soon as possible.

**Comment by onionknightdd** [comment]
> Could you try `export HF_ENDPOINT=https://hf-mirror.com`? I will add modelscope support as soon as possible.

okay thank you very much
