### ISSUE TITLE
How to pre-cache the build-in model resource (not registering)

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#895]
As mentioned in title 

the background is: if the product is deployed to prodcution , there is no chance to access the internet , so is  there any way/documents to intruduce how to make the xinferrence know the model is already catched in local .
we do not prefered to make it work by registering a built-in model as a custom model which may cause unknow behaviors.

any suggustions/documents is welcomed
Great thanks to the mighty community in advance！！！

**Comment by qinxuye** [comment]
I think there's a solution that might be the easiest for now.

Use xinference to download the models on a machine that connected to internet, then copy XINFERENCE_HOME to the production machines with the same places.

Feel free to give your suggestion.

**Comment by onionknightdd** [comment]
> I think there's a solution that might be the easiest for now.
> 
> 
> 
> Use xinference to download the models on a machine that connected to internet, then copy XINFERENCE_HOME to the production machines with the same places.
> 
> 
> 
> Feel free to give your suggestion.

Thank you very much!!!
