### ISSUE TITLE
希望能指定特定的worker，特定的gpu运行模型

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#905]
如题，这对于充分利用GPU资源非常重要。

另外，默认的max_tokens_field太小了。

不管是vllmGenerateConfig的16，还是max_tokens_field里的128，都设置的太小了。建议将这个量改大些，最好在用户未提供max_tokens时,从prompt和模型的最大上下文中估算

**Comment by aresnow1** [comment]
max_tokens 会在下个版本调整，指定 worker 和 GPU 会在后面版本设计加入。

**Comment by zhanghx0905** [comment]
谢谢

**Comment by flyicewei** [comment]
这个怎么调用GPU，我的机器上是有GPU的nvidia-smi也是有输出的，但是运行的时候就是跑CPU，问题回答的特别慢。
