### ISSUE TITLE
希望未来能导出一些Prometheus指标，监控worker或模型的负载

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#908]
vllm 就导出了一些有用的监控指标。

https://docs.vllm.ai/en/latest/serving/metrics.html

这个feature能提高分布式系统的可观测性。这些指标能被Prometheus捕获，由Grafana可视化。

**Comment by qinxuye** [comment]
https://github.com/xorbitsai/inference/pull/906

有个 PR 已经在做了。

**Comment by zhanghx0905** [comment]
> #906
> 
> 有个 PR 已经在做了。

感谢
