### ISSUE TITLE
Any further plan to add access key for rest API call

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#918]
As  mentioned in title .

Model services are exposed by http reuqest for many cases, seems there is no palce in system to add authentication in http request (like the bare token in openai ), or it's already in the system?

Any related infomation/documentation  is welcomed !!!

**Comment by aresnow1** [comment]
We have implemented [OAuth2 system](https://inference.readthedocs.io/en/latest/user_guide/auth_system.html) in #793 , access key will be supported in the next two to three versions.

**Comment by onionknightdd** [comment]
> We have implemented [OAuth2 system](https://inference.readthedocs.io/en/latest/user_guide/auth_system.html) in #793 , access key will be supported in the next two to three versions.

It seems the OAuth2 system is designed for the model management (correct me if i m wrong).
The access key i mentioned is for the api authentication , that would be great if that is also what you meant 

very appreciate the team's contribution
