### ISSUE TITLE
无法加载TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ模型[BUG]

### ISSUE THREAD

**Issue by gahoo** [xorbitsai/inference#928]
加载`TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ`模型时，报错：
```
ImportError: [address=0.0.0.0:43741, pid=107] Loading an AWQ quantized model requires auto-awq library (`pip install autoawq`)
```

经测试，直接使用vllm是可以加载Mixtral-8x7B-Instruct-v0.1-AWQ的，而似乎xinference并没有使用vllm加载这个模型。

在[文档](https://inference.readthedocs.io/zh-cn/latest/user_guide/backends.html)中，`mixtral-instruct-v0.1`并不在支持的模型之列，估计是这个原因造成的。建议加上对`mixtral-instruct-v0.1`的支持。

**Comment by aresnow1** [comment]
我们下个版本增加下支持。

**Comment by gahoo** [comment]
好。AWQ量化的vllm应该都支持的，是否考虑放开对模型种类的限制？或者把参数暴露出来，让用户选择是否使用vllm加载模型？

**Comment by codingl2k1** [comment]
Fixed by: https://github.com/xorbitsai/inference/pull/936
