### ISSUE TITLE
model_id from python client

### ISSUE THREAD

**Issue by stdweird** [xorbitsai/inference#930]
### Is your feature request related to a problem? Please describe
the python client has a `describe_model` method, but the returned data does not include the `model_id`; something i would like to get access to, e.g. to get the tokenizer via `AutoTokenizer` usinhg the model_id

### Describe the solution you'd like
`describe_model` should provide `model_id`

**Comment by aresnow1** [comment]
The parameter of `describe_model` is `model_id`, and you cannot get tokenizer using model_id.

**Comment by stdweird** [comment]
@aresnow1 i am not talking about the uid, but the model_id from the spec like https://github.com/xorbitsai/inference/blob/369aca4943b83e58e4955e75b2f183540eb52c30/xinference/model/llm/llm_family.json#L34
