### ISSUE TITLE
How to delete a downloaded model

### ISSUE THREAD

**Issue by oliverdeveloperprojects** [xorbitsai/inference#932]
I have donwloaded a big LLM using lauch command, but it doesnt work for me so I decied to uninstall it to free space. But I cannot find the way. HOw can I do it?

Thanks.

**Comment by aresnow1** [comment]
Models are downloaded from huggingface, they are usually located in the "~/.cache/huggingface/hub" folder.

**Comment by oliverdeveloperprojects** [comment]
Thanks! That was aswesome help.  👍
