### ISSUE TITLE
模型名称太长的时候，加载模型页面会导致加载按钮被挤到看不见的地方[BUG]

### ISSUE THREAD

**Issue by gahoo** [xorbitsai/inference#934]
如题，建议调整css或者改成列表式的UI。

**Comment by ChengjieLi28** [comment]
@gahoo 感谢建议。后续可能会改成如果超过某个长度，显示xyz...，同时光标移上去显示全名 的形式。

**Comment by gahoo** [comment]
嗯……这个改动比较容易实施。不过，很多模型只是末尾后缀不一样，这样就不太容易一眼看出来了。比如`-INT4`、`-AWQ`之类的。

另外，是否考虑加一个修改或者reregister的按钮？

**Comment by aresnow1** [comment]
Closed by #979
