### ISSUE TITLE
Faster rerank model

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#935]
是否有可能通过onnx替代sentence transformer实现更快的rerank API？在一个RAG应用中embedding的负载并不大，但rerank的负载会相对大一些，是系统中仅次于llm的瓶颈

根据
https://github.com/netease-youdao/BCEmbedding/issues/9
的说法，可以通过其他的后端来加速rerank

**Comment by aresnow1** [comment]
这个需要生成对应的模型文件，使用上会麻烦点，后续我们评估下。
