### ISSUE TITLE
BUG: [Distributed] When you press ctrl-c to kill supervisor first, then press ctrl-c to kill worker after that, the worker process cannot be killed.

### ISSUE THREAD

**Issue by ChengjieLi28** [xorbitsai/inference#940]
Note that the issue tracker is NOT the place for general support.

**Comment by hainaweiben** [comment]
I tested this issue by first starting the supervisor process on 10.0.0.3 as follows:
![1491c566a7d8882002fab81e4651cca0](https://github.com/xorbitsai/inference/assets/112739514/e3610479-3609-4f1c-8d63-e8106abac5d7)

Then, I initiated worker processes both on 10.0.0.3 and 10.0.0.2 respectively:
![21d6333a8470498541481e4debbe84e3](https://github.com/xorbitsai/inference/assets/112739514/a75a1d75-2152-4518-8e05-c9d94dc9721e)
![7993cdb6ee25de8cefc73d7365de7200](https://github.com/xorbitsai/inference/assets/112739514/901472a5-1164-4df5-ad38-13aecdfb7166)

![5b7ed0748e4f28197091f09cb43f12e6](https://github.com/xorbitsai/inference/assets/112739514/ac665551-6e8c-4226-a91a-82365e072454)
![50eea238dcd28af04f508ba95fdb6f5e](https://github.com/xorbitsai/inference/assets/112739514/c06cdd35-066d-4b0a-a251-7be1b3fd4d63)

Subsequently, I terminated the supervisor and worker processes one after another using Ctrl+C. Upon checking with the ps command to search for any remaining processes, no worker processes were found to be still running.
![be6eb1cba3111a9e92288ef17aae64be](https://github.com/xorbitsai/inference/assets/112739514/50161027-5bfa-4391-a9db-eb2b25031bff)
![fbcf1d626f7459a39c0d090842d91421](https://github.com/xorbitsai/inference/assets/112739514/fc9bdc3e-d538-42cd-b631-a5d5ed9b1e69)

So, I believe this bug does not exist in the current version.
