### ISSUE TITLE
新增whisper.base和distilwhisper，调整rerank model的参数传入方式

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#942]
你们好，我看到whisper模型在最新版本得到了实现，非常感谢你们的工作。我想要增加一些audio模型，包括whisper.base和distilwhisper。

另外，在v0.8.2的改动中，rerank模型启动时传参方式被调整了，我认为这种调整是不合理的，阻止了用户向CrossEncoder传入更多参数，应该改回来。

https://github.com/xorbitsai/inference/commit/e16454ae3a6078b1a933c44d3faf5df38146f1d1#
```python
        self._model = CrossEncoder(
            # self._model_path, device=self._device, **self._model_config  # before
            self._model_path, device=self._device, automodel_args=self._model_config # After
        )
```
如果可以的话，我愿意为此提交pr，谢谢。

**Comment by aresnow1** [comment]
欢迎 PR，之前的改动只考虑了传给 AutoModelForSequenceClassification 的参数，可以改回去。
