### ISSUE TITLE
BUG: supervisor tries to connect to workers which are no longer connected

### ISSUE THREAD

**Issue by bufferoverflow** [xorbitsai/inference#943]
### Describe the bug

Supervisor tries to connect to  workers which are no longer connected

### To Reproduce

To help us to reproduce this bug, please provide information below:

1. Your Python version: `3.10.4`
2. The version of xinference you use. `0.7.5, 0.8.1, 0.8.2`
1. start the supervisor: `xinference-supervisor --log-level DEBUG`
2. start worker one: `xinference-worker -e http://0.0.0.0:9997   --log-level DEBUG
3. start worker two: `xinference-worker -e http://0.0.0.0:9997   --log-level DEBUG`
1. query status: `curl -s -X 'GET'   'http://0.0.0.0:9997/status'   -H 'accept: application/json' | jq`, see two workers
1. stop worker one
1. query status: `curl -s -X 'GET'   'http://0.0.0.0:9997/status'   -H 'accept: application/json' | jq`, see two workers

Another test I did:
1. deploying the bge-base-en embedding model on each worker
1. `curl -X 'POST'   'http://0.0.0.0:9997/v1/embeddings'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{"model": "bge-base-en", "input": "The"}'` => works
1. stop worker one
1. `curl -X 'POST'   'http://0.0.0.0:9997/v1/embeddings'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{"model": "bge-base-en", "input": "The"}'` => does **not** work
2. response is `{"detail":"[address=0.0.0.0:55686, pid=588926] [Errno 111] Connect call failed ('0.0.0.0', 49208)"}`

### Expected behavior

If a worker is stopped it should not be contacted anymore and not be listed within status endpoint.

**Comment by aresnow1** [comment]
Thanks for your feedback, there is an issue with the heartbeat between the worker and supervisor. We will attempt to fix it in the next version.
