### ISSUE TITLE
多张V100卡部署Qwen-72B Int4量化模型失败

### ISSUE THREAD

**Issue by yaoyasong** [xorbitsai/inference#945]
xinference支持多卡运行一个模型吗？

xinference 0.8.2
启动模型是选择的N-GPU：auto

错误信息：
Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`

**Comment by qinxuye** [comment]
看上去是显存不够？

**Comment by yaoyasong** [comment]
> 看上去是显存不够？

单张卡显存不够，但4张合起来显存是够得，就是不知道xinference加载模型时，是如何设置才能够多卡并行加载？

**Comment by yaoyasong** [comment]
解决了，N-GPU设置成4，可以4张卡并行加载

**Comment by Summer17xia** [comment]
命令行lunch的时候需要加参数--n-gpu而不是N-GPU
