### ISSUE TITLE
qwen-chat-14B Max Tokens是否有问题

### ISSUE THREAD

**Issue by xbl916** [xorbitsai/inference#951]
我用pytorch 4-bit 模式运行。无论是api调用或者是xinference自带的web界面，Max Tokens最多设置2000出头一点，一旦超过就会报错[address=0.0.0.0:33108, pid=131] cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous    
我是xinference, version 0.8.2
我的设备显存太小，只能 4-bit 模式运行

**Comment by ChiayenGu** [comment]
我是qwen-14b gptq运行 int8模式，我也报错RuntimeError: [address=0.0.0.0:44297, pid=36716] cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous，根据楼上说的把MaxTokens调小一点有效果，不报错了。

版本是0.8.2，cuda12.2

**Comment by xbl916** [comment]
> 我是qwen-14b gptq运行int8模式，我也报错RuntimeError: [address=0.0.0.0:44297, pid=36716]无法将0个元素的张量重塑为形状[-1, 0]，因为未指定的维度大小-1可以可以是任意值而且是不明确的，根据楼上说的把MaxTokens调小一点有效果，不报错了（但是要提示和答案一起吐回来）。
> 
> 版本是0.8.2，cuda12.2

设置小的MaxTokens是能用，但是根据qwen那边说明14B型号是支持到8K Tokens的，所以想说这个是不是xinference的bug。我之前有用chatglm3-6b那个选择8Ktoken就没有问题
