### ISSUE TITLE
能不能做一个登录验证功能

### ISSUE THREAD

**Issue by 143heyan** [xorbitsai/inference#963]
现在谁都能上去操作模型，存在安全风险。

**Comment by aresnow1** [comment]
https://inference.readthedocs.io/zh-cn/latest/user_guide/auth_system.html 根据这个文档配置

**Comment by 143heyan** [comment]
![image](https://github.com/xorbitsai/inference/assets/143150794/4eff1163-ae19-482e-8f94-8726c70c023a)
设置了密码open ai格式API访问的时候Authorization怎么写Bearer xxxx写密码就出现上面的错误

**Comment by 143heyan** [comment]
> https://inference.readthedocs.io/zh-cn/latest/user_guide/auth_system.html 根据这个文档配置

Could not validate credentials

**Comment by ChengjieLi28** [comment]
> ![image](https://private-user-images.githubusercontent.com/143150794/301492749-4eff1163-ae19-482e-8f94-8726c70c023a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDU2NDAsIm5iZiI6MTcwNjg0NTM0MCwicGF0aCI6Ii8xNDMxNTA3OTQvMzAxNDkyNzQ5LTRlZmYxMTYzLWFlMTktNDgyZS04Zjk0LTg3MjZjNzBjMDIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwMzQyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjM3NGM2NWJlMzc4MjkwNjJhMzYwNzliYTZkZjkyMzcwMGYyNjU1NmU3OTNhMGRjNDk1ZTFkZWJjYmMwMTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GaHoXuUmW-aImFg97ikQSp985iH-gMwku1wzXR_QJ0M) 设置了密码open ai格式API访问的时候Authorization怎么写Bearer xxxx写密码就出现上面的错误

1. 先通过用户名密码请求 `<endpoint>/token` 获取bearer token
```
POST /token HTTP/1.1
Accept: application/json
Content-Type: application/json

request body:
{
    "username": "<user>",
    "password": "<pass>"
}

response body:
{"access_token": <access_token>, "token_type": "bearer"}
```
2. 拿到上面的access_token之后，在其他请求的header中加入
```
Authorization: Bearer <access_token>
```
即可
