### ISSUE TITLE
迁移到pydantic v2以支持vllm v0.3.0

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#966]
vllm刚刚更新了v0.3.0，这次更新和上次相差了一个月，主要的新改进是prefix cache。
他们将pydantic迁移到了v2，与xinference产生了冲突。应该适时迁移到pydantic v2以与vllm同步

**Comment by aresnow1** [comment]
我们会在近期做兼容支持，有兴趣的话可以提 PR 贡献 :)
