### ISSUE TITLE
xinference ui 增加音频模型

### ISSUE THREAD

**Issue by andylzming** [xorbitsai/inference#989]
- 官方文档 xinference 已经支持 Image model 和音频模型

![11](https://github.com/xorbitsai/inference/assets/21255047/0c09ceb8-8f2d-42c6-9051-7a5e6b9045a0)

-  xinference ui 还没有增加相关支持

![12](https://github.com/xorbitsai/inference/assets/21255047/7ed0bdea-7300-43d4-bfc6-d6a3127c6ff5)

**Comment by qinxuye** [comment]
Text2Image 正在 #792 里支持。

**Comment by andylzming** [comment]
> Text2Image 正在 #985 里支持。

语音转文本、文本转语音是否会同时支持？

**Comment by qinxuye** [comment]
> > Text2Image 正在 #985 里支持。
> 
> 语音转文本、文本转语音是否会同时支持？

在文生图支持完成后就会支持。
