### ISSUE TITLE
Some LLaMA2 Chat GGUF models have wrong URLs?

### ISSUE THREAD

**Issue by slobentanzer** [xorbitsai/inference#993]
### Describe the bug
Some builtin models of llama-2-chat fail to download (version 0.8.4). I could not get Q6 and Q8, with those errors:

```
Entry Not Found for url: https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGUF/resolve/main/llama-2-70b-chat.Q6_K.gguf.
Entry Not Found for url: https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGUF/resolve/main/llama-2-70b-chat.Q8_0.gguf.
```

I didn't try all the models, but I had no issue getting the other new builtin GGUF versions of LLaMA2 Chat for "Q2_K", "Q3_K_M", "Q4_K_M", "Q5_K_M".

**Comment by aresnow1** [comment]
There is indeed an issue. These two model files have been divided into two parts. We need to figure out how to resolve this problem.
