### ISSUE TITLE
BUG：设置/v1/chat/completions接口参数stream=True时，接口返回“Internal Server Error”

### ISSUE THREAD

**Issue by simmoncn** [xorbitsai/inference#997]
### Describe the bug
在接口调用/v1/chat/completions, 发现接口stream参数 只能是string，但是openAI官方的接口里是bool型，目前想把模型服务换成xinference，发现以前的代码跑不通，一步步调参数，发现是这个stream的问题，但现有项目里都是赋值的bool值，请帮忙看看是否是bug还是使用方式不对。
### To Reproduce
curl调用报错如下：
![image](https://github.com/xorbitsai/inference/assets/6668773/fecbb17f-6b3c-4f4e-9eb6-e26eb560d136)

这个是OpenAI官方的参数说明：
<img width="639" alt="image" src="https://github.com/xorbitsai/inference/assets/6668773/606b8096-4272-40b7-affe-0e63fd0814fc">

### Expected behavior
支持在http post设置stream=True

**Comment by codingl2k1** [comment]
你用的是哪个版本的xinference？服务端有没有错误信息？

**Comment by simmoncn** [comment]
> 你用的是哪个版本的xinference？服务端有没有错误信息？

@codingl2k1 用的昨天发布的最新版0.8.5， debug信息打开了，没看到异常信息

**Comment by codingl2k1** [comment]
![image](https://github.com/xorbitsai/inference/assets/138426806/c8b3f45f-56a8-458c-998e-a7bda35d6517)

**Comment by codingl2k1** [comment]
`"stream": true`看着是正常的，我这里没办法复现你的问题。

**Comment by simmoncn** [comment]
> json的true是小写的，你确定post过去的是个合法的json吗？

代码里定义的是Bool，所以赋值是大写的True，这个我刚才试的确还是报错，不过小写的是对的

**Comment by simmoncn** [comment]
我这边改了我的代码，应该可以了，多谢
